(()=>{"use strict";
const repo='gymwhaleysspot-dot/mt12-jarvis-continuous',api='https://api.github.com/repos/'+repo,raw='https://raw.githubusercontent.com/'+repo+'/main/',$=s=>document.querySelector(s);let busy=false;
const token=()=>($('#token')?.value||'').trim(),valid=t=>/^(ghp_|github_pat_|gho_|ghu_|ghs_|ghr_)[A-Za-z0-9_]+$/.test(t)&&t.length>20,headers=(auth=true)=>{const h={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(auth&&valid(token()))h.Authorization='Bearer '+token();return h};
function need(){if(!valid(token()))throw Error('Enter a valid GitHub token. Classic ghp_ and fine-grained github_pat_ tokens are supported.')}
function note(x,bad=false){const e=$('#control');if(e){e.textContent=x;e.classList.toggle('bad',bad);e.dataset.fault=bad?'1':'0'}decorate()}
function clearFault(){const e=$('#control');if(e){e.textContent='Fault cleared. Ready.';e.classList.remove('bad');e.dataset.fault='0'}document.querySelectorAll('.stream.bad').forEach(x=>x.classList.remove('bad'));decorate()}
async function req(url,opt={}){const r=await fetch(url,{cache:'no-store',headers:{...headers(true),'Content-Type':'application/json'},...opt});if(!r.ok){if(r.status===404)return null;throw Error(r.status+' '+await r.text())}return r.status===204?null:r.json()}
async function verify(){need();const r=await fetch('https://api.github.com/rate_limit',{cache:'no-store',headers:headers(true)});const body=await r.text();if(!r.ok)throw Error('Token verification failed: '+r.status+' '+body);const d=JSON.parse(body),c=d.resources?.core;return c?`Authenticated · API ${c.remaining}/${c.limit} remaining · resets ${new Date(c.reset*1000).toLocaleTimeString()}`:'Authenticated'}
async function dispatch(){try{need();const b=$('#start');if(b)b.disabled=true;note('Verifying GitHub token…');const auth=await verify();note(auth+'\nDispatching MT12 factory…');const r=await fetch(api+'/actions/workflows/master-ai-continuous.yml/dispatches',{method:'POST',headers:{...headers(true),'Content-Type':'application/json'},body:JSON.stringify({ref:'main'})});const body=await r.text();if(!r.ok)throw Error(r.status+' '+body);note(auth+'\nFactory start accepted. Waiting for run registration…');setTimeout(()=>location.reload(),3000)}catch(e){note('Start failed: '+e.message,true)}finally{setTimeout(()=>{const b=$('#start');if(b)b.disabled=false},3000)}}
const dec=s=>decodeURIComponent(escape(atob((s||'').replace(/\n/g,'')))),enc=s=>btoa(unescape(encodeURIComponent(s)));
async function getCatalog(){const x=await req(api+'/contents/reports/factory-catalog.json?ref=main');if(!x)throw Error('Factory catalog does not exist yet.');return{sha:x.sha,data:JSON.parse(dec(x.content))}}
async function putCatalog(sha,data,msg){data.updated=new Date().toISOString();await req(api+'/contents/reports/factory-catalog.json',{method:'PUT',body:JSON.stringify({message:msg,content:enc(JSON.stringify(data,null,2)),sha,branch:'main'})})}
async function removePath(path){const x=await req(api+'/contents/'+path+'?ref=main');if(!x)return false;await req(api+'/contents/'+path,{method:'DELETE',body:JSON.stringify({message:'Delete factory build '+path,sha:x.sha,branch:'main'})});return true}
function pathsFor(b){const root='generations/factory/'+b.family+'/'+b.base,accepted='generations/accepted/'+b.base;return[root+'.luac',root+'.lua',root+'-CHANGELOG.md',root+'-changelog.json',accepted+'.luac',accepted+'.lua',accepted+'-CHANGELOG.md',accepted+'-changelog.json']}
async function reloadVault(){location.reload()}
async function deleteBuild(base){if(busy)return;try{need();const c=await getCatalog(),b=(c.data.builds||[]).find(x=>x.base===base);if(!b)throw Error('Build '+base+' is no longer in the catalog.');if(!confirm('Delete '+base+' Lua, LUAC and changelog files?'))return;busy=true;note('Deleting '+base+'…');for(const p of pathsFor(b))await removePath(p);c.data.builds=(c.data.builds||[]).filter(x=>x.base!==base);await putCatalog(c.sha,c.data,'Delete factory build '+base);setTimeout(reloadVault,700)}catch(e){note('Delete failed: '+e.message,true)}finally{busy=false}}
async function deleteAll(){if(busy)return;try{need();const c=await getCatalog(),builds=c.data.builds||[];if(!builds.length){note('Vault is already empty.');return}if(!confirm('Delete ALL '+builds.length+' complete factory builds?'))return;if(!confirm('FINAL WARNING: this removes Lua, LUAC and changelog files. Continue?'))return;busy=true;const paths=new Set;for(const b of builds)for(const p of pathsFor(b))paths.add(p);let n=0;for(const p of paths){await removePath(p);note('Deleting factory files… '+(++n)+'/'+paths.size)}c.data.builds=[];await putCatalog(c.sha,c.data,'Delete all factory builds');setTimeout(reloadVault,700)}catch(e){note('Delete all failed: '+e.message,true)}finally{busy=false}}
function addDownload(row,href,label,cls){if(row.querySelector('.'+cls))return;const a=document.createElement('a');a.className='btn '+cls;a.href=href;a.download='';a.textContent=label;row.appendChild(a)}
function latestRow(d){const base=d.generation||'latest',family=d.family||'accepted',score=d.score??'—',luac=raw+d.luac,lua=raw+d.lua,ch=raw+d.changelog;return '<div class="build latestAccepted" data-base="'+base+'"><div><span class="pill live">LATEST ACCEPTED</span><br><b>'+String(base).toUpperCase()+'</b><br><small>'+family+' · accepted '+(d.updated||'')+'</small></div><div>score <b class="ok">'+score+'</b></div><div class="ok">READY</div><a href="'+luac+'" download>DOWNLOAD .LUAC</a><a class="btn downloadLua" href="'+lua+'" download>DOWNLOAD .LUA</a><a class="btn downloadChangelog" href="'+ch+'" download>CHANGELOG</a></div>'}
async function syncLatest(){try{const r=await fetch(raw+'reports/status.json?x='+Date.now(),{cache:'no-store'});if(!r.ok)return;const d=await r.json(),v=$('#vault');if(!v||d.status!=='accepted'||!d.luac)return;const base=d.generation||'';if(v.querySelector('[data-base="'+base+'"]')||v.querySelector('a[href*="/'+base+'.luac"]'))return;v.insertAdjacentHTML('afterbegin',latestRow(d));decorate()}catch{}}
async function liveRun(){try{if(!valid(token())){const stream=$('#stream');if(stream&&!stream.dataset.authWarn){stream.dataset.authWarn='1';stream.textContent='Enter and save a GitHub token for live Actions status without shared-IP rate limits.\n'+stream.textContent}return}const r=await fetch(api+'/actions/workflows/master-ai-continuous.yml/runs?per_page=1',{cache:'no-store',headers:headers(true)});if(!r.ok){if(r.status===403){const rem=r.headers.get('x-ratelimit-remaining'),reset=r.headers.get('x-ratelimit-reset');note('GitHub API limit reached'+(rem?' · remaining '+rem:'')+(reset?' · resets '+new Date(Number(reset)*1000).toLocaleTimeString():''),true)}return}const d=await r.json(),run=d.workflow_runs?.[0];if(!run)return;const status=$('#status');if(status)status.textContent=run.conclusion||run.status;let text='Run #'+run.run_number+' · '+run.status+(run.conclusion?' / '+run.conclusion:'');if(run.status==='in_progress'){const jr=await fetch(api+'/actions/runs/'+run.id+'/jobs?per_page=10',{cache:'no-store',headers:headers(true)});if(jr.ok){const jd=await jr.json(),job=jd.jobs?.[0],active=job?.steps?.find(x=>x.status==='in_progress');if(active)text+=' · '+active.name}}const stream=$('#stream');if(stream&&stream.dataset.publicLive!==text){stream.dataset.publicLive=text;stream.textContent='['+new Date().toLocaleTimeString()+'] '+text+'\n'+stream.textContent.slice(0,10000)}}catch{}}
function decorate(){const start=$('#start');if(start&&!start.dataset.authBound){start.dataset.authBound='1';start.onclick=dispatch}const save=$('#save');if(save&&!save.dataset.authBound){save.dataset.authBound='1';save.onclick=async()=>{try{need();localStorage.setItem('mt12.factory.classic',token());note(await verify()+'\nToken saved locally.')}catch(e){note(e.message,true)}}const label=$('#token')?.closest('label');if(label&&!label.dataset.modern){label.dataset.modern='1';label.childNodes[0].textContent='GitHub token ';const p=label.parentElement?.querySelector('.sub');if(p)p.textContent='Classic ghp_ and fine-grained github_pat_ tokens are supported. The token stays only in this browser.'}const refresh=$('#vaultRefresh');if(refresh&&!refresh.dataset.adminBound){refresh.dataset.adminBound='1';refresh.onclick=reloadVault}const controls=refresh?.parentElement;if(controls&&!$('#clearFault')){const b=document.createElement('button');b.className='btn';b.id='clearFault';b.textContent='CLEAR FAULT';b.onclick=clearFault;controls.appendChild(b)}if(controls&&!$('#deleteAllLuacs')){const b=document.createElement('button');b.className='btn danger';b.id='deleteAllLuacs';b.textContent='DELETE ALL BUILDS';b.onclick=deleteAll;controls.appendChild(b)}const fault=$('#control')?.dataset.fault==='1'||!!document.querySelector('#vault .bad,#stream.bad'),clear=$('#clearFault');if(clear)clear.hidden=!fault;document.querySelectorAll('#vault .build').forEach(row=>{const luac=row.querySelector('a[href*=".luac"]');if(!luac)return;const href=luac.getAttribute('href'),base=(href.match(/\/([^/]+)\.luac(?:\?|$)/)||[])[1];if(!base)return;row.dataset.base=base;addDownload(row,href.replace(/\.luac(?:\?|$)/,'.lua'),'DOWNLOAD .LUA','downloadLua');addDownload(row,href.replace(/\.luac(?:\?|$)/,'-CHANGELOG.md'),'CHANGELOG','downloadChangelog');if(!row.querySelector('.deleteLuac')){const b=document.createElement('button');b.className='btn danger deleteLuac';b.textContent='DELETE';b.onclick=()=>deleteBuild(base);row.appendChild(b)}})}
const st=document.createElement('style');st.textContent='.btn.danger{border-color:var(--r);background:linear-gradient(135deg,#702033,#3a1019);color:#fff}.build{grid-template-columns:1.25fr .55fr .55fr repeat(4,auto)}.build .downloadLua,.build .downloadChangelog{color:var(--c)}.latestAccepted{border-color:var(--g);box-shadow:0 0 24px #5dff9e22}.deleteLuac{padding:9px 11px}#clearFault{border-color:var(--a);color:var(--a)}#clearFault[hidden]{display:none!important}@media(max-width:820px){.build{grid-template-columns:1fr 1fr}.build a,.deleteLuac{grid-column:auto}}';document.head.appendChild(st);new MutationObserver(()=>{decorate();syncLatest()}).observe(document.documentElement,{childList:true,subtree:true});decorate();syncLatest();liveRun();setInterval(syncLatest,10000);setInterval(liveRun,10000);
})();