(()=>{"use strict";
const repo='gymwhaleysspot-dot/mt12-jarvis-continuous',api='https://api.github.com/repos/'+repo,raw='https://raw.githubusercontent.com/'+repo+'/main/';
const $=s=>document.querySelector(s),tok=()=>($('#token')?.value||'').trim();
const H=()=>({Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+tok()});
const enc=s=>btoa(unescape(encodeURIComponent(s))),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function req(url,opt={}){const r=await fetch(url,{cache:'no-store',headers:H(),...opt});if(!r.ok)throw Error(r.status+' '+(await r.text()).slice(0,600));return r.status===204?null:r.json()}
async function put(path,content,msg){let old=null;try{old=await req(api+'/contents/'+path+'?ref=main')}catch(e){if(!String(e.message).startsWith('404 '))throw e}const body={message:msg,content:enc(content),branch:'main'};if(old?.sha)body.sha=old.sha;return req(api+'/contents/'+path,{method:'PUT',body:JSON.stringify(body)})}
function status(x,bad=false){const e=$('#manualFactoryStatus');if(e){e.textContent=x;e.className='stream '+(bad?'bad':'')}}
function safeName(x){return String(x||'').toLowerCase().replace(/[^a-z0-9_-]/g,'').slice(0,6)}
async function loadLatest(){try{const r=await fetch(raw+'reports/manual-factory-latest.json?x='+Date.now(),{cache:'no-store'});if(!r.ok)return;const d=await r.json(),e=$('#manualLatest');if(!e)return;const margin=Number.isFinite(d.margin)?d.margin:'—',bytes=Number.isFinite(d.luac_bytes)?d.luac_bytes:'—';e.innerHTML='<div class="facts"><div class="fact"><b>Release</b><span>'+esc(d.release||'—')+'</span></div><div class="fact"><b>Status</b><span class="'+(/PASS/.test(d.status||'')?'ok':'bad')+'">'+esc(d.status||'—')+'</span></div><div class="fact"><b>LUAC bytes</b><span>'+esc(bytes)+'</span></div><div class="fact"><b>Margin</b><span>'+esc(margin)+'</span></div></div>'+(d.release?'<div class="row" style="margin-top:8px"><a class="btn go" download href="'+raw+'factory_runs/'+encodeURIComponent(d.release)+'/'+encodeURIComponent(d.release)+'.luac">DOWNLOAD .LUAC</a><a class="btn" target="_blank" href="'+raw+'factory_runs/'+encodeURIComponent(d.release)+'/'+encodeURIComponent(d.release)+'_report.html">OPEN REPORT</a></div>':'') }catch(e){status('Latest-report read failed: '+e.message,true)}}
async function build(){try{if(!tok())throw Error('Save a GitHub token with Contents and Actions write access.');const file=$('#manualLua').files[0];if(!file)throw Error('Choose a .lua source file.');const rel=safeName($('#manualRelease').value);if(!rel)throw Error('Enter a release name, maximum 6 characters.');$('#manualRelease').value=rel;const base=$('#manualBaseline').value.trim();const text=await file.text(),path='factory_inbox/'+rel+'.lua';status('Uploading '+path+'…');await put(path,text,'Queue factory source '+rel);status('Source uploaded. Dispatching compiler/auditor…');await req(api+'/actions/workflows/manual-factory-build.yml/dispatches',{method:'POST',body:JSON.stringify({ref:'main',inputs:{source_path:path,release:rel,baseline_path:base,strict:$('#manualStrict').checked?'true':'false'}})});status('Build accepted. GitHub Actions will audit, compile, normalize, publish the LUAC, interface manifest and HTML report.');setTimeout(loadLatest,5000)}catch(e){status('Build failed to start: '+e.message,true)}}
function install(){if($('#manualFactory'))return;const grid=document.querySelector('.grid');if(!grid)return;const s=document.createElement('section');s.id='manualFactory';s.className='card wide';s.innerHTML='<div class="row"><div><h2 style="margin:0">Source-to-LUAC Build Station</h2><p class="sub">The Python audit factory is wired directly into this page through GitHub Actions.</p></div><span class="pill ok">AUDIT + COMPILE + NORMALIZE</span></div><div class="facts" style="margin-top:10px"><label class="fact"><b>Lua source</b><input id="manualLua" type="file" accept=".lua,text/plain"></label><label class="fact"><b>Release (≤6 chars)</b><input id="manualRelease" value="a15yb" maxlength="6"></label><label class="fact"><b>Baseline repository path</b><input id="manualBaseline" value="generations/accepted/a15ya.lua" placeholder="optional/path.lua"></label><label class="fact"><b>Strict gate</b><span><input id="manualStrict" type="checkbox" style="width:auto"> fail on warnings</span></label></div><button id="manualBuild" class="btn go" style="width:100%;margin-top:10px">UPLOAD, AUDIT AND BUILD NORMALIZED LUAC</button><div id="manualFactoryStatus" class="stream" style="min-height:76px;margin-top:10px">Ready. The source is committed to factory_inbox, then manual-factory-build.yml runs tools/mt12_factory.py.</div><h3>Latest manual factory result</h3><div id="manualLatest" class="stream" style="min-height:74px">No result loaded.</div>';
const vault=[...grid.querySelectorAll('.card.wide')].at(-1);grid.insertBefore(s,vault||null);$('#manualBuild').onclick=build;loadLatest();setInterval(loadLatest,12000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
