(()=>{"use strict";
const repo='gymwhaleysspot-dot/mt12-jarvis-continuous',api='https://api.github.com/repos/'+repo,$=s=>document.querySelector(s);let busy=false;
const token=()=>($('#token')?.value||'').trim(),valid=t=>/^ghp_[A-Za-z0-9_]{20,}$/.test(t),headers=()=>({Accept:'application/vnd.github+json',Authorization:'Bearer '+token(),'Content-Type':'application/json'});
function need(){if(!valid(token()))throw Error('A saved classic ghp_ token is required to delete factory files.')}
function note(x,bad=false){const e=$('#control');if(e){e.textContent=x;e.classList.toggle('bad',bad);e.dataset.fault=bad?'1':'0'}decorate()}
function clearFault(){const e=$('#control');if(e){e.textContent='Fault cleared. Ready.';e.classList.remove('bad');e.dataset.fault='0'}document.querySelectorAll('.stream.bad').forEach(x=>x.classList.remove('bad'));decorate()}
async function req(url,opt={}){const r=await fetch(url,{cache:'no-store',headers:headers(),...opt});if(!r.ok){if(r.status===404)return null;throw Error(r.status+' '+await r.text())}return r.status===204?null:r.json()}
const dec=s=>decodeURIComponent(escape(atob((s||'').replace(/\n/g,'')))),enc=s=>btoa(unescape(encodeURIComponent(s)));
async function getCatalog(){const x=await req(api+'/contents/reports/factory-catalog.json?ref=main');if(!x)throw Error('Factory catalog does not exist yet.');return{sha:x.sha,data:JSON.parse(dec(x.content))}}
async function putCatalog(sha,data,msg){data.updated=new Date().toISOString();await req(api+'/contents/reports/factory-catalog.json',{method:'PUT',body:JSON.stringify({message:msg,content:enc(JSON.stringify(data,null,2)),sha,branch:'main'})})}
async function removePath(path){const x=await req(api+'/contents/'+path+'?ref=main');if(!x)return false;await req(api+'/contents/'+path,{method:'DELETE',body:JSON.stringify({message:'Delete factory build '+path,sha:x.sha,branch:'main'})});return true}
function pathsFor(b){const root='generations/factory/'+b.family+'/'+b.base,accepted='generations/accepted/'+b.base;return[ root+'.luac',root+'.lua',root+'-CHANGELOG.md',root+'-changelog.json',accepted+'.luac',accepted+'.lua',accepted+'-CHANGELOG.md',accepted+'-changelog.json' ]}
async function reloadVault(){const b=$('#vaultRefresh');try{if(b){b.disabled=true;b.textContent='Reloading…'}note('Reloading vault…');location.reload()}catch(e){note('Reload failed: '+e.message,true)}finally{if(b){b.disabled=false;b.textContent='Reload vault'}}}
async function deleteBuild(base){if(busy)return;try{need();const c=await getCatalog(),b=(c.data.builds||[]).find(x=>x.base===base);if(!b)throw Error('Build '+base+' is no longer in the catalog.');if(!confirm('Delete '+base+' Lua, LUAC and changelog files?'))return;busy=true;note('Deleting '+base+'…');for(const p of pathsFor(b))await removePath(p);c.data.builds=(c.data.builds||[]).filter(x=>x.base!==base);await putCatalog(c.sha,c.data,'Delete factory build '+base);setTimeout(reloadVault,700)}catch(e){note('Delete failed: '+e.message,true)}finally{busy=false}}
async function deleteAll(){if(busy)return;try{need();const c=await getCatalog(),builds=c.data.builds||[];if(!builds.length){note('Vault is already empty.');return}if(!confirm('Delete ALL '+builds.length+' complete factory builds?'))return;if(!confirm('FINAL WARNING: this removes Lua, LUAC and changelog files. Continue?'))return;busy=true;const paths=new Set;for(const b of builds)for(const p of pathsFor(b))paths.add(p);let n=0;for(const p of paths){await removePath(p);note('Deleting factory files… '+(++n)+'/'+paths.size)}c.data.builds=[];await putCatalog(c.sha,c.data,'Delete all factory builds');setTimeout(reloadVault,700)}catch(e){note('Delete all failed: '+e.message,true)}finally{busy=false}}
function addDownload(row,href,label,cls){if(row.querySelector('.'+cls))return;const a=document.createElement('a');a.className='btn '+cls;a.href=href;a.download='';a.textContent=label;row.appendChild(a)}
function decorate(){const refresh=$('#vaultRefresh');if(refresh&&!refresh.dataset.adminBound){refresh.dataset.adminBound='1';refresh.onclick=reloadVault}const controls=refresh?.parentElement;if(controls&&!$('#clearFault')){const b=document.createElement('button');b.className='btn';b.id='clearFault';b.textContent='CLEAR FAULT';b.onclick=clearFault;controls.appendChild(b)}if(controls&&!$('#deleteAllLuacs')){const b=document.createElement('button');b.className='btn danger';b.id='deleteAllLuacs';b.textContent='DELETE ALL BUILDS';b.onclick=deleteAll;controls.appendChild(b)}const fault=$('#control')?.dataset.fault==='1'||!!document.querySelector('#vault .bad,#stream.bad'),clear=$('#clearFault');if(clear)clear.hidden=!fault;
document.querySelectorAll('#vault .build').forEach(row=>{const luac=row.querySelector('a[href*=".luac"]');if(!luac)return;const href=luac.getAttribute('href'),base=(href.match(/\/([^/]+)\.luac(?:\?|$)/)||[])[1];if(!base)return;addDownload(row,href.replace(/\.luac(?:\?|$)/,'.lua'),'DOWNLOAD .LUA','downloadLua');addDownload(row,href.replace(/\.luac(?:\?|$)/,'-CHANGELOG.md'),'CHANGELOG','downloadChangelog');if(!row.querySelector('.deleteLuac')){const b=document.createElement('button');b.className='btn danger deleteLuac';b.textContent='DELETE';b.onclick=()=>deleteBuild(base);row.appendChild(b)}})}
const st=document.createElement('style');st.textContent='.btn.danger{border-color:var(--r);background:linear-gradient(135deg,#702033,#3a1019);color:#fff}.build{grid-template-columns:1.25fr .55fr .55fr repeat(4,auto)}.build .downloadLua,.build .downloadChangelog{color:var(--c)}.deleteLuac{padding:9px 11px}#clearFault{border-color:var(--a);color:var(--a)}#clearFault[hidden]{display:none!important}@media(max-width:820px){.build{grid-template-columns:1fr 1fr}.build a,.deleteLuac{grid-column:auto}}';document.head.appendChild(st);new MutationObserver(decorate).observe(document.documentElement,{childList:true,subtree:true});decorate();
})();
