#!/usr/bin/env node
import fs from 'node:fs';import crypto from 'node:crypto';
const cfg=JSON.parse(fs.readFileSync('keleb/config.json','utf8'));const state=JSON.parse(fs.readFileSync('keleb/state.json','utf8'));const mem=JSON.parse(fs.readFileSync('keleb/memory.json','utf8'));const research=fs.existsSync('keleb/research/current.json')?JSON.parse(fs.readFileSync('keleb/research/current.json','utf8')):{componentEvidence:{},researchGaps:[]};
const now=()=>new Date().toISOString(),rnd=(a,b)=>a+Math.random()*(b-a),cl=(v,a,b)=>Math.max(a,Math.min(b,v));
const bounds={dashboardDepth:[.15,.27],dashboardHeight:[.08,.15],steeringRadius:[.135,.19],steeringZ:[1.36,1.54],seatWidth:[.18,.27],seatDepth:[.25,.36],seatHeight:[.30,.44],seatSeparation:[.40,.55],cageTubeRadius:[.018,.032],cageRoofZ:[1.90,2.10],centerTunnelWidth:[.10,.20],shifterHeight:[.16,.30],handbrakeLength:[.20,.38],harnessWidth:[.025,.05],detailLevel:[.8,1.4]};
const paramToComponent={dashboardDepth:'dashboard',dashboardHeight:'dashboard',steeringRadius:'steering_wheel',steeringZ:'steering_wheel',seatWidth:'seat_driver',seatDepth:'seat_driver',seatHeight:'seat_driver',seatSeparation:'seat_driver',cageTubeRadius:'roll_cage_front_left',cageRoofZ:'roll_cage_front_left',centerTunnelWidth:'floor_tunnel',shifterHeight:'sequential_shifter',handbrakeLength:'hydraulic_handbrake',harnessWidth:'harness_driver',detailLevel:'interior_wiring'};
function evidence(c){return (research.componentEvidence?.[c]?.length||0)}
function score(p){let s=50;for(const [k,v] of Object.entries(p)){const [a,b]=bounds[k],mid=(a+b)/2,span=(b-a)/2;s+=Math.max(0,1-Math.abs(v-mid)/span)*.25;const c=paramToComponent[k];s+=Math.min(1,evidence(c)/3)*.35}return Number(s.toFixed(4))}
const base=state.parameters;const candidates=[];for(let i=0;i<cfg.candidatePopulation;i++){const p={...base};const keys=Object.keys(bounds);const n=i<keys.length?1:2;for(let j=0;j<n;j++){const k=keys[(i+j*3)%keys.length],b=bounds[k],span=b[1]-b[0],confidence=Math.min(1,evidence(paramToComponent[k])/3),step=span*(.025+.035*confidence);p[k]=cl(p[k]+rnd(-step,step),b[0],b[1])}candidates.push({id:`keleb-${state.generation+1}-${i}`,parameters:p,proxyScore:score(p)})}candidates.sort((a,b)=>b.proxyScore-a.proxyScore);const championScore=state.championScore??score(base);const elite=candidates[0];const gain=elite.proxyScore-championScore;const proposal={schema:1,generatedAt:now(),baseGeneration:state.generation,championScore,elite,gain:Number(gain.toFixed(4)),promotionEligible:gain>=cfg.promotion.minimumGain,requiresVisualValidation:true,forbiddenMutationScopes:cfg.forbiddenMutationScopes,researchGaps:research.researchGaps||[],population:candidates};fs.mkdirSync('keleb/lab',{recursive:true});fs.writeFileSync('keleb/lab/proposal.json',JSON.stringify(proposal,null,2)+'\n');mem.cycles=(mem.cycles||0)+1;mem.researchGaps=proposal.researchGaps;mem.history=(mem.history||[]).slice(-49);mem.history.push({at:now(),generation:state.generation,elite:elite.id,proxyScore:elite.proxyScore,gain:proposal.gain,promotionEligible:proposal.promotionEligible});fs.writeFileSync('keleb/memory.json',JSON.stringify(mem,null,2)+'\n');console.log(JSON.stringify({generation:state.generation,candidates:candidates.length,championScore,elite:elite.proxyScore,gain:proposal.gain,promotionEligible:proposal.promotionEligible},null,2));
