#!/usr/bin/env node
import fs from 'node:fs';import crypto from 'node:crypto';
const cfg=JSON.parse(fs.readFileSync('keleb/config.json','utf8'));const twin=JSON.parse(fs.readFileSync('keleb/interior-twin.json','utf8'));const now=()=>new Date().toISOString();const out=[];const rejected=[];const seen=new Set();
const terms={dashboard:['dashboard','instrument','display','cluster'],steering_wheel:['steering wheel','wheel rim'],seat_driver:['seat','bucket seat'],seat_codriver:['co-driver seat','codriver seat','bucket seat'],roll_cage_front_left:['roll cage','rollcage','safety cage'],roll_cage_front_right:['roll cage','rollcage','safety cage'],roll_cage_rear_left:['roll cage','rollcage','safety cage'],roll_cage_rear_right:['roll cage','rollcage','safety cage'],sequential_shifter:['sequential shifter','gear lever','shifter'],hydraulic_handbrake:['handbrake','hand brake'],harness_driver:['harness','seat belt'],harness_codriver:['harness','seat belt'],center_console:['center console','switch panel'],pedal_box:['pedal box','pedals'],door_card_left:['door card','door panel'],door_card_right:['door card','door panel'],fire_extinguisher:['fire extinguisher','extinguisher']};
const clean=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();const id=s=>crypto.createHash('sha256').update(s).digest('hex').slice(0,20);const comps=text=>{const t=String(text||'').toLowerCase(),r=[];for(const [k,a] of Object.entries(terms))if(a.some(x=>t.includes(x)))r.push(k);return [...new Set(r)]};
async function get(u){const r=await fetch(u,{headers:{'User-Agent':'Keleb-Interior-Research/1.0'}});if(!r.ok)throw Error(`${r.status}`);return r}
async function bing(q){try{const xml=await(await get('https://www.bing.com/search?format=rss&q='+encodeURIComponent(q))).text();for(const m of xml.matchAll(/<item>[\s\S]*?<title>([\s\S]*?)<\/title>[\s\S]*?<link>([\s\S]*?)<\/link>[\s\S]*?<description>([\s\S]*?)<\/description>[\s\S]*?<\/item>/gi)){const title=clean(m[1]),url=clean(m[2]),summary=clean(m[3]),text=`${title} ${summary}`.toLowerCase();if(!/citro[eë]n|c3 wrc|wrc|rally|cockpit|interior|roll cage|dashboard|steering|seat/.test(text)){rejected.push({title,url,reason:'not interior automotive'});continue}if(seen.has(url))continue;seen.add(url);out.push({id:id(url),provider:'web',title,url,summary,components:comps(text),retrievedAt:now(),truthEligible:false})}}catch(e){}}
async function crossref(q){try{const j=await(await get('https://api.crossref.org/works?rows=8&query.bibliographic='+encodeURIComponent(q))).json();for(const x of j.message?.items||[]){const title=clean(x.title?.[0]),url=x.URL||'',summary=clean(x.abstract||x['container-title']?.[0]||''),text=`${title} ${summary}`.toLowerCase();if(!/automotive|vehicle|cockpit|interior|dashboard|seat|steering|photogrammetry|segmentation|depth|render/.test(text))continue;if(!url||seen.has(url))continue;seen.add(url);out.push({id:id(url),provider:'Crossref',title,url,summary,components:comps(text),retrievedAt:now(),truthEligible:false})}}catch(e){}}
for(const q of cfg.researchTopics){await bing(q);await crossref(q)}
const componentEvidence={};for(const s of out)for(const c of s.components){(componentEvidence[c]??=[]).push(s.id)}
const gaps=Object.keys(twin.components).filter(c=>!(componentEvidence[c]?.length));const report={schema:1,identity:'Keleb Interior Research',generatedAt:now(),sources:out.slice(0,80),componentEvidence,researchGaps:gaps,rejected:rejected.slice(0,80),authority:'subordinate to owner interior Truth'};fs.mkdirSync('keleb/research',{recursive:true});fs.writeFileSync('keleb/research/current.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({sources:report.sources.length,components:Object.keys(componentEvidence).length,gaps:gaps.length},null,2));
