import{GitHubClient,BASE,OWNER,REPO,sha256,bytesToB64,safeName,requestId,sleep}from'./api.js';import{parseCSV,summarize,suggestPairs,drawSeries,makeLabel}from'./replay.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),gh=new GitHubClient(),DRAFT='a17y_home_draft_v2',QUEUE='a17y_offline_queue_v2';
let files=[],selected=new Set(),activeRun=null,currentFile=null,currentRows=null,page=1,query='',archived=false;
const log=s=>{$('console').textContent=`${new Date().toLocaleTimeString()}  ${s}\n`+$('console').textContent};
const saveDraft=()=>localStorage.setItem(DRAFT,JSON.stringify({mission:$('mission').value,model:$('model').value,child:$('child').value,branch:$('candidateBranch').value,selected:[...selected],activeRun}));
function loadDraft(){try{const d=JSON.parse(localStorage.getItem(DRAFT)||'{}');$('mission').value=d.mission||$('mission').value;$('model').value=d.model||'openai/gpt-4.1';$('child').value=d.child||'';$('candidateBranch').value=d.branch||'main';selected=new Set(d.selected||[]);activeRun=d.activeRun||null;}catch{}}
function tokenUI(){$('token').value=gh.token;$('remember').checked=gh.remembered();$('auth').textContent=gh.token?'Token loaded; validate permissions.':'Not connected.';}
async function connect(){try{gh.setToken($('token').value,$('remember').checked);const p=await gh.testPermissions();$('auth').innerHTML=`<b class="ok">Connected:</b> ${esc(p.repo)} · Actions ${p.actions?'enabled':'disabled'} · main ${p.sha.slice(0,8)}`;$('rate').textContent=`API remaining: ${gh.rate.remaining??'?'}`;await refreshLogs();await refreshRuns();}catch(e){$('auth').innerHTML=`<span class="bad">${esc(e.message)}</span>`;}}
async function repoTree(){const ref=await gh.api('/git/ref/heads/main'),tree=await gh.api(`/git/trees/${ref.object.sha}?recursive=1`);return tree.tree||[];}
async function refreshLogs(){const list=$('logList');list.innerHTML='<div class="small">Loading repository evidence…</div>';try{const tree=await repoTree();files=tree.filter(x=>x.type==='blob'&&x.path.startsWith(archived?'archive/replays/':'tests/replays/')&&x.path.endsWith('.csv')).map(x=>({name:x.path.split('/').pop(),path:x.path,sha:x.sha,size:x.size||0}));renderLogs();renderPairs();$('logCount').textContent=`${files.length} logs`; }catch(e){list.innerHTML=`<div class="bad">${esc(e.message)}</div>`;}}
function filtered(){return files.filter(f=>!query||f.name.toLowerCase().includes(query)||f.path.toLowerCase().includes(query));}
function renderLogs(){const all=filtered(),per=30,max=Math.max(1,Math.ceil(all.length/per));page=Math.min(page,max);const slice=all.slice((page-1)*per,page*per),box=$('logList');box.innerHTML=slice.map(f=>`<div class="item"><input aria-label="Select ${esc(f.name)}" type="checkbox" data-select="${esc(f.path)}" ${selected.has(f.path)?'checked':''}><div><b>${esc(f.name)}</b><div class="small">${esc(f.path)} · ${(f.size/1024).toFixed(1)} KB</div></div><div class="actions"><button class="btn" data-view="${esc(f.path)}">VIEW</button><button class="btn" data-download="${esc(f.path)}">DOWNLOAD</button><button class="btn warn" data-archive="${esc(f.path)}">${archived?'RESTORE':'ARCHIVE'}</button></div></div>`).join('')||'<div class="small">No matching logs.</div>';$('pageState').textContent=`Page ${page}/${max}`;box.querySelectorAll('[data-select]').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.select):selected.delete(x.dataset.select);syncSelection()});box.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>openLog(x.dataset.view));box.querySelectorAll('[data-download]').forEach(x=>x.onclick=()=>downloadRepoFile(x.dataset.download));box.querySelectorAll('[data-archive]').forEach(x=>x.onclick=()=>archiveFile(x.dataset.archive));syncSelection();}
function syncSelection(){$('selectedLogs').value=[...selected].join('\n');$('selectedCount').textContent=`${selected.size} selected`;saveDraft();}
function renderPairs(){const pairs=suggestPairs(files);$('pairList').innerHTML=pairs.slice(0,12).map(g=>`<div class="chip">Possible pair: ${g.map(x=>esc(x.name)).join(' + ')}</div>`).join('')||'<span class="small">No automatic pairs detected.</span>';}
async function getContent(path,ref='main'){const d=await gh.api(`/contents/${encodeURIComponent(path).replace(/%2F/g,'/')}?ref=${encodeURIComponent(ref)}`);return Uint8Array.from(atob(d.content.replace(/\n/g,'')),c=>c.charCodeAt(0));}
async function downloadRepoFile(path){const b=await getContent(path),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([b]));a.download=path.split('/').pop();a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);}
async function openLog(path){try{const b=await getContent(path),text=new TextDecoder().decode(b),rows=parseCSV(text),s=summarize(rows);currentFile=path;currentRows=rows;$('viewer').classList.remove('hidden');$('viewTitle').textContent=path;$('viewStats').innerHTML=`<span class="chip">${s.data.length} rows</span><span class="chip">${s.head.length} columns</span>`+Object.entries(s.counts).map(([k,v])=>`<span class="chip">${k.toUpperCase()}: ${v.episodes} episodes</span>`).join('');drawSeries($('chart'),s);$('preview').innerHTML='<thead><tr>'+s.head.map(h=>`<th>${esc(h)}</th>`).join('')+'</tr></thead><tbody>'+s.data.slice(0,300).map(r=>'<tr>'+s.head.map((_,i)=>`<td>${esc(r[i]??'')}</td>`).join('')+'</tr>').join('')+'</tbody>';location.hash='viewer';}catch(e){log(`VIEW FAILED: ${e.message}`)}}
async function archiveFile(path){try{const mode=path.startsWith('archive/'),dest=mode?path.replace(/^archive\/replays\//,'tests/replays/'):path.replace(/^tests\/replays\//,'archive/replays/');if(!confirm(`${mode?'Restore':'Archive'} ${path}?`))return;const src=await gh.api(`/contents/${path}?ref=main`);await gh.api(`/contents/${dest}`,{method:'PUT',body:JSON.stringify({message:`${mode?'Restore':'Archive'} replay ${path}`,content:src.content,branch:'main'})});await gh.api(`/contents/${path}`,{method:'DELETE',body:JSON.stringify({message:`Move replay to ${dest}`,sha:src.sha,branch:'main'})});selected.delete(path);await refreshLogs();}catch(e){log(`ARCHIVE FAILED: ${e.message}`)}}
async function uploadLogs(){const chosen=[...$('files').files];if(!chosen.length)return log('Choose CSV files first.');const max=20*1024*1024;try{const tree=await repoTree(),known=new Set(tree.map(x=>x.path.match(/([a-f0-9]{64})/i)?.[1]).filter(Boolean));let done=0;for(const f of chosen){if(f.size>max)throw Error(`${f.name} exceeds 20 MB browser-safe limit.`);const buf=await f.arrayBuffer(),hash=await sha256(buf);if(known.has(hash)){log(`Duplicate skipped: ${f.name}`);continue;}const baseName=`${hash}-${safeName(f.name)}`,path=`tests/replays/${baseName}`,meta=`evidence/logs/${hash}.json`;const manifest={schema:'A17Y_EVIDENCE_LOG_V2',sha256:hash,name:f.name,path,uploadedAt:new Date().toISOString(),size:f.size,type:$('logType').value,vehicle:$('vehicle').value,surface:$('surface').value,notes:$('notes').value,edgeTx:$('edgeTx').value,elrs:$('elrs').value,luaSha:$('luaSha').value,ymlSha:$('ymlSha').value};await gh.api(`/contents/${path}`,{method:'PUT',body:JSON.stringify({message:`Import replay ${f.name} [${hash}]`,content:bytesToB64(buf),branch:'main'})});await gh.api(`/contents/${meta}`,{method:'PUT',body:JSON.stringify({message:`Record evidence manifest ${hash}`,content:btoa(unescape(encodeURIComponent(JSON.stringify(manifest,null,2)))),branch:'main'})});known.add(hash);done++;$('uploadBar').style.width=`${done/chosen.length*100}%`;buf.byteLength;await sleep(80);}log(`Uploaded ${done} new replay(s) with manifests.`);await refreshLogs();}catch(e){log(`UPLOAD FAILED: ${e.message}`)}}
function addLabel(){if(!currentFile)return log('Open a log first.');const label=makeLabel(currentFile,$('labelStart').value,$('labelEnd').value,$('labelType').value,$('labelNote').value),q=JSON.parse(localStorage.getItem(QUEUE)||'[]');q.push(label);localStorage.setItem(QUEUE,JSON.stringify(q));renderQueue();}
function renderQueue(){const q=JSON.parse(localStorage.getItem(QUEUE)||'[]');$('queue').innerHTML=q.map(x=>`<div class="chip">${esc(x.type)} · ${esc(x.file)} [${x.start}-${x.end}]</div>`).join('')||'<span class="small">No queued labels.</span>';}
async function syncQueue(){const q=JSON.parse(localStorage.getItem(QUEUE)||'[]');for(const x of q){const path=`evidence/labels/${x.id}.json`;await gh.api(`/contents/${path}`,{method:'PUT',body:JSON.stringify({message:`Add ground-truth label ${x.id}`,content:btoa(unescape(encodeURIComponent(JSON.stringify(x,null,2)))),branch:'main'})});}localStorage.removeItem(QUEUE);renderQueue();log(`Synced ${q.length} label(s).`);}
async function dispatchBuilder(generate=true,ref='main'){const id=requestId(),inputs={child:$('child').value.trim(),mission:$('mission').value.trim(),generate:String(generate),logs:[...selected].join(' '),model:$('model').value.trim(),request_id:id};await gh.dispatch('workbench.yml',ref,inputs);activeRun={requestId:id,workflow:'workbench.yml',ref,startedAt:Date.now()};saveDraft();log(`Builder dispatched: ${id} on ${ref}`);await trackRun();}
async function dispatchDirector(){const id=requestId();await gh.dispatch('autonomous-director.yml','main',{mission:$('mission').value.trim(),logs:[...selected].join(' '),model:$('model').value.trim(),request_id:id});activeRun={requestId:id,workflow:'autonomous-director.yml',ref:'main',startedAt:Date.now()};saveDraft();log(`Director dispatched: ${id}`);await trackRun();}
async function trackRun(){if(!activeRun)return;for(let i=0;i<20;i++){const d=await gh.runs('event=workflow_dispatch&per_page=50'),run=(d.workflow_runs||[]).find(r=>(r.display_title||'').includes(activeRun.requestId)||(r.name||'').includes(activeRun.requestId));if(run){activeRun.runId=run.id;activeRun.url=run.html_url;saveDraft();await showRun(run);return;}await sleep(1500);}log('Run dispatched but exact request ID not visible yet. Refresh Runs.');}
async function refreshRuns(){try{const d=await gh.runs(`per_page=50&page=${$('runPage').value||1}`),wanted=(d.workflow_runs||[]).filter(r=>/workbench|director|mission|completion/i.test(`${r.path} ${r.name} ${r.display_title}`));$('runs').innerHTML=wanted.map(r=>runCard(r)).join('')||'<div class="small">No runs found.</div>';$('rate').textContent=`API remaining: ${gh.rate.remaining??'?'}`;}catch(e){$('runs').innerHTML=`<div class="bad">${esc(e.message)}</div>`;}}
function runCard(r){const state=r.status==='completed'?(r.conclusion==='success'?'pass':'fail'):'pending';return`<div class="item"><span class="badge ${state}">${esc(r.status==='completed'?r.conclusion:r.status)}</span><div><b>${esc(r.display_title||r.name)}</b><div class="small">#${r.run_number} · ${esc(r.head_branch||'')} · ${new Date(r.created_at).toLocaleString()}</div></div><div class="actions"><button class="btn" data-showrun="${r.id}">DETAILS</button><button class="btn good" data-artifacts="${r.id}">ARTIFACTS</button>${r.status==='in_progress'||r.status==='queued'?`<button class="btn danger" data-cancel="${r.id}">CANCEL</button>`:''}${r.status==='completed'&&r.conclusion!=='success'?`<button class="btn warn" data-rerun="${r.id}">RETRY FAILED</button>`:''}</div></div>`;}
async function bindRunButtons(){document.querySelectorAll('[data-showrun]').forEach(b=>b.onclick=async()=>showRunById(b.dataset.showrun));document.querySelectorAll('[data-artifacts]').forEach(b=>b.onclick=()=>showArtifacts(b.dataset.artifacts));document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{await gh.cancel(b.dataset.cancel);refreshRuns()});document.querySelectorAll('[data-rerun]').forEach(b=>b.onclick=async()=>{await gh.rerun(b.dataset.rerun);refreshRuns()});}
async function showRunById(id){const d=await gh.runs('per_page=100'),r=(d.workflow_runs||[]).find(x=>String(x.id)===String(id));if(r)showRun(r);}
async function showRun(r){const j=await gh.jobs(r.id),steps=(j.jobs||[]).flatMap(job=>job.steps.map(s=>({job:job.name,...s})));$('timeline').innerHTML=steps.map(s=>`<div class="stage ${s.conclusion==='success'?'pass':s.conclusion==='failure'?'fail':s.status==='in_progress'?'active':''}"><div>${s.conclusion==='success'?'✓':s.conclusion==='failure'?'✕':'•'}</div><div><b>${esc(s.name)}</b><div class="small">${esc(s.job)} · ${esc(s.status)} ${s.conclusion?`· ${esc(s.conclusion)}`:''}</div></div></div>`).join('');$('activeRunTitle').textContent=r.display_title||r.name;location.hash='runDetails';}
async function showArtifacts(id){const d=await gh.artifacts(id),box=$('artifacts');box.innerHTML=(d.artifacts||[]).map(a=>`<div class="item"><span>📦</span><div><b>${esc(a.name)}</b><div class="small">${(a.size_in_bytes/1024/1024).toFixed(2)} MB · expires ${new Date(a.expires_at).toLocaleDateString()}</div></div><button class="btn good" data-download-art="${a.id}" data-name="${esc(a.name)}.zip">DOWNLOAD ZIP</button></div>`).join('')||'<div class="small">No artifacts.</div>';box.querySelectorAll('[data-download-art]').forEach(b=>b.onclick=()=>gh.downloadArtifact(b.dataset.downloadArt,b.dataset.name));location.hash='artifacts';}
async function createCandidate(build=false){const f=$('lua').files[0];if(!f)throw Error('Choose a Lua file.');const text=await f.text(),digest=await sha256(new TextEncoder().encode(text)),id=`${Date.now()}-${digest.slice(0,12)}-${crypto.getRandomValues(new Uint16Array(1))[0].toString(16)}`,branch=`candidate/mobile-${id}`,path=`candidates/mobile/${id}/source.lua`,ref=await gh.api('/git/ref/heads/main');$('sourcePreview').textContent=text.slice(0,30000);$('sourceSha').textContent=digest;await gh.api('/git/refs',{method:'POST',body:JSON.stringify({ref:`refs/heads/${branch}`,sha:ref.object.sha})});await gh.api(`/contents/${path}`,{method:'PUT',body:JSON.stringify({message:`Add immutable candidate ${id}`,content:btoa(unescape(encodeURIComponent(text))),branch})});$('candidateBranch').value=branch;$('child').value=path;saveDraft();log(`Candidate ${path} created on ${branch}`);if(build)await dispatchBuilder(false,branch);}
async function loadCandidates(){const tree=await repoTree(),cs=tree.filter(x=>x.path.startsWith('candidates/')&&x.path.endsWith('.lua')).slice(-100);$('candidates').innerHTML=cs.map(x=>`<div class="item"><span>🧬</span><div><b>${esc(x.path)}</b><div class="small">${x.sha.slice(0,12)}</div></div><button class="btn" data-usecandidate="${esc(x.path)}">USE</button></div>`).join('');$('candidates').querySelectorAll('[data-usecandidate]').forEach(b=>b.onclick=()=>{$('child').value=b.dataset.usecandidate;saveDraft()});}
function wire(){tokenUI();loadDraft();renderQueue();['mission','model','child','candidateBranch'].forEach(id=>$(id).addEventListener('input',saveDraft));$('saveToken').onclick=connect;$('clearToken').onclick=()=>{gh.clear();tokenUI()};$('upload').onclick=uploadLogs;$('refreshLogs').onclick=refreshLogs;$('search').oninput=e=>{query=e.target.value.toLowerCase();page=1;renderLogs()};$('prev').onclick=()=>{page=Math.max(1,page-1);renderLogs()};$('next').onclick=()=>{page++;renderLogs()};$('showArchive').onchange=e=>{archived=e.target.checked;selected.clear();refreshLogs()};$('selectAll').onclick=()=>{filtered().forEach(f=>selected.add(f.path));renderLogs()};$('clearSelection').onclick=()=>{selected.clear();renderLogs()};$('closeViewer').onclick=()=>$('viewer').classList.add('hidden');$('addLabel').onclick=addLabel;$('syncLabels').onclick=()=>syncQueue().catch(e=>log(e.message));$('runBuilder').onclick=()=>dispatchBuilder(!$('child').value.trim(),$('candidateBranch').value.trim()||'main').catch(e=>log(e.message));$('runDirector').onclick=()=>dispatchDirector().catch(e=>log(e.message));$('createCandidate').onclick=()=>createCandidate(false).catch(e=>log(e.message));$('createBuild').onclick=()=>createCandidate(true).catch(e=>log(e.message));$('refreshRuns').onclick=async()=>{await refreshRuns();bindRunButtons()};$('loadCandidates').onclick=loadCandidates;$('resume').onclick=()=>activeRun?.runId?showRunById(activeRun.runId):trackRun();document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));if(gh.token){connect().catch(()=>{})}setInterval(()=>{if(!document.hidden&&gh.token)refreshRuns().then(bindRunButtons).catch(()=>{})},30000);}
wire();