import{GitHubClient,BASE,sha256}from'./api.js';
const gh=new GitHubClient(),$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),bound=new WeakSet(),bypass=new WeakSet();
async function dependencyGuard(btn){if(bypass.has(btn)){bypass.delete(btn);return;}const path=btn.dataset.archive;if(!path)return;const q=encodeURIComponent(`"${path}" repo:gymwhaleysspot-dot/mt12-jarvis-continuous`);let deps=[];try{const d=await gh.request(`https://api.github.com/search/code?q=${q}`);deps=(d.items||[]).filter(x=>x.path!==path).slice(0,10).map(x=>x.path);}catch{}if(deps.length&&!confirm(`This replay is referenced by ${deps.length} repository file(s):\n\n${deps.join('\n')}\n\nContinue to the archive confirmation?`))return;bypass.add(btn);btn.onclick?.();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-archive]');if(!b||bypass.has(b))return;e.preventDefault();e.stopImmediatePropagation();dependencyGuard(b).catch(x=>alert(x.message));},true);
async function previewCandidate(){const f=$('lua')?.files?.[0];if(!f)return;const text=await f.text(),digest=await sha256(new TextEncoder().encode(text));$('sourceSha').textContent=digest;let diff='';try{const d=await gh.api('/contents/a17y.lua?ref=main'),parent=decodeURIComponent(escape(atob(d.content.replace(/\n/g,'')))),A=parent.split(/\r?\n/),B=text.split(/\r?\n/),n=Math.max(A.length,B.length),out=[];for(let i=0;i<n&&out.length<300;i++)if(A[i]!==B[i])out.push(`@@ line ${i+1}\n- ${A[i]??''}\n+ ${B[i]??''}`);diff=out.join('\n');}catch(e){diff=`Parent diff unavailable: ${e.message}`;}$('sourcePreview').textContent=`SOURCE SHA-256 ${digest}\nSIZE ${new Blob([text]).size} bytes\n\nCHANGED LINES PREVIEW\n${diff||'No line differences detected.'}\n\nSOURCE PREVIEW\n${text.slice(0,20000)}`;}
$('lua')?.addEventListener('change',()=>previewCandidate().catch(e=>alert(e.message)));
async function branchCatalog(){try{const branches=await gh.api('/branches?per_page=100'),c=branches.filter(b=>b.name.startsWith('candidate/'));let box=document.getElementById('branchCatalog');if(!box){box=document.createElement('div');box.id='branchCatalog';box.className='chips';$('candidates').before(box);}box.innerHTML=c.map(b=>`<button class="btn" data-branch="${esc(b.name)}">${esc(b.name)}</button>`).join('')||'<span class="small">No candidate branches.</span>';box.querySelectorAll('[data-branch]').forEach(b=>b.onclick=()=>{$('candidateBranch').value=b.dataset.branch;localStorage.setItem('a17y_last_candidate_branch',b.dataset.branch);});}catch(e){alert(e.message)}}
const branchButton=document.createElement('button');branchButton.className='btn';branchButton.textContent='LOAD BRANCHES';branchButton.onclick=branchCatalog;$('loadCandidates')?.after(branchButton);
async function artifacts(id){const d=await gh.artifacts(id),box=$('artifacts');box.innerHTML=(d.artifacts||[]).map(a=>`<div class="item"><span>📦</span><div><b>${esc(a.name)}</b><div class="small">${(a.size_in_bytes/1048576).toFixed(2)} MB</div></div><button class="btn good" data-direct-art="${a.id}" data-name="${esc(a.name)}.zip">DOWNLOAD ZIP</button></div>`).join('')||'<div class="small">No artifacts found.</div>';box.querySelectorAll('[data-direct-art]').forEach(b=>b.onclick=()=>gh.downloadArtifact(b.dataset.directArt,b.dataset.name));location.hash='artifacts';}
async function details(id){const d=await gh.jobs(id),steps=(d.jobs||[]).flatMap(j=>j.steps.map(s=>({job:j.name,...s})));$('timeline').innerHTML=steps.map(s=>`<div class="stage ${s.conclusion==='success'?'pass':s.conclusion==='failure'?'fail':s.status==='in_progress'?'active':''}"><div>${s.conclusion==='success'?'✓':s.conclusion==='failure'?'✕':'•'}</div><div><b>${esc(s.name)}</b><div class="small">${esc(s.job)} · ${esc(s.status)}${s.conclusion?` · ${esc(s.conclusion)}`:''}</div></div></div>`).join('');location.hash='runDetails';}
function bindRunControls(){document.querySelectorAll('[data-showrun],[data-artifacts],[data-cancel],[data-rerun]').forEach(b=>{if(bound.has(b))return;bound.add(b);if(b.dataset.showrun)b.addEventListener('click',()=>details(b.dataset.showrun));if(b.dataset.artifacts)b.addEventListener('click',()=>artifacts(b.dataset.artifacts));if(b.dataset.cancel)b.addEventListener('click',async()=>{await gh.cancel(b.dataset.cancel);$('refreshRuns').click()});if(b.dataset.rerun)b.addEventListener('click',async()=>{await gh.rerun(b.dataset.rerun);$('refreshRuns').click()});});}
new MutationObserver(bindRunControls).observe($('runs'),{childList:true,subtree:true});bindRunControls();
for(const id of['auth','console','runs','timeline','artifacts'])$(id)?.setAttribute('aria-live','polite');
window.addEventListener('online',()=>{const q=JSON.parse(localStorage.getItem('a17y_offline_queue_v2')||'[]');if(q.length)$('console').textContent=`Internet restored. ${q.length} ground-truth label(s) are waiting to sync.\n`+$('console').textContent;});