import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';
const ROOT=process.cwd(),now=new Date().toISOString(),readJSON=(p,d)=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return d}},walk=(dir,ext)=>{if(!fs.existsSync(dir))return[];const out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())out.push(...walk(p,ext));else if(!ext||p.endsWith(ext))out.push(p)}return out},hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const old=readJSON('chief-engineer/memory.json',{lessons:[],history:[],confidence:{},hardwareFingerprint:null});
const logs=walk('tests/replays','.csv'),missions=walk('engineering-missions').filter(p=>/MISSION\.json$/i.test(p)),evidence=walk('evidence').filter(p=>/\.json$/i.test(p)),research=readJSON('research/current.json',{}),completion=readJSON('public/completion-data/dashboard.json',{}),missionCurrent=readJSON('public/mission-data/current.json',{});
const topics={jump:['jump','air','land'],traction:['tc','slip','traction'],braking:['abs','brake','lock'],gps:['gps','location'],rpm:['rpm','speed','lag'],dropout:['drop','freeze','missing'],memory:['memory','heap','gc'],logging:['log','csv','blackbox'],gyro:['gyro','steer','yaw']};
const samples={};for(const k of Object.keys(topics))samples[k]={mentions:0,logs:0,positive:0,negative:0};
for(const file of logs){let text='';try{text=fs.readFileSync(file,'utf8').slice(0,250000).toLowerCase()}catch{};for(const[k,words]of Object.entries(topics)){if(words.some(w=>text.includes(w))){samples[k].logs++;samples[k].mentions+=words.reduce((n,w)=>n+(text.match(new RegExp(w,'g'))||[]).length,0)}}}
const docs=[...evidence,...missions];for(const file of docs){let text='';try{text=fs.readFileSync(file,'utf8').toLowerCase()}catch{};for(const[k,words]of Object.entries(topics))if(words.some(w=>text.includes(w))){samples[k].mentions++;if(/pass|improv|verified|success/.test(text))samples[k].positive++;if(/fail|regress|false|missing|blocked|error/.test(text))samples[k].negative++}}
const subsystem=Object.entries(samples).map(([name,s])=>{const volume=Math.min(1,(s.logs*2+s.mentions/30)/20),agreement=(s.positive+1)/(s.positive+s.negative+2),physical=name==='memory'?Boolean(completion?.certificates?.MT12_RUNTIME?.status==='PASS'):true;let confidence=Math.round(100*(.25+.45*volume+.3*agreement));if(!physical)confidence=Math.min(confidence,69);const risk=Math.min(100,Math.round((s.negative*18)+(1-volume)*35+(physical?0:20)));const expectedGain=Math.max(1,Math.round((100-confidence)*.35+risk*.25));return{name,confidence,risk,expectedGain,evidenceLogs:s.logs,mentions:s.mentions,physicalAuthority:physical?'AVAILABLE':'PENDING'}}).sort((a,b)=>b.risk-a.risk);
const contradictions=[];for(const s of subsystem)if(samples[s.name].positive>0&&samples[s.name].negative>0)contradictions.push({topic:s.name,severity:Math.min(100,25+samples[s.name].negative*15),statement:`Evidence contains both successful and adverse outcomes for ${s.name}.`,action:'Create a targeted mission using the newest contradictory sessions.'});
const backlog=subsystem.map(s=>{const complexity=['memory','dropout'].includes(s.name)?3:['jump','traction','braking'].includes(s.name)?2:1,priority=Math.round((s.risk*.42+s.expectedGain*.38+(100-s.confidence)*.2)/complexity);return{id:`ce-${s.name}`,title:`Improve ${s.name} intelligence`,topic:s.name,priority,confidence:s.confidence,expectedGain:s.expectedGain,complexity:['','Low','Medium','High'][complexity],reason:`Risk ${s.risk}; confidence ${s.confidence}%; ${s.evidenceLogs} replay log(s) provide direct observability.`,recommendedMission:`Diagnose and improve ${s.name} using the latest selected evidence. Preserve all protected behavior and require replay, bench, and road authority before promotion.`}}).sort((a,b)=>b.priority-a.priority);
const nodes=[...logs.map(p=>({id:hash(p).slice(0,16),type:'drive-log',path:p})),...missions.map(p=>({id:hash(p).slice(0,16),type:'mission',path:p})),...evidence.map(p=>({id:hash(p).slice(0,16),type:'evidence',path:p})),...subsystem.map(s=>({id:`subsystem:${s.name}`,type:'subsystem',...s}))];
const edges=[];for(const n of nodes.filter(n=>n.type==='drive-log'))for(const s of subsystem)if(samples[s.name].logs)edges.push({from:n.id,to:`subsystem:${s.name}`,relation:'observes'});for(const n of nodes.filter(n=>n.type==='mission'))for(const s of subsystem)edges.push({from:n.id,to:`subsystem:${s.name}`,relation:'evaluates'});
const score={overall:Math.round(subsystem.reduce((n,s)=>n+s.confidence,0)/Math.max(1,subsystem.length)),safety:Math.round(100-subsystem.filter(s=>['traction','braking','dropout'].includes(s.name)).reduce((n,s)=>n+s.risk,0)/3),evidence:Math.min(100,logs.length*4+evidence.length*3),hardware:completion?.overall==='PASS'?100:55,release:missionCurrent?.releaseLadder?.stage==='TRUSTED_RELEASE'?100:65};
const dashboard={schema:1,generatedAt:now,chiefEngineer:{mode:'evidence-bounded autonomous coordination',authority:'RECOMMEND_AND_DISPATCH_ONLY',autoPromotion:false},score,subsystems:subsystem,backlog,contradictions,graph:{nodes:nodes.length,edges:edges.length},topRecommendation:backlog[0]||null,currentMission:missionCurrent?.mission||null,researchDigest:research?.summary||research?.status||'No structured research summary available.',completionStatus:completion?.overall||'PENDING'};
const memory={...old,updatedAt:now,confidence:Object.fromEntries(subsystem.map(s=>[s.name,s.confidence])),history:[...(old.history||[]),{at:now,score:score.overall,top:backlog[0]?.topic||null}].slice(-200),lessons:[...(old.lessons||[]),...contradictions.map(c=>({at:now,type:'contradiction',topic:c.topic,statement:c.statement}))].slice(-500)};
fs.mkdirSync('public/chief-data',{recursive:true});fs.writeFileSync('public/chief-data/dashboard.json',JSON.stringify(dashboard,null,2));fs.writeFileSync('public/chief-data/graph.json',JSON.stringify({generatedAt:now,nodes,edges},null,2));fs.writeFileSync('public/chief-data/backlog.json',JSON.stringify({generatedAt:now,items:backlog},null,2));fs.writeFileSync('public/chief-data/contradictions.json',JSON.stringify({generatedAt:now,items:contradictions},null,2));fs.writeFileSync('chief-engineer/memory.json',JSON.stringify(memory,null,2));console.log(JSON.stringify({score:score.overall,top:backlog[0],nodes:nodes.length,edges:edges.length},null,2));