#!/usr/bin/env node
import fs from'node:fs';import fsp from'node:fs/promises';import path from'node:path';import os from'node:os';import crypto from'node:crypto';import{execFileSync,spawn}from'node:child_process';
const root=path.resolve(import.meta.dirname,'..'),stateDir=path.join(os.homedir(),'.a17y-mt12'),statePath=path.join(stateDir,'state.json');fs.mkdirSync(stateDir,{recursive:true});
const readJson=(p,f)=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return f}},state=readJson(statePath,{schema:1,seen:{},history:[]});
const save=()=>fs.writeFileSync(statePath,JSON.stringify(state,null,2)+'\n');const sha=async p=>crypto.createHash('sha256').update(await fsp.readFile(p)).digest('hex');
function volumes(){let a=[];if(process.platform==='win32'){try{const s=execFileSync('powershell',['-NoProfile','-Command','Get-Volume | Where-Object {$_.DriveLetter} | Select-Object -ExpandProperty DriveLetter | ConvertTo-Json'],{encoding:'utf8'});const v=JSON.parse(s);a=(Array.isArray(v)?v:[v]).filter(Boolean).map(x=>`${x}:\\`)}catch{}}else{for(const d of process.platform==='darwin'?['/Volumes']:[`/media/${os.userInfo().username}`,`/run/media/${os.userInfo().username}`,'/mnt'])if(fs.existsSync(d))for(const n of fs.readdirSync(d))a.push(path.join(d,n))}return[...new Set(a)].filter(fs.existsSync)}
function detect(){const out=[];for(const m of volumes()){const name=path.basename(m).toUpperCase(),logs=path.join(m,'LOGS');if(name.includes('EDGETX_UF2'))out.push({type:'UF2',mount:m});else if(fs.existsSync(logs)||fs.existsSync(path.join(m,'MODELS'))||fs.existsSync(path.join(m,'RADIO')))out.push({type:'MT12_STORAGE',mount:m,logs})}return out}
async function walk(d,a=[]){if(!fs.existsSync(d))return a;for(const e of await fsp.readdir(d,{withFileTypes:true})){const p=path.join(d,e.name);e.isDirectory()?await walk(p,a):a.push(p)}return a}
async function sync(mount,{push=false}={}){const logs=path.join(mount,'LOGS'),dst=path.join(root,'tests','replays');await fsp.mkdir(dst,{recursive:true});let added=[];for(const p of await walk(logs)){if(!/\.csv$/i.test(p))continue;const h=await sha(p);if(state.seen[h])continue;const n=`mt12-${new Date().toISOString().replace(/[:.]/g,'-')}-${path.basename(p)}`;await fsp.copyFile(p,path.join(dst,n));state.seen[h]={source:p,dest:`tests/replays/${n}`,at:new Date().toISOString()};added.push(n)}state.history.unshift({at:new Date().toISOString(),action:'sync',mount,added});save();if(push&&added.length){execFileSync('git',['add','tests/replays'],{cwd:root,stdio:'inherit'});execFileSync('git',['commit','-m',`Import ${added.length} MT12 logs`],{cwd:root,stdio:'inherit'});execFileSync('git',['push'],{cwd:root,stdio:'inherit'})}return added}
async function backup(mount){const stamp=new Date().toISOString().replace(/[:.]/g,'-'),out=path.join(stateDir,'backups',stamp);await fsp.mkdir(out,{recursive:true});const files=[];for(const p of await walk(mount)){const rel=path.relative(mount,p);if(rel.startsWith('.Trash'))continue;const q=path.join(out,'files',rel);await fsp.mkdir(path.dirname(q),{recursive:true});await fsp.copyFile(p,q);files.push({path:rel,bytes:(await fsp.stat(p)).size,sha256:await sha(p)})}const manifest={schema:1,radio:'RadioMaster MT12',createdAt:new Date().toISOString(),mount,files};await fsp.writeFile(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');state.history.unshift({at:new Date().toISOString(),action:'backup',out,files:files.length});save();return out}
async function flashEdgeTx(firmware,mount){if(!/\.uf2$/i.test(firmware))throw Error('MT12 safe updater requires an official .uf2 firmware file');if(path.basename(mount).toUpperCase()!=='EDGETX_UF2')throw Error('EDGETX_UF2 drive not detected');const before=await sha(firmware),dest=path.join(mount,path.basename(firmware));await fsp.copyFile(firmware,dest);const after=await sha(dest);if(before!==after)throw Error('UF2 copy verification failed');state.history.unshift({at:new Date().toISOString(),action:'edgetx-uf2-copy',firmware,sha256:before,mount,status:'copied-verified'});save();return{sha256:before,dest}}
function findConfigurator(){const c=process.platform==='win32'?[path.join(process.env.LOCALAPPDATA||'','Programs','ExpressLRS Configurator','ExpressLRS Configurator.exe')]:process.platform==='darwin'?['/Applications/ExpressLRS Configurator.app/Contents/MacOS/ExpressLRS Configurator']:['expresslrs-configurator','ExpressLRS Configurator'];for(const p of c){if(p.includes(path.sep)&&fs.existsSync(p))return p;if(!p.includes(path.sep)){try{execFileSync('which',[p],{stdio:'ignore'});return p}catch{}}}return null}
function openElrs(profile){const exe=findConfigurator();if(!exe)throw Error('ExpressLRS Configurator is not installed');const env={...process.env,A17Y_ELRS_PROFILE:path.resolve(profile)};spawn(exe,[],{detached:true,stdio:'ignore',env}).unref();state.history.unshift({at:new Date().toISOString(),action:'open-elrs-configurator',profile:path.resolve(profile)});save()}
async function watch(){console.log('A17Y MT12 helper watching for connections. Ctrl+C to stop.');let known='';setInterval(async()=>{const d=detect(),key=JSON.stringify(d);if(key===known)return;known=key;console.log(new Date().toISOString(),d);for(const x of d)if(x.type==='MT12_STORAGE')try{const a=await sync(x.mount,{push:process.env.A17Y_AUTO_PUSH==='1'});if(a.length)console.log('Imported',a)}catch(e){console.error(e.message)}},2500)}
const[cmd,...args]=process.argv.slice(2);try{if(cmd==='detect')console.log(JSON.stringify(detect(),null,2));else if(cmd==='sync'){const m=args[0]||detect().find(x=>x.type==='MT12_STORAGE')?.mount;if(!m)throw Error('MT12 storage not found');console.log(await sync(m,{push:args.includes('--push')}))}else if(cmd==='backup'){const m=args[0]||detect().find(x=>x.type==='MT12_STORAGE')?.mount;if(!m)throw Error('MT12 storage not found');console.log(await backup(m))}else if(cmd==='flash-edgetx'){const m=args[1]||detect().find(x=>x.type==='UF2')?.mount;if(!args[0]||!m)throw Error('Usage: flash-edgetx firmware.uf2 [EDGETX_UF2 mount]');console.log(await flashEdgeTx(args[0],m))}else if(cmd==='open-elrs'){if(!args[0])throw Error('Usage: open-elrs profile.json');openElrs(args[0])}else if(cmd==='watch'||!cmd)await watch();else throw Error('Commands: detect, watch, sync [mount] [--push], backup [mount], flash-edgetx firmware.uf2 [mount], open-elrs profile.json')}catch(e){console.error('ERROR:',e.message);process.exit(1)}
