#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
const cfg=JSON.parse(fs.readFileSync('protected/a17y-contract.json','utf8')),out=path.resolve(process.env.RCOS_OUT||'dist-rcos');
const parent=path.resolve(process.argv[2]||cfg.parent),child=path.resolve(process.argv[3]||process.argv[2]||cfg.parent),mission=(process.argv[4]||'Exact deterministic release').trim(),logs=process.argv.slice(5).filter(fs.existsSync);
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),run=(c,a,o={})=>execFileSync(c,a,{encoding:'utf8',maxBuffer:256*1024*1024,...o}),fail=m=>{throw Error('RCOS REJECTED: '+m)};
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});for(const p of [parent,child])if(!fs.existsSync(p))fail('missing '+p);if(sha(parent)!==cfg.sha256)fail('protected parent SHA mismatch');
const stripComments=s=>s.replace(/--\[\[[\s\S]*?\]\]/g,'').replace(/--[^\n]*/g,'');
function inspect(p,role){const raw=fs.readFileSync(p,'utf8'),s=stripComments(raw);for(const x of cfg.required)if(!s.includes(x))fail(role+' executable contract missing '+x);for(const x of cfg.forbidden)if(s.includes(x))fail(role+' forbidden '+x);if(/\dlocal\s+[A-Za-z_]/.test(s)||/local\s+[A-Za-z_]\w*\s*=\s*[^;\n]+local\s+[A-Za-z_]/.test(s))fail(role+' joined declaration');run('luac5.3',['-p',p]);return raw}
const ps=inspect(parent,'parent'),cs=inspect(child,'child');
function compile(p,n){const q=path.join(out,n+'.luac');run('bash',['toolchain/compile_mt12.sh',p,q],{env:{...process.env,MAX_BYTES:String(cfg.maxNormalizedBytes)}});if(fs.readFileSync(q).subarray(12,17).toString('hex')!=='0404040404')fail(n+' bad MT12 header');return q}
const pl=compile(parent,'parent'),cl=compile(child,'child');
function trace(p,n){const q=path.join(out,n+'-trace.csv');run('lua5.3',['scripts/mt12-harness.lua',p,q]);return q}const pt=trace(parent,'parent'),ct=trace(child,'child');
const rows=p=>fs.readFileSync(p,'utf8').trim().split(/\r?\n/).map(x=>x.split(','));
function compare(a,b){if(a.length!==b.length)return{lengthMismatch:true,changedRows:Math.max(a.length,b.length),maxDelta:1e9,totalDelta:1e9,points:[]};let changedRows=0,maxDelta=0,totalDelta=0;const points=[];for(let i=1;i<a.length;i++){let row=false,rd=0;for(let j=1;j<Math.min(a[i].length,b[i].length);j++){const x=Number(a[i][j]),y=Number(b[i][j]);if(Number.isFinite(x)&&Number.isFinite(y)){const d=Math.abs(x-y);if(d){row=true;rd=Math.max(rd,d);maxDelta=Math.max(maxDelta,d);totalDelta+=d}}}if(row){changedRows++;if(points.length<50)points.push({row:i,maxDelta:rd})}}return{changedRows,maxDelta,totalDelta,points}}
const synthetic=compare(rows(pt),rows(ct));
const replay=[];let replayChangedRows=0,replayMaxDelta=0,replayRows=0;
for(let i=0;i<logs.length;i++){const f=logs[i],p=path.join(out,`replay-${i+1}-parent.csv`),c=path.join(out,`replay-${i+1}-child.csv`);let pm,cm;try{pm=JSON.parse(run('lua5.3',['scripts/mt12-csv-replay.lua',parent,f,p]).trim());cm=JSON.parse(run('lua5.3',['scripts/mt12-csv-replay.lua',child,f,c]).trim());if(pm.rows<1||cm.rows<1)throw Error('log has no data rows');if(pm.mapped<2||cm.mapped<2)throw Error(`insufficient telemetry mapping (${pm.mapped}/${cm.mapped})`)}catch(e){replay.push({file:path.basename(f),sha256:sha(f),executed:false,error:String(e.message).slice(0,1000)});continue}const cmp=compare(rows(p),rows(c));replayRows+=Math.min(pm.rows,cm.rows);replayChangedRows+=cmp.changedRows;replayMaxDelta=Math.max(replayMaxDelta,cmp.maxDelta);replay.push({file:path.basename(f),sha256:sha(f),executed:true,rows:pm.rows,mapped:pm.mapped,comparison:cmp})}
const executed=replay.filter(x=>x.executed),lower=mission.toLowerCase();let passed=true;const reasons=[];
if(lower.includes('without regress')||lower.includes('preserve')){if(synthetic.maxDelta>cfg.maximumOutputDelta){passed=false;reasons.push(`synthetic max delta >${cfg.maximumOutputDelta}`)}if(replayMaxDelta>cfg.maximumOutputDelta){passed=false;reasons.push(`recorded replay max delta >${cfg.maximumOutputDelta}`)}}
if(child!==parent&&synthetic.changedRows===0&&replayChangedRows===0){passed=false;reasons.push('candidate has no measurable behavior change')}
if(logs.length&&executed.length===0){passed=false;reasons.push('no uploaded log had enough mapped telemetry to execute')}
const missionMetrics={passed,reasons,syntheticChangedRows:synthetic.changedRows,syntheticMaxDelta:synthetic.maxDelta,replayChangedRows,replayMaxDelta,replayRows,executedLogs:executed.length,totalLogs:logs.length};
const systems=['Sensors','Truth speed','Jump detection','TC','ABS','Gyro','Learning','Persistence','Voice','Dashboard','Logging'],words={Sensors:['GPS_LOST','gps','sensor'],'Truth speed':['rpmMph','RPM2MPH','truth'],'Jump detection':['jump','air','land'],TC:['TC','tc'],ABS:['ABS','abs'],Gyro:['GYR','gyro','vG'],Learning:['learn','score','adapt'],Persistence:['MEMPATH','wrmem','rdmem'],Voice:['voice','mood','trait'],Dashboard:['lcd.','page'],Logging:['bb_','LOGS','io.write']};
const diff=systems.map(s=>{const ks=words[s],pc=ks.reduce((n,k)=>n+(ps.split(k).length-1),0),cc=ks.reduce((n,k)=>n+(cs.split(k).length-1),0);return{system:s,parentSignals:pc,childSignals:cc,changed:pc!==cc}});
const authority=executed.length?'REPLAY VERIFIED':logs.length?'LOG EVIDENCE UNEXECUTABLE':'SIMULATION PASSED';
const report={product:'A17Y RC Engineering OS',mission,stages:{verifier:'PASSED',recordedReplay:executed.length?'EXECUTED':logs.length?'UNEXECUTABLE':'NO LOGS',releaseManager:passed?'EVIDENCE GATES PASSED':'REJECTED'},parent:{file:path.basename(parent),sha256:sha(parent),sourceBytes:fs.statSync(parent).size,normalizedBytes:fs.statSync(pl).size},child:{file:path.basename(child),sha256:sha(child),sourceBytes:fs.statSync(child).size,normalizedBytes:fs.statSync(cl).size},comparison:{sameSource:sha(parent)===sha(child),sameBytecode:sha(pl)===sha(cl),...synthetic},systems:diff,replays:replay,replayExecution:{executed:executed.length>0,executedLogs:executed.length,totalLogs:logs.length,rows:replayRows,changedRows:replayChangedRows,maxDelta:replayMaxDelta},missionMetrics,promotion:{current:authority,bench:false,road:false,automatic:false},generatedAt:new Date().toISOString()};
fs.copyFileSync(parent,path.join(out,'PARENT.lua'));fs.copyFileSync(child,path.join(out,'CHILD.lua'));fs.copyFileSync(cl,path.join(out,'DEPLOY.luac'));fs.writeFileSync(path.join(out,'REPORT.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(out,'DIFF.json'),JSON.stringify({systems:diff,synthetic:synthetic.points,replays:replay},null,2)+'\n');fs.writeFileSync(path.join(out,'PROMOTION.json'),JSON.stringify(report.promotion,null,2)+'\n');fs.writeFileSync(path.join(out,'CREW-CHIEF.txt'),[`Mission: ${mission}`,`Recorded logs executed: ${executed.length}/${logs.length}`,`Replay rows: ${replayRows}`,`Authority: ${authority}`,`Mission gates: ${passed?'PASS':'FAIL'}`,...reasons].join('\n')+'\n');if(!passed)fail('mission-specific evidence gates failed: '+reasons.join('; '));console.log(JSON.stringify(report,null,2));
