#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
const root=process.cwd(),cfg=JSON.parse(fs.readFileSync('protected/a17y-contract.json','utf8')),out=path.resolve(process.env.RCOS_OUT||'dist-rcos');
const parent=path.resolve(process.argv[2]||cfg.parent),child=path.resolve(process.argv[3]||process.argv[2]||cfg.parent),mission=(process.argv[4]||'Exact deterministic release').trim();
const logs=process.argv.slice(5).filter(Boolean),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),run=(c,a,o={})=>execFileSync(c,a,{encoding:'utf8',maxBuffer:128*1024*1024,...o}),fail=m=>{throw Error('RCOS REJECTED: '+m)};
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});for(const p of [parent,child])if(!fs.existsSync(p))fail('missing '+p);if(sha(parent)!==cfg.sha256)fail('protected parent SHA mismatch');
function inspect(p,role){const s=fs.readFileSync(p,'utf8');for(const x of cfg.required)if(!s.includes(x))fail(role+' missing '+x);for(const x of cfg.forbidden)if(s.includes(x))fail(role+' forbidden '+x);if(/\dlocal\s+[A-Za-z_]/.test(s)||/local\s+[A-Za-z_]\w*\s*=\s*[^;\n]+local\s+[A-Za-z_]/.test(s))fail(role+' joined declaration');run('luac5.3',['-p',p]);return s}
const ps=inspect(parent,'parent'),cs=inspect(child,'child');
function compile(p,n){const q=path.join(out,n+'.luac');run('bash',['toolchain/compile_mt12.sh',p,q],{env:{...process.env,MAX_BYTES:String(cfg.maxNormalizedBytes)}});if(fs.readFileSync(q).subarray(12,17).toString('hex')!=='0404040404')fail(n+' bad MT12 header');return q}
const pl=compile(parent,'parent'),cl=compile(child,'child');
function trace(p,n){const q=path.join(out,n+'-trace.csv');run('lua5.3',['scripts/mt12-harness.lua',p,q]);return q}const pt=trace(parent,'parent'),ct=trace(child,'child');
const rows=p=>fs.readFileSync(p,'utf8').trim().split(/\r?\n/).map(x=>x.split(',')),a=rows(pt),b=rows(ct);if(a.length!==b.length)fail('trace length changed');let changed=0,maxDelta=0,totalDelta=0;const points=[];for(let i=1;i<a.length;i++){let row=false,rd=0;for(let j=1;j<Math.min(a[i].length,b[i].length);j++){const x=Number(a[i][j]),y=Number(b[i][j]);if(Number.isFinite(x)&&Number.isFinite(y)){const d=Math.abs(x-y);if(d){row=true;rd=Math.max(rd,d);maxDelta=Math.max(maxDelta,d);totalDelta+=d}}}if(row){changed++;if(points.length<50)points.push({row:i,maxDelta:rd,parent:a[i],child:b[i]})}}
const systems=['Sensors','Truth speed','Jump detection','TC','ABS','Gyro','Learning','Persistence','Voice','Dashboard','Logging'];const words={Sensors:['GPS_LOST','gps','sensor'], 'Truth speed':['rpmMph','RPM2MPH','truth'], 'Jump detection':['jump','air','land'],TC:['TC','tc'],ABS:['ABS','abs'],Gyro:['GYR','gyro','vG'],Learning:['learn','score','adapt'],Persistence:['MEMPATH','wrmem','rdmem'],Voice:['voice','mood','trait'],Dashboard:['lcd.','page'],Logging:['bb_','LOGS','io.write']};
const diff=[];for(const s of systems){const ks=words[s],pc=ks.reduce((n,k)=>n+(ps.split(k).length-1),0),cc=ks.reduce((n,k)=>n+(cs.split(k).length-1),0);diff.push({system:s,parentSignals:pc,childSignals:cc,changed:pc!==cc})}
const replay=[];for(const f of logs){if(!fs.existsSync(f))continue;const text=fs.readFileSync(f,'utf8'),lines=text.split(/\r?\n/).filter(Boolean);replay.push({file:path.basename(f),bytes:fs.statSync(f).size,rows:Math.max(0,lines.length-1),sha256:sha(f),columns:lines[0]?.split(',').length||0})}
const report={product:'A17Y RC Engineering OS',mission,stages:{engineer:'MISSION RECORDED',verifier:'PASSED',replayLab:replay.length?'LOGS INDEXED':'NO LOGS',diffExplorer:'COMPLETE',crewChief:'COMPLETE',releaseManager:'SIMULATION PASSED'},parent:{file:path.basename(parent),sha256:sha(parent),sourceBytes:fs.statSync(parent).size,normalizedBytes:fs.statSync(pl).size},child:{file:path.basename(child),sha256:sha(child),sourceBytes:fs.statSync(child).size,normalizedBytes:fs.statSync(cl).size},comparison:{sameSource:sha(parent)===sha(child),sameBytecode:sha(pl)===sha(cl),changedRows:changed,maxDelta,totalDelta,points},systems:diff,replays:replay,promotion:{current:'SIMULATION PASSED',bench:false,road:false,automatic:false},generatedAt:new Date().toISOString()};
const crew=[`Mission: ${mission}.`,`Parent integrity verified: ${report.parent.sha256===cfg.sha256?'yes':'no'}.`,`Child compiled and normalized for MT12: yes.`,`Behavior trace changed on ${changed} rows; maximum numeric delta ${maxDelta}.`,replay.length?`${replay.length} real log file(s) indexed for evidence.`:'No real logs supplied; road claims are prohibited.',changed?'This child changes runtime behavior and requires focused bench review.':'This is a byte-for-byte behavior baseline build.','Promotion stops at SIMULATION PASSED until manual bench and road evidence is recorded.'];
fs.copyFileSync(parent,path.join(out,'PARENT.lua'));fs.copyFileSync(child,path.join(out,'CHILD.lua'));fs.copyFileSync(cl,path.join(out,'DEPLOY.luac'));fs.writeFileSync(path.join(out,'REPORT.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(out,'CREW-CHIEF.txt'),crew.join('\n')+'\n');fs.writeFileSync(path.join(out,'DIFF.json'),JSON.stringify({systems:diff,points},null,2)+'\n');fs.writeFileSync(path.join(out,'PROMOTION.json'),JSON.stringify(report.promotion,null,2)+'\n');console.log(JSON.stringify(report,null,2));