#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const cfg=JSON.parse(fs.readFileSync('protected/a17y-contract.json','utf8'));
const parent=path.resolve(process.argv[2]||cfg.parent);
const child=path.resolve(process.argv[3]||parent);
const mission=(process.argv[4]||process.env.WORKBENCH_MISSION||'Exact deterministic release').trim();
const out=path.resolve(process.env.WORKBENCH_OUT||'dist-workbench');
const logFile=process.env.WORKBENCH_LOG_FILE;
const logs=(logFile&&fs.existsSync(logFile)?fs.readFileSync(logFile,'utf8').split(/\r?\n/):[]).filter(Boolean).filter(fs.existsSync);
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const run=(c,a,o={})=>execFileSync(c,a,{encoding:'utf8',maxBuffer:256*1024*1024,...o});
const fail=(m,details={})=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'REJECTED.json'),JSON.stringify({status:'REJECTED',reason:m,details,mission,generatedAt:new Date().toISOString()},null,2)+'\n');throw new Error(`WORKBENCH REJECTED: ${m}`)};
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
for(const p of [parent,child])if(!fs.existsSync(p))fail(`missing ${p}`);
if(sha(parent)!==cfg.sha256)fail('parent SHA-256 does not match protected A17Y');
const rcosOut=path.join(out,'rcos');
run('node',['workbench/rcos.mjs',parent,child,mission,...logs],{env:{...process.env,RCOS_OUT:rcosOut}});
const rcos=JSON.parse(fs.readFileSync(path.join(rcosOut,'REPORT.json'),'utf8'));
const deploy=path.join(rcosOut,'DEPLOY.luac');
const bytecodeStress=JSON.parse(run('lua5.3',['scripts/mt12-bytecode-stress.lua',deploy,'16']).trim());
const byteTrace=path.join(out,'normalized-bytecode-trace.csv');
run('lua5.3',['scripts/mt12-harness.lua',deploy,byteTrace]);
const sourceTrace=path.join(rcosOut,'child-trace.csv');
const parse=p=>fs.readFileSync(p,'utf8').trim().split(/\r?\n/).map(x=>x.split(','));
const a=parse(sourceTrace),b=parse(byteTrace);if(a.length!==b.length)fail('normalized bytecode trace length differs from source',{sourceRows:a.length,bytecodeRows:b.length});
let bytecodeDelta=0,bytecodeChangedRows=0;
for(let i=1;i<a.length;i++){let changed=false;for(let j=1;j<Math.min(a[i].length,b[i].length);j++){const x=Number(a[i][j]),y=Number(b[i][j]);if(Number.isFinite(x)&&Number.isFinite(y)){const d=Math.abs(x-y);bytecodeDelta=Math.max(bytecodeDelta,d);if(d)changed=true}}if(changed)bytecodeChangedRows++}
if(bytecodeChangedRows||bytecodeDelta)fail('normalized bytecode behavior differs from source',{bytecodeChangedRows,bytecodeDelta});
const maxChangedRows=Number(process.env.MAX_CHANGED_ROWS||cfg.maximumChangedRows||500);
const maxDelta=Number(process.env.MAX_OUTPUT_DELTA||cfg.maximumOutputDelta||700);
const maxGrowthKB=Number(process.env.MAX_HOST_MEMORY_GROWTH_KB||256);
if(rcos.comparison.changedRows>maxChangedRows)fail('candidate changes too many synthetic rows',{actual:rcos.comparison.changedRows,limit:maxChangedRows});
if(rcos.comparison.maxDelta>maxDelta)fail('candidate output delta exceeds safety limit',{actual:rcos.comparison.maxDelta,limit:maxDelta});
if(bytecodeStress.growthKB>maxGrowthKB)fail('host memory stress growth exceeds limit',{actual:bytecodeStress.growthKB,limit:maxGrowthKB});
const missionMetrics=rcos.missionMetrics||{};
if(rcos.comparison.sameSource===false && missionMetrics.passed===false)fail('candidate did not satisfy mission-specific evidence gates',missionMetrics);
const deploySha=sha(deploy),sourceSha=sha(child);
const report={status:'accepted',stage:rcos.replayExecution?.executed?'REPLAY VERIFIED':'LOG EVIDENCE REVIEWED',mission,parent:rcos.parent,child:rcos.child,comparison:rcos.comparison,missionMetrics,replayExecution:rcos.replayExecution,bytecode:{sha256:deploySha,normalizedBytes:fs.statSync(deploy).size,sourceTraceEquivalent:true,stress:bytecodeStress},identity:{sourceSha256:sourceSha,normalizedLuacSha256:deploySha,compiler:'Lua 5.3 stripped',normalizer:'toolchain/normalize_luac53_mt12.js',workflowRunId:process.env.GITHUB_RUN_ID||null,workflowSha:process.env.GITHUB_SHA||null},limits:{maxChangedRows,maxDelta,maxGrowthKB,maxNormalizedBytes:cfg.maxNormalizedBytes},protectedParent:true,automaticPromotion:false,benchRequired:true,roadRequired:true,generatedAt:new Date().toISOString()};
for(const f of ['PARENT.lua','CHILD.lua','DEPLOY.luac','REPORT.json','CREW-CHIEF.txt','DIFF.json','PROMOTION.json']){const src=path.join(rcosOut,f);if(fs.existsSync(src))fs.copyFileSync(src,path.join(out,f))}
fs.writeFileSync(path.join(out,'REPORT.json'),JSON.stringify(report,null,2)+'\n');
fs.writeFileSync(path.join(out,'IDENTITY.json'),JSON.stringify(report.identity,null,2)+'\n');
fs.writeFileSync(path.join(out,'PROMOTION.txt'),`${report.stage}\nNormalized bytecode executed and matched source trace.\nManual bench and road approval required.\n`);
console.log(JSON.stringify(report,null,2));
