#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
export function discover(extra=''){const roots=['tests/replays','evidence/bench','evidence/road'];const set=new Set(extra.split(/\s+/).filter(Boolean));for(const r of roots)if(fs.existsSync(r))for(const f of fs.readdirSync(r,{recursive:true}))if(/\.csv$/i.test(f))set.add(path.join(r,f));return[...set].filter(fs.existsSync).sort()}
function csvLine(s){let a=[],q='',z=false;for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'){if(z&&s[i+1]==='"'){q+='"';i++}else z=!z}else if(c===','&&!z){a.push(q);q=''}else q+=c}a.push(q);return a}
const norm=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_');
const num=x=>{let n=Number(String(x??'').replace(/[^0-9+-.eE]/g,''));return Number.isFinite(n)?n:null};
const pick=(row,map,names)=>{for(const n of names){let i=map.get(norm(n));if(i!=null){let v=num(row[i]);if(v!=null)return v}}return null};
export function parseLog(file){const lines=fs.readFileSync(file,'utf8').split(/\r?\n/).filter(Boolean),head=lines.length?csvLine(lines[0]):[],map=new Map(head.map((x,i)=>[norm(x),i])),rows=lines.slice(1).map(csvLine);let events={tc:0,abs:0,jump:0,landing:0,gpsLoss:0,rpmDrop:0,channelDrop:0,restart:0},active={};let samples=[];for(let i=0;i<rows.length;i++){let r=rows[i],s={i,time:pick(r,map,['time','timestamp','datetime']),mph:pick(r,map,['mph','speed','gps_speed','truth_mph']),rpm:pick(r,map,['rpm','truth_rpm']),tc:pick(r,map,['tc','tca','tc_event','traction']),abs:pick(r,map,['abs','abs_event']),jump:pick(r,map,['jump','airborne','air']),land:pick(r,map,['landing','land']),gps:pick(r,map,['gps','gps_valid','gps_fix']),thr:pick(r,map,['thr','throttle','ch2']),gyro:pick(r,map,['gyr','gyro','ch3'])};samples.push(s);let flags={tc:(s.tc??0)>0.5,abs:(s.abs??0)>0.5,jump:(s.jump??0)>0.5,landing:(s.land??0)>0.5,gpsLoss:s.gps===0,rpmDrop:i>0&&s.rpm===0&&(samples[i-1].rpm??0)>100,channelDrop:s.thr===0&&i>0&&(samples[i-1].thr??0)>100,restart:i>0&&s.time!=null&&samples[i-1].time!=null&&s.time<samples[i-1].time};for(const[k,v]of Object.entries(flags)){if(v&&!active[k])events[k]++;active[k]=v}}
return{file,sha256:sha(file),bytes:fs.statSync(file).size,columns:head,rows:rows.length,events,samples};}
export function summarize(files){return files.map(parseLog).map(x=>({file:x.file,sha256:x.sha256,bytes:x.bytes,rows:x.rows,columns:x.columns,events:x.events}));}
if(import.meta.url===`file://${process.argv[1]}`)console.log(JSON.stringify(summarize(discover(process.env.DIRECTOR_LOGS||'')),null,2));
