#!/usr/bin/env node
import fs from 'node:fs';import crypto from 'node:crypto';
const cfg=JSON.parse(fs.readFileSync('nickelle/research-config.json','utf8'));const queue=JSON.parse(fs.readFileSync('nickelle/research-queue.json','utf8'));const token=process.env.GITHUB_TOKEN||'';const now=()=>new Date().toISOString(),runId=`nickelle-research-${Date.now()}`;const requested=(process.env.NICKELLE_RESEARCH_TOPIC||'').trim();const open=(queue.queue||[]).filter(x=>x.status==='open').sort((a,b)=>(b.priority||0)-(a.priority||0));const topic=requested||open[0]?.request||cfg.topics[0];
const sources=[],rejected=[],seen=new Set(),activity=[];const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&[a-z]+;/gi,' ').replace(/\s+/g,' ').trim();const key=s=>crypto.createHash('sha256').update(s).digest('hex').slice(0,20);const add=(phase,message,extra={})=>activity.push({at:now(),phase,message,...extra});
const EXACT=/\bmjx\b|\b7303\b|citro[eë]n|\bc3\s*wrc\b|world rally car|hyper go/i;
const AUTO=/\bautomotive\b|\bvehicle\b|\bpassenger car\b|\brally car\b|\bcar body\b|\bcar exterior\b|\bheadlamp\b|\bheadlight\b|\bgrille\b|\bbumper\b|\bwheel arch\b|\bfender\b|\broof scoop\b|\brear wing\b|\bdiffuser\b|\blivery\b/i;
const VISION=/photogrammetry|gaussian splatting|\bnerf\b|neural radiance|semantic segmentation|instance segmentation|monocular depth|depth estimation|surface normal|camera calibration|camera pose|focal length estimation|inverse rendering|material estimation|\bpbr\b|roughness estimation|clearcoat|perceptual similarity|\blpips\b|\bdino\b|vision transformer|image correspondence|optical flow|webgl|webgpu|level of detail|anti-alias|z[- ]fighting/i;
const VISUAL=/3d reconstruction|mesh reconstruction|object reconstruction|shape estimation|texture reconstruction|uv mapping|decal|rendering|graphics|computer vision|image matching|feature matching/i;
const JUNK=/railway|railroad|wheel[-– ]rail|aircraft|airplane|aerofoil|supersonic|hypersonic|cavitation|heat conduction|lippmann|scattering potential|mating regulatory|worm profiling|robot stair|jet noise|marine hull|ship hydrodynamic|medical imaging|protein|molecular|astronomy|satellite orbit/i;
const PARTS=[['front_grille',/\bgrille\b|front fascia|front air intake/i],['projector_left',/headlamp|headlight|projector lamp|\bdrl\b/i],['projector_right',/headlamp|headlight|projector lamp|\bdrl\b/i],['front_arches',/wheel arch|front fender|fender flare/i],['wheel_fl',/road wheel|rally wheel|tire|tyre|wheel fitment|wheel stance/i],['wheel_fr',/road wheel|rally wheel|tire|tyre|wheel fitment|wheel stance/i],['wheel_rl',/road wheel|rally wheel|tire|tyre|wheel fitment|wheel stance/i],['wheel_rr',/road wheel|rally wheel|tire|tyre|wheel fitment|wheel stance/i],['roof_scoop',/roof scoop|roof vent/i],['rear_wing',/rear wing|rear spoiler/i],['diffuser',/rear diffuser|underbody diffuser/i],['livery',/vehicle livery|rally livery|decal|uv mapping|texture reconstruction|paint scheme/i]];
function classify(s){const text=`${s.title||''} ${s.summary||''}`.toLowerCase();const exact=EXACT.test(text),auto=AUTO.test(text),vision=VISION.test(text),visual=VISUAL.test(text),junk=JUNK.test(text);if(junk&&!exact&&!auto)return{accept:false,reason:'junk-domain'};if(exact)return{accept:true,klass:'target-vehicle',base:90};if(auto&&(vision||visual))return{accept:true,klass:'automotive-vision',base:72};if(auto)return{accept:true,klass:'automotive-reference',base:64};if(vision)return{accept:true,klass:'graphics-cv-method',base:54};if(visual&&!junk)return{accept:true,klass:'graphics-method',base:42};return{accept:false,reason:'missing-automotive-or-graphics-context'};}
function score(s,c){const text=`${s.title||''} ${s.summary||''}`;let n=c.base||0;if(EXACT.test(text))n+=35;if(AUTO.test(text))n+=18;if(VISION.test(text))n+=18;if(VISUAL.test(text))n+=10;if(PARTS.some(([,r])=>r.test(text)))n+=12;if(s.provider==='arXiv')n+=4;if(s.doi)n+=2;return n;}
function addSource(s){if(!s.url||!s.title)return;const id=key(s.url);if(seen.has(id))return;seen.add(id);const c=classify(s);if(!c.accept){rejected.push({id,title:s.title,url:s.url,reason:c.reason,score:0});return}const x={id,retrievedAt:now(),...s,relevanceClass:c.klass};x.relevanceScore=score(x,c);if(x.relevanceScore<46){rejected.push({id,title:x.title,url:x.url,reason:'below-strict-threshold',score:x.relevanceScore});return}sources.push(x)}
async function get(url,h={}){const r=await fetch(url,{headers:{'User-Agent':'Nickelle-Visual-Research/1.2',Accept:'application/json, application/atom+xml, text/html;q=0.8',...h}});if(!r.ok)throw Error(`${r.status} ${url}`);return r}
async function arxiv(q){add('SEARCH',`arXiv visual search: ${q}`);const t=await(await get('https://export.arxiv.org/api/query?search_query=all:'+encodeURIComponent(q)+'&start=0&max_results=12&sortBy=relevance&sortOrder=descending')).text();for(const e of t.matchAll(/<entry>([\s\S]*?)<\/entry>/g)){const x=e[1];addSource({kind:'paper',provider:'arXiv',title:clean(x.match(/<title>([\s\S]*?)<\/title>/)?.[1]),url:x.match(/<id>(.*?)<\/id>/)?.[1],summary:clean(x.match(/<summary>([\s\S]*?)<\/summary>/)?.[1]),published:x.match(/<published>(.*?)<\/published>/)?.[1]||null,query:q})}}
async function crossref(q){add('SEARCH',`Crossref visual search: ${q}`);const j=await(await get('https://api.crossref.org/works?rows=20&select=DOI,title,URL,abstract,container-title,published&query.bibliographic='+encodeURIComponent(q))).json();for(const x of j.message?.items||[])addSource({kind:'paper',provider:'Crossref',title:clean(x.title?.[0]),url:x.URL,summary:clean(x.abstract||x['container-title']?.[0]||''),published:x.published?.['date-parts']?.[0]?.join('-')||null,query:q,doi:x.DOI||null})}
const queries=[topic,...cfg.topics.filter(x=>x!==topic).slice(0,7)];for(const q of queries){try{await arxiv(q)}catch(e){add('WARNING','arXiv failed',{query:q,error:e.message})}try{await crossref(q)}catch(e){add('WARNING','Crossref failed',{query:q,error:e.message})}}
sources.sort((a,b)=>b.relevanceScore-a.relevanceScore);const limited=sources.slice(0,cfg.maxSourcesPerRun);
function extract(t){const f=t.match(/```(?:json)?\s*([\s\S]*?)```/i);if(f)t=f[1];const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a<0||b<a)throw Error('no JSON object');return JSON.parse(t.slice(a,b+1))}
async function synth(){if(!token||!limited.length)return null;const digest=limited.map(s=>({id:s.id,title:s.title,url:s.url,provider:s.provider,published:s.published,score:s.relevanceScore,relevanceClass:s.relevanceClass,summary:s.summary.slice(0,1500)}));const prompt=`You are Nickelle, Michael's dedicated visual research scientist. Objective: ${topic}. Michael is a digital twin of the owner's MJX Hyper Go 7303 Citroen C3 WRC-style RC car. Authority order: ${cfg.authorityOrder.join(' > ')}. Owner physical evidence always outranks web evidence. Generated renders can never establish physical truth. Sources: ${JSON.stringify(digest)}. Reject sources that are not truly applicable to automotive exterior reconstruction or rendering even if they share words like body, wheel, wing, geometry, or exact. Return strict JSON: summary, acceptedFindings[], rejectedFindings[], contradictions[], visualMeasurements[], componentConstraints[], researchGaps[], nextQueries[]. Each accepted finding: claim, sourceIds, confidence, semanticComponents, evidenceType, applicability, testableVisualHypothesis. Measurements require direct support; never invent dimensions.`;for(const m of [cfg.primaryModel,...cfg.fallbackModels])for(let a=1;a<=2;a++)try{const r=await fetch('https://models.github.ai/inference/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({model:m,temperature:.03,max_tokens:10000,messages:[{role:'system',content:'Be a skeptical automotive computer-vision and graphics research scientist. Preserve uncertainty and contradictions. Never let generated imagery override owner truth.'},{role:'user',content:prompt}]})});if(!r.ok)throw Error(`${r.status}: ${await r.text()}`);const j=await r.json();return{model:m,...extract(j.choices?.[0]?.message?.content||'')}}catch(e){add('WARNING','visual synthesis failed',{model:m,attempt:a,error:e.message})}return null}
function deterministicEvidence(list){const out=[];for(const s of list){const text=`${s.title||''} ${s.summary||''}`;if(!(EXACT.test(text)||AUTO.test(text)))continue;const comps=[...new Set(PARTS.filter(([,re])=>re.test(text)).map(([p])=>p))];if(!comps.length)continue;out.push({sourceIds:[s.id],semanticComponents:comps,confidence:s.relevanceClass==='target-vehicle'?.54:.46,evidenceType:'deterministic_source_relevance',claim:`Source '${s.title}' contains automotive evidence directly mentioning ${comps.join(', ')}; use only as a research lead until checked against owner Truth.`,applicability:'research prioritization and hypothesis generation only',testableVisualHypothesis:'Verify the cited source against owner photographs/measurements before applying geometry or material changes.',truthEligible:false})}return out.slice(0,24)}
const ai=await synth(),ids=new Set(limited.map(x=>x.id));const accepted=(ai?.acceptedFindings||[]).filter(f=>f.sourceIds?.length&&f.sourceIds.every(x=>ids.has(x))&&Number(f.confidence)>=.55).slice(0,cfg.maxAcceptedPerRun);const deterministic=deterministicEvidence(limited);if(!ai)add('FALLBACK',`External synthesis unavailable; preserved ${deterministic.length} strict automotive component leads from ${limited.length} qualified sources.`);const gaps=[...(ai?.researchGaps||[])];if(!limited.length)gaps.push({type:'source_gap',request:`Find official MJX 7303 or Citroen C3 WRC exterior reference sources for: ${topic}`,priority:.95});if(limited.length&&!accepted.length&&!deterministic.length)gaps.push({type:'evidence_gap',request:`Find directly automotive, component-specific evidence for: ${topic}`,priority:.9});
const report={schema:3,identity:cfg.identity,runId,topic,startedAt:activity[0]?.at||now(),completedAt:now(),queries,sources:limited,rejectedSources:rejected.slice(0,80),acceptedFindings:accepted,deterministicEvidence:deterministic,rejectedFindings:ai?.rejectedFindings||[],contradictions:ai?.contradictions||[],visualMeasurements:ai?.visualMeasurements||[],componentConstraints:ai?.componentConstraints||[],researchGaps:gaps,nextQueries:ai?.nextQueries||[],summary:ai?.summary||`Collected ${limited.length} strictly qualified visual sources; external synthesis unavailable; ${deterministic.length} automotive component leads preserved.`,model:ai?.model||null,synthesisAvailable:!!ai,activity};fs.mkdirSync('nickelle/research/history',{recursive:true});fs.writeFileSync('nickelle/research/current.json',JSON.stringify(report,null,2)+'\n');fs.writeFileSync(`nickelle/research/history/${runId}.json`,JSON.stringify(report,null,2)+'\n');fs.writeFileSync('nickelle/research/state.json',JSON.stringify({schema:3,status:'COMPLETE',runId,topic,updatedAt:now(),sources:limited.length,accepted:accepted.length,deterministicEvidence:deterministic.length,rejected:rejected.length,contradictions:report.contradictions.length,gaps:gaps.length,model:report.model,synthesisAvailable:!!ai,summary:report.summary},null,2)+'\n');console.log(JSON.stringify({runId,topic,sources:limited.length,accepted:accepted.length,deterministicEvidence:deterministic.length,rejected:rejected.length,gaps:gaps.length,model:report.model,synthesisAvailable:!!ai},null,2));
