#!/usr/bin/env node
import fs from 'node:fs';import crypto from 'node:crypto';
const cfg=JSON.parse(fs.readFileSync('nickelle/research-config.json','utf8'));const queue=JSON.parse(fs.readFileSync('nickelle/research-queue.json','utf8'));const token=process.env.GITHUB_TOKEN||'';const now=()=>new Date().toISOString(),runId=`nickelle-research-${Date.now()}`;const requested=(process.env.NICKELLE_RESEARCH_TOPIC||'').trim();const open=(queue.queue||[]).filter(x=>x.status==='open').sort((a,b)=>(b.priority||0)-(a.priority||0));const topic=requested||open[0]?.request||cfg.topics[0];
const visualTerms=['mjx','7303','citroen','c3 wrc','rally','body','bumper','grille','headlight','projector','drl','wheel','arch','fender','wing','spoiler','diffuser','roof scoop','livery','decal','photogrammetry','reconstruction','nerf','gaussian splatting','segmentation','depth','surface normal','camera pose','focal length','inverse rendering','pbr','roughness','metallic','clearcoat','optics','uv','texture','perceptual','lpips','dino','clip','webgl','webgpu','lod','aliasing','z-fighting'];
const sources=[],rejected=[],seen=new Set(),activity=[];const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&[a-z]+;/gi,' ').replace(/\s+/g,' ').trim();const key=s=>crypto.createHash('sha256').update(s).digest('hex').slice(0,20);const add=(phase,message,extra={})=>activity.push({at:now(),phase,message,...extra});
function score(s){const text=`${s.title||''} ${s.summary||''} ${s.query||''}`.toLowerCase();let n=0;for(const t of visualTerms)if(text.includes(t))n+=t.includes(' ')?8:4;if(/mjx|citro[eë]n|c3 wrc|automotive|vehicle/i.test(text))n+=18;if(/photogrammetry|gaussian splatting|inverse rendering|semantic segmentation|depth anything|segformer|surface normal|camera calibration|pbr|headlamp|webgl|webgpu/i.test(text))n+=20;if(s.provider==='arXiv')n+=6;if(s.doi)n+=2;return n}
function addSource(s){if(!s.url||!s.title)return;const id=key(s.url);if(seen.has(id))return;seen.add(id);const x={id,retrievedAt:now(),...s};x.relevanceScore=score(x);if(x.relevanceScore<22){rejected.push({id,title:x.title,url:x.url,score:x.relevanceScore});return}sources.push(x)}
async function get(url,h={}){const r=await fetch(url,{headers:{'User-Agent':'Nickelle-Visual-Research/1.1',Accept:'application/json, application/atom+xml, text/html;q=0.8',...h}});if(!r.ok)throw Error(`${r.status} ${url}`);return r}
async function arxiv(q){add('SEARCH',`arXiv visual search: ${q}`);const t=await(await get('https://export.arxiv.org/api/query?search_query=all:'+encodeURIComponent(q)+'&start=0&max_results=12&sortBy=relevance&sortOrder=descending')).text();for(const e of t.matchAll(/<entry>([\s\S]*?)<\/entry>/g)){const x=e[1];addSource({kind:'paper',provider:'arXiv',title:clean(x.match(/<title>([\s\S]*?)<\/title>/)?.[1]),url:x.match(/<id>(.*?)<\/id>/)?.[1],summary:clean(x.match(/<summary>([\s\S]*?)<\/summary>/)?.[1]),published:x.match(/<published>(.*?)<\/published>/)?.[1]||null,query:q})}}
async function crossref(q){add('SEARCH',`Crossref visual search: ${q}`);const j=await(await get('https://api.crossref.org/works?rows=20&select=DOI,title,URL,abstract,container-title,published&query.bibliographic='+encodeURIComponent(q))).json();for(const x of j.message?.items||[])addSource({kind:'paper',provider:'Crossref',title:clean(x.title?.[0]),url:x.URL,summary:clean(x.abstract||x['container-title']?.[0]||''),published:x.published?.['date-parts']?.[0]?.join('-')||null,query:q,doi:x.DOI||null})}
const queries=[topic,...cfg.topics.filter(x=>x!==topic).slice(0,7)];for(const q of queries){try{await arxiv(q)}catch(e){add('WARNING','arXiv failed',{query:q,error:e.message})}try{await crossref(q)}catch(e){add('WARNING','Crossref failed',{query:q,error:e.message})}}
sources.sort((a,b)=>b.relevanceScore-a.relevanceScore);const limited=sources.slice(0,cfg.maxSourcesPerRun);
function extract(t){const f=t.match(/```(?:json)?\s*([\s\S]*?)```/i);if(f)t=f[1];const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a<0||b<a)throw Error('no JSON object');return JSON.parse(t.slice(a,b+1))}
async function synth(){if(!token||!limited.length)return null;const digest=limited.map(s=>({id:s.id,title:s.title,url:s.url,provider:s.provider,published:s.published,score:s.relevanceScore,summary:s.summary.slice(0,1500),query:s.query}));const prompt=`You are Nickelle, Michael's dedicated visual research scientist. Objective: ${topic}. Michael is a digital twin of the owner's MJX Hyper Go 7303 Citroen C3 WRC-style RC car. Authority order: ${cfg.authorityOrder.join(' > ')}. Owner physical evidence always outranks web evidence. Generated renders can never establish physical truth. Sources: ${JSON.stringify(digest)}. Return strict JSON: summary, acceptedFindings[], rejectedFindings[], contradictions[], visualMeasurements[], componentConstraints[], researchGaps[], nextQueries[]. Each accepted finding: claim, sourceIds, confidence, semanticComponents, evidenceType, applicability, testableVisualHypothesis. Measurements must include value/range/unit only when directly supported; never invent dimensions. Component constraints must map evidence to semantic components such as front_grille, projector_left/right, wheel_fl/fr/rl/rr, front_arches, roof_scoop, rear_wing, diffuser, livery. Separate cited evidence from inference.`;for(const m of [cfg.primaryModel,...cfg.fallbackModels])for(let a=1;a<=2;a++)try{const r=await fetch('https://models.github.ai/inference/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({model:m,temperature:.05,max_tokens:10000,messages:[{role:'system',content:'Be a skeptical automotive computer-vision and graphics research scientist. Preserve uncertainty and contradictions. Never let generated imagery override owner truth.'},{role:'user',content:prompt}]})});if(!r.ok)throw Error(`${r.status}: ${await r.text()}`);const j=await r.json();return{model:m,...extract(j.choices?.[0]?.message?.content||'')}}catch(e){add('WARNING','visual synthesis failed',{model:m,attempt:a,error:e.message})}return null}
function deterministicEvidence(list){
  const map=[
    ['front_grille',/grille|front fascia|air intake/i],['projector_left',/headlamp|headlight|projector|drl|lamp/i],['projector_right',/headlamp|headlight|projector|drl|lamp/i],['front_arches',/wheel arch|fender|arch/i],['wheel_fl',/wheel|tire|tyre|stance/i],['wheel_fr',/wheel|tire|tyre|stance/i],['wheel_rl',/wheel|tire|tyre|stance/i],['wheel_rr',/wheel|tire|tyre|stance/i],['roof_scoop',/roof scoop|roof vent|scoop/i],['rear_wing',/rear wing|spoiler|aerofoil|aerodynamic/i],['diffuser',/diffuser|rear aero|underbody/i],['livery',/livery|decal|texture|uv|paint/i]
  ];
  const out=[];
  for(const s of list){const text=`${s.title||''} ${s.summary||''} ${s.query||''}`;const comps=[...new Set(map.filter(([,re])=>re.test(text)).map(([p])=>p))];if(!comps.length)continue;out.push({sourceIds:[s.id],semanticComponents:comps,confidence:Math.min(.52,.28+(s.relevanceScore||0)/300),evidenceType:'deterministic_source_relevance',claim:`Source '${s.title}' contains directly indexed material relevant to ${comps.join(', ')}; use as a research lead, not physical truth.`,applicability:'research prioritization and hypothesis generation only',testableVisualHypothesis:'Compare the cited source against owner Truth/reference imagery before applying any geometry or material change.'})}
  return out.slice(0,24);
}
const ai=await synth(),ids=new Set(limited.map(x=>x.id));const accepted=(ai?.acceptedFindings||[]).filter(f=>f.sourceIds?.length&&f.sourceIds.every(x=>ids.has(x))&&Number(f.confidence)>=.55).slice(0,cfg.maxAcceptedPerRun);const deterministic=deterministicEvidence(limited);if(!ai)add('FALLBACK',`External synthesis unavailable; preserved ${deterministic.length} deterministic source-backed visual leads without promoting them to Truth.`);
const report={schema:2,identity:cfg.identity,runId,topic,startedAt:activity[0]?.at||now(),completedAt:now(),queries,sources:limited,rejectedSources:rejected.slice(0,50),acceptedFindings:accepted,deterministicEvidence:deterministic,rejectedFindings:ai?.rejectedFindings||[],contradictions:ai?.contradictions||[],visualMeasurements:ai?.visualMeasurements||[],componentConstraints:ai?.componentConstraints||[],researchGaps:ai?.researchGaps||[],nextQueries:ai?.nextQueries||[],summary:ai?.summary||`Collected ${limited.length} visual sources. External synthesis unavailable; ${deterministic.length} conservative component leads preserved for Nickelle's research bridge.`,model:ai?.model||null,synthesisAvailable:!!ai,activity};fs.mkdirSync('nickelle/research/history',{recursive:true});fs.writeFileSync('nickelle/research/current.json',JSON.stringify(report,null,2)+'\n');fs.writeFileSync(`nickelle/research/history/${runId}.json`,JSON.stringify(report,null,2)+'\n');fs.writeFileSync('nickelle/research/state.json',JSON.stringify({schema:2,status:'COMPLETE',runId,topic,updatedAt:now(),sources:limited.length,accepted:accepted.length,deterministicEvidence:deterministic.length,contradictions:report.contradictions.length,gaps:report.researchGaps.length,model:report.model,synthesisAvailable:!!ai,summary:report.summary},null,2)+'\n');console.log(JSON.stringify({runId,topic,sources:limited.length,accepted:accepted.length,deterministicEvidence:deterministic.length,contradictions:report.contradictions.length,gaps:report.researchGaps.length,model:report.model,synthesisAvailable:!!ai},null,2));
