import{state,subscribe,refresh,setWorkspace,runMission,metrics,health}from'./state.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={command:'Command',vehicle:'Vehicle AI',evidence:'Evidence',intelligence:'Intelligence',factory:'Factory',firmware:'Firmware',radio:'MT12',releases:'Releases',tools:'Tools',system:'System'};
const descriptions={command:'Assign objectives and watch Jarvis coordinate the entire platform.',vehicle:'Controller brains, genomes, tuning, simulation, replay and learning.',evidence:'Upload, attribute, pair, replay and label radio and blackbox logs.',intelligence:'Research, memory, hypotheses, counterfactuals, knowledge graph and digital twin.',factory:'Generate, compile, normalize, challenge and rank Lua and LUAC candidates.',firmware:'EdgeTX and ExpressLRS discovery, compatibility, packaging and update safety.',radio:'MT12 backup, models, YAML, SD-card state, restore, flash and recovery.',releases:'Artifacts, promotion authority, rollback, certificates and trusted delivery.',tools:'Mobile companions, native helper, viewers, tuners and support utilities.',system:'GitHub, workflows, runs, artifacts, failures, repository and health.'};
function nav(){const w=state.capabilities?.workspaces||[];const buttons=w.map(x=>`<button class="navbtn ${state.workspace===x.id?'active':''}" data-workspace="${x.id}"><span class="dot"></span>${esc(x.label)}</button>`).join('');$('#sideNav').innerHTML=`<div class="navgroup"><div class="navlabel">Jarvis Platform</div>${buttons}</div>`;$('#mobileNav').innerHTML=buttons.replaceAll('navbtn','');document.querySelectorAll('[data-workspace]').forEach(b=>b.onclick=()=>setWorkspace(b.dataset.workspace))}
function missions(workspace){return(state.capabilities?.missions||[]).filter(m=>m.workspace===workspace)}
function dataFor(workspace){return(state.capabilities?.dataSources||[]).filter(d=>d.workspace===workspace)}
function missionCards(workspace){const ms=missions(workspace);return ms.length?`<div class="workflow-grid">${ms.map(m=>`<article class="workflow"><strong>${esc(m.label)}</strong><div class="muted">${esc(m.workflow)}</div><div class="actions"><button class="btn primary" data-run="${m.id}">RUN</button><button class="btn" data-openwf="${m.workflow}">HISTORY</button></div></article>`).join('')}</div>`:'<div class="empty">No direct workflow is assigned to this workspace.</div>'}
function sourceCards(workspace){const ds=dataFor(workspace);return ds.length?`<div class="list">${ds.map(d=>{const v=state.data[d.path];return`<div class="item"><div class="title">${esc(d.id)}</div><div class="meta">${esc(d.path)} · ${v?'loaded':'not available'}</div></div>`}).join('')}</div>`:'<div class="empty">No repository data sources are mapped here.</div>'}
function workspace(){const id=state.workspace,m=metrics(),h=health();$('#workspaceTitle').textContent=labels[id]||'Jarvis';$('#workspaceDescription').textContent=descriptions[id]||'';const common=`<section class="grid"><article class="card span-8"><h3>Available operations</h3>${missionCards(id)}</article><article class="card span-4"><h3>Workspace data</h3>${sourceCards(id)}</article></section>`;
let special='';
if(id==='command')special=`<section class="grid"><article class="card span-8"><h3>Engineering objective</h3><textarea id="objective" placeholder="Tell Jarvis what outcome you need. Jarvis will choose the research, firmware, controller, evidence, simulation and device steps."></textarea><div class="mission-types">${['Autonomous','Investigate','Improve controller','Analyze logs','Firmware update','MT12 recovery'].map((x,i)=>`<button class="mission-type ${i===0?'active':''}">${x}</button>`).join('')}</div><button class="btn primary" id="startMission">START JARVIS MISSION</button></article><article class="card span-4"><h3>Current platform state</h3><div class="pipeline"><div class="stage ${h.github==='healthy'?'ok':'fail'}"><i></i><span>GitHub intelligence link</span><b>${h.github}</b></div><div class="stage ${h.factory==='running'?'run':'ok'}"><i></i><span>Autonomous factory</span><b>${h.factory}</b></div><div class="stage ${h.knowledge==='ready'?'ok':''}"><i></i><span>Knowledge graph</span><b>${h.knowledge}</b></div><div class="stage ${h.firmware==='ready'?'ok':''}"><i></i><span>Firmware intelligence</span><b>${h.firmware}</b></div></div></article></section>`;
if(id==='vehicle')special=`<section class="grid"><article class="card span-3"><h3>Champion</h3><div class="metric">${esc(m.champion)}</div><div class="muted">Current controller track</div></article><article class="card span-3"><h3>Simulation runs</h3><div class="metric">${m.simulations.toLocaleString()}</div><div class="muted">Latest adaptive twin cycle</div></article><article class="card span-3"><h3>Episodes</h3><div class="metric">${m.episodes.toLocaleString()}</div><div class="muted">Attributed learning events</div></article><article class="card span-3"><h3>Transfer confidence</h3><div class="metric">${m.confidence==null?'—':Math.round(m.confidence*100)+'%'}</div><div class="muted">Simulation-to-real estimate</div></article></section>`;
if(id==='firmware')special=`<section class="grid"><article class="card span-6"><h3>EdgeTX</h3><p class="muted">Discover versions, check RadioMaster MT12 compatibility, preserve models and SD content, build update packages, verify backup readiness, and certify after flashing.</p><div class="chips"><span class="chip">DISCOVERED</span><span class="chip">COMPATIBILITY CHECKED</span><span class="chip">READY TO FLASH</span><span class="chip">POST-FLASH CERTIFIED</span></div></article><article class="card span-6"><h3>ExpressLRS</h3><p class="muted">Discover radio-module and receiver releases, validate target and regulatory compatibility, prepare secure builds, protect binding information, and support recovery.</p><div class="chips"><span class="chip">VERSION CATALOG</span><span class="chip">TARGET CHECK</span><span class="chip">SECURE BUILD</span><span class="chip">RECOVERY</span></div></article></section>`;
if(id==='system')special=`<section class="grid"><article class="card span-8"><h3>Recent workflow runs</h3><div class="tablewrap"><table><thead><tr><th>Workflow</th><th>Status</th><th>Conclusion</th><th>Branch</th></tr></thead><tbody>${state.runs.slice(0,20).map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.status)}</td><td>${esc(r.conclusion||'pending')}</td><td>${esc(r.head_branch)}</td></tr>`).join('')}</tbody></table></div></article><article class="card span-4"><h3>Connection</h3><div class="item"><div class="title">${state.connected?`Connected as ${esc(state.user?.login)}`:'Not connected'}</div><div class="meta">Classic PAT shared across the full Jarvis platform.</div></div><button class="btn" id="openAuth">MANAGE CONNECTION</button></article></section>`;
$('#workspaceBody').innerHTML=special+common;wire()}
function render(){nav();workspace();$('#connectionState').textContent=state.connected?'CONNECTED':'OFFLINE';$('#connectionState').className=state.connected?'ok':'';$('#updated').textContent=state.updatedAt?new Date(state.updatedAt).toLocaleTimeString():'—';$('#loading').hidden=!state.loading;if(state.error)$('#globalError').textContent=state.error}
function wire(){document.querySelectorAll('[data-run]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='DISPATCHING…';try{const id=b.dataset.run;const inputs=id==='engineering-mission'?{topic:$('#objective')?.value?.trim()||''}:{};await runMission(id,inputs);b.textContent='STARTED'}catch(e){alert(e.message);b.textContent='FAILED'}finally{setTimeout(()=>{b.disabled=false;b.textContent='RUN'},1500)}});document.querySelectorAll('[data-openwf]').forEach(b=>b.onclick=()=>window.open(`https://github.com/${apiRepo()}/actions/workflows/${b.dataset.openwf}`,'_blank'));$('#startMission')?.addEventListener('click',async()=>{const objective=$('#objective').value.trim();if(!objective)return alert('Enter an engineering objective.');await runMission('engineering-mission',{topic:objective});alert('Jarvis mission started.')} );$('#openAuth')?.addEventListener('click',openDrawer)}
function apiRepo(){return'gymwhaleysspot-dot/mt12-jarvis-continuous'}
function openDrawer(){$('#drawer').classList.add('open');$('#overlay').classList.add('open')}function closeDrawer(){$('#drawer').classList.remove('open');$('#overlay').classList.remove('open')}
$('#refresh').onclick=refresh;$('#connection').onclick=openDrawer;$('#closeDrawer').onclick=closeDrawer;$('#overlay').onclick=closeDrawer;$('#testToken').onclick=async()=>{try{await refresh();$('#authMessage').textContent=state.connected?`Connected as ${state.user.login}`:'Credential not available.'}catch(e){$('#authMessage').textContent=e.message}};$('#clearToken').onclick=()=>{window.A17YToken?.clear?.();localStorage.removeItem('a17y_classic_pat');localStorage.removeItem('a17y_pat');location.reload()};
subscribe(render);const initial=location.hash.slice(1);if(initial)state.workspace=initial;refresh();