import{state,subscribe,refresh,setWorkspace,runMission,syncMT12,metrics,health,latestGeneration,selectedGeneration,selectGeneration,producerState}from'./state.js';
import{GitHubAPI as api}from'./api.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString():'—';
const short=s=>s?String(s).slice(0,12):'—';
const repo='gymwhaleysspot-dot/mt12-jarvis-continuous';
const labels={command:'Command',vehicle:'Vehicle AI',evidence:'Evidence',intelligence:'Intelligence',factory:'Factory',firmware:'Firmware',radio:'MT12',releases:'Releases',tools:'Tools',system:'System'};
const desc={command:'Live controller lineage, factory generations, evidence, promotion authority and MT12 operations.',vehicle:'Compare the defended canonical parent against the newest generated controller and inspect what actually changed.',evidence:'Import MT12 logs, attribute them to runtime identities, replay events and feed evidence back into engineering.',intelligence:'Research memory, hypotheses, causal learning, knowledge graph and the next highest-information experiment.',factory:'One scheduler, one autonomous rewrite producer, immutable generations, historical dedup and explicit manual tools.',firmware:'Named EdgeTX and ExpressLRS releases, verified packages, backup-first flashing and recovery.',radio:'RadioMaster MT12 device state, backups, models, YAML, SD card, controller deploy files and recovery.',releases:'Canonical parent, experimental winners, authority levels, exact hashes, promotion and rollback.',tools:'Mobile companion, iPhone sync, desktop helper, viewers, tuners and support utilities.',system:'Workflow topology, live runs, data contracts, GitHub connection and wiring health.'};
const modes={automatic:'AUTO',manual:'MANUAL','manual-fallback':'FALLBACK','manual-legacy':'LEGACY','automatic-producer':'PRODUCER'};
function nav(){
  const w=state.capabilities?.workspaces||[];
  const html=w.map(x=>`<button class="navbtn ${state.workspace===x.id?'active':''}" data-workspace="${x.id}"><span class="nav-dot"></span><span>${esc(x.label)}</span></button>`).join('');
  $('#sideNav').innerHTML=html;$('#mobileNav').innerHTML=html;$$('[data-workspace]').forEach(b=>b.onclick=()=>setWorkspace(b.dataset.workspace));
}
function setTop(){
  const p=producerState(),g=latestGeneration(),c=state.canonical;
  $('#producerPill').className=`live-pill ${p.state==='RUNNING'?'running':p.state==='READY'?'good':'warn'}`;$('#producerPill em').textContent=p.state;
  $('#parentPill').className='live-pill good';$('#parentPill em').textContent=c?.name?.toUpperCase()||'—';
  $('#generationPill').className=`live-pill ${g?'good':'warn'}`;$('#generationPill em').textContent=g?`#${g.runNumber} ${String(g.tournament?.winner||'').toUpperCase()}`:'NONE';
  $('#connectionState').textContent=state.connected?'CONNECTED':'PUBLIC';$('#updated').textContent=state.updatedAt?new Date(state.updatedAt).toLocaleTimeString():'—';
}
function hero(){
  const m=metrics(),h=health();$('#workspaceTitle').textContent=labels[state.workspace]||'Jarvis';$('#workspaceDescription').textContent=desc[state.workspace]||'';$('#workspaceKicker').textContent=state.workspace==='factory'?'ONE SCHEDULER · ONE PRODUCER':state.workspace==='vehicle'?'DEFENDED CONTROLLER LINEAGE':'CLOSED-LOOP MT12 ENGINEERING';
  $('#heroFacts').innerHTML=`<div><span>Canonical parent</span><b>${esc(m.canonical)}</b></div><div><span>Latest generation</span><b>${m.latestRun?'#'+m.latestRun:'—'}</b></div><div><span>Latest winner</span><b>${esc(m.winner)}</b></div><div><span>Producer</span><b>${esc(h.producer)}</b></div>`;
}
const missions=w=>(state.capabilities?.missions||[]).filter(m=>m.workspace===w);
function missionCards(w){
  const ms=missions(w).filter(m=>m.id!=='firmware-build-flash');
  return ms.length?`<div class="mission-grid">${ms.map(m=>`<article class="mission-card"><div class="row spread"><span class="tag ${m.mode==='automatic-producer'?'good':''}">${esc(modes[m.mode]||'ACTION')}</span><span class="mono">${esc(m.workflow)}</span></div><h4>${esc(m.label)}</h4><div class="actions"><button class="btn primary" data-run="${m.id}">RUN</button><button class="btn" data-history="${m.workflow}">HISTORY</button></div></article>`).join('')}</div>`:'<div class="empty">No direct workflow is assigned here.</div>';
}
function canonicalCard(){
  const c=state.canonical;if(!c)return`<article class="card"><h3>Canonical parent</h3><div class="empty">No canonical release manifest resolved.</div></article>`;
  return`<article class="card accent"><div class="row spread"><div><div class="kicker">DEFENDED ENGINEERING PARENT</div><h2>${esc(c.name?.toUpperCase())}</h2></div><span class="authority">${esc(c.authority||'CANONICAL')}</span></div><p>${esc(c.architecture||'Canonical controller release.')}</p><div class="stat-grid"><div><span>LUAC</span><b>${fmt(c.normalizedBytes)} B</b></div><div><span>Ceiling</span><b>${fmt(c.ceilingBytes)} B</b></div><div><span>Hardware</span><b>${esc(c.hardwareStatus||'—')}</b></div><div><span>SHA</span><b class="mono">${short(c.luacSha256)}</b></div></div><div class="actions"><a class="btn primary" href="${api.raw(`${c.base}${c.deploy}`)}" download>DOWNLOAD LUAC</a><a class="btn" href="${api.raw(`${c.base}${c.source}`)}" download>DOWNLOAD LUA</a><a class="btn" href="${api.raw(`${c.base}MANIFEST.json`)}" target="_blank" rel="noopener">MANIFEST</a><a class="btn" href="${api.raw(`${c.base}BUILD-AUDIT.txt`)}" target="_blank" rel="noopener">AUDIT</a></div></article>`;
}
function winnerCard(g=latestGeneration()){
  const w=g?.winner;if(!g||!w)return`<article class="card"><h3>Latest autonomous winner</h3><div class="empty">No persisted rewrite generation is available.</div></article>`;
  const n=`${w.candidate?.toUpperCase()}-${g.runNumber}`;
  return`<article class="card winner"><div class="row spread"><div><div class="kicker">AUTONOMOUS GENERATION WINNER</div><h2>${esc(n)}</h2></div><span class="score">${esc(w.score??'—')}</span></div><p>${esc(w.profile)} profile · parent ${esc(g.tournament?.parent)} · ${esc(w.authority)}</p><div class="stat-grid"><div><span>LUAC</span><b>${fmt(w.normalizedBytes)} B</b></div><div><span>Source</span><b>${fmt(w.sourceBytes)} B</b></div><div><span>Identity</span><b class="mono">${esc(w.runtimeIdentity?.token||'—')}</b></div><div><span>LUAC SHA</span><b class="mono">${short(w.luacSha256)}</b></div></div><div class="actions"><a class="btn primary" href="${api.raw(`${g.base}${w.candidate}/${w.candidate}.luac`)}" download="${w.candidate}-${g.runNumber}.luac">DOWNLOAD LUAC</a><a class="btn" href="${api.raw(`${g.base}${w.candidate}/${w.candidate}.lua`)}" download="${w.candidate}-${g.runNumber}.lua">DOWNLOAD LUA</a><a class="btn" href="${api.raw(`${g.base}${w.candidate}/MANIFEST.json`)}" target="_blank" rel="noopener">MANIFEST</a><a class="btn" href="${api.raw(`${g.base}TOURNAMENT.json`)}" target="_blank" rel="noopener">TOURNAMENT</a></div></article>`;
}
function defenseMatrix(){
  const items=[['Protected EdgeTX APIs','pcall wrappers'],['Persistent memory','dual /LOGS/m0 + /LOGS/m1'],['Memory pressure','memOpt()'],['GVar watchdog','watch()'],['Causal coefficient','V[179] × .0045 fixed'],['Authority startup','92 → 96 progressive ceiling'],['Persistent causal state','V[704] + X[46]'],['Runtime identity','BB groups 144–151']];
  return`<article class="card"><div class="row spread"><div><div class="kicker">JRW6D DEFENDED FLOOR</div><h3>Mandatory lineage protections</h3></div><span class="tag good">HARD GATE</span></div><div class="defense-grid">${items.map(([a,b])=>`<div class="defense"><i>✓</i><div><b>${esc(a)}</b><span>${esc(b)}</span></div></div>`).join('')}</div><p class="muted">Rewrite candidates are allowed to experiment around this floor; they are not allowed to remove it.</p></article>`;
}
function generationList(){
  if(!state.generations.length)return`<div class="empty">No persisted rewrite generations discovered from successful producer runs.</div>`;
  return`<div class="generation-list">${state.generations.map(g=>{const w=g.winner,sel=g.mission===state.selectedGeneration;return`<button class="generation-row ${sel?'selected':''}" data-generation="${g.mission}"><span><b>#${g.runNumber}</b><small>${esc(g.mission)}</small></span><span><b>${esc((w?.candidate||g.tournament?.winner||'—').toUpperCase())}</b><small>${esc(w?.profile||'—')}</small></span><span><b>${w?fmt(w.normalizedBytes)+' B':'—'}</b><small>${esc(g.tournament?.verdict||g.conclusion||'—')}</small></span></button>`}).join('')}</div>`;
}
function candidateTable(g=selectedGeneration()){
  const cs=g?.tournament?.candidates||[];if(!g||!cs.length)return`<div class="empty">Select a persisted generation to inspect its candidates.</div>`;
  return`<div class="tablewrap"><table><thead><tr><th>Candidate</th><th>Profile</th><th>Score</th><th>LUAC</th><th>Delta</th><th>Authority</th><th>Files</th></tr></thead><tbody>${cs.map(c=>`<tr class="${c.candidate===g.tournament.winner?'winner-row':''}"><td><b>${esc(c.candidate.toUpperCase())}-${g.runNumber}</b>${c.candidate===g.tournament.winner?'<span class="mini-badge">WINNER</span>':''}<div class="mono tiny">${short(c.luacSha256)}</div></td><td>${esc(c.profile)}</td><td>${esc(c.score??'—')}</td><td>${fmt(c.normalizedBytes)} B</td><td>+${esc(c.intelligenceDelta??0)}</td><td>${esc(c.authority)}</td><td><div class="actions"><a class="btn tiny-btn" href="${api.raw(`${g.base}${c.candidate}/${c.candidate}.luac`)}" download>LUAC</a><a class="btn tiny-btn" href="${api.raw(`${g.base}${c.candidate}/${c.candidate}.lua`)}" download>LUA</a><a class="btn tiny-btn" href="${api.raw(`${g.base}${c.candidate}/MANIFEST.json`)}" target="_blank" rel="noopener">JSON</a></div></td></tr>`).join('')}</tbody></table></div>`;
}
function comparison(){
  const c=state.canonical,g=latestGeneration(),w=g?.winner;if(!c||!w)return'';const delta=(w.normalizedBytes||0)-(c.normalizedBytes||0);
  return`<article class="card"><div class="kicker">PARENT → WINNER</div><h3>${esc(c.name.toUpperCase())} vs ${esc(w.candidate.toUpperCase())}-${g.runNumber}</h3><div class="compare"><div><span>Parent size</span><b>${fmt(c.normalizedBytes)} B</b></div><div class="arrow">→</div><div><span>Winner size</span><b>${fmt(w.normalizedBytes)} B</b></div><div><span>Byte delta</span><b class="${delta>0?'warn-text':'good-text'}">${delta>=0?'+':''}${fmt(delta)} B</b></div><div><span>Winner profile</span><b>${esc(w.profile)}</b></div><div><span>Static score</span><b>${esc(w.score??'—')}</b></div></div><p class="muted">A static winner is still experimental. Bench and returned road-log evidence remain separate promotion authority.</p></article>`;
}
function commandPanel(){const m=state.data['public/jarvis-data/active-mission.json']||{};return`<section class="dash-grid two">${canonicalCard()}${winnerCard()}</section><section class="dash-grid two">${comparison()}<article class="card"><div class="kicker">ENGINEERING OBJECTIVE</div><h3>Tell Jarvis what to solve</h3><textarea id="objective" placeholder="Example: improve jump classification without weakening JRW6D defenses or exceeding 87 KB"></textarea><div class="actions"><button class="btn primary" id="startMission">START MISSION</button><button class="btn" data-workspace="factory">OPEN FACTORY</button></div><div class="pipeline compact-pipeline"><div><span>State</span><b>${esc(m.state||'READY')}</b></div><div><span>Stage</span><b>${esc(m.stage||'—')}</b></div><div><span>Next experiment</span><b>${esc(m.nextExperiment||'highest-information planning')}</b></div></div></article></section>${defenseMatrix()}`}
function vehiclePanel(){return`<section class="dash-grid two">${canonicalCard()}${winnerCard()}</section>${comparison()}${defenseMatrix()}<section class="card"><div class="row spread"><div><div class="kicker">CURRENT GENERATION</div><h3>Candidate tournament</h3></div><span class="tag">${esc(selectedGeneration()?.mission||'none')}</span></div>${candidateTable()}</section>`}
function factoryPanel(){const p=producerState();return`<section class="dash-grid three"><article class="metric-card"><span>Producer</span><b>${esc(p.state)}</b><small>jarvis-complete-rewrite-factory.yml</small></article><article class="metric-card"><span>Canonical parent</span><b>${esc(state.canonical?.name||'—')}</b><small>defended engineering floor</small></article><article class="metric-card"><span>Persisted generations</span><b>${state.generations.length}</b><small>latest successful runs loaded</small></article></section><section class="dash-grid factory-grid"><article class="card"><div class="row spread"><div><div class="kicker">IMMUTABLE GENERATIONS</div><h3>Rewrite history</h3></div><button class="btn primary" data-run="rewrite-factory">BUILD NEW GENERATION</button></div>${generationList()}</article><article class="card"><div class="row spread"><div><div class="kicker">SELECTED TOURNAMENT</div><h3>${selectedGeneration()?`#${selectedGeneration().runNumber}`:'No generation'}</h3></div><span class="tag good">HISTORICAL DEDUP</span></div>${candidateTable()}</article></section>${defenseMatrix()}<section class="card"><div class="kicker">FACTORY OPERATIONS</div><h3>Automatic producer and explicit manual tools</h3>${missionCards('factory')}</section>`}
function evidencePanel(){const s=state.data['public/evidence-data/sync.json']||{},logs=state.data['factory/memory/historical-log-index.json']||{};return`<section class="dash-grid three"><article class="metric-card"><span>Sync state</span><b>${esc(s.state||'READY')}</b><small>${esc(s.stage||'connect-mt12')}</small></article><article class="metric-card"><span>New files</span><b>${fmt(s.newFileCount||0)}</b><small>last import</small></article><article class="metric-card"><span>Known logs</span><b>${fmt(logs.uniqueLogs??logs.logs?.length??0)}</b><small>historical evidence index</small></article></section><section class="card accent"><div class="row spread"><div><div class="kicker">USB / IPHONE EVIDENCE</div><h3>Jarvis Sync</h3><p>Backup first, copy new radio and blackbox logs, SHA-256 deduplicate, identify the runtime controller, then start replay and learning.</p></div><button class="btn primary" id="jarvisSync">JARVIS SYNC</button></div><div class="chipline"><span class="tag good">BACKUP FIRST</span><span class="tag">IDENTITY 144–151</span><span class="tag">SHA-256 DEDUP</span><span class="tag">AUTO LEARN</span></div></section><section class="card"><div class="kicker">EVIDENCE OPERATIONS</div>${missionCards('evidence')}</section>`}
function intelligencePanel(){const m=metrics(),r=state.data['research/current.json']||{},q=state.data['research/questions.json']||{};return`<section class="dash-grid four"><article class="metric-card"><span>Evidence facts</span><b>${fmt(m.facts)}</b></article><article class="metric-card"><span>Knowledge nodes</span><b>${fmt(m.nodes)}</b></article><article class="metric-card"><span>Episodes</span><b>${fmt(m.episodes)}</b></article><article class="metric-card"><span>Logs</span><b>${fmt(m.logs)}</b></article></section><section class="dash-grid two"><article class="card"><div class="kicker">CURRENT RESEARCH</div><h3>${esc(r.area||r.topic||'Highest-information experiment')}</h3><div class="console">${esc(JSON.stringify(r,null,2)).slice(0,5000)}</div></article><article class="card"><div class="kicker">OPEN QUESTIONS</div><h3>What Jarvis still needs to learn</h3><div class="console">${esc(JSON.stringify(q,null,2)).slice(0,5000)}</div></article></section><section class="card">${missionCards('intelligence')}</section>`}
function releasePanel(){const idx=state.data['public/builds/index.json']||{};return`<section class="dash-grid two">${canonicalCard()}${winnerCard()}</section><section class="dash-grid two">${comparison()}<article class="card"><div class="kicker">PROMOTION AUTHORITY</div><h3>${idx.recommended?'Recommended: '+esc(idx.recommended):'No road-proven recommendation yet'}</h3><div class="authority-ladder">${(state.capabilities?.authority?.controller||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div><p class="muted">Compilation, static scoring and factory victory do not automatically become bench- or road-proven authority.</p></article></section><section class="card">${missionCards('releases')}</section>`}
function firmwarePanel(){const d=state.data['public/device-data/releases.json']||{},e=d.edgeTx||{},x=d.expressLrs||{};const card=(name,r)=>`<article class="card"><div class="kicker">${esc(name)}</div><h3>${esc(r?.name||r?.tag||'No catalog release')}</h3><p>${esc(r?.version||r?.tag||'—')}</p><div class="actions"><button class="btn" data-run="firmware-catalog">REFRESH CATALOG</button><button class="btn" data-history="firmware-build-flash.yml">BUILD / FLASH HISTORY</button></div></article>`;return`<section class="dash-grid two">${card('EDGETX STABLE',e.stable)}${card('EXPRESSLRS STABLE',x.stable)}</section><section class="card"><div class="kicker">FIRMWARE OPERATIONS</div>${missionCards('firmware')}</section>`}
function radioPanel(){return`<section class="dash-grid four"><article class="metric-card"><span>Radio</span><b>MT12</b><small>RadioMaster</small></article><article class="metric-card"><span>Runtime</span><b>Lua 5.3</b><small>normalized bytecode</small></article><article class="metric-card"><span>LUAC ceiling</span><b>87 KB</b><small>engineering limit</small></article><article class="metric-card"><span>Monitor channels</span><b>15 / 16</b><small>TCT / GYR</small></article></section><section class="dash-grid two">${canonicalCard()}<article class="card"><div class="kicker">DEVICE CONTRACT</div><h3>Deploy and recovery</h3><div class="defense-grid"><div class="defense"><i>✓</i><div><b>Normalized deploy</b><span>use final .luac only</span></div></div><div class="defense"><i>✓</i><div><b>Backup first</b><span>before firmware or model changes</span></div></div><div class="defense"><i>✓</i><div><b>Car-off guard</b><span>controller remains bench-safe</span></div></div><div class="defense"><i>✓</i><div><b>Persistent memory</b><span>checksummed A/B files</span></div></div></div></article></section><section class="card">${missionCards('radio')}</section>`}
function toolsPanel(){return`<section class="card"><div class="kicker">COMPANION ECOSYSTEM</div><h3>Mobile, desktop and support tooling</h3>${missionCards('tools')}</section>`}
function systemPanel(){const h=health(),caps=state.capabilities,failed=state.runs.filter(r=>r.status==='completed'&&r.conclusion==='failure').slice(0,12);return`<section class="dash-grid four"><article class="metric-card"><span>Scheduler</span><b>${esc(h.scheduler)}</b></article><article class="metric-card"><span>Producer</span><b>${esc(h.producer)}</b></article><article class="metric-card"><span>GitHub</span><b>${esc(h.github)}</b></article><article class="metric-card"><span>Data contract</span><b>v${esc(caps?.schema||'—')}</b></article></section><section class="dash-grid two"><article class="card"><div class="kicker">LIVE TOPOLOGY</div><h3>${esc(caps?.orchestration?.policy||'—')}</h3><div class="topology"><div><b>Scheduler</b><span>${esc(caps?.orchestration?.scheduler||'—')}</span></div><i>→</i><div><b>Controller producer</b><span>${esc(caps?.orchestration?.controllerProducer||'—')}</span></div><i>→</i><div><b>Immutable generations</b><span>rewrite-&lt;run&gt;-&lt;attempt&gt;</span></div></div><div class="chipline"><span class="tag good">HISTORICAL DEDUP</span><span class="tag">NO SELF-REQUEUE</span><span class="tag">MANUAL SECONDARIES</span></div></article><article class="card"><div class="kicker">CONNECTION</div><h3>${state.connected?'Authenticated as '+esc(state.user?.login):'Public read mode'}</h3><button class="btn" id="openAuth">MANAGE GITHUB CONNECTION</button><p class="muted">Public state remains readable without a token. Workflow dispatches require the saved PAT.</p></article></section><section class="card"><div class="row spread"><div><div class="kicker">RECENT WORKFLOWS</div><h3>Latest repository activity</h3></div><span class="tag ${failed.length?'warn':'good'}">${failed.length} RECENT FAILURES</span></div><div class="tablewrap"><table><thead><tr><th>Run</th><th>Workflow</th><th>Status</th><th>Conclusion</th><th>SHA</th></tr></thead><tbody>${state.runs.slice(0,30).map(r=>`<tr><td>#${esc(r.run_number)}</td><td>${esc(r.name)}</td><td>${esc(r.status)}</td><td>${esc(r.conclusion||'pending')}</td><td class="mono">${short(r.head_sha)}</td></tr>`).join('')}</tbody></table></div></section><section class="card"><div class="kicker">SYSTEM OPERATIONS</div>${missionCards('system')}</section>`}
function workspace(){let body='';switch(state.workspace){case'command':body=commandPanel();break;case'vehicle':body=vehiclePanel();break;case'factory':body=factoryPanel();break;case'evidence':body=evidencePanel();break;case'intelligence':body=intelligencePanel();break;case'releases':body=releasePanel();break;case'firmware':body=firmwarePanel();break;case'radio':body=radioPanel();break;case'tools':body=toolsPanel();break;case'system':body=systemPanel();break;default:body=commandPanel()}$('#workspaceBody').innerHTML=body;wire()}
function render(){nav();setTop();hero();workspace();$('#loading').hidden=!state.loading;$('#globalError').hidden=!state.error;$('#globalError').textContent=state.error||''}
async function dispatchButton(b){const id=b.dataset.run,old=b.textContent;b.disabled=true;b.textContent='DISPATCHING…';try{await runMission(id);b.textContent='STARTED'}catch(e){alert(e.message);b.textContent='FAILED'}finally{setTimeout(()=>{b.disabled=false;b.textContent=old},1800)}}
function openDrawer(open=true){$('#drawer').classList.toggle('open',open);$('#overlay').classList.toggle('open',open)}
function wire(){
  $$('[data-run]').forEach(b=>b.onclick=()=>dispatchButton(b));
  $$('[data-history]').forEach(b=>b.onclick=()=>window.open(`https://github.com/${repo}/actions/workflows/${b.dataset.history}`,'_blank','noopener'));
  $$('[data-generation]').forEach(b=>b.onclick=()=>selectGeneration(b.dataset.generation));
  $$('[data-workspace]').forEach(b=>b.onclick=()=>setWorkspace(b.dataset.workspace));
  const mission=$('#startMission');if(mission)mission.onclick=async()=>{const text=$('#objective').value.trim();if(!text)return alert('Enter an engineering objective.');mission.disabled=true;try{await runMission('engineering-mission',{topic:text})}catch(e){alert(e.message)}finally{mission.disabled=false}};
  const sync=$('#jarvisSync');if(sync)sync.onclick=async()=>{sync.disabled=true;sync.textContent='SYNCING…';try{await syncMT12()}catch(e){alert(e.message)}finally{sync.disabled=false;sync.textContent='JARVIS SYNC'}};
  const auth=$('#openAuth');if(auth)auth.onclick=()=>openDrawer(true);
}
$('#refresh').onclick=()=>refresh();$('#connection').onclick=()=>openDrawer(true);$('#closeDrawer').onclick=()=>openDrawer(false);$('#overlay').onclick=()=>openDrawer(false);$('#homeButton').onclick=()=>setWorkspace('command');
$('#testToken').onclick=async()=>{const box=$('#authMessage');box.textContent='Testing…';try{const u=await api.user();box.textContent=`Connected as ${u.login}.`;await refresh()}catch(e){box.textContent=`Connection failed: ${e.message}`}};
$('#clearToken').onclick=()=>{window.A17YToken?.clear?.();localStorage.removeItem('a17y_classic_pat');localStorage.removeItem('a17y_pat');$('#authMessage').textContent='Saved token cleared.';refresh()};
subscribe(render);const initial=location.hash.slice(1);if(initial)state.workspace=initial;refresh();
