import{GitHubAPI as api}from'./api.js';
const allowed=/\.(csv|log|txt|json|lua|luac|ya?ml)$/i,MAX=90*1024*1024;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s||'file').replace(/[^A-Za-z0-9._/-]+/g,'_').replace(/^\/+|\.\.(?=\/|$)/g,'').slice(-200);
const key='jarvis_evidence_upload_v3';
const load=()=>{try{return JSON.parse(localStorage.getItem(key)||'{"hashes":{},"pending":[]}')}catch{return{hashes:{},pending:[]}}};
const save=x=>localStorage.setItem(key,JSON.stringify(x));
async function hash(file){const b=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const sessionId=()=>`ios-${new Date().toISOString().replace(/[-:.]/g,'').slice(0,15)}-${Math.random().toString(36).slice(2,7)}`;
function setStatus(t,p=0){const e=$('#eosStatus'),b=$('#eosBar');if(e)e.textContent=t;if(b)b.value=Math.max(0,Math.min(100,p))}
function render(){
  if(location.hash!=='#evidence')return;
  const body=$('#workspaceBody');
  if(!body||body.querySelector('#eosPick'))return;
  body.innerHTML=`<section class="grid"><article class="card span-8"><div class="row"><div><div class="chip">IPHONE 17 EVIDENCE OS</div><h3>Sync, pair, verify and learn</h3><p class="muted">Select the MT12 LOGS folder. Uploads resume file-by-file, preserve paths, hash every item, reject unsafe types, and dispatch the complete evidence authority pipeline.</p></div><button class="btn primary" id="eosPick">SELECT MT12 LOGS</button></div><input id="eosFiles" type="file" webkitdirectory directory multiple accept=".csv,.log,.txt,.json,.lua,.luac,.yml,.yaml" hidden><progress id="eosBar" max="100" value="0" aria-label="Evidence upload progress"></progress><div id="eosStatus" class="meta">Ready.</div><div class="chips"><span class="chip">RESUMABLE</span><span class="chip">SHA-256</span><span class="chip">90 MB/FILE</span><span class="chip">PATH SANITIZED</span><span class="chip">AUTO PAIR</span><span class="chip">AUTO REPLAY</span></div></article><article class="card span-4"><h3>Evidence authority</h3><div id="eosSummary" class="list"><div class="item"><div class="title">Waiting for evidence</div><div class="meta">A session report appears after upload.</div></div></div><button class="btn" id="eosResume">RESUME FAILED FILES</button></article></section><section class="grid"><article class="card span-6"><h3>Session review</h3><div id="eosSessions" class="empty">No reviewed sessions loaded.</div></article><article class="card span-6"><h3>Phone certification & install</h3><p class="muted">Record real MT12 results and install normalized LUACs through Files without pretending Safari can perform DFU flashing.</p><div class="actions"><button class="btn" data-cert="LOADED">LOADED</button><button class="btn" data-cert="BENCH_PROVEN">BENCH PROVEN</button><button class="btn" data-cert="ROAD_PROVEN">ROAD PROVEN</button><button class="btn danger" data-cert="MEMORY_PANIC">MEMORY PANIC</button><button class="btn danger" data-cert="CONTROL_REGRESSION">CONTROL REGRESSION</button></div><ol class="muted"><li>Download the named normalized .luac from Vehicle AI.</li><li>Open Downloads in Files and copy it to the MT12 scripts folder.</li><li>Keep the previous LUAC as rollback.</li><li>Return here and record the result; Jarvis updates authority and parent selection.</li></ol><p class="muted"><b>Firmware:</b> iPhone may download and copy packages, but EdgeTX DFU and ExpressLRS serial flashing require a supported native flashing host.</p></article></section>`;
  wire();
  loadReports();
}
async function loadReports(){try{const s=await api.optionalFile('public/evidence-data/sessions.json')||{};const rows=s.sessions||[];const box=$('#eosSessions');if(box)box.innerHTML=rows.length?rows.slice(0,12).map(x=>`<div class="item"><div class="title">${esc(x.id)} · ${esc(x.controller||'UNATTRIBUTED')} · ${Math.round((x.confidence||0)*100)}%</div><div class="meta">${esc(x.type||'UNKNOWN')} · ${esc(x.duration||'—')} · ${Number(x.events?.tc||0)} TC · ${Number(x.events?.abs||0)} ABS · ${Number(x.events?.jumps||0)} jumps · ${esc(x.state||'REVIEW')}</div></div>`).join(''):'<div class="empty">No reviewed sessions yet.</div>'}catch(e){console.warn(e)}}
async function upload(files,onlyPending=false){if(!api.token())throw Error('Connect the classic GitHub token first.');const db=load(),sid=sessionId(),base=`evidence/raw/${sid}`,list=onlyPending?files.filter(f=>db.pending.some(p=>p.name===f.name&&p.size===f.size)):files.filter(f=>allowed.test(f.name)&&f.size>0&&f.size<=MAX);if(!list.length)throw Error('No supported files selected.');let uploaded=0,duplicate=0,failed=0;const records=[];db.pending=[];for(let i=0;i<list.length;i++){const f=list[i],pct=Math.round(i/list.length*100);setStatus(`Hashing ${i+1}/${list.length}: ${f.name}`,pct);try{const sha=await hash(f),path=clean(f.webkitRelativePath||f.name);if(db.hashes[sha]){duplicate++;records.push({path,size:f.size,sha256:sha,status:'duplicate',duplicateOf:db.hashes[sha]});continue}setStatus(`Uploading ${i+1}/${list.length}: ${f.name}`,pct);await api.putBytes(`${base}/${path}`,new Uint8Array(await f.arrayBuffer()),`Import iPhone evidence ${sid}: ${path}`);db.hashes[sha]=`${base}/${path}`;uploaded++;records.push({path,size:f.size,sha256:sha,status:'uploaded',modifiedAt:new Date(f.lastModified).toISOString()})}catch(error){failed++;db.pending.push({name:f.name,size:f.size,path:f.webkitRelativePath||f.name,error:error.message});records.push({path:f.name,size:f.size,status:'failed',error:error.message})}save(db)}const manifest={schema:3,id:sid,source:'iPhone 17 Safari Files',createdAt:new Date().toISOString(),state:failed?'PARTIAL':'UPLOADED',newFileCount:uploaded,duplicatesSkipped:duplicate,failedFiles:failed,files:records,security:{allowedExtensions:['csv','log','txt','json','lua','luac','yml','yaml'],maxFileBytes:MAX,pathSanitized:true,tokenRedacted:true},next:'evidence-authority'};await api.putText(`${base}/MANIFEST.json`,JSON.stringify(manifest,null,2)+'\n',`Publish evidence manifest ${sid}`);await api.putText('public/evidence-data/sync.json',JSON.stringify({...manifest,message:`${uploaded} uploaded, ${duplicate} duplicate, ${failed} failed.`},null,2)+'\n',`Publish evidence sync state ${sid}`);setStatus('Starting pairing, attribution, replay, twin calibration and mutation authority…',95);await api.dispatch('evidence-authority.yml',{session_id:sid});setStatus(`Complete: ${uploaded} uploaded, ${duplicate} skipped, ${failed} pending.`,100);const summary=$('#eosSummary');if(summary)summary.innerHTML=`<div class="item"><div class="title">${esc(sid)}</div><div class="meta">${uploaded} new · ${duplicate} duplicate · ${failed} failed · authority pipeline dispatched</div></div>`}
function wire(){const pick=$('#eosPick'),inp=$('#eosFiles'),resume=$('#eosResume');if(!pick||!inp)return;pick.onclick=()=>{inp.value='';inp.click()};inp.onchange=async()=>{pick.disabled=true;try{await upload([...inp.files])}catch(e){alert(e.message);setStatus(`Failed: ${e.message}`)}finally{pick.disabled=false}};if(resume)resume.onclick=()=>alert('Reconnect the MT12 and select the same LOGS folder. Jarvis will skip completed hashes and retry only missing files.');document.querySelectorAll('[data-cert]').forEach(b=>b.onclick=async()=>{try{const controller=prompt('Controller name (example j00002):');if(!controller)return;const note=prompt('Optional test note:')||'';const rec={schema:1,controller,result:b.dataset.cert,note,recordedAt:new Date().toISOString(),source:'iPhone 17'};await api.putText(`evidence/certifications/${clean(controller)}-${Date.now()}.json`,JSON.stringify(rec,null,2)+'\n',`Record ${controller} ${rec.result}`);await api.dispatch('evidence-authority.yml',{session_id:'certification'});alert('Certification recorded and authority update started.')}catch(e){alert(e.message)}})}
let scheduled=false;
const scheduleRender=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;render()})};
new MutationObserver(mutations=>{if(location.hash!=='#evidence'||$('#eosPick'))return;if(mutations.some(m=>[...m.addedNodes].some(n=>n.nodeType===1&&(n.id==='workspaceBody'||n.querySelector?.('#workspaceBody')))))scheduleRender()}).observe(document.body,{childList:true,subtree:true});
window.addEventListener('hashchange',scheduleRender);
window.addEventListener('load',scheduleRender);
scheduleRender();
