import{GitHubAPI as api}from'./api.js';
const allowed=/\.(csv|log|txt|json|lua|luac|ya?ml)$/i,MAX=90*1024*1024;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s||'file').replace(/[^A-Za-z0-9._/-]+/g,'_').replace(/^\/+|\.\.(?=\/|$)/g,'').slice(-200);
const key='jarvis_evidence_upload_v4';
const load=()=>{try{return JSON.parse(localStorage.getItem(key)||'{"hashes":{},"pending":[]}')}catch{return{hashes:{},pending:[]}}};
const save=x=>localStorage.setItem(key,JSON.stringify(x));
async function hash(file){const b=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const sessionId=()=>`ios-${new Date().toISOString().replace(/[-:.]/g,'').slice(0,15)}-${Math.random().toString(36).slice(2,7)}`;
function setStatus(t,p=0){const e=$('#eosStatus'),b=$('#eosBar');if(e)e.textContent=t;if(b)b.value=Math.max(0,Math.min(100,p))}
function evidenceActive(){return location.hash==='#evidence'||$('#workspaceTitle')?.textContent?.trim()==='Evidence'}
export function mountEvidence(){
 if(!evidenceActive())return false;
 const body=$('#workspaceBody');if(!body)return false;
 if(body.dataset.owner==='evidence-os'&&$('#eosPick'))return true;
 body.dataset.owner='evidence-os';
 body.innerHTML=`<section class="grid"><article class="card span-8"><div class="row"><div><div class="chip">IPHONE 17 EVIDENCE OS</div><h3>Sync, pair, verify and learn</h3><p class="muted">Connect the MT12 by USB-C, then select its LOGS folder in Files. Jarvis hashes, deduplicates, uploads and starts attribution, replay and learning.</p></div><div class="actions"><button class="btn primary" id="eosPick">SELECT MT12 LOGS</button><button class="btn" id="eosPickFiles">SELECT LOG FILES</button></div></div><input id="eosFolder" type="file" webkitdirectory multiple accept=".csv,.log,.txt,.json,.lua,.luac,.yml,.yaml" hidden><input id="eosFiles" type="file" multiple accept=".csv,.log,.txt,.json,.lua,.luac,.yml,.yaml" hidden><progress id="eosBar" max="100" value="0" aria-label="Evidence upload progress"></progress><div id="eosStatus" class="meta">Ready. Choose the MT12 LOGS folder or individual logs.</div><div class="chips"><span class="chip">IPHONE FILES</span><span class="chip">RESUMABLE</span><span class="chip">SHA-256</span><span class="chip">AUTO PAIR</span><span class="chip">AUTO REPLAY</span></div></article><article class="card span-4"><h3>Connection check</h3><div id="eosConnection" class="list"><div class="item"><div class="title">GitHub token</div><div class="meta">${api.token()?'Detected':'Not detected — tap CONNECTED/OFFLINE above'}</div></div><div class="item"><div class="title">Folder picker</div><div class="meta">${'webkitdirectory' in document.createElement('input')?'Available':'Use SELECT LOG FILES fallback'}</div></div></div><button class="btn" id="eosTest">TEST EVIDENCE CONNECTION</button><button class="btn" id="eosResume">RESUME FAILED FILES</button></article></section><section class="grid"><article class="card span-6"><h3>Session review</h3><div id="eosSessions" class="empty">Loading reviewed sessions…</div></article><article class="card span-6"><h3>Phone certification & install</h3><div class="actions"><button class="btn" data-cert="LOADED">LOADED</button><button class="btn" data-cert="BENCH_PROVEN">BENCH PROVEN</button><button class="btn" data-cert="ROAD_PROVEN">ROAD PROVEN</button><button class="btn danger" data-cert="MEMORY_PANIC">MEMORY PANIC</button><button class="btn danger" data-cert="CONTROL_REGRESSION">CONTROL REGRESSION</button></div><p class="muted">Download a normalized LUAC from Vehicle AI, copy it to the MT12 through Files, preserve the previous file for rollback, then record the result here.</p></article></section>`;
 loadReports();return true;
}
async function loadReports(){try{const s=await api.optionalFile('public/evidence-data/sessions.json')||{};const rows=s.sessions||[],box=$('#eosSessions');if(box)box.innerHTML=rows.length?rows.slice(0,12).map(x=>`<div class="item"><div class="title">${esc(x.id)} · ${esc(x.controller||'UNATTRIBUTED')} · ${Math.round((x.confidence||0)*100)}%</div><div class="meta">${esc(x.type||'UNKNOWN')} · ${Number(x.events?.tc||0)} TC · ${Number(x.events?.abs||0)} ABS · ${Number(x.events?.jumps||0)} jumps · ${esc(x.state||'REVIEW')}</div></div>`).join(''):'<div class="empty">No reviewed sessions yet.</div>'}catch(e){const box=$('#eosSessions');if(box)box.innerHTML=`<div class="empty">Could not load sessions: ${esc(e.message)}</div>`}}
async function upload(files){if(!api.token())throw Error('Connect the classic GitHub token first.');const db=load(),sid=sessionId(),base=`evidence/raw/${sid}`,list=[...files].filter(f=>allowed.test(f.name)&&f.size>0&&f.size<=MAX);if(!list.length)throw Error('No supported, non-empty files were selected.');let uploaded=0,duplicate=0,failed=0;const records=[];db.pending=[];for(let i=0;i<list.length;i++){const f=list[i],pct=Math.round(i/list.length*90);setStatus(`Hashing ${i+1}/${list.length}: ${f.name}`,pct);try{const sha=await hash(f),path=clean(f.webkitRelativePath||f.name);if(db.hashes[sha]){duplicate++;records.push({path,size:f.size,sha256:sha,status:'duplicate',duplicateOf:db.hashes[sha]});continue}setStatus(`Uploading ${i+1}/${list.length}: ${f.name}`,pct);await api.putBytes(`${base}/${path}`,new Uint8Array(await f.arrayBuffer()),`Import iPhone evidence ${sid}: ${path}`);db.hashes[sha]=`${base}/${path}`;uploaded++;records.push({path,size:f.size,sha256:sha,status:'uploaded'})}catch(error){failed++;db.pending.push({name:f.name,size:f.size,path:f.webkitRelativePath||f.name,error:error.message});records.push({path:f.name,size:f.size,status:'failed',error:error.message})}save(db)}const manifest={schema:4,id:sid,source:'iPhone Safari Files',createdAt:new Date().toISOString(),state:failed?'PARTIAL':'UPLOADED',newFileCount:uploaded,duplicatesSkipped:duplicate,failedFiles:failed,files:records};setStatus('Publishing manifest…',92);await api.putText(`${base}/MANIFEST.json`,JSON.stringify(manifest,null,2)+'\n',`Publish evidence manifest ${sid}`);await api.putText('public/evidence-data/sync.json',JSON.stringify({...manifest,message:`${uploaded} uploaded, ${duplicate} duplicate, ${failed} failed.`},null,2)+'\n',`Publish evidence sync state ${sid}`);setStatus('Starting evidence authority…',96);await api.dispatch('evidence-authority.yml',{session_id:sid});setStatus(`Complete: ${uploaded} uploaded, ${duplicate} skipped, ${failed} failed.`,100)}
async function choose(input){input.value='';input.click()}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||!evidenceActive())return;try{if(b.id==='eosPick'){e.preventDefault();return choose($('#eosFolder'))}if(b.id==='eosPickFiles'){e.preventDefault();return choose($('#eosFiles'))}if(b.id==='eosTest'){e.preventDefault();b.disabled=true;const u=await api.user();setStatus(`Connected to GitHub as ${u.login}. Evidence workflow ready.`,0);b.disabled=false;return}if(b.id==='eosResume'){e.preventDefault();setStatus('Select the same folder again. Completed hashes will be skipped.',0);return choose($('#eosFolder'))}if(b.dataset.cert){e.preventDefault();const controller=prompt('Controller name:');if(!controller)return;const note=prompt('Optional test note:')||'',rec={schema:1,controller,result:b.dataset.cert,note,recordedAt:new Date().toISOString(),source:'iPhone'};await api.putText(`evidence/certifications/${clean(controller)}-${Date.now()}.json`,JSON.stringify(rec,null,2)+'\n',`Record ${controller} ${rec.result}`);await api.dispatch('evidence-authority.yml',{session_id:'certification'});setStatus('Certification recorded and authority update started.',0)}}catch(error){setStatus(`Failed: ${error.message}`,0);alert(error.message)}});
document.addEventListener('change',async e=>{if(!evidenceActive()||!['eosFolder','eosFiles'].includes(e.target.id))return;const files=[...e.target.files];if(!files.length)return;try{e.target.disabled=true;await upload(files)}catch(error){setStatus(`Failed: ${error.message}`,0);alert(error.message)}finally{e.target.disabled=false}});
window.addEventListener('hashchange',()=>requestAnimationFrame(mountEvidence));
window.addEventListener('load',()=>requestAnimationFrame(mountEvidence));
setInterval(()=>{if(evidenceActive()&&!$('#eosPick'))mountEvidence()},500);
requestAnimationFrame(mountEvidence);
