(()=>{
'use strict';
const REPO='gymwhaleysspot-dot/mt12-jarvis-continuous';
const CATALOG='public/device-data/releases.json';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const size=n=>Number.isFinite(Number(n))?(Number(n)/1048576).toFixed(1)+' MB':'—';
const date=v=>v?new Date(v).toLocaleString():'—';
let catalog=null,loading=null,painting=false;
async function load(){if(catalog)return catalog;if(!loading)loading=fetch(CATALOG+'?v='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Firmware catalog '+r.status);return r.json()}).then(x=>(catalog=x)).finally(()=>loading=null);return loading}
function hrefWorkflow(name){return `https://github.com/${REPO}/actions/workflows/${name}`}
function assetLink(a,label){if(!a?.downloadUrl)return'';return `<a class="btn" href="${esc(a.downloadUrl)}" target="_blank" rel="noopener">${esc(label||'DOWNLOAD')}</a>`}
function releaseCard(kind,r,accent){if(!r)return `<article class="card"><h3>${esc(kind)}</h3><div class="empty">No release resolved.</div></article>`;
 const fw=kind==='EdgeTX'?(r.mt12Firmware?.[0]||r.firmwareBundles?.[0]||r.assets?.find(a=>/^edgetx-firmware-.*\.zip$/i.test(a.name))):(r.firmwareAssets?.[0]||r.assets?.[0]);
 const cfg=kind==='ExpressLRS'?(r.configuratorAssets?.[0]||null):null;
 const target=kind==='EdgeTX'?(r.targetMatched?'MT12 TARGET RESOLVED':r.firmwareBundles?.length?'MT12 INSIDE OFFICIAL BUNDLE':'TARGET NOT RESOLVED'):'MT12 INTERNAL ELRS TARGET';
 return `<article class="card ${accent?'accent':''}"><div class="row spread"><div><div class="kicker">${esc(kind.toUpperCase())} STABLE</div><h2>${esc(r.version||r.tag||'—')}</h2></div><span class="tag ${r.channel==='stable'?'good':''}">${esc(r.channel||'release')}</span></div><p>${esc(r.name||'')}</p><div class="stat-grid"><div><span>Target</span><b>${esc(target)}</b></div><div><span>Published</span><b>${esc(date(r.publishedAt))}</b></div><div><span>Package</span><b>${esc(fw?.name||'—')}</b></div><div><span>Size</span><b>${esc(size(fw?.size))}</b></div></div><div class="actions">${assetLink(fw,kind==='EdgeTX'?'DOWNLOAD OFFICIAL FIRMWARE':'DOWNLOAD ELRS ASSET')}${assetLink(cfg,'DOWNLOAD CONFIGURATOR')}<a class="btn" href="${esc(r.notesUrl||'#')}" target="_blank" rel="noopener">RELEASE NOTES</a></div></article>`}
function prereleaseRow(kind,r){if(!r)return'';const fw=kind==='EdgeTX'?(r.mt12Firmware?.[0]||r.firmwareBundles?.[0]||r.assets?.find(a=>/^edgetx-firmware-.*\.zip$/i.test(a.name))):(r.firmwareAssets?.[0]||r.assets?.[0]);return `<article class="metric-card"><span>${esc(kind)} prerelease</span><b>${esc(r.version||r.tag||'—')}</b><small>${esc(fw?.name||'no package resolved')}</small>${fw?`<a class="btn tiny-btn" href="${esc(fw.downloadUrl)}" target="_blank" rel="noopener">DOWNLOAD</a>`:''}</article>`}
function html(d){const e=d.edgeTx||{},x=d.expressLrs||{};return `<section id="firmwareCenter" data-jarvis-firmware-center="1"><section class="dash-grid two">${releaseCard('EdgeTX',e.stable,true)}${releaseCard('ExpressLRS',x.stable,true)}</section><section class="dash-grid two">${prereleaseRow('EdgeTX',e.prerelease)}${prereleaseRow('ExpressLRS',x.prerelease)}</section><section class="card"><div class="row spread"><div><div class="kicker">MT12 FIRMWARE OPERATIONS</div><h3>Catalog · build · verify · flash</h3></div><span class="tag good">${esc(d.target?.radio||'RadioMaster MT12')}</span></div><p>EdgeTX MT12 firmware is distributed inside the official EdgeTX firmware bundle. Jarvis now exposes that bundle instead of hiding the release when no separate MT12-named GitHub asset exists. ExpressLRS releases remain visible with the configured MT12 internal 2.4 GHz target.</p><div class="actions"><a class="btn primary" href="${hrefWorkflow('firmware-build-flash.yml')}" target="_blank" rel="noopener">BUILD / FLASH</a><a class="btn" href="${hrefWorkflow('firmware-catalog.yml')}" target="_blank" rel="noopener">REFRESH CATALOG</a><a class="btn" href="${CATALOG}" target="_blank" rel="noopener">VIEW CATALOG JSON</a></div><div class="console">Catalog generated: ${esc(date(d.generatedAt))}\nEdgeTX target: ${esc(d.target?.edgeTxTarget||'RadioMaster MT12')}\nExpressLRS target: ${esc(d.target?.elrsTarget||'RadioMaster MT12 Internal 2.4GHz TX')}</div></section></section>`}
async function paint(){if(painting)return;const body=document.getElementById('workspaceBody');const title=document.getElementById('workspaceTitle');const active=location.hash==='#firmware'||title?.textContent?.trim()==='Firmware';if(!body||!active)return;const existing=document.getElementById('firmwareCenter');if(existing)return;painting=true;try{const d=await load();if(!document.getElementById('firmwareCenter')&&(location.hash==='#firmware'||document.getElementById('workspaceTitle')?.textContent?.trim()==='Firmware'))body.insertAdjacentHTML('afterbegin',html(d))}catch(e){if(!document.getElementById('firmwareCenter'))body.insertAdjacentHTML('afterbegin',`<section id="firmwareCenter" class="card"><h3>Firmware catalog</h3><div class="notice error">${esc(e.message)}</div><div class="actions"><a class="btn" href="${hrefWorkflow('firmware-catalog.yml')}" target="_blank">OPEN CATALOG WORKFLOW</a></div></section>`)}finally{painting=false}}
new MutationObserver(()=>paint()).observe(document.documentElement,{subtree:true,childList:true,characterData:true});
window.addEventListener('hashchange',()=>setTimeout(paint,0));
window.addEventListener('load',paint);
setTimeout(paint,300);
})();
