import{state,subscribe}from'./state.js';
import{mountEvidence}from'./evidence-os.js';
const REPO='gymwhaleysspot-dot/mt12-jarvis-continuous';
let scheduled=false;
function workflowPath(name){return `.github/workflows/${name}`}
function activeWorkflows(){return new Set((state.workflows||[]).filter(w=>w.state==='active').map(w=>w.path))}
function missionMap(){return new Map((state.capabilities?.missions||[]).map(m=>[m.id,m]))}
function validateControls(){const active=activeWorkflows(),missions=missionMap(),known=state.workflows?.length>0;document.querySelectorAll('[data-run]').forEach(button=>{const mission=missions.get(button.dataset.run),valid=mission&&(!known||active.has(workflowPath(mission.workflow)));button.disabled=!mission||(known&&!valid);button.setAttribute('aria-disabled',String(button.disabled));button.title=!mission?'Mission is not registered':known&&!valid?`Workflow unavailable: ${mission.workflow}`:`Run ${mission.label}`;if(!mission)button.textContent='UNAVAILABLE'});document.querySelectorAll('[data-openwf]').forEach(button=>{const name=button.dataset.openwf,valid=!known||active.has(workflowPath(name));button.disabled=known&&!valid;button.setAttribute('aria-disabled',String(button.disabled));button.title=valid?`Open ${name} workflow history`:`Workflow unavailable: ${name}`})}
function reportWiring(){const box=document.querySelector('#globalError');if(!box||state.loading)return;const active=activeWorkflows(),known=state.workflows?.length>0,missingMissions=known?(state.capabilities?.missions||[]).filter(m=>!active.has(workflowPath(m.workflow))):[],missingRequiredData=(state.capabilities?.dataSources||[]).filter(d=>d.required===true&&state.data[d.path]==null),critical=[];if(!state.capabilities)critical.push('capabilities unavailable');if(missingMissions.length)critical.push(`${missingMissions.length} operations unavailable`);if(missingRequiredData.length)critical.push(`${missingRequiredData.length} required data sources unavailable`);if(state.error)box.textContent=`Connection status: ${state.error}`;else if(critical.length)box.textContent=`Wiring status: ${critical.join(' · ')}. Unavailable controls are disabled.`;else box.textContent=''}
function installHistoryLinks(){document.querySelectorAll('[data-openwf]:not([data-integration-wired])').forEach(button=>{button.dataset.integrationWired='1';button.addEventListener('click',event=>{if(button.disabled)return;event.preventDefault();window.open(`https://github.com/${REPO}/actions/workflows/${encodeURIComponent(button.dataset.openwf)}`,'_blank','noopener')},true)})}
function reconcile(){scheduled=false;if(location.hash==='#evidence'||state.workspace==='evidence')mountEvidence();validateControls();installHistoryLinks();reportWiring()}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(reconcile)}
subscribe(schedule);window.addEventListener('hashchange',schedule);window.addEventListener('load',schedule);new MutationObserver(mutations=>{if(mutations.some(m=>m.target.closest?.('#workspaceBody,#sideNav,#mobileNav')||m.target.id==='workspaceBody'))schedule()}).observe(document.body,{childList:true,subtree:true});schedule();
