import{state,subscribe}from'./state.js';
import{mountEvidence}from'./evidence-os.js';
const REPO='gymwhaleysspot-dot/mt12-jarvis-continuous';
let scheduled=false;
function workflowPath(name){return `.github/workflows/${name}`}
function activeWorkflows(){return new Set((state.workflows||[]).filter(w=>w.state==='active').map(w=>w.path))}
function missionMap(){return new Map((state.capabilities?.missions||[]).map(m=>[m.id,m]))}
function validateControls(){const active=activeWorkflows(),missions=missionMap();document.querySelectorAll('[data-run]').forEach(button=>{const mission=missions.get(button.dataset.run),valid=mission&&active.has(workflowPath(mission.workflow));button.disabled=!valid;button.setAttribute('aria-disabled',String(!valid));button.title=valid?`Run ${mission.label}`:mission?`Workflow unavailable: ${mission.workflow}`:'Mission is not registered';if(!valid)button.textContent='UNAVAILABLE'});document.querySelectorAll('[data-openwf]').forEach(button=>{const name=button.dataset.openwf,valid=active.has(workflowPath(name));button.disabled=!valid;button.setAttribute('aria-disabled',String(!valid));button.title=valid?`Open ${name} workflow history`:`Workflow unavailable: ${name}`})}
function reportWiring(){const box=document.querySelector('#globalError');if(!box||state.loading)return;const active=activeWorkflows(),missingMissions=(state.capabilities?.missions||[]).filter(m=>!active.has(workflowPath(m.workflow))),missingData=(state.capabilities?.dataSources||[]).filter(d=>state.data[d.path]==null),critical=[];if(!state.capabilities)critical.push('capabilities unavailable');if(missingMissions.length)critical.push(`${missingMissions.length} operations unavailable`);if(missingData.length)critical.push(`${missingData.length} data sources unavailable`);if(critical.length&&!state.error)box.textContent=`Wiring status: ${critical.join(' · ')}. Dead controls are disabled.`}
function installHistoryLinks(){document.querySelectorAll('[data-openwf]:not([data-integration-wired])').forEach(button=>{button.dataset.integrationWired='1';button.addEventListener('click',event=>{if(button.disabled)return;event.preventDefault();window.open(`https://github.com/${REPO}/actions/workflows/${encodeURIComponent(button.dataset.openwf)}`,'_blank','noopener')},true)})}
function reconcile(){scheduled=false;if(location.hash==='#evidence'||state.workspace==='evidence')mountEvidence();validateControls();installHistoryLinks();reportWiring()}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(reconcile)}
subscribe(schedule);window.addEventListener('hashchange',schedule);window.addEventListener('load',schedule);new MutationObserver(mutations=>{if(mutations.some(m=>m.target.closest?.('#workspaceBody,#sideNav,#mobileNav')||m.target.id==='workspaceBody'))schedule()}).observe(document.body,{childList:true,subtree:true});schedule();
