import{GitHubAPI as api}from'./api.js';
const allowed=/\.(csv|log|txt|json|lua|luac|ya?ml)$/i;
const maxBytes=95*1024*1024;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s||'file').replace(/[^A-Za-z0-9._/-]+/g,'_').replace(/^\/+|\.\.(?=\/|$)/g,'').slice(-180);
const stamp=()=>new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');
async function digest(file){const hash=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function saved(){try{return new Set(JSON.parse(localStorage.getItem('jarvis_iphone_sync_hashes')||'[]'))}catch{return new Set}}
function store(set){localStorage.setItem('jarvis_iphone_sync_hashes',JSON.stringify([...set].slice(-3000)))}
function setStatus(text,kind=''){const e=document.querySelector('#iphoneSyncStatus');if(e){e.textContent=text;e.className=`meta ${kind}`}}
export function iPhoneSyncPanel(state){const s=state.data['public/evidence-data/sync.json']||{};return`<section class="grid"><article class="card span-8"><div class="row"><div><div class="chip">IPHONE 17 · USB-C</div><h3>Jarvis Sync</h3><p class="muted">Connect the MT12 to the iPhone, open its LOGS folder in Files, then Jarvis uploads only new evidence and starts learning.</p></div><button class="btn primary" id="iphoneSyncButton">SYNC MT12 LOGS</button></div><input id="iphoneSyncInput" type="file" multiple webkitdirectory directory accept=".csv,.log,.txt,.json,.lua,.luac,.yml,.yaml" hidden><div class="pipeline"><div class="stage"><i></i><span>1</span><b>Connect MT12 by USB-C</b></div><div class="stage"><i></i><span>2</span><b>Select the LOGS folder</b></div><div class="stage"><i></i><span>3</span><b>Hash and upload new files</b></div><div class="stage"><i></i><span>4</span><b>Attribute, replay and learn</b></div></div><div id="iphoneSyncStatus" class="meta">Ready. Safari will open the Files picker.</div></article><article class="card span-4"><h3>Latest sync</h3><div class="item"><div class="title">${esc(s.state||'NO SYNC YET')}</div><div class="meta">${esc(s.message||'No iPhone evidence import has been recorded.')}</div></div><div class="chips"><span class="chip">NEW ${Number(s.newFileCount||0)}</span><span class="chip">SKIPPED ${Number(s.duplicatesSkipped||0)}</span></div><p class="muted">No desktop runner is required for iPhone sync. The optional native helper remains available for unattended computer sync and firmware flashing.</p></article></section>`}
export function wireIPhoneSync({refresh}){const button=document.querySelector('#iphoneSyncButton'),input=document.querySelector('#iphoneSyncInput');if(!button||!input)return;button.onclick=()=>{if(!api.token())return alert('Connect your classic GitHub token first.');input.value='';input.click()};input.onchange=async()=>{const all=[...input.files],files=all.filter(f=>allowed.test(f.name)&&f.size>0&&f.size<=maxBytes);if(!files.length)return setStatus('No supported log or controller files were selected.','bad');button.disabled=true;const known=saved(),session=`iphone-${stamp()}`,base=`logs/iphone/${session}`;let uploaded=0,skipped=0;const records=[];try{setStatus(`Reading ${files.length} files from the MT12…`);for(let i=0;i<files.length;i++){const f=files[i],hash=await digest(f),relative=clean(f.webkitRelativePath||f.name);if(known.has(hash)){skipped++;records.push({path:relative,name:f.name,size:f.size,sha256:hash,status:'duplicate'});continue}setStatus(`Uploading ${i+1}/${files.length}: ${f.name}`);await api.putBytes(`${base}/${relative}`,new Uint8Array(await f.arrayBuffer()),`Import iPhone MT12 evidence ${session}`);known.add(hash);uploaded++;records.push({path:relative,name:f.name,size:f.size,sha256:hash,status:'uploaded',modifiedAt:new Date(f.lastModified).toISOString()})}store(known);const manifest={schema:1,source:'iPhone 17 Safari Files picker',session,state:'IMPORTED',stage:'learning-dispatched',updatedAt:new Date().toISOString(),newFileCount:uploaded,duplicatesSkipped:skipped,files:records,message:`Imported ${uploaded} new files from the MT12; skipped ${skipped} duplicates.`};await api.putText(`${base}/SYNC-MANIFEST.json`,JSON.stringify(manifest,null,2)+'\n',`Publish iPhone MT12 sync manifest ${session}`);await api.putText('public/evidence-data/sync.json',JSON.stringify(manifest,null,2)+'\n',`Publish latest iPhone MT12 sync state ${session}`);setStatus('Evidence uploaded. Starting attribution, replay and learning…','ok');for(const wf of ['log-index.yml','historical-log-reingest.yml','jarvis-knowledge-graph.yml'])await api.dispatch(wf,{});setStatus(`Complete: ${uploaded} new files uploaded, ${skipped} duplicates skipped. Learning started.`,'ok');await refresh()}catch(error){console.error(error);setStatus(`Sync failed: ${error.message}`,'bad');alert(error.message)}finally{button.disabled=false}}}
