import {THREE,createGarage,build7303} from './mjx7303-render-v6.js';
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const garageCanvas=$('#garage3d'),driveCanvas=$('#drive3d'),garageView=$('#garageView'),driveView=$('#driveView');
let garage=createGarage(garageCanvas),car=MJX7303PHYSICS.make(),drive=null,last=performance.now(),keys={left:0,right:0,gas:0,brake:0},surface='asphalt';
function cameraAngle(name){const a={front:Math.PI,front3q:Math.PI*.76,side:Math.PI*.5,rear3q:Math.PI*.24,rear:0}[name];garage.setAngle(a??0)}
document.querySelectorAll('[data-angle]').forEach(b=>b.onclick=()=>cameraAngle(b.dataset.angle));$('#autoRotate').onclick=()=>garage.setAuto(true);
function buildDrive(){if(drive)return drive;const renderer=new THREE.WebGLRenderer({canvas:driveCanvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene();scene.background=new THREE.Color(0x0b1a2a);scene.fog=new THREE.Fog(0x0d2231,18,95);const camera=new THREE.PerspectiveCamera(58,1,.05,180);camera.position.set(0,2.4,6.5);
 scene.add(new THREE.HemisphereLight(0xcceeff,0x26331f,2));const sun=new THREE.DirectionalLight(0xfff3dc,4);sun.position.set(-5,10,3);sun.castShadow=true;scene.add(sun);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(240,240),new THREE.MeshStandardMaterial({color:0x1b2e1f,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
 const roadMat=new THREE.MeshStandardMaterial({color:0x282d31,roughness:.82,metalness:.03});const road=new THREE.Mesh(new THREE.PlaneGeometry(10,240),roadMat);road.rotation.x=-Math.PI/2;road.position.y=.012;road.receiveShadow=true;scene.add(road);
 for(let z=-115;z<115;z+=8){const stripe=new THREE.Mesh(new THREE.PlaneGeometry(.14,3.4),new THREE.MeshBasicMaterial({color:0xe9eef0}));stripe.rotation.x=-Math.PI/2;stripe.position.set(0,.018,z);scene.add(stripe)}
 for(const sx of[-1,1])for(let z=-110;z<110;z+=9){const post=new THREE.Mesh(new THREE.BoxGeometry(.08,.65,.08),new THREE.MeshStandardMaterial({color:0xcdd6dc,metalness:.55,roughness:.35}));post.position.set(sx*5.35,.32,z);scene.add(post)}
 const model=build7303();model.scale.set(.7,.7,.7);model.position.y=.18;scene.add(model);
 function resize(){const r=driveCanvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}const ro=new ResizeObserver(resize);ro.observe(driveCanvas);resize();drive={renderer,scene,camera,model,roadMat,ro};return drive}
function mode(m){const g=m==='garage';garageView.hidden=!g;driveView.hidden=g;document.body.dataset.mode=m;if(!g)buildDrive();}
$('#garageBtn').onclick=()=>mode('garage');$('#driveBtn').onclick=()=>mode('drive');
function bind(btn,k){const on=e=>{e.preventDefault();keys[k]=1},off=e=>{e.preventDefault();keys[k]=0};btn.onpointerdown=on;btn.onpointerup=off;btn.onpointercancel=off;btn.onpointerleave=off}document.querySelectorAll('[data-k]').forEach(b=>bind(b,b.dataset.k));
addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=1;if(e.key==='ArrowRight'||e.key==='d')keys.right=1;if(e.key==='ArrowUp'||e.key==='w')keys.gas=1;if(e.key==='ArrowDown'||e.key==='s')keys.brake=1});addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=0;if(e.key==='ArrowRight'||e.key==='d')keys.right=0;if(e.key==='ArrowUp'||e.key==='w')keys.gas=0;if(e.key==='ArrowDown'||e.key==='s')keys.brake=0});
$('#surface').onchange=e=>surface=e.target.value;$('#resetCar').onclick=()=>car=MJX7303PHYSICS.make();$('#crashCar').onclick=()=>MJX7303PHYSICS.impact(car,['front','rear','left','right'][Math.floor(Math.random()*4)],95);
function hud(){const t=car.telemetry,c=car.channels,d=car.dyn,h=car.health;$('#mph').textContent=Math.round(t.truthMph);$('#rpm').textContent=Math.round(t.truthRpm);$('#tct').textContent=c.TCT;$('#gyr').textContent=c.GYR;$('#state').textContent=t.state;$('#reason').textContent=t.reason;$('#battery').textContent=d.batteryV.toFixed(1)+'V';$('#structure').textContent=Math.round(h.structure*100)+'%';$('#motor').textContent=Math.round(h.motor*100)+'%';$('#steering').textContent=Math.round(h.steering*100)+'%';$('#diff').textContent=Math.round(h.diff*100)+'%'}
function update3D(dt){if(!drive)return;const speed=car.telemetry.truthMph;drive.model.rotation.z=-car.dyn.roll||0;drive.model.rotation.x=car.dyn.pitch||0;drive.model.position.x=clamp(car.dyn.x*.35,-3.7,3.7);for(const w of drive.model.userData.wheels||[])w.rotation.x+=speed*dt*.16;drive.camera.position.x+=(drive.model.position.x-drive.camera.position.x)*.06;drive.camera.position.y=2.15+Math.min(.75,speed/120);drive.camera.position.z=6.2-Math.min(1.2,speed/80);drive.camera.lookAt(drive.model.position.x,.65,-2.5);drive.roadMat.color.set(surface==='gravel'?0x665e52:surface==='wet'?0x1a2024:surface==='grass'?0x283d29:0x282d31);drive.scene.position.z=(drive.scene.position.z+speed*dt*.04)%8;drive.renderer.render(drive.scene,drive.camera)}
function frame(now){const dt=Math.min(.033,(now-last)/1000||.016);last=now;if(document.body.dataset.mode==='drive'){MJX7303PHYSICS.step(car,dt,{steer:(keys.right?1:0)-(keys.left?1:0),throttle:keys.gas?1:0,brake:keys.brake?1:0,surface},{gyr:+$('#gyrTune').value,tcSlip:+$('#tcTune').value/100});update3D(dt);hud()}requestAnimationFrame(frame)}
mode('garage');hud();requestAnimationFrame(frame);
