import {THREE,createGarage,build7303} from './mjx7303-render-v6.js';
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const garageCanvas=$('#garage3d'),driveCanvas=$('#drive3d'),garageView=$('#garageView'),driveView=$('#driveView');
const SAVE='jarvis-mjx7303-v6-garage';
const defaults={cash:25000,engine:0,turbo:0,tires:0,brakes:0,weight:0,nitrous:0,gyr:260,tc:25,pressure:32,diff:55,suspension:50};
let garageState={...defaults,...JSON.parse(localStorage.getItem(SAVE)||'{}')};
const persist=()=>localStorage.setItem(SAVE,JSON.stringify(garageState));
let garage=createGarage(garageCanvas),car=MJX7303PHYSICS.make(),drive=null,last=performance.now(),keys={left:0,right:0,gas:0,brake:0,nitrous:0},surface='asphalt',nitrousCharge=1;
function money(v){return '$'+Math.round(v).toLocaleString()}
function cameraAngle(name){const a={front:Math.PI,front3q:Math.PI*.76,side:Math.PI*.5,rear3q:Math.PI*.24,rear:0}[name];garage.setAngle(a??0)}
document.querySelectorAll('[data-angle]').forEach(b=>b.onclick=()=>cameraAngle(b.dataset.angle));$('#autoRotate').onclick=()=>garage.setAuto(true);
function installGarage(){
 const wrap=document.createElement('aside');wrap.className='real-garage';wrap.innerHTML=`<div class="rg-head"><div><small>JARVIS PERFORMANCE GARAGE</small><b>MJX 7303 BUILD</b></div><strong id="rgCash"></strong></div><div class="rg-stats"><div><span>POWER</span><b id="rgPower"></b></div><div><span>GRIP</span><b id="rgGrip"></b></div><div><span>BRAKE</span><b id="rgBrake"></b></div><div><span>WEIGHT</span><b id="rgWeight"></b></div></div><div class="rg-parts" id="rgParts"></div><div class="rg-tune"><b>MT12 / CHASSIS SETUP</b><label>GYR <output id="oGyr"></output><input id="gGyr" type="range" min="120" max="460"></label><label>TC SLIP <output id="oTc"></output><input id="gTc" type="range" min="5" max="60"></label><label>TIRE PSI <output id="oPsi"></output><input id="gPsi" type="range" min="20" max="45"></label><label>DIFF LOCK <output id="oDiff"></output><input id="gDiff" type="range" min="0" max="100"></label><label>SUSPENSION <output id="oSusp"></output><input id="gSusp" type="range" min="0" max="100"></label></div>`;
 garageView.appendChild(wrap);
 const parts=[['engine','ENGINE',3200,5],['turbo','TURBO',4200,4],['tires','RALLY TIRES',2500,5],['brakes','BRAKES',2200,5],['weight','WEIGHT REDUCTION',3600,4],['nitrous','NITROUS',3000,4]];
 const list=$('#rgParts');
 function render(){
  $('#rgCash').textContent=money(garageState.cash);$('#rgPower').textContent=Math.round(100+garageState.engine*8+garageState.turbo*11)+'%';$('#rgGrip').textContent=Math.round(100+garageState.tires*7)+'%';$('#rgBrake').textContent=Math.round(100+garageState.brakes*8)+'%';$('#rgWeight').textContent=(4.94-garageState.weight*.11).toFixed(2)+'kg';
  list.innerHTML='';for(const [id,label,cost,max] of parts){const lv=garageState[id],price=Math.round(cost*(1+lv*.65)),row=document.createElement('div');row.className='rg-part';row.innerHTML=`<div><b>${label}</b><small>STAGE ${lv}/${max}</small></div><button ${lv>=max||garageState.cash<price?'disabled':''}>${lv>=max?'MAX':money(price)}</button>`;row.querySelector('button').onclick=()=>{if(lv>=max||garageState.cash<price)return;garageState.cash-=price;garageState[id]++;persist();render()};list.appendChild(row)}
  const vals=[['gGyr','oGyr','gyr',''],['gTc','oTc','tc','%'],['gPsi','oPsi','pressure',' PSI'],['gDiff','oDiff','diff','%'],['gSusp','oSusp','suspension','%']];for(const [i,o,k,s] of vals){$('#'+i).value=garageState[k];$('#'+o).textContent=garageState[k]+s}
 }
 for(const [id,key,out,sfx] of [['gGyr','gyr','oGyr',''],['gTc','tc','oTc','%'],['gPsi','pressure','oPsi',' PSI'],['gDiff','diff','oDiff','%'],['gSusp','suspension','oSusp','%']])$('#'+id).oninput=e=>{garageState[key]=+e.target.value;$('#'+out).textContent=garageState[key]+sfx;persist()};
 render();
 const css=document.createElement('style');css.textContent=`.real-garage{position:absolute;right:12px;top:12px;bottom:12px;width:min(330px,38vw);z-index:6;overflow:auto;padding:12px;border:1px solid #315b75;border-radius:16px;background:#050d15e8;backdrop-filter:blur(18px);box-shadow:0 22px 65px #000b}.rg-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.rg-head small,.rg-part small,.rg-stats span{display:block;color:#82a1b4;font-size:9px}.rg-head b{font-size:16px}.rg-head strong{font-size:16px;color:#82e8ff}.rg-stats{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:10px 0}.rg-stats div,.rg-part{border:1px solid #243f52;border-radius:10px;background:#091721;padding:8px}.rg-stats b{font-size:14px}.rg-parts{display:grid;gap:6px}.rg-part{display:flex;justify-content:space-between;align-items:center}.rg-part button{border:1px solid #3a6c87;background:#123149;color:white;border-radius:8px;padding:7px 9px;font-weight:850}.rg-part button:disabled{opacity:.38}.rg-tune{margin-top:10px;border-top:1px solid #29485c;padding-top:10px}.rg-tune label{display:grid;grid-template-columns:1fr auto;gap:4px;margin-top:8px;color:#9bb5c5;font-size:9px}.rg-tune input{grid-column:1/3;width:100%}.rg-tune output{color:#fff;font-weight:800}@media(max-width:760px){.real-garage{left:8px;right:8px;top:auto;bottom:8px;width:auto;max-height:48%;padding:9px}.garage-ui{bottom:50%;}.rg-parts{grid-template-columns:1fr 1fr}.rg-part{padding:6px}.rg-tune{display:none}.rg-head b{font-size:13px}.rg-stats{grid-template-columns:repeat(4,1fr)}.rg-stats div{padding:5px}}`;document.head.appendChild(css);
}
installGarage();
function buildDrive(){if(drive)return drive;const renderer=new THREE.WebGLRenderer({canvas:driveCanvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene();scene.background=new THREE.Color(0x0b1a2a);scene.fog=new THREE.Fog(0x0d2231,18,95);const camera=new THREE.PerspectiveCamera(58,1,.05,180);camera.position.set(0,2.4,6.5);scene.add(new THREE.HemisphereLight(0xcceeff,0x26331f,2));const sun=new THREE.DirectionalLight(0xfff3dc,4);sun.position.set(-5,10,3);sun.castShadow=true;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(240,240),new THREE.MeshStandardMaterial({color:0x1b2e1f,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const roadMat=new THREE.MeshStandardMaterial({color:0x282d31,roughness:.82,metalness:.03});const road=new THREE.Mesh(new THREE.PlaneGeometry(10,240),roadMat);road.rotation.x=-Math.PI/2;road.position.y=.012;road.receiveShadow=true;scene.add(road);for(let z=-115;z<115;z+=8){const stripe=new THREE.Mesh(new THREE.PlaneGeometry(.14,3.4),new THREE.MeshBasicMaterial({color:0xe9eef0}));stripe.rotation.x=-Math.PI/2;stripe.position.set(0,.018,z);scene.add(stripe)}for(const sx of[-1,1])for(let z=-110;z<110;z+=9){const post=new THREE.Mesh(new THREE.BoxGeometry(.08,.65,.08),new THREE.MeshStandardMaterial({color:0xcdd6dc,metalness:.55,roughness:.35}));post.position.set(sx*5.35,.32,z);scene.add(post)}const model=build7303();model.scale.set(.7,.7,.7);model.position.y=.18;scene.add(model);function resize(){const r=driveCanvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}const ro=new ResizeObserver(resize);ro.observe(driveCanvas);resize();drive={renderer,scene,camera,model,roadMat,ro};return drive}
function mode(m){const g=m==='garage';garageView.hidden=!g;driveView.hidden=g;document.body.dataset.mode=m;if(!g)buildDrive()}
$('#garageBtn').onclick=()=>mode('garage');$('#driveBtn').onclick=()=>mode('drive');
function bind(btn,k){const on=e=>{e.preventDefault();keys[k]=1},off=e=>{e.preventDefault();keys[k]=0};btn.onpointerdown=on;btn.onpointerup=off;btn.onpointercancel=off;btn.onpointerleave=off}document.querySelectorAll('[data-k]').forEach(b=>bind(b,b.dataset.k));
addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=1;if(e.key==='ArrowRight'||e.key==='d')keys.right=1;if(e.key==='ArrowUp'||e.key==='w')keys.gas=1;if(e.key==='ArrowDown'||e.key==='s')keys.brake=1;if(e.key==='Shift')keys.nitrous=1});addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=0;if(e.key==='ArrowRight'||e.key==='d')keys.right=0;if(e.key==='ArrowUp'||e.key==='w')keys.gas=0;if(e.key==='ArrowDown'||e.key==='s')keys.brake=0;if(e.key==='Shift')keys.nitrous=0});
$('#surface').onchange=e=>surface=e.target.value;$('#resetCar').onclick=()=>car=MJX7303PHYSICS.make();$('#crashCar').onclick=()=>MJX7303PHYSICS.impact(car,['front','rear','left','right'][Math.floor(Math.random()*4)],95);
function hud(){const t=car.telemetry,c=car.channels,d=car.dyn,h=car.health;$('#mph').textContent=Math.round(t.truthMph);$('#rpm').textContent=Math.round(t.truthRpm);$('#tct').textContent=c.TCT;$('#gyr').textContent=c.GYR;$('#state').textContent=t.state;$('#reason').textContent=t.reason;$('#battery').textContent=d.batteryV.toFixed(1)+'V';$('#structure').textContent=Math.round(h.structure*100)+'%';$('#motor').textContent=Math.round(h.motor*100)+'%';$('#steering').textContent=Math.round(h.steering*100)+'%';$('#diff').textContent=Math.round(h.diff*100)+'%'}
function applyGarage(dt){const power=garageState.engine*.018+garageState.turbo*.025,weight=1+garageState.weight*.018,grip=garageState.tires*.012,brk=garageState.brakes*.02,diff=garageState.diff/100;if(keys.gas)car.dyn.vy+=power*weight*dt*8;if(keys.brake)car.dyn.vy*=Math.max(0,1-brk*dt*5);car.dyn.vx*=Math.max(.9,1-grip*dt*.5);car.dyn.yawRate*=1-diff*.015*dt;if(keys.nitrous&&garageState.nitrous>0&&nitrousCharge>0){car.dyn.vy+=garageState.nitrous*.04*dt*10;nitrousCharge=clamp(nitrousCharge-dt*.22,0,1)}else nitrousCharge=clamp(nitrousCharge+dt*.035,0,1)}
function update3D(dt){if(!drive)return;const speed=car.telemetry.truthMph;drive.model.rotation.z=-car.dyn.roll||0;drive.model.rotation.x=car.dyn.pitch||0;drive.model.position.x=clamp(car.dyn.x*.35,-3.7,3.7);for(const w of drive.model.userData.wheels||[])w.rotation.x+=speed*dt*.16;drive.camera.position.x+=(drive.model.position.x-drive.camera.position.x)*.06;drive.camera.position.y=2.15+Math.min(.75,speed/120);drive.camera.position.z=6.2-Math.min(1.2,speed/80);drive.camera.lookAt(drive.model.position.x,.65,-2.5);drive.roadMat.color.set(surface==='gravel'?0x665e52:surface==='wet'?0x1a2024:surface==='grass'?0x283d29:0x282d31);drive.scene.position.z=(drive.scene.position.z+speed*dt*.04)%8;drive.renderer.render(drive.scene,drive.camera)}
function frame(now){const dt=Math.min(.033,(now-last)/1000||.016);last=now;if(document.body.dataset.mode==='drive'){MJX7303PHYSICS.step(car,dt,{steer:(keys.right?1:0)-(keys.left?1:0),throttle:keys.gas?1:0,brake:keys.brake?1:0,surface},{gyr:garageState.gyr,tcSlip:garageState.tc/100,pressure:garageState.pressure});applyGarage(dt);update3D(dt);hud()}requestAnimationFrame(frame)}
mode('garage');hud();requestAnimationFrame(frame);
