(()=>{
'use strict';
const $=s=>document.querySelector(s),P=window.MJX7303PHYSICS,R=window.MJX7303RENDER;if(!P||!R)throw Error('MJX 7303 V5 assets missing');
const cv=$('#scene'),ctx=cv.getContext('2d'),K={left:0,right:0,gas:0,brake:0,boost:0};let car=P.make(),mode='garage',last=0,time=0,W=0,H=0,D=1,garageYaw=-.72,garageTarget=-.72,autoRotate=true,surface='asphalt';const tune={gyr:260,tcSlip:.25,pressure:32};
function size(){const r=cv.getBoundingClientRect();D=Math.min(2,devicePixelRatio||1);W=Math.max(320,r.width);H=Math.max(280,r.height);cv.width=W*D;cv.height=H*D;ctx.setTransform(D,0,0,D,0,0)}addEventListener('resize',size);size();
function damage(){return{structure:1-car.health.structure,wheels:car.wheels.map(w=>w.punctured?1:Math.max(w.wear||0,(car.nodes[w.node]?.damage||0)))} }
function setMode(m){mode=m;document.body.dataset.mode=m;$('#garagePanel').hidden=m!=='garage';$('#drivePanel').hidden=m!=='drive';$('#modeGarage').classList.toggle('active',m==='garage');$('#modeDrive').classList.toggle('active',m==='drive');if(m==='drive'){autoRotate=false;garageYaw=Math.PI}}
function renderGarage(dt){if(autoRotate)garageTarget+=dt*.24;garageYaw+=(garageTarget-garageYaw)*Math.min(1,dt*4);R.garage(ctx,W,H,{time});const s=Math.min(W,H)*.17;R.car(ctx,{x:W*.5,y:H*.63,scale:s,yaw:garageYaw,pitch:-.18,damage:damage(),lights:true,wire:$('#wire').checked});ctx.fillStyle='#d7effb';ctx.font='900 11px system-ui';ctx.fillText('MJX HYPER GO 7303 // DIGITAL TWIN',18,H-22);ctx.fillStyle='#6f93a8';ctx.font='11px system-ui';ctx.fillText('Drag the car or choose an angle · damage is rendered live',18,H-7)}
function renderDrive(){const d=car.dyn,t=car.telemetry;R.road(ctx,W,H,{speed:t.truthMph,offset:d.x||d.vx||0,time,surface:t.surface});const yaw=Math.PI+(d.yawRate||0)*.13,roll=clamp((d.latAccel||0)*.012,-.15,.15);ctx.save();ctx.translate(0,Math.abs(roll)*8);R.car(ctx,{x:W*.5+(d.vx||0)*11,y:H*.77,scale:Math.min(W,H)*.105,yaw,pitch:-.03+roll*.12,damage:damage(),lights:true});ctx.restore();if(t.airborne){ctx.fillStyle='#ffd66e';ctx.font='900 24px system-ui';ctx.textAlign='center';ctx.fillText('AIRBORNE',W/2,H*.23);ctx.textAlign='left'}}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function physics(dt){if(mode!=='drive')return;const steer=(K.right?1:0)-(K.left?1:0),throttle=K.gas?1:0,brake=K.brake?1:0;P.step(car,dt,{steer,throttle,brake,boost:K.boost,surface},tune)}
function h(id,v){const e=$(id);if(e)e.textContent=v}function bar(id,v){const e=$(id);if(e)e.style.width=clamp(v,0,1)*100+'%'}
function hud(){const d=car.dyn,t=car.telemetry,c=car.channels;h('#mph',Math.round(t.truthMph||0));h('#rpm',Math.round(t.truthRpm||0).toLocaleString());h('#gear',d.gear);h('#bat',(d.batteryV||0).toFixed(1)+'V');h('#amps',Math.round(d.currentA||0)+'A');h('#state',t.state||'GROUND');h('#reason',t.reason||'READY');h('#tct',c.TCT);h('#gyr',c.GYR);h('#tcState',c.TC?'ACTIVE':'READY');h('#absState',c.ABS?'ACTIVE':'READY');bar('#structure',car.health.structure);bar('#motor',car.health.motor);bar('#steering',car.health.steering);bar('#suspension',car.health.suspension);bar('#soc',d.batterySoc||0);car.wheels.forEach((w,i)=>{h('#w'+i,`${w.name} ${Math.round(Math.abs(w.slipRatio||0)*100)}% · ${Math.round(w.tempC||0)}°`)});h('#stOut',Math.round((c.ST||0)*1024));h('#thOut',Math.round((c.TH||0)*1024))}
function loop(ts){const dt=Math.min(.033,(ts-last)/1000||.016);last=ts;time=ts;physics(dt);ctx.clearRect(0,0,W,H);if(mode==='garage')renderGarage(dt);else renderDrive();hud();requestAnimationFrame(loop)}
function bind(btn,k){const on=e=>{e.preventDefault();K[k]=1},off=e=>{e.preventDefault();K[k]=0};btn.onpointerdown=on;btn.onpointerup=off;btn.onpointercancel=off;btn.onpointerleave=off}
document.querySelectorAll('[data-k]').forEach(b=>bind(b,b.dataset.k));
$('#modeGarage').onclick=()=>setMode('garage');$('#modeDrive').onclick=()=>setMode('drive');$('#repair').onclick=()=>car=P.make();$('#impact').onclick=()=>P.impact(car,['front','left','right','rear'][Math.floor(Math.random()*4)],95);$('#auto').onclick=()=>autoRotate=!autoRotate;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{autoRotate=false;garageTarget=+b.dataset.view});
$('#surface').onchange=e=>surface=e.target.value;$('#gy').oninput=e=>tune.gyr=+e.target.value;$('#tc').oninput=e=>tune.tcSlip=+e.target.value/100;$('#pr').oninput=e=>tune.pressure=+e.target.value;
let drag=false,px=0;cv.addEventListener('pointerdown',e=>{if(mode!=='garage')return;drag=true;px=e.clientX;cv.setPointerCapture(e.pointerId);autoRotate=false});cv.addEventListener('pointermove',e=>{if(!drag||mode!=='garage')return;garageTarget+=(e.clientX-px)*.012;px=e.clientX});cv.addEventListener('pointerup',()=>drag=false);cv.addEventListener('pointercancel',()=>drag=false);
addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='a')K.left=1;if(e.key==='ArrowRight'||e.key==='d')K.right=1;if(e.key==='ArrowUp'||e.key==='w')K.gas=1;if(e.key==='ArrowDown'||e.key==='s')K.brake=1;if(e.code==='Space')K.boost=1});addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='a')K.left=0;if(e.key==='ArrowRight'||e.key==='d')K.right=0;if(e.key==='ArrowUp'||e.key==='w')K.gas=0;if(e.key==='ArrowDown'||e.key==='s')K.brake=0;if(e.code==='Space')K.boost=0});
setMode('garage');requestAnimationFrame(loop);
})();
