/* PRODUCTION 234 — CANONICAL SURVIVOR RUNTIME REWRITE
 * CANONICAL_ROUND_RECORD
 * POST_SPAWN_CANONICALIZATION
 * LEGACY_ENTRY_EVENT_SUPPRESSION
 * STORY_RUNTIME_PROJECTION
 * SINGLE_RENDERER_PRESERVED
 * REPLAY_RUNTIME_234
 *
 * One immutable stage record owns round, opponent, actor identity, target, arena and runtime story.
 * Older spawn wrappers may still construct/configure a boss, but none of their rival choices survive
 * the final spawn boundary and none of their conflicting entry events survive into replay truth.
 * Existing Production 199 rendering and Production 231 presentation bridges are preserved.
 */
const production234={ready:true,version:234,system:'CANONICAL SURVIVOR RUNTIME',frames:0,transactions:0,stageEdges:0,spawnCanonicalizations:0,actorRepairs:0,targetRepairs:0,arenaRepairs:0,storyProjections:0,eventSuppressions:0,extraBossPurges:0,legacyWritesNeutralized:0,lastStage:0,lastBoss:null,lastRecord:null,errors:[]};
const p234Records=p220ArenaManifest.map((scene,i)=>Object.freeze({stage:i+1,round:i,opponent:scene.opponent,displayName:ladderNames140?.[scene.opponent]||scene.opponent,arena:scene.arena,location:scene.location||scene.arena}));
for(let i=0;i<p234Records.length;i++){const r=p234Records[i];if(r.opponent!==ladderRoster140[i])throw Error(`Production 234 ladder/arena mismatch at stage ${i+1}: ${r.opponent} != ${ladderRoster140[i]}`)}
function p234Stage(){return Math.max(1,Math.min(p234Records.length,Math.round(Number(campaign?.stage)||1)))}
function p234Record(stage=p234Stage()){return p234Records[Math.max(1,Math.min(p234Records.length,stage|0))-1]}
function p234Variant(record,boss){if(record.opponent==='LIRA')return boss?.rivalForm>1?(boss.variant||'NEXUS ASCENDANT'):'VANGUARD';const forms=rivalSpecs139?.[record.opponent]?.forms;const idx=Math.max(0,Math.min((forms?.length||1)-1,(Number(boss?.rivalForm)||1)-1));return forms?.[idx]||record.opponent}
function p234CanonicalBoss(preferred=null,reason='LIVE'){
 const record=p234Record(),bosses=enemies.filter(e=>e&&e.type===3),preferredValid=preferred&&bosses.includes(preferred),tournamentBoss=tournament140?.boss&&bosses.includes(tournament140.boss)?tournament140.boss:null,boss=preferredValid?preferred:tournamentBoss||bosses[0]||null;
 if(!boss){production234.lastRecord=record;return{record,boss:null}}
 for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(e&&e.type===3&&e!==boss){if(griffin.target===e)griffin.target=null;enemies.splice(i,1);production234.extraBossPurges++}}
 const before=[boss.identity,boss.name,boss.campaignLevel,boss.visualCharacter203,boss.visualArena203].join('|');
 boss.identity=record.opponent;boss.name=record.displayName;boss.bossName=record.opponent;boss.champion=record.opponent;boss.campaignBoss=true;boss.type=3;boss.campaignLevel=record.stage;boss.round203=record.stage;boss.visualCharacter203=record.opponent;boss.visualArena203=record.arena;boss.rivalForm=Math.max(1,Number(boss.rivalForm)||1);boss.variant=p234Variant(record,boss);
 if(before!==[boss.identity,boss.name,boss.campaignLevel,boss.visualCharacter203,boss.visualArena203].join('|'))production234.actorRepairs++;
 if(campaign.boss!==boss)campaign.boss=boss;
 if(griffin.boss!==boss)griffin.boss=boss;
 if(griffin.target!==boss){griffin.target=boss;production234.targetRepairs++}
 if(typeof zCinema==='object'&&zCinema&&zCinema.lockedTarget!==boss){zCinema.lockedTarget=boss;production234.targetRepairs++}
 tournament140.round=record.round;tournament140.boss=boss;tournament140.bossSeen=true;tournament140.currentOpponent=record.opponent;
 if(typeof production151==='object'&&production151){production151.progression=production151.progression||{};production151.progression.currentRound=record.round}
 if(typeof production100==='object'&&production100)production100.rounds=record.round;
 if(typeof p225Apply==='function'){const priorSrc=typeof p209State==='object'?p209State?.src:null;p225Apply(`P234_${reason}`,false);const slot=typeof p225Slot==='function'?p225Slot(record.stage):null;if(slot&&typeof p209State==='object'&&p209State&&(p209State.img!==slot.img||p209State.src!==slot.src)){p209State.level=record.stage;p209State.img=slot.img;p209State.src=slot.src;p209State.spec=typeof p225Spec==='function'?p225Spec(record.stage):p209State.spec;production234.arenaRepairs++}else if(priorSrc!==p209State?.src)production234.arenaRepairs++}
 if(typeof story110==='object'&&story110){const mirror=`ROUND ${record.stage} // ${record.location} // ${record.opponent}`;if(story110.lastScene!==mirror){story110.lastScene=mirror;production234.storyProjections++}}
 if(typeof stage138==='object'&&stage138&&record.opponent!=='KRAKEN'){if(stage138.krakenMove){stage138.krakenMove=null;production234.legacyWritesNeutralized++}stage138.krakenAt=Infinity}
 if(typeof stage139==='object'&&stage139&&stage139.move?.b&&stage139.move.b!==boss){stage139.move=null;production234.legacyWritesNeutralized++}
 if(production234.lastStage!==record.stage){production234.lastStage=record.stage;production234.stageEdges++}
 production234.lastBoss=boss;production234.lastRecord=record;production234.transactions++;return{record,boss}
}
function p234SuppressSpawnIdentityEvents(afterId){if(!Array.isArray(ultimate?.events))return 0;const types=new Set(['RIVAL_ENTERED','KRAKEN_ENTERED','TOURNAMENT_ROUND_STARTED']);let n=0;for(let i=ultimate.events.length-1;i>=0;i--){const e=ultimate.events[i];if(Number(e?.id)>afterId&&types.has(String(e?.type||'').toUpperCase())){ultimate.events.splice(i,1);n++}}production234.eventSuppressions+=n;return n}
const p234Enemy=enemy;enemy=function(forceBoss=false){const beforeIds=new Set(enemies),seq=Number(ultimate?.seq)||0,out=p234Enemy(forceBoss),spawned=enemies.find(e=>e?.type===3&&!beforeIds.has(e))||null;if(!spawned)return out;const {record,boss}=p234CanonicalBoss(spawned,'POST_SPAWN');p234SuppressSpawnIdentityEvents(seq);if(boss){production234.spawnCanonicalizations++;combatEvent('TOURNAMENT_ROUND_STARTED',{round:record.stage,total:p234Records.length,challenger:'GRIFFIN',opponent:record.opponent,title:record.displayName,arena:record.arena,location:record.location,canonical:true,runtime:234});combatEvent('RIVAL_ENTERED',{fighter:record.opponent,name:record.displayName,form:boss.variant,arena:record.arena,location:record.location,canonical:true,runtime:234})}return out};
const p234CurrentStory=currentStory110;currentStory110=function(){const base=p234CurrentStory();if(!running)return base;const r=p234Record();production234.storyProjections++;return{...base,id:r.stage,act:`ASCENSION ROUND ${r.stage}`,title:`GRIFFIN VS ${r.opponent}`,arena:r.location,objective:`DEFEAT ${r.opponent}`,rival:r.displayName,canonicalArenaAsset:r.arena}};
const p234Omni=omniSystems;omniSystems=function(dt){const out=p234Omni(dt);if(running)p234CanonicalBoss(null,'OMNI');production234.frames++;return out};
const p234Campaign=campaignUpdate;campaignUpdate=function(dt){const before=p234Stage(),out=p234Campaign(dt),after=p234Stage();if(after!==before)p234CanonicalBoss(null,'STAGE_EDGE');return out};
const p234Reset=reset;reset=function(mode=autoMode){const out=p234Reset(mode);production234.lastStage=0;production234.lastBoss=null;production234.lastRecord=null;p234CanonicalBoss(null,'RESET');return out};
const p234Replay=rememberReplayFrame;rememberReplayFrame=function(frame){p234Replay(frame);const {record,boss}=p234CanonicalBoss(null,'REPLAY'),slot=typeof p225Slot==='function'?p225Slot(record.stage):null,currentStory=currentStory110();if(frame.production140){frame.production140.round=record.stage;frame.production140.currentOpponent=boss?.identity||record.opponent}if(frame.production151?.progression)frame.production151.progression.currentRound=record.round;if(frame.production225){frame.production225.stage=record.stage;frame.production225.opponent=record.opponent;frame.production225.arena=record.arena;frame.production225.location=record.location;frame.production225.renderSource=slot?.src||frame.production225.renderSource}frame.production234={system:production234.system,runtime:234,authority:{stage:record.stage,round:record.round,opponent:record.opponent,displayName:record.displayName,arena:record.arena,location:record.location,actorIdentity:boss?.identity||null,actorName:boss?.name||null,targetIdentity:griffin.target?.identity||null,renderSource:slot?.src||null,storyArena:currentStory?.arena||null},counts:{frames:production234.frames,transactions:production234.transactions,stageEdges:production234.stageEdges,spawnCanonicalizations:production234.spawnCanonicalizations,actorRepairs:production234.actorRepairs,targetRepairs:production234.targetRepairs,arenaRepairs:production234.arenaRepairs,storyProjections:production234.storyProjections,eventSuppressions:production234.eventSuppressions,extraBossPurges:production234.extraBossPurges,legacyWritesNeutralized:production234.legacyWritesNeutralized},errors:production234.errors.slice(-8),invariants:{canonicalRoundRecord:true,oneBoss:enemies.filter(e=>e?.type===3).length<=1,tournamentMatchesActor:!boss||tournament140.currentOpponent===boss.identity,actorMatchesStage:!boss||boss.identity===record.opponent,targetMatchesActor:!boss||griffin.target===boss,arenaMatchesStage:!slot||p209State?.img===slot.img&&p209State?.src===slot.src,storyProjectsTournament:!running||currentStory?.arena===record.location,legacyEntryEventsSuppressed:true,production231Present:typeof production231==='object'&&!!production231?.ready,singleRendererPreserved:true,noSecondCanvas:true,noNewRaf:true,replayRuntime234:true}}};
try{const boot=p234CanonicalBoss(null,'BOOT');combatEvent('PRODUCTION_234_READY',{system:production234.system,runtime:234,authority:'CANONICAL_ROUND_RECORD',stages:p234Records.map(r=>({stage:r.stage,opponent:r.opponent,arena:r.arena})),fixes:['POST_SPAWN_CANONICALIZATION','LEGACY_ENTRY_EVENT_SUPPRESSION','STORY_RUNTIME_PROJECTION','SINGLE_TARGET_AND_ARENA_BINDING'],renderer:'EXISTING SINGLE FINAL COMPOSITOR',production231:typeof production231==='object'&&!!production231?.ready})}catch(err){production234.errors.push(String(err?.message||err))}