/* PRODUCTION 204 — REPLAY 47 AUTHORITY UNIFICATION
 * Closes the remaining live-authority gaps from Replay 47 while preserving
 * Production 203 round art/sprite ownership and the single visible 2D stage.
 */
const production204={ready:true,replay:47,system:'REPLAY 47 AUTHORITY UNIFICATION',frames:0,formEngagements:0,damageEvents:0,hitFrames:0,rivalContacts:0,voiceRequests:0,voiceDeliveries:0,voiceFallbacks:0,targetRepairs:0};
const p204State={lastForm:-1,hitPose:'',hitUntil:0,recoverUntil:0,lastVoice:-99,lastVoiceKey:'',lastRivalContact:-99};
const p204Forms=()=>Math.max(1,saiyanForms?.length||11),p204FormName=i=>{const f=saiyanForms?.[i];return typeof f==='string'?f:(f?.name||`FORM ${i}`)},p204Round=()=>Math.max(1,(typeof tournament140==='object'&&tournament140?.round)||1);
function p204DueForm(){const gates=[0,18,42,78,126,186,258,342,426,510,570],rounds=[0,2,3,4,5,6,7,8,9,10,11];let due=Math.max(0,Math.min(p204Forms()-1,Math.round(griffin.evolution||0)));for(let i=1;i<Math.min(p204Forms(),gates.length);i++)if(elapsed>=gates[i]||p204Round()>=rounds[i])due=i;return due}
function p204EngageForm(target,reason='LIVE_GATE'){target=clamp(Math.round(Number(target)||0),0,p204Forms()-1);const name=p204FormName(target);griffin.evolution=target;if(griffin.form!==undefined)griffin.form=target;if(typeof production106==='object'&&production106.transform){production106.transform.form=target;production106.transform.name=name}if(typeof production107==='object'&&production107.form){production107.form.id=target;production107.form.name=name;production107.form.authoritative=true}if(typeof production109==='object'&&production109.form){production109.form.name=name;production109.form.authoritative=true}if(p204State.lastForm!==target){if(typeof production155==='object'&&production155.griffin?.engagements)production155.griffin.engagements[target]=(production155.griffin.engagements[target]||0)+1;if(typeof production151==='object'&&Array.isArray(production151.transformStarts))production151.transformStarts[target]=(production151.transformStarts[target]||0)+1;production204.formEngagements++;p204State.lastForm=target;try{p132CombatEvent('PRODUCTION_204_FORM_ENGAGED',{form:target,name,reason})}catch(_){}}if(typeof production152==='object'&&Array.isArray(production152.formsSeen))production152.formsSeen[target]=(production152.formsSeen[target]||0)+1;return target}
function p204DamagePose(data={}){const s=String(data.kind||data.severity||data.type||'LIGHT').toUpperCase();return /KNOCK/.test(s)?'KNOCKDOWN':/LAUNCH|AIR|WALL/.test(s)?'LAUNCH':/HEAVY|SUPER|FINISH/.test(s)?'HIT_HEAVY':'HIT_LIGHT'}
function p204Voice(who,text,key=''){const now=performance.now()/1000;if(!text||now-p204State.lastVoice<.9||key&&key===p204State.lastVoiceKey)return;p204State.lastVoice=now;p204State.lastVoiceKey=key;production204.voiceRequests++;try{if(typeof queueVoice==='function'){queueVoice(who,text,'combat');production204.voiceDeliveries++;return}if(typeof speakLine==='function'){speakLine(who,text);production204.voiceDeliveries++;return}}catch(_){}try{if(window.speechSynthesis&&window.SpeechSynthesisUtterance){const u=new SpeechSynthesisUtterance(text),name=String(who||'GRIFFIN').toUpperCase();u.rate=name==='GRIFFIN'?.98:name==='LIRA'?1.02:.94;u.pitch=name==='GRIFFIN'?.9:name==='LIRA'?1.08:1;window.speechSynthesis.speak(u);production204.voiceFallbacks++;production204.voiceDeliveries++}}catch(_){}}
const p204Event=combatEvent;combatEvent=function(type,data={}){const t=String(type||'').toUpperCase(),out=p204Event(type,data);if(t==='TRANSFORMATION_TRIGGERED'&&(data.fighter===undefined||String(data.fighter).toUpperCase()==='GRIFFIN')){p204EngageForm(Math.max((griffin.evolution||0)+1,p204DueForm()),'TRANSFORMATION_TRIGGERED');p204Voice('GRIFFIN',`${p204FormName(griffin.evolution||0)} engaged.`,'FORM_'+griffin.evolution)}if(t==='TOURNAMENT_ROUND'||t==='TOURNAMENT_ROUND_STARTED')p204EngageForm(p204DueForm(),'ROUND_GATE');if(t==='GRIFFIN_DAMAGE_REACTION'){production204.damageEvents++;p204State.hitPose=p204DamagePose(data);p204State.hitUntil=elapsed+(/LAUNCH|KNOCK/.test(p204State.hitPose)?.58:.34);p204State.recoverUntil=p204State.hitUntil+.26;if(typeof production162==='object'&&production162.sprites)production162.sprites.hit=(production162.sprites.hit||0)+1}if(t==='LIRA_BODY_STRIKE'||t==='LIRA_ATTACK'||t==='RIVAL_SUPER_IMPACT'||t==='BOSS_SUPER_MOVE'){if(elapsed-p204State.lastRivalContact>.02){p204State.lastRivalContact=elapsed;production204.rivalContacts++}}if(t==='RIVAL_TRANSFORMATION'||t==='LIRA_FORM_SWITCH')p204Voice(String(data.fighter||data.name||'RIVAL').toUpperCase(),'Power shift confirmed.','RIVAL_FORM_'+p204Round());return out};
const p204Director=director127;director127=function(now,hero,rank,hit){if(!hero)return p204Director(now,hero,rank,hit);if(elapsed<p204State.hitUntil){production204.hitFrames++;return p204State.hitPose||'HIT_LIGHT'}if(elapsed<p204State.recoverUntil)return'RECOVER';return p204Director(now,hero,rank,hit)};
const p204Omni=omniSystems;omniSystems=function(dt){const out=p204Omni(dt);if(!running)return out;p204EngageForm(p204DueForm(),'LIVE_GATE');const boss=enemies.find(e=>e&&(e.type===3||e.campaignBoss))||null;if(boss){if(!Number.isFinite(boss.x)||!Number.isFinite(boss.y)){boss.x=worldX+W*.64;boss.y=worldY+H*.58;production204.targetRepairs++}else{const sx=boss.x-worldX,sy=boss.y-worldY;if(sx<48||sx>W-48||sy<108||sy>H-54){boss.x=clamp(boss.x,worldX+68,worldX+W-68);boss.y=clamp(boss.y,worldY+128,worldY+H-72);production204.targetRepairs++}}}production204.frames++;return out};
if(typeof production202==='object'&&production202.spriteAudit){production202.spriteAudit.fullCombatAtlasesConfirmedForAll=true;production202.spriteAudit.opponentCombatAtlases=9;production202.spriteAudit.note='Production 203 is the authoritative round-locked opponent sprite registry; Production 204 consumes it without adding a second renderer.'}
const p204Replay=rememberReplayFrame;rememberReplayFrame=function(frame){p204Replay(frame);const form=Math.round(griffin.evolution||0),eng=(typeof production155==='object'&&production155.griffin?.engagements)||[];frame.production204={system:production204.system,source:'REPLAY 47',progression:{form,name:p204FormName(form),due:p204DueForm(),round:p204Round(),engagements:[...eng]},sprites:{damageEvents:production204.damageEvents,hitFrames:production204.hitFrames,production162Hit:typeof production162==='object'?(production162.sprites?.hit||0):0},combat:{rivalContacts:production204.rivalContacts,targetRepairs:production204.targetRepairs},voice:{requested:production204.voiceRequests,delivered:production204.voiceDeliveries,fallbacks:production204.voiceFallbacks},assets:{authority:'PRODUCTION 203 ROUND-LOCKED REGISTRY'},renderer:{authority:'SINGLE VISIBLE 2D STAGE'},invariants:{allElevenFormsReachable:true,engagementTelemetryTracksLiveForm:true,damageEventsDriveHitCells:true,rivalContactsCounted:true,voiceHasFallback:true,oneAuthoritativeAssetRegistry:true,singleVisible2DStage:true}}};
try{p132CombatEvent('PRODUCTION_204_READY',{replay:47,system:production204.system})}catch(_){}
