/* PRODUCTION 229 — REPLAY 61 LIVE RUNTIME + RELEASE CLOSURE */
const production229={ready:true,replay:61,system:'REPLAY 61 LIVE RUNTIME + RELEASE CLOSURE',frames:0,transformPoseRepairs:0,attackPoseOverrides:0,storyRepairs:0,alignmentRepairs:0,errors:[]};
const p229AttackPose=value=>{const t=String(value||'').toUpperCase();if(/BEAM|BLAST|CANNON|LANCE|RAY|VOLLEY|NOVA|ERASURE/.test(t))return'BEAM';if(/KNEE|KICK|AXE|DIVE|HEEL|ROUNDHOUSE/.test(t))return'KICK';if(/SPIN|SWEEP|CYCLONE|TORNADO/.test(t))return'SPIN';if(/HOOK|ELBOW|UPPER|CROSS|SMASH|FINISHER|BREAKER|DRIVER/.test(t))return'CROSS';if(/DASH|VANISH|STEP|PURSUIT|RUSH/.test(t))return'DASH';return'JAB'};
function p229Story(){try{if(typeof story110!=='object'||!story110)return;const total=Math.max(0,Number(story110.totalChapters)||0),done=Array.isArray(story110.completed)?story110.completed.length:0;if(total>0&&done>=total&&Number(story110.chapter)>=total-1&&story110.scene!=='CLEAR'){story110.scene='CLEAR';production229.storyRepairs++}}catch(err){production229.errors.push('story:'+String(err?.message||err))}}
function p229Alignment(){try{if(typeof production157!=='object'||!production157)return false;const order=Array.isArray(production157.order)?production157.order:[],skills=Array.isArray(production157.skills)?production157.skills:[];const aligned=order.length>0&&order.length===skills.length&&skills.every((row,i)=>row&&row.form===order[i]&&Array.isArray(row.skills)&&row.skills.length>=2);production157.faults=production157.faults||{};production157.invariants=production157.invariants||{};if(aligned&&(!production157.invariants.bodySkillIndicesAligned||Number(production157.faults.alignment)!==0)){production229.alignmentRepairs++;production157.faults.alignment=0;production157.invariants.bodySkillIndicesAligned=true}if(typeof production159==='object'&&production159?.live)production159.live.bodySkillAlignment=aligned;return aligned}catch(err){production229.errors.push('alignment:'+String(err?.message||err));return false}}
function p229TransformPose(){try{if(typeof griffin!=='object'||typeof owen!=='object'||griffin?.transformation?.active)return;const pose=String(owen.pose||'').toUpperCase(),wanted=String(owen.wanted||'').toUpperCase();if(pose!=='TRANSFORM'&&wanted!=='TRANSFORM')return;const mode=String(griffin.mode||'').toUpperCase(),replacement=/BEAM|VOLLEY|BLAST/.test(mode)?'BEAM':/VANISH|PURSUIT|DASH/.test(mode)?'DASH':/EVADE|PARRY|GUARD|COUNTER/.test(mode)?'GUARD':'FLIGHT';owen.pose=replacement;owen.wanted=replacement;if(owen.phase==='ANTICIPATION')owen.phase='LOOP';owen.stateTime=Math.min(Number(owen.stateTime)||0,.18);production229.transformPoseRepairs++}catch(err){production229.errors.push('pose:'+String(err?.message||err))}}
const p229Event=combatEvent;combatEvent=function(type,data={}){const out=p229Event(type,data);try{const t=String(type||'').toUpperCase(),move=String(data.move||data.pose||data.kind||data.name||'');if(!griffin?.transformation?.active&&['MELEE_COMBO_BEAT','MELEE_CONTACT_CONFIRMED','CHRISTIAN_CONTACT','GRIFFIN_FORM_SKILL','SUPER_MOVE_TRIGGERED','SUPER_MOVE_IMPACT','FINISHER_CONFIRMED'].includes(t)){const pose=p229AttackPose(move);if(typeof p199SetPose==='function')p199SetPose(pose,t.includes('SUPER')?.72:.38,move);production229.attackPoseOverrides++}}catch(err){production229.errors.push('event:'+String(err?.message||err))}return out};
const p229Omni=omniSystems;omniSystems=function(dt){const out=p229Omni(dt);p229Story();p229Alignment();p229TransformPose();if(typeof p228StoryTruth==='function')p228StoryTruth();production229.frames++;return out};
const p229Reset=reset;reset=function(mode=autoMode){const out=p229Reset(mode);p229Story();p229Alignment();return out};
const p229Replay=rememberReplayFrame;rememberReplayFrame=function(frame){p229Replay(frame);p229Story();const aligned=p229Alignment();p229TransformPose();const staleTransform=!!(typeof griffin==='object'&&!griffin?.transformation?.active&&typeof owen==='object'&&(String(owen.pose||'').toUpperCase()==='TRANSFORM'||String(owen.wanted||'').toUpperCase()==='TRANSFORM'));const storyDone=typeof story110==='object'&&Array.isArray(story110?.completed)&&story110.completed.length>=Number(story110?.totalChapters||Infinity);frame.production229={system:production229.system,source:'REPLAY 61',release:{runtime:229,requires:[196,199,204,220,221,222,223,224,225,228,229]},repairs:{transformPose:production229.transformPoseRepairs,attackPose:production229.attackPoseOverrides,story:production229.storyRepairs,alignment:production229.alignmentRepairs},truth:{bodySkillAligned:aligned,storyScene:typeof story110==='object'?story110?.scene:null,storyComplete:storyDone,owenPose:typeof owen==='object'?owen?.pose:null,owenWanted:typeof owen==='object'?owen?.wanted:null,griffinTransformActive:!!(typeof griffin==='object'&&griffin?.transformation?.active),production228Active:typeof production228==='object'&&production228?.ready===true},errors:production229.errors.slice(-6),invariants:{production228Present:typeof production228==='object'&&production228?.ready===true,staleTransformPoseBlocked:!staleTransform,canonicalBodySkillAlignment:aligned,completedStoryLockedClear:!storyDone||story110?.scene==='CLEAR',attackEventsDrivePose:true,singleRendererPreserved:true,noNewCanvas:true,noNewRaf:true}}};
try{p229Story();p229Alignment();p229TransformPose();p132CombatEvent('PRODUCTION_229_READY',{system:production229.system,fixes:['DEPLOYED_RUNTIME_228_REQUIRED','STALE_TRANSFORM_POSE_BLOCKED','CANONICAL_BODY_SKILL_ALIGNMENT_RECOMPUTED','COMPLETED_STORY_CLEAR_LOCK','ATTACK_EVENTS_REBIND_VISUAL_POSE'],renderer:'EXISTING SINGLE FINAL COMPOSITOR'})}catch(err){production229.errors.push(String(err?.message||err))}
