/* PRODUCTION 202 — STATE-OF-ART 2D ARENA FIGHT ENGINE
 * Research-derived principles: rush chains, committed recovery, vanish pursuit,
 * real blast clashes, transformation turning points, resource-scaled pressure,
 * and animation state authority. Original characters/assets only.
 */
const production202={ready:true,system:'STATE-OF-ART 2D ARENA FIGHT ENGINE',frames:0,firstFightFrames:0,chains:0,vanishes:0,clashes:0,deflects:0,whiffs:0,recoveries:0,transformBuffs:0,spriteAudit:null};
const p202State={phase:'NEUTRAL',until:0,chain:0,lastHit:-99,lastWhiff:-99,lastVanish:-99,lastClash:-99,lastForm:griffin.evolution||0,ki:100,skill:0};
const p202Roster=['GRIFFIN','LIRA','KRAKEN','KAIROX','MIREYA','ZEPHYRA','SOLENNE','SABLE','ORUN','MORDREN'];
const p202ArenaAssets=['lira-nexus-v1.webp','kraken-abyss-v1.webp','kairox-caldera-v1.webp','mireya-prism-v1.webp','zephyra-tempest-v1.webp','solenne-corona-v1.webp','sable-eclipse-v1.webp','orun-ion-v1.webp','mordren-singularity-v1.webp'];
function p202AuditSprites(){const authored=['griffin-atlas-v3.webp','griffin-ascended-atlas-v3.webp','griffin-speed-form-atlas-v1.webp','griffin-guardian-form-atlas-v1.webp','griffin-destroyer-form-atlas-v1.webp','griffin-instinct-form-atlas-v1.webp','griffin-celestial-overdrive-atlas-v1.webp','griffin-omega-instinct-atlas-v1.webp'];production202.spriteAudit={roster:p202Roster.length,griffinAtlases:authored.length,opponentArenaPortraits:p202ArenaAssets.length,fullCombatAtlasesConfirmedForAll:false,note:'Nine opponent arena portraits are present; repository evidence does not establish a complete multi-cell combat atlas for every opponent.'};return production202.spriteAudit}
p202AuditSprites();
const p202OldEvent=combatEvent;
combatEvent=function(type,data={}){const t=String(type||'').toUpperCase(),out=p202OldEvent(type,data);if(t==='MELEE_CONTACT_CONFIRMED'){p202State.chain=Math.min(4,p202State.chain+1);p202State.phase='HIT_CONFIRM';p202State.until=elapsed+.16;production202.chains++;p202State.ki=Math.min(100,p202State.ki+3)}else if(t==='MELEE_CONTACT_MISSED'){p202State.chain=0;p202State.phase='WHIFF_RECOVERY';p202State.until=elapsed+.32;production202.whiffs++;p202State.lastWhiff=elapsed}else if(t==='GRIFFIN_DAMAGE_REACTION'){p202State.chain=0;p202State.phase='HIT_STUN';p202State.until=elapsed+.24}else if(t==='TRANSFORMATION_TRIGGERED'){p202State.phase='TRANSFORM';p202State.until=elapsed+2.25;p202State.skill=Math.max(0,p202State.skill-1);production202.transformBuffs++;griffin.difficulty=Math.max(1,(griffin.difficulty||1)*1.04)}return out};
function p202Target(){return griffin.target||griffin.boss||enemies.find(e=>e&&(e.type===3||e.campaignBoss))||null}
function p202Screen(e){return e?{x:e.x-worldX,y:e.y-worldY}:null}
function p202Clash(){if(elapsed-p202State.lastClash<.35)return;for(let i=0;i<shots.length;i++){const a=shots[i];if(!a)continue;for(let j=0;j<hostile.length;j++){const b=hostile[j];if(!b)continue;const d=Math.hypot((a.x||0)-(b.x||0),(a.y||0)-(b.y||0));if(d<28){p202State.lastClash=elapsed;production202.clashes++;a.dead=true;b.dead=true;const cx=((a.x||0)+(b.x||0))*.5,cy=((a.y||0)+(b.y||0))*.5;rings.push({x:cx,y:cy,r:8,max:58,life:.28,color:'#dff7ff'});try{p132CombatEvent('PRODUCTION_202_BLAST_CLASH',{x:cx,y:cy})}catch(_){}return}}}}
const p202OldOmni=omniSystems;
omniSystems=function(dt){const out=p202OldOmni(dt);if(!running)return out;production202.frames++;if((typeof tournament140==='object'?(tournament140.round||1):1)===1)production202.firstFightFrames++;p202State.ki=Math.min(100,p202State.ki+dt*5.5);p202State.skill=Math.min(5,p202State.skill+dt*.055);const target=p202Target();if(target){const s=p202Screen(target);if(s&&(s.x<56||s.x>W-56||s.y<116||s.y>H-52)){target.x=clamp(target.x,worldX+76,worldX+W-76);target.y=clamp(target.y,worldY+136,worldY+H-72)}const dx=target.x-player.x,dy=target.y-player.y,d=Math.hypot(dx,dy)||1;if(d>245&&elapsed-p202State.lastVanish>.75&&p202State.ki>18){player.x+=dx/d*Math.min(d-155,190);player.y+=dy/d*Math.min(d-155,190);p202State.ki-=18;p202State.lastVanish=elapsed;production202.vanishes++;p202State.phase='VANISH_PURSUIT';p202State.until=elapsed+.18}if(d<72&&p202State.phase==='NEUTRAL'){const push=(72-d)*.5;player.x-=dx/d*push;player.y-=dy/d*push}}p202Clash();if(elapsed>p202State.until&&(p202State.phase!=='NEUTRAL')){p202State.phase='NEUTRAL';p202State.chain=0;production202.recoveries++}if((griffin.evolution||0)!==p202State.lastForm){p202State.lastForm=griffin.evolution||0;p202State.phase='TRANSFORM';p202State.until=elapsed+2.1}return out};
const p202OldDirector=director127;
director127=function(now,hero,rank,hit){if(!hero)return p202OldDirector(now,hero,rank,hit);if(p202State.phase==='WHIFF_RECOVERY')return'RECOVER';if(p202State.phase==='HIT_STUN')return'HIT_HEAVY';if(p202State.phase==='VANISH_PURSUIT')return'DASH';if(p202State.phase==='TRANSFORM')return'TRANSFORM';if(p202State.phase==='HIT_CONFIRM'){const seq=['JAB','CROSS','KICK','SPIN'];return seq[Math.max(0,Math.min(3,p202State.chain-1))]}return p202OldDirector(now,hero,rank,hit)};
const p202OldReplay=rememberReplayFrame;
rememberReplayFrame=function(frame){p202OldReplay(frame);frame.production202={system:production202.system,engine:{phase:p202State.phase,chain:p202State.chain,ki:+p202State.ki.toFixed(1),skill:+p202State.skill.toFixed(2),rushChains:production202.chains,vanishes:production202.vanishes,blastClashes:production202.clashes,whiffs:production202.whiffs,recoveries:production202.recoveries},sprites:production202.spriteAudit,invariants:{firstFightUsesSameCombatAuthority:true,confirmedHitsDriveChains:true,whiffsHaveRecovery:true,vanishCostsResource:true,blastClashesRequireCollision:true,transformationsChangeState:true,singleVisible2DStage:true}}};
try{p132CombatEvent('PRODUCTION_202_READY',{system:production202.system,spriteAudit:production202.spriteAudit})}catch(_){}
