/* PRODUCTION 196 — CONTACT-BOUND ARENA-FIGHTER CHOREOGRAPHY
   Injected inside core-survivor.js before the closing IIFE by the release build. */
const production196={ready:true,reference:'ARENA FIGHTER RUSH / BLAST IMPACT / TRANSFORMATION STUDY',kiHits:0,kiMisses:0,hostileHits:0,beamHits:0,lightningHits:0,contactExplosions:0,transformBeats:0,voiceBeats:0,clashes:0};
const p196Hurt=hurt;hurt=function(e,damage,color='#73f3ff'){const before=e?.hp;const out=p196Hurt(e,damage,color);if(e&&Number.isFinite(e.x)&&Number.isFinite(e.y)&&before!==e.hp){dbzImpact158(vector113.g,e.x,e.y,color,Math.min(1.8,.65+damage/55));production196.contactExplosions++;combatEvent('ENERGY_CONTACT_CONFIRMED',{damage:Math.round(damage),x:Math.round(e.x),y:Math.round(e.y),boss:e.type===3})}return out};
function nearest196(px,py,range){let best=null,bd=range;for(const e of enemies){if(!isTournamentFighter160(e))continue;const d=Math.hypot(e.x-px,e.y-py);if(d<bd){best=e;bd=d}}return best}
const p196Omni=omniSystems;omniSystems=function(dt){p196Omni(dt);if(!running)return;
 // Ki/projectile authority: visual bursts only occur at the actual collision point.
 for(let i=shots.length-1;i>=0;i--){const s=shots[i];if(s.p196Hit)continue;const e=nearest196(s.x,s.y,(s.r||5)+42);if(!e)continue;s.p196Hit=true;const damage=Math.max(5,(s.damage||player.damage*.36));hurt(e,damage,'#79f6ff');zImpact(e.x,e.y,'#79f6ff',1.35);burst(e.x,e.y,'#9cffff',7);production196.kiHits++;combatEvent('KI_BLAST_CONTACT',{damage:Math.round(damage),x:e.x,y:e.y,boss:e.type===3});shots.splice(i,1)}
 for(let i=hostile.length-1;i>=0;i--){const s=hostile[i],d=Math.hypot(s.x-player.x,s.y-player.y);if(d>(s.r||7)+player.r+9)continue;const damage=Math.max(3,s.damage||7);player.hp=Math.max(0,player.hp-damage);zImpact(player.x,player.y,'#ff4b72',1.25);burst(player.x,player.y,'#ff7894',6);production196.hostileHits++;combatEvent('RIVAL_KI_CONTACT',{damage:Math.round(damage),x:player.x,y:player.y});hostile.splice(i,1)}
 // Lightning is a strike, not ambient decoration: acquire a live fighter and terminate on body contact.
 if(player.lightning>0&&elapsed-(production196.lastLightning||-9)>.7){const e=nearest196(player.x,player.y,390);if(e){production196.lastLightning=elapsed;const damage=8+player.lightning*4+(griffin.evolution||0)*1.4;hurt(e,damage,'#d8fbff');beams.push({x1:player.x,y1:player.y,x2:e.x,y2:e.y,color:'#bff8ff',life:.12,damage,power:1.1});production196.lightningHits++;combatEvent('LIGHTNING_CONTACT',{damage:Math.round(damage),x:e.x,y:e.y})}}
 // Beam endpoints are contact-authoritative; clamp an overshooting beam to the first fighter it actually reaches.
 for(const b of beams){if(b.p196Resolved)continue;const dx=b.x2-b.x1,dy=b.y2-b.y1,ll=dx*dx+dy*dy;if(ll<4)continue;let hit=null,bestT=2;for(const e of enemies){if(!isTournamentFighter160(e))continue;const t=clamp(((e.x-b.x1)*dx+(e.y-b.y1)*dy)/ll,0,1),px=b.x1+dx*t,py=b.y1+dy*t,d=Math.hypot(e.x-px,e.y-py);if(d<48&&t<bestT){hit=e;bestT=t}}if(hit){b.x2=hit.x;b.y2=hit.y;b.p196Resolved=true;hurt(hit,Math.max(10,b.damage||player.damage*.55),'#eaffff');production196.beamHits++;combatEvent('BEAM_CONTACT',{x:hit.x,y:hit.y,boss:hit.type===3})}}
};
// Transformation choreography: anticipation -> charge -> release -> recovery, with lightning tied to the fighter.
const p196Begin=beginGriffinTransformation;beginGriffinTransformation=function(stage){const out=p196Begin(stage);if(!griffin.transformation?.active)return out;production196.transformBeats++;const form=saiyanForms[stage]||saiyanForms[griffin.evolution||0];iylaScene(form?.name||'ASCENSION','POWER RISE · BODY CHANGE · CONTROL',form?.color||'#eaffff',2.6,30);soundTransform101(1+stage*.07);voiceEnqueue101('jaxon',['I can hold this power. Now I make it precise.','The form is stable. Every strike still needs a target.','Power changed. My timing does not.'][stage%3],{context:'transform',priority:9,force:true,ttl:12000});production196.voiceBeats++;return out};
// Confirmed melee receives a short readable hit-stop and a reaction; misses receive motion only.
const p196Event=combatEvent;combatEvent=function(type,data={}){const e=p196Event(type,data),t=String(type||'').toUpperCase();if(t==='MELEE_CONTACT_CONFIRMED'||t==='CHRISTIAN_CONTACT'){owen.hold=Math.max(owen.hold||0,.045);shake=Math.max(shake,4);soundImpact101(.9,clamp(((data.x||player.x)-player.x)/420,-.8,.8))}else if(t.includes('MISSED'))soundWhoosh101(.45);if(t.includes('CLASH'))production196.clashes++;return e};
// More varied original combat callouts without copying franchise dialogue.
voiceLexicon101.common.opening.push('Close the gap, read the guard, then commit','The next exchange starts at contact range','Energy follows the fighter, not empty space','I am waiting for the real opening');
voiceLexicon101.common.tactic.push('chain the launch into pursuit','meet the blast at its collision point','vanish only when the follow-up is reachable','let the impact decide the camera','save the explosion for confirmed contact');
voiceLexicon101.common.transform.push('The aura is locking to the new body','The surge is settling into controlled power','The transformation has a beginning, peak, and recovery');
voiceLexicon101.griffin.power.push('This blast ends at the opponent, not the horizon','I will confirm the line before I release','The charge is useless until the strike connects');
voiceLexicon101.lira.power.push('I will force your guard before I release','My blast follows your escape line','I am aiming through your next step');
const p196Replay=rememberReplayFrame;rememberReplayFrame=function(frame){p196Replay(frame);frame.production196={system:'CONTACT-BOUND RUSH / KI / TRANSFORMATION CHOREOGRAPHY',reference:production196.reference,contacts:{ki:production196.kiHits,rivalKi:production196.hostileHits,beam:production196.beamHits,lightning:production196.lightningHits,explosions:production196.contactExplosions},cinema:{transformBeats:production196.transformBeats,voiceBeats:production196.voiceBeats,clashes:production196.clashes},invariants:{energyTerminatesOnFighters:true,explosionsRequireContact:true,lightningTargetsFighters:true,transformationsHaveStagedBeat:true,originalDialogue:true}}};
p132CombatEvent('PRODUCTION_196_READY',{combat:'CONTACT-BOUND KI + BEAMS + LIGHTNING',choreography:'RUSH / LAUNCH / PURSUIT / IMPACT',transform:'STAGED POWER-UP',audio:'CONTACT-DRIVEN SFX + EXPANDED ORIGINAL VOICES'});