(()=>{
'use strict';
const RACING_HASH='racing',FRAME_SRC='racing-mjx7303-v30.html?v=20260808xr31b';let bodyObserver=null,loadTimer=0;
function setText(el,text){if(el&&el.textContent!==text)el.textContent=text}function setHTML(el,html){if(el&&el.innerHTML!==html)el.innerHTML=html}function active(){return location.hash.replace(/^#/,'')===RACING_HASH}
function syncClass(){document.body.classList.toggle('racing-active',active())}
function isV31Frame(f){const s=f?.getAttribute('src')||'';return s.includes('racing-mjx7303-v30.html')&&s.includes('xr31b')}
function mount(){syncClass();if(!active())return;const body=document.getElementById('workspaceBody');if(!body)return;setText(document.getElementById('workspaceTitle'),'MJX 7303 Simulator V31');setText(document.getElementById('workspaceDescription'),'Jarvis XR V31: reference-driven MJX 7303 / C3 WRC body geometry, custom WebGL2 GGX/ACES renderer, mobile-first framing, and spawn-safe fixed-step dynamics.');setText(document.getElementById('workspaceKicker'),'JARVIS // RACING V31 REFERENCE BODY');setHTML(document.getElementById('heroFacts'),'');const existing=body.querySelector('.racing-frame');if(existing){if(isV31Frame(existing))return;body.innerHTML=''}body.innerHTML='<section class="racing-card"><div class="racing-load" role="status">Loading Jarvis XR V31…</div><iframe class="racing-frame" src="'+FRAME_SRC+'" title="MJX 7303 Jarvis XR Racing V31" allow="fullscreen" loading="eager"></iframe><div class="racing-error" hidden>Jarvis XR V31 could not load. <a href="racing-mjx7303-v30.html?v=20260808directxr31b" target="_blank" rel="noopener">Open V31 directly</a></div></section>';const frame=body.querySelector('.racing-frame'),status=body.querySelector('.racing-load'),err=body.querySelector('.racing-error');clearTimeout(loadTimer);frame.addEventListener('load',()=>{clearTimeout(loadTimer);if(status)status.hidden=true;if(err)err.hidden=true},{once:true});frame.addEventListener('error',()=>{clearTimeout(loadTimer);if(status)status.hidden=true;if(err)err.hidden=false},{once:true});loadTimer=setTimeout(()=>{if(!isV31Frame(body.querySelector('.racing-frame'))){body.innerHTML='';mount()}},12000)}
function observe(){const body=document.getElementById('workspaceBody');if(!body)return;if(bodyObserver)bodyObserver.disconnect();bodyObserver=new MutationObserver(()=>{if(!active())return;const f=body.querySelector('.racing-frame');if(!f||!isV31Frame(f))queueMicrotask(mount)});bodyObserver.observe(body,{childList:true,subtree:true})}
addEventListener('hashchange',()=>{syncClass();queueMicrotask(mount)});addEventListener('pageshow',()=>{syncClass();observe();mount()});if(document.readyState==='loading')addEventListener('DOMContentLoaded',()=>{syncClass();observe();mount()},{once:true});else{syncClass();observe();mount()}
})();