import{GitHubAPI as api}from'./api.js';
const paths=['factory/latest-cycle.json','factory/tracks.json','factory/vehicle-model-calibrated.json','factory/memory/evidence.json','factory/memory/experiments.json','factory/memory/design.json','factory/memory/episodes.json','factory/memory/historical-log-index.json','public/jarvis-data/knowledge-graph.json','public/jarvis-data/summary.json','public/jarvis-data/active-mission.json','research/state.json','research/current.json','research/questions.json','public/chief-data/dashboard.json','public/builds/index.json','public/builds/recommended.json','public/completion-data/dashboard.json','public/device-data/releases.json','public/control-data/state.json','public/mission-data/state.json','public/v3-data/council.json'];
const listeners=new Set();
export const state={capabilities:null,data:{},runs:[],workflows:[],releases:[],connected:false,user:null,rate:null,loading:false,error:null,updatedAt:null,workspace:'command'};
export function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)}function emit(){for(const fn of listeners)fn(state)}
export function setWorkspace(id){state.workspace=id;location.hash=id;emit()}
export async function refresh(){state.loading=true;state.error=null;emit();try{state.capabilities=await fetch('jarvis/capabilities.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`Capabilities ${r.status}`);return r.json()});const [runs,workflows,releases,user,rate,...files]=await Promise.allSettled([api.runs(),api.workflows(),api.releases(),api.user(),api.rate(),...paths.map(p=>api.optionalFile(p))]);state.runs=runs.value?.workflow_runs||[];state.workflows=workflows.value?.workflows||[];state.releases=releases.value||[];state.user=user.value||null;state.rate=rate.value||null;state.connected=!!state.user;paths.forEach((p,i)=>state.data[p]=files[i]?.value??null);state.updatedAt=new Date().toISOString()}catch(error){state.error=error.message;state.connected=false}finally{state.loading=false;emit()}}
export async function runMission(id,inputs={}){const mission=state.capabilities?.missions?.find(x=>x.id===id);if(!mission)throw Error('Unknown mission');if(!state.workflows.some(w=>w.path===`.github/workflows/${mission.workflow}`))throw Error(`Workflow is not active: ${mission.workflow}`);await api.dispatch(mission.workflow,{...mission.inputs,...inputs});await refresh();return mission}
export function metrics(){const d=state.data,graph=d['public/jarvis-data/knowledge-graph.json']||{},summary=d['public/jarvis-data/summary.json']||{},episodes=d['factory/memory/episodes.json']||{},logs=d['factory/memory/historical-log-index.json']||{},cycle=d['factory/latest-cycle.json']||{},tracks=d['factory/tracks.json']||{},builds=d['public/builds/index.json']||{};return{facts:summary.evidenceFacts??summary.facts??0,nodes:graph.nodes?.length??graph.nodeCount??0,edges:graph.edges?.length??graph.edgeCount??0,episodes:episodes.episodes?.length??episodes.count??0,logs:logs.logs?.length??logs.uniqueLogs??0,simulations:cycle.digitalTwin?.monteCarloRuns??0,champion:builds.recommended??tracks.champion?.name??tracks.champion??cycle.tracks?.champion?.name??'—',confidence:cycle.digitalTwin?.calibration?.transferConfidence??summary.confidence??null,uniqueBuilds:builds.uniqueBuilds??builds.builds?.length??0,duplicates:builds.duplicatesRejected??0,latest:builds.latest??null}}
export function health(){const failed=state.runs.filter(r=>r.status==='completed'&&r.conclusion==='failure').slice(0,5),catalog=state.data['public/device-data/releases.json'],index=state.data['public/builds/index.json'];return{github:state.connected?'healthy':'offline',factory:state.runs.some(r=>/(Factory|LUAC AI Builder|Workbench|Guaranteed)/i.test(r.name||'')&&['queued','in_progress','waiting','pending'].includes(r.status))?'running':'ready',firmware:catalog?.edgeTx?.stable&&catalog?.expressLrs?.stable?'ready':'unknown',radio:catalog?'ready':'unknown',knowledge:state.data['public/jarvis-data/summary.json']?'ready':'unknown',evolution:index?.schema>=3?'ready':'unknown',failures:failed}}
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(state.capabilities?.workspaces?.some(x=>x.id===id)){state.workspace=id;emit()}});