(()=>{'use strict';
const H='survivor',GRAPHICS_VERSION=4,CACHE='20260819scratch300engine4',SRC=`survivor.html?v=${CACHE}`;let observer,timer;
if(!document.querySelector('link[data-survivor-style]')){const link=document.createElement('link');link.rel='stylesheet';link.href=`jarvis/survivor-tab.css?v=${CACHE}`;link.dataset.survivorStyle='1';document.head.append(link)}
const active=()=>location.hash.slice(1)===H;
const rgba=(hex,a)=>{const n=parseInt(hex.slice(1),16);return `rgba(${n>>16},${n>>8&255},${n&255},${a})`};
const FORM_COLORS=['#70eaff','#ffe35f','#ffcc45','#ffae38','#71fff0','#8cffb5','#d06fff','#83b5ff','#f4f7ff','#dce9ff','#ffffff'];
const RIVAL_COLORS={LIRA:'#ff58d0',KAIROX:'#ff784d',SOLENNE:'#ffd65e',MIREYA:'#bb7cff',ZEPHYRA:'#72d8ff',ORUN:'#76fff0',MORDREN:'#8f75ff',SABLE:'#ff82ac',KRAKEN:'#54a9ff'};
function stopGraphics(){const f=document.querySelector('.survivor-frame');if(f?.__survivorGraphicsTimer){clearInterval(f.__survivorGraphicsTimer);f.__survivorGraphicsTimer=0}}
function applyGraphics(frame){try{const d=frame.contentDocument,w=frame.contentWindow;if(!d||!w)return;d.documentElement.dataset.survivorGraphics=GRAPHICS_VERSION;
let style=d.getElementById('survivor-cinematic-engine-v4');if(!style){style=d.createElement('style');style.id='survivor-cinematic-engine-v4';style.textContent=`
:root{--heroAura:rgba(112,234,255,.24);--rivalAura:rgba(255,88,208,.2);--stageAccent:#65eaff;--camX:0px;--camY:0px;--camScale:1.018;--impact:0}
html,body{background:#01030a!important}body{isolation:isolate;perspective:900px}canvas{position:relative;z-index:0;filter:saturate(1.42) contrast(1.15) brightness(1.045);transform:translate3d(var(--camX),var(--camY),0) scale(var(--camScale));transform-origin:50% 58%;transition:filter .08s linear;image-rendering:auto}
body:before{content:"";position:fixed;inset:-10%;z-index:1;pointer-events:none;background:radial-gradient(circle at 27% 68%,var(--heroAura),transparent 25%),radial-gradient(circle at 73% 68%,var(--rivalAura),transparent 25%),repeating-linear-gradient(116deg,transparent 0 52px,rgba(140,225,255,.018) 53px 54px),linear-gradient(180deg,rgba(130,215,255,.07),transparent 32%,rgba(0,0,0,.1) 72%,rgba(0,0,0,.42));mix-blend-mode:screen;animation:engineAura 2.3s ease-in-out infinite alternate}
body:after{content:"";position:fixed;inset:0;z-index:2;pointer-events:none;background:radial-gradient(ellipse at center,transparent 38%,rgba(0,3,12,.22) 70%,rgba(0,0,0,.64) 100%),linear-gradient(90deg,rgba(88,225,255,.055),transparent 17%,transparent 83%,rgba(255,84,205,.055));box-shadow:inset 0 0 110px rgba(0,0,0,.5)}
.hud{z-index:4}.top b{font-weight:950!important;text-shadow:0 0 12px currentColor,0 2px 6px #000}.clock,.status,.caption{background:linear-gradient(180deg,rgba(9,25,40,.84),rgba(2,8,18,.78))!important;backdrop-filter:blur(13px) saturate(1.3);-webkit-backdrop-filter:blur(13px) saturate(1.3);box-shadow:0 9px 28px rgba(0,0,0,.32),inset 0 1px rgba(255,255,255,.08)}
.clock{border-color:var(--stageAccent)!important}.bars{gap:12px!important}.bar{height:10px!important;border-color:rgba(255,255,255,.2)!important;background:rgba(0,0,0,.62)!important;box-shadow:inset 0 1px 5px #000,0 1px rgba(255,255,255,.05)}.bar i{box-shadow:0 0 14px currentColor;transition:width .1s linear}.meter{height:5px!important}.caption{border-left-color:var(--stageAccent)!important}.screen{background:radial-gradient(circle at 50% 32%,rgba(37,94,137,.78),rgba(2,5,14,.97) 66%)!important;backdrop-filter:blur(6px)}.panel{padding:clamp(20px,5vw,44px);border:1px solid rgba(113,235,255,.24);border-radius:24px;background:linear-gradient(160deg,rgba(7,22,39,.8),rgba(3,8,18,.66));box-shadow:0 30px 100px #000c,inset 0 1px rgba(255,255,255,.09)}
html[data-engine-impact="1"] canvas{filter:saturate(1.65) contrast(1.3) brightness(1.16)}html[data-engine-impact="1"] body:after{background:radial-gradient(circle at center,rgba(255,255,255,.16),transparent 32%),radial-gradient(ellipse at center,transparent 36%,rgba(0,0,0,.7) 100%)}
html[data-form="6"] body:before,html[data-form="7"] body:before,html[data-form="8"] body:before,html[data-form="9"] body:before,html[data-form="10"] body:before{animation-duration:1.1s;filter:saturate(1.35) brightness(1.15)}
@keyframes engineAura{from{opacity:.7;transform:scale(.985)}to{opacity:1;transform:scale(1.03)}}@media(max-width:600px){canvas{--camScale:1.012}.bar{height:9px!important}.panel{border-radius:18px;padding:20px 14px}.status{font-size:7px!important}}
`;d.head.append(style)}
let prev={hp:null,bhp:null,form:null,stage:null,x:0};const sync=()=>{if(!frame.isConnected||!active()){clearInterval(frame.__survivorGraphicsTimer);frame.__survivorGraphicsTimer=0;return}try{const s=w.JarvisSurvivor?.getState?.();if(!s)return;const hc=FORM_COLORS[s.form]||FORM_COLORS[0],rc=RIVAL_COLORS[s.opponent]||'#ff58d0',heroRatio=s.heroHp/240,bossRatio=Math.max(0,Math.min(1,s.bossHp/(520+s.stage*150)));d.documentElement.dataset.form=String(s.form);d.documentElement.dataset.stage=String(s.stage);d.documentElement.style.setProperty('--heroAura',rgba(hc,s.form>=6?.34:.24));d.documentElement.style.setProperty('--rivalAura',rgba(rc,.22));d.documentElement.style.setProperty('--stageAccent',rc);const tension=Math.max(0,1-Math.min(heroRatio,bossRatio));d.documentElement.style.setProperty('--camScale',String(1.018+tension*.018));d.documentElement.style.setProperty('--camX',`${Math.sin(performance.now()/900+s.stage)*tension*3}px`);d.documentElement.style.setProperty('--camY',`${Math.cos(performance.now()/1100+s.form)*tension*2}px`);const impact=(prev.hp!==null&&s.heroHp<prev.hp)||(prev.bhp!==null&&s.bossHp<prev.bhp)||prev.form!==null&&s.form!==prev.form||prev.stage!==null&&s.stage!==prev.stage;if(impact){d.documentElement.dataset.engineImpact='1';clearTimeout(frame.__engineImpactTimer);frame.__engineImpactTimer=setTimeout(()=>d.documentElement.dataset.engineImpact='0',95)}prev={hp:s.heroHp,bhp:s.bossHp,form:s.form,stage:s.stage,x:0}}catch{}};sync();clearInterval(frame.__survivorGraphicsTimer);frame.__survivorGraphicsTimer=setInterval(sync,90)}catch{}}
function mount(){document.body.classList.toggle('survivor-active',active());if(!active()){stopGraphics();return}const body=document.getElementById('workspaceBody');if(!body)return;document.getElementById('workspaceTitle').textContent='JARVIS // CORE SURVIVOR';document.getElementById('workspaceDescription').textContent='Custom cinematic engine: adaptive camera, depth grading, aura fields, impact flashes and tournament-scale sprite combat.';document.getElementById('workspaceKicker').textContent='ENGINE V4 // FIGHT · ADAPT · ASCEND';document.getElementById('heroFacts').innerHTML='';const frame=body.querySelector('.survivor-frame');if(frame?.src.includes(CACHE)){applyGraphics(frame);return}body.innerHTML=`<section class="survivor-card graphics-v4"><div class="survivor-load">Booting Survivor cinematic engine v4…</div><iframe class="survivor-frame" src="${SRC}" title="Jarvis Core Survivor" allow="autoplay; fullscreen" loading="eager"></iframe></section>`;const load=body.querySelector('.survivor-load'),f=body.querySelector('iframe');f.addEventListener('load',()=>{load.hidden=true;applyGraphics(f)},{once:true});clearTimeout(timer);timer=setTimeout(()=>{if(load)load.textContent='Loading high-detail arenas and fighter atlases…'},8000)}
function watch(){observer?.disconnect();const body=document.getElementById('workspaceBody');if(body){observer=new MutationObserver(()=>active()&&!body.querySelector('.survivor-frame')&&queueMicrotask(mount));observer.observe(body,{childList:true})}}addEventListener('hashchange',()=>queueMicrotask(mount));addEventListener('pageshow',()=>{watch();mount()});if(document.readyState==='loading')addEventListener('DOMContentLoaded',()=>{watch();mount()},{once:true});else{watch();mount()}
})();
