#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const root=path.resolve(process.argv[2]);const missionPath=path.join(root,'MISSION.json');const mission=JSON.parse(fs.readFileSync(missionPath,'utf8'));const files=[];function walk(d){for(const n of fs.readdirSync(d)){const p=path.join(d,n),s=fs.statSync(p);if(s.isDirectory())walk(p);else files.push(p)}}walk(root);const rel=p=>path.relative(root,p);const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const manifest=files.filter(p=>!p.endsWith('AUDIT-MANIFEST.json')).map(p=>({path:rel(p),bytes:fs.statSync(p).size,sha256:sha(p)}));
const replayPassed=mission.releaseLadder.find(x=>x.stage==='LOG_REPLAY_PASSED')?.passed===true;const benchPassed=mission.releaseLadder.find(x=>x.stage==='MT12_BENCH_PASSED')?.passed===true;const roadPassed=mission.releaseLadder.find(x=>x.stage==='ROAD_TESTED')?.passed===true;const adversarial=mission.releaseLadder.find(x=>x.stage==='ADVERSARIAL_REVIEW_PASSED')?.passed===true;
const notifications=[];if(mission.selectedCandidate)notifications.push({level:'info',type:'candidate-selected',message:`${mission.selectedCandidate} leads the tournament`,mission:mission.id});if(!replayPassed)notifications.push({level:'warning',type:'replay-required',message:'Recorded replay authority is incomplete',mission:mission.id});if(replayPassed&&!benchPassed)notifications.push({level:'action',type:'bench-required',message:'Replay passed; upload MT12 bench certificate next',mission:mission.id});if(benchPassed&&!roadPassed)notifications.push({level:'action',type:'road-required',message:'Bench passed; road evidence is required',mission:mission.id});if(mission.memoryCompatibility?.status!=='STATIC_CHECKED')notifications.push({level:'warning',type:'memory-evidence',message:'Saved-memory compatibility needs evidence',mission:mission.id});
const rollback={recommended:false,reason:'No trusted road regression comparison available',confidence:0};if(mission.roadComparison?.throttleInterruptionsIncreasePct>10){rollback.recommended=true;rollback.reason=`Throttle interruptions increased ${mission.roadComparison.throttleInterruptionsIncreasePct}%`;rollback.confidence=mission.roadComparison.confidence||0.8}mission.rollback=rollback;mission.notifications=notifications;mission.updatedAt=new Date().toISOString();
const release={mission:mission.id,stage:mission.stage,selectedCandidate:mission.selectedCandidate||null,claims:[],knownRisks:notifications.filter(x=>x.level==='warning').map(x=>x.message),untestedAreas:[!replayPassed?'recorded replay':null,!benchPassed?'MT12 bench':null,!roadPassed?'road test':null,!adversarial?'adversarial review':null].filter(Boolean),hashManifest:'AUDIT-MANIFEST.json',automaticPromotion:false};
fs.writeFileSync(path.join(root,'NOTIFICATIONS.json'),JSON.stringify(notifications,null,2)+'\n');fs.writeFileSync(path.join(root,'ROLLBACK.json'),JSON.stringify(rollback,null,2)+'\n');fs.writeFileSync(path.join(root,'RELEASE.json'),JSON.stringify(release,null,2)+'\n');fs.writeFileSync(path.join(root,'MISSION.json'),JSON.stringify(mission,null,2)+'\n');
const audit={mission:mission.id,generatedAt:new Date().toISOString(),manifest,claimPolicy:'Every performance claim must identify metric, baseline, candidate, logs, event windows and confidence.',completeArchiveIncludes:['mission','sources','logs','labels','baseline','candidates','diffs','replay-results','research','AI-decisions','bench-evidence','road-evidence','release-hashes'],offlineQueueContract:{items:['logs','labels','notes','candidate-requests','backup-manifests'],uploadWhenOnline:true}};fs.writeFileSync(path.join(root,'AUDIT-MANIFEST.json'),JSON.stringify(audit,null,2)+'\n');
fs.writeFileSync(path.join(root,'RELEASE-NOTES.md'),`# A17Y Mission ${mission.id}\n\n## Stage\n${mission.stage}\n\n## Selected candidate\n${mission.selectedCandidate||'None'}\n\n## Evidence\n- Logs: ${mission.evidence.logs.length}\n- Human labels: ${mission.evidence.labels.length}\n- Event windows: ${mission.events.length}\n- Replay passed: ${replayPassed}\n- Adversarial review passed: ${adversarial}\n- MT12 bench passed: ${benchPassed}\n- Road tested: ${roadPassed}\n\n## Known risks\n${release.knownRisks.map(x=>`- ${x}`).join('\n')||'- None recorded'}\n\n## Untested areas\n${release.untestedAreas.map(x=>`- ${x}`).join('\n')||'- None'}\n\nNo unsupported performance statement is included.\n`);
console.log(JSON.stringify({mission:mission.id,stage:mission.stage,notifications:notifications.length,rollback},null,2));
