#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(process.argv[2]||'dist-mission/current');const mission=JSON.parse(fs.readFileSync(path.join(root,'MISSION.json'),'utf8'));const profiles=['conservative','performance','learning','memory-efficient','alternative-algorithm'];
const read=p=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return null}};
const rows=profiles.map(profile=>{const base=path.join(root,'tournament',profile);const w=read(path.join(base,'workbench','REPORT.json'));const d=read(path.join(base,'director','REPORT.json'))||read(path.join(base,'director','DECISION.json'));const accepted=w?.status==='accepted';const stage=w?.stage||'REJECTED';const replay=Number(w?.replayExecution?.executedLogs||0);const changed=Number(w?.comparison?.changedRows||0);const delta=Number(w?.comparison?.maxDelta||0);const bytes=Number(w?.bytecode?.normalizedBytes||Infinity);const missionPassed=w?.missionMetrics?.passed!==false;const score=(accepted?100:0)+(replay*10)+(missionPassed?30:-50)-Math.min(30,changed/20)-Math.min(30,delta/20)-Math.max(0,(bytes-80000)/500);return{profile,accepted,stage,replay,changedRows:changed,maxDelta:delta,bytes:Number.isFinite(bytes)?bytes:null,missionPassed,score:Number(score.toFixed(3)),director:d,report:w}}).sort((a,b)=>b.score-a.score);
const winner=rows.find(x=>x.accepted&&x.missionPassed)||null;
const objections=[];for(const c of rows){if(!c.accepted)objections.push(`${c.profile}: deterministic workbench rejected`);if(c.maxDelta>700)objections.push(`${c.profile}: output delta ${c.maxDelta} exceeds safety boundary`);if(c.changedRows>500)objections.push(`${c.profile}: changed ${c.changedRows} rows`);if(c.bytes&&c.bytes>87000)objections.push(`${c.profile}: normalized bytecode exceeds 87 KB`);if(c.replay===0)objections.push(`${c.profile}: no recorded replay authority`)}
const adversarial={status:winner&&objections.filter(x=>x.startsWith(winner.profile+':')).length===0?'PASSED':'REQUEST_EVIDENCE',winner:winner?.profile||null,objections,checks:{overfit:rows.every(x=>x.replay>0)?'reviewed':'unproven',hiddenRegression:rows.some(x=>x.maxDelta>700)?'risk':'bounded',unreachableProtection:'delegated to protected runtime checks',falseConfidence:rows.some(x=>x.stage==='REPLAY VERIFIED'&&x.replay===0)?'found':'not-found',sensorStates:'counterfactual/fuzz stage required',memoryRisk:rows.some(x=>(x.bytes||0)>85000)?'high-margin-risk':'bounded',dashboardBreakage:'protected contract required',persistenceBreakage:'memory laboratory required'}};
mission.candidates=rows.map(x=>({id:`${mission.id}-${x.profile}`,profile:x.profile,status:x.accepted?'EVALUATED':'REJECTED',metrics:{score:x.score,replay:x.replay,changedRows:x.changedRows,maxDelta:x.maxDelta,bytes:x.bytes,missionPassed:x.missionPassed},artifacts:[`tournament/${x.profile}`]}));mission.adversarialReview=adversarial;if(winner){mission.selectedCandidate=winner.profile;mission.stage=winner.replay>0&&adversarial.status==='PASSED'?'ADVERSARIAL_REVIEW_PASSED':'SIMULATION_PASSED'}
for(const s of mission.releaseLadder){if(['GENERATED','STATIC_CHECKED','COMPILED','NORMALIZED','SIMULATION_PASSED'].includes(s.stage)&&winner)s.passed=true;if(s.stage==='LOG_REPLAY_PASSED')s.passed=!!winner&&winner.replay>0;if(s.stage==='ADVERSARIAL_REVIEW_PASSED')s.passed=adversarial.status==='PASSED'}
fs.writeFileSync(path.join(root,'TOURNAMENT-RESULT.json'),JSON.stringify({rows,winner,adversarial},null,2)+'\n');fs.writeFileSync(path.join(root,'ADVERSARIAL-REVIEW.json'),JSON.stringify(adversarial,null,2)+'\n');fs.writeFileSync(path.join(root,'MISSION.json'),JSON.stringify(mission,null,2)+'\n');console.log(JSON.stringify({winner:winner?.profile||null,adversarial:adversarial.status},null,2));
