#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const root=process.cwd(),statePath='discovery/state.json',out='public/v3-data/discovery.json';
const read=p=>fs.existsSync(p)?fs.readFileSync(p,'utf8'):'';const json=(p,f)=>{try{return JSON.parse(read(p)||'')}catch{return f}};const walk=(d,a=[])=>{if(!fs.existsSync(d))return a;for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);e.isDirectory()?walk(p,a):a.push(p)}return a};const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const now=new Date().toISOString();
let state=json(statePath,{schema:1,discoveries:[],revisitCandidates:[],dismissed:[],history:[]});state.status='RUNNING';state.startedAt=now;state.updatedAt=now;state.currentPhase='OBSERVE';state.message='Mining logs, research, memory, health, roadmap and test evidence.';fs.writeFileSync(statePath,JSON.stringify(state,null,2)+'\n');
const logs=walk('tests/replays').filter(x=>x.toLowerCase().endsWith('.csv'));const bench=walk('evidence/bench').filter(x=>x.endsWith('.json'));const road=walk('evidence/road').filter(x=>x.endsWith('.json'));const memory=json('director/memory.json',{generations:[],lessons:[],rejectedHypotheses:[],successfulPatterns:[]});const research=json('research/current.json',{acceptedFindings:[],conflicts:[],newQuestions:[],sources:[]});const health=json('public/v3-data/health.json',{status:'UNKNOWN',checks:[]});const roadmap=json('director/v3/features.json',{features:[]});
function csvStats(p){const s=read(p),lines=s.split(/\r?\n/).filter(Boolean),h=(lines[0]||'').toLowerCase();const count=k=>lines.slice(1).reduce((n,l)=>n+(l.toLowerCase().includes(k)?1:0),0);return{file:p,rows:Math.max(0,lines.length-1),bytes:fs.statSync(p).size,sha256:sha(p),signals:{tc:count('tc'),abs:count('abs'),jump:count('jump'),gps:count('gps'),rpm:count('rpm'),drop:count('drop')}}}
const catalog=logs.map(csvStats);const opportunities=[];const add=o=>opportunities.push({id:`d-${crypto.randomUUID()}`,createdAt:now,status:'PROPOSED',...o});
const totalRows=catalog.reduce((n,x)=>n+x.rows,0),sessions=catalog.length;
if(!sessions)add({title:'Collect representative replay evidence',category:'evidence',problem:'No replay logs are available for evidence-backed engineering.',evidence:['tests/replays contains no CSV sessions'],expectedImpact:95,confidence:.99,effort:20,risk:5,nextExperiment:'Upload at least one radio telemetry CSV and one blackbox CSV from the same drive.',affectedSystems:['Replay Lab','Diagnosis','Mission scoring']});
else{const agg=k=>catalog.reduce((n,x)=>n+x.signals[k],0);for(const [k,title,sys] of [['drop','Investigate telemetry and channel dropouts','sensor observability'],['jump','Audit jump and landing classification','jump and landing classification'],['gps','Measure GPS loss and recovery behavior','truth MPH and GPS fusion'],['rpm','Measure RPM lag and dropout behavior','truth RPM'],['tc','Review TC timing and release quality','traction control'],['abs','Review ABS timing and release quality','ABS']]){const n=agg(k);if(n)add({title,category:'replay anomaly',problem:`${n} ${k.toUpperCase()}-related row indicators appear across ${sessions} replay session(s).`,evidence:catalog.filter(x=>x.signals[k]).slice(0,8).map(x=>`${x.file}: ${x.signals[k]} indicators / ${x.rows} rows`),expectedImpact:Math.min(92,55+Math.log10(n+1)*18),confidence:Math.min(.94,.45+Math.min(1,sessions/5)*.25+Math.min(1,n/50)*.24),effort:45,risk:25,nextExperiment:`Run schema-aware event extraction for ${k}, label true and false events, and compare A17Y against a no-change baseline.`,affectedSystems:[sys,'Replay Lab','Crew Chief']})}}
for(const f of research.acceptedFindings||[])add({title:`Evaluate research finding: ${f.title||f.finding||'unnamed finding'}`,category:'research transfer',problem:f.summary||f.finding||'A cited external finding may apply to A17Y.',evidence:(f.sourceIds||[]).map(id=>`research source ${id}`),expectedImpact:Math.round(40+35*Number(f.confidence||.5)),confidence:Number(f.confidence||.5),effort:55,risk:35,nextExperiment:'Translate the finding into a falsifiable hypothesis and test it against held-out replay sessions before editing Lua.',affectedSystems:f.affectedSystems||['Research Lab','Director']});
for(const r of memory.rejectedHypotheses||[]){const age=Date.now()-Date.parse(r.at||0),newEvidence=sessions>0||research.acceptedFindings?.length;if(newEvidence&&age>7*864e5)add({title:`Revisit retired hypothesis: ${r.title||'unnamed'}`,category:'hypothesis revisit',problem:'A previously rejected idea may deserve reconsideration because the evidence base has changed.',evidence:[`Previously rejected: ${r.reason||'no reason recorded'}`,`${sessions} replay sessions now available`,`${research.acceptedFindings?.length||0} accepted research findings available`],expectedImpact:50,confidence:.55,effort:35,risk:40,nextExperiment:'Re-run the original disconfirming test using only newly added evidence; do not reuse the old candidate.',affectedSystems:['Engineering Memory','Causal Scientist']})}
if(health.status&&health.status!=='HEALTHY')add({title:'Repair Engineering OS health degradation',category:'platform reliability',problem:`System health is ${health.status}.`,evidence:(health.checks||[]).filter(x=>x.status&&x.status!=='PASS').map(x=>`${x.name}: ${x.status}`).slice(0,10),expectedImpact:100,confidence:.98,effort:25,risk:10,nextExperiment:'Resolve failing workflow or repository integrity checks before generating controller candidates.',affectedSystems:['Workflow health','Repository integrity']});
const planned=(roadmap.features||[]).filter(x=>x.status==='planned');if(planned.length)add({title:'Select the next roadmap capability by measured value',category:'roadmap',problem:`${planned.length} roadmap features remain planned without evidence-based sequencing.`,evidence:planned.slice(0,12).map(x=>`#${x.id} ${x.name}`),expectedImpact:45,confidence:.75,effort:15,risk:5,nextExperiment:'Score planned features by blocked decisions, available evidence, implementation cost and safety benefit.',affectedSystems:['Roadmap','Engineering Council']});
for(const o of opportunities)o.priority=Math.round((o.expectedImpact*o.confidence*100)/(Math.max(10,o.effort)*(1+o.risk/100)));opportunities.sort((a,b)=>b.priority-a.priority||b.confidence-a.confidence);
const selected=opportunities.slice(0,12);state.status='COMPLETE';state.currentPhase='RANK';state.updatedAt=now;state.lastCompletedAt=now;state.currentQuestion=selected[0]?.title||null;state.message=selected.length?`${selected.length} ranked engineering discoveries are ready for review.`:'No actionable discovery exceeded the evidence threshold.';state.discoveries=selected;state.revisitCandidates=selected.filter(x=>x.category==='hypothesis revisit');state.history=[{at:now,sessions,totalRows,researchFindings:research.acceptedFindings?.length||0,discoveries:selected.map(x=>({id:x.id,title:x.title,priority:x.priority}))},...(state.history||[])].slice(0,100);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(statePath,JSON.stringify(state,null,2)+'\n');fs.writeFileSync(out,JSON.stringify({generatedAt:now,status:state.status,message:state.message,topDiscovery:selected[0]||null,discoveries:selected,evidence:{sessions,totalRows,bench:bench.length,road:road.length,researchFindings:research.acceptedFindings?.length||0,memoryGenerations:memory.generations?.length||0,health:health.status}},null,2)+'\n');console.log(JSON.stringify({discoveries:selected.length,top:selected[0]?.title||null},null,2));