#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const root=process.cwd(),spec=JSON.parse(fs.readFileSync(path.join(root,'spec/a16a-upgrade.json'),'utf8')),dist=path.join(root,'dist-a16a');
fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});
const token=process.env.GITHUB_TOKEN;if(!token)throw Error('GITHUB_TOKEN missing');const modelId=process.env.A16_MODEL||spec.model;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),run=(c,a,o={})=>execFileSync(c,a,{encoding:'utf8',maxBuffer:128*1024*1024,...o});
const extract=t=>{const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a<0||b<a)throw Error('model returned no JSON');return JSON.parse(t.slice(a,b+1))};
async function model(messages,temp=.25,max_tokens=18000){const r=await fetch('https://models.github.ai/inference/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',Accept:'application/vnd.github+json'},body:JSON.stringify({model:modelId,temperature:temp,max_tokens,messages})});if(!r.ok)throw Error(`GitHub Models ${r.status}: ${await r.text()}`);const j=await r.json();return j.choices?.[0]?.message?.content||''}
function compile(src,name){const raw=path.join(dist,`${name}_raw.luac`),norm=path.join(dist,`${name}.luac`);run('luac5.3',['-p',src]);run('luac5.3',['-s','-o',raw,src]);run('node',[path.join(root,'toolchain/normalize_luac53_mt12.js'),raw,norm]);const b=fs.readFileSync(norm);return{raw,norm,bytes:b.length,sha256:sha(b)}}
function apply(src,patches){if(!Array.isArray(patches)||!patches.length||patches.length>18)throw Error('invalid patch count');let out=src;for(const [i,p] of patches.entries()){if(typeof p.find!=='string'||typeof p.replace!=='string'||!p.find)throw Error(`bad patch ${i+1}`);const at=out.indexOf(p.find);if(at<0)throw Error(`patch ${i+1} find not found`);if(out.indexOf(p.find,at+1)>=0)throw Error(`patch ${i+1} find not unique`);out=out.slice(0,at)+p.replace+out.slice(at+p.find.length)}return out}
function audit(s){const e=[];if(!s.startsWith('--A16A'))e.push('missing A16A header');if(s.includes('local evABS=0local sessOn=false'))e.push('syntax defect');if(s.includes(':read('))e.push('fileHandle:read forbidden');if(!s.includes('io.read('))e.push('io.read missing');if(!/setgv\(7,1024\)/.test(s))e.push('GV7 guard missing');for(const k of ['A16OBS','A16ARB','A16JMP','A16ELIG','A16CHAL','A16MEM','A16PRESS','A16WATCH','A16EP'])if(!s.includes(k))e.push(`marker ${k} missing`);if(!/return\s*\{\s*init\s*=/.test(s)||!s.includes('background=')||!s.includes('run='))e.push('EdgeTX contract missing');if(e.length)throw Error(e.join('; '))}
async function phase(src,p,round){const prompt=`Rebuild the supplied complete RadioMaster MT12 EdgeTX Lua 5.3 controller into release A16A. Phase ${p.name}, repair round ${round}. Implement every numbered requirement in this phase as real compact behavior integrated into existing sensing, control, learning, persistence, dashboard and diagnostics. Preserve every listed feature. Do not use comments or markers as substitutes for behavior. Do not remove or weaken functions. Use compact arrays and consolidate duplication to recover bytecode. Return strict JSON {"summary":"...","implemented":["number and executable proof"],"patches":[{"find":"exact unique source text","replace":"complete replacement","reason":"..."}]}. Use at most 18 exact patches; complete function replacement is allowed. Permanent executable identifiers or constants must include A16OBS A16ARB A16JMP A16ELIG A16CHAL A16MEM A16PRESS A16WATCH A16EP. Requirements: ${JSON.stringify(p.requirements)}. Preserve: ${JSON.stringify(spec.preserve)}. Target normalized bytecode <=${spec.target_limit}; hard limit ${spec.hard_limit}. SOURCE:\n${src}`;return extract(await model([{role:'system',content:'You are a senior embedded control engineer. Return only exact JSON patches. Every claim must map to executable Lua behavior.'},{role:'user',content:prompt}],round===1?.32:.18,20000))}
async function compress(src,bytes){const prompt=`This complete A16A EdgeTX Lua source compiles but normalized bytecode is ${bytes} bytes. Reduce it below ${spec.target_limit} without removing, simplifying, weakening or disabling any behavior. Consolidate equivalent expressions, deduplicate state transitions, shorten local structures, remove only unreachable duplication, and preserve all A16 markers and interfaces. Return strict JSON {"patches":[{"find":"exact unique text","replace":"equivalent smaller text","reason":"..."}]}. At most 18 patches. SOURCE:\n${src}`;return extract(await model([{role:'system',content:'You optimize Lua 5.3 bytecode while preserving exact behavior.'},{role:'user',content:prompt}],.12,18000))}
async function auditAI(parent,src,build){const prompt=`Adversarially audit A16A against A15YA. Confirm all 29 numbered upgrades are executable, integrated and not marker-only; identify regressions in throttle pass-through, TC, ABS, gyro, jump, persistence, I/O, dashboard, voice/personality, learning and car-off behavior. Build=${JSON.stringify(build)}. Return strict JSON {"verdict":"accept|reject","coverage":[{"n":1,"status":"pass|fail","proof":"..."}],"regressions":["..."],"safety":0-100,"completeness":0-100}. PARENT:\n${parent}\nA16A:\n${src}`;return extract(await model([{role:'system',content:'You are an adversarial MT12 safety and completeness auditor. Reject unsupported claims.'},{role:'user',content:prompt}],.05,14000))}
async function main(){const parentPath=path.join(root,spec.source),parent=fs.readFileSync(parentPath,'utf8');let src=parent.replace(/^--[^\n]*/,'--A16A new-series unified observable authority intelligence').replace('local evABS=0local sessOn=false','local evABS=0;local sessOn=false');const log={release:spec.release,parent:spec.source,parentSha256:sha(Buffer.from(parent)),model:modelId,phases:[],status:'building'};
for(const p of spec.phases){let ok=false,last='';for(let r=1;r<=3&&!ok;r++){try{const plan=await phase(src,p,r),cand=apply(src,plan.patches),tmp=path.join(dist,`phase-${p.name}.lua`);fs.writeFileSync(tmp,cand);compile(tmp,`phase-${p.name}`);src=cand;log.phases.push({name:p.name,round:r,summary:plan.summary,implemented:plan.implemented});ok=true}catch(e){last=String(e.message||e)}}if(!ok)throw Error(`phase ${p.name} failed: ${last}`)}
audit(src);const out=path.join(dist,'a16a.lua');fs.writeFileSync(out,src);let b=compile(out,'a16a');for(let r=1;b.bytes>spec.target_limit&&r<=4;r++){const plan=await compress(src,b.bytes),cand=apply(src,plan.patches);fs.writeFileSync(out,cand);b=compile(out,'a16a');src=cand;log.phases.push({name:'bytecode-compression',round:r,bytes:b.bytes})}if(b.bytes>spec.target_limit)throw Error(`A16A ${b.bytes} exceeds target ${spec.target_limit}`);audit(src);
run('lua5.3',[path.join(root,'scripts/mt12-harness.lua'),out,path.join(dist,'a16a-trace.csv')]);if(fs.existsSync(path.join(root,'scripts/evaluate-fitness.mjs')))run('node',[path.join(root,'scripts/evaluate-fitness.mjs'),out,path.join(dist,'a16a-fitness.json')]);
const review=await auditAI(parent,src,b);log.review=review;if(review.verdict!=='accept'||review.safety<90||review.completeness<92||!Array.isArray(review.coverage)||review.coverage.length<29||review.coverage.some(x=>x.status!=='pass'))throw Error('A16A adversarial audit rejected');fs.copyFileSync(b.norm,path.join(dist,'DEPLOY.luac'));log.status='SIMULATION VERIFIED';log.sourceBytes=Buffer.byteLength(src);log.sourceSha256=sha(Buffer.from(src));log.normalizedBytes=b.bytes;log.normalizedSha256=b.sha256;log.physicalMargin=spec.hard_limit-b.bytes;log.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(dist,'A16A-BUILD.json'),JSON.stringify(log,null,2)+'\n');fs.writeFileSync(path.join(dist,'README.txt'),`A16A SIMULATION VERIFIED\nDeploy only DEPLOY.luac\nNormalized size: ${b.bytes}\nPhysical margin: ${log.physicalMargin}\nNot bench or road verified.\n`)}
main().catch(e=>{fs.writeFileSync(path.join(dist,'FAILED.txt'),String(e.stack||e)+'\n');console.error(e);process.exit(1)});
