#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';
const root=process.cwd(),R=path.join(root,'reports');fs.mkdirSync(R,{recursive:true});
const topics=[
 {family:'monday',query:'vehicle state estimation sensor fusion adaptive filtering wheel speed GPS RPM',keys:['lerp','q']},
 {family:'tuesday',query:'traction control anti lock braking model predictive control slip estimation',keys:['lerp','i9']},
 {family:'cloud',query:'online learning confidence calibration concept drift meta learning embedded systems',keys:['trait','md']},
 {family:'html',query:'embedded Lua memory optimization real time observability fault tolerant telemetry',keys:['q','i9','trait']}
];
const ua={'User-Agent':'mt12-jarvis-research/1.0 (public engineering research)','Accept':'application/json, application/xml, text/plain'};
async function get(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{headers:ua,signal:c.signal});if(!r.ok)throw Error(String(r.status));return await r.text()}finally{clearTimeout(t)}}
function clean(s=''){return s.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()}
function words(s){return new Set(String(s).toLowerCase().match(/[a-z][a-z0-9-]{2,}/g)||[])}
function score(text,q){const w=words(text),k=[...words(q)];return k.reduce((n,x)=>n+(w.has(x)?1:0),0)}
async function arxiv(t){const u='https://export.arxiv.org/api/query?search_query=all:'+encodeURIComponent(t.query)+'&start=0&max_results=8&sortBy=submittedDate&sortOrder=descending',x=await get(u),out=[];for(const e of x.split('<entry>').slice(1)){const title=clean((e.match(/<title>([\s\S]*?)<\/title>/)||[])[1]),summary=clean((e.match(/<summary>([\s\S]*?)<\/summary>/)||[])[1]),url=clean((e.match(/<id>(.*?)<\/id>/)||[])[1]);if(title)out.push({source:'arXiv',title,summary:summary.slice(0,700),url,score:score(title+' '+summary,t.query)})}return out}
async function crossref(t){const u='https://api.crossref.org/works?query='+encodeURIComponent(t.query)+'&filter=from-pub-date:2018-01-01&sort=relevance&rows=8',j=JSON.parse(await get(u)),out=[];for(const x of j.message?.items||[]){const title=clean(x.title?.[0]),summary=clean(x.abstract||x['container-title']?.[0]||''),url=x.URL||'';if(title)out.push({source:'Crossref',title,summary:summary.slice(0,700),url,score:score(title+' '+summary,t.query)})}return out}
async function semantic(t){const u='https://api.semanticscholar.org/graph/v1/paper/search?query='+encodeURIComponent(t.query)+'&limit=8&fields=title,abstract,url,year,citationCount',j=JSON.parse(await get(u)),out=[];for(const x of j.data||[]){if(x.title)out.push({source:'Semantic Scholar',title:clean(x.title),summary:clean(x.abstract||'').slice(0,700),url:x.url||'',year:x.year,citations:x.citationCount||0,score:score(x.title+' '+(x.abstract||''),t.query)+(x.citationCount>25?1:0)})}return out}
async function github(t){const token=process.env.GITHUB_TOKEN,h={...ua,Accept:'application/vnd.github+json'};if(token)h.Authorization='Bearer '+token;const c=new AbortController(),z=setTimeout(()=>c.abort(),12000);try{const r=await fetch('https://api.github.com/search/repositories?q='+encodeURIComponent(t.query+' language:Lua')+'&sort=stars&order=desc&per_page=8',{headers:h,signal:c.signal});if(!r.ok)return[];const j=await r.json();return(j.items||[]).map(x=>({source:'GitHub',title:x.full_name,summary:clean(x.description||'').slice(0,500),url:x.html_url,stars:x.stargazers_count,score:score(x.full_name+' '+(x.description||''),t.query)+(x.stargazers_count>100?1:0)}))}finally{clearTimeout(z)}}
const families={};for(const t of topics){const settled=await Promise.allSettled([arxiv(t),crossref(t),semantic(t),github(t)]),items=settled.flatMap(x=>x.status==='fulfilled'?x.value:[]).filter(x=>x.url&&x.title);const seen=new Set(),ranked=items.sort((a,b)=>b.score-a.score).filter(x=>{const k=x.title.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).slice(0,12);const text=ranked.map(x=>x.title+' '+x.summary).join(' ').toLowerCase();const signals={adaptive:/adaptive|online|recursive|kalman|bayesian/.test(text),robust:/robust|fault|outlier|hysteresis|uncertain/.test(text),predictive:/predictive|model predictive|forecast|observer/.test(text),smooth:/smooth|interpolation|filter|slew/.test(text)};let preferred=[...t.keys];if(signals.robust)preferred.unshift('q','md');if(signals.adaptive)preferred.unshift('trait','md');if(signals.smooth)preferred.unshift('lerp');preferred=[...new Set(preferred)];families[t.family]={query:t.query,preferredFunctions:preferred,signals,evidence:ranked,errors:settled.filter(x=>x.status==='rejected').map(x=>String(x.reason))}}
const report={schema:1,engine:'mt12-autonomous-research-v1',created:new Date().toISOString(),policy:{publicSourcesOnly:true,citationsRequired:true,untrustedTextNeverExecuted:true,networkTimeoutMs:12000,maxEvidencePerFamily:12},families};fs.writeFileSync(path.join(R,'research-latest.json'),JSON.stringify(report,null,2));let md='# MT12 autonomous research brief\n\nGenerated '+report.created+'\n\n';for(const[k,v]of Object.entries(families)){md+='## '+k.toUpperCase()+'\n\nQuery: `'+v.query+'`\n\nPreferred function targets: '+v.preferredFunctions.map(x=>'`'+x+'`').join(', ')+'\n\n';for(const e of v.evidence)md+='- ['+e.title+']('+e.url+') — '+e.source+'\n';md+='\n'}fs.writeFileSync(path.join(R,'research-latest.md'),md);console.log('Research brief built from '+Object.values(families).reduce((n,x)=>n+x.evidence.length,0)+' cited sources.');