#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';
const root=process.cwd(),R=path.join(root,'reports'),pending=JSON.parse(fs.readFileSync(path.join(R,'pending-state.json'),'utf8')),p=pending.p,g=pending.genome;
const cl=(x,a,b)=>Math.max(a,Math.min(b,x));
function launch(mu){let mph=0,rpm=0,cut=0,jerk=0,last=1;for(let i=0;i<140;i++){let target=37000*(1-Math.exp(-i/30)),wheel=target*p.rpmK,sl=Math.max(0,wheel-mph),tc=cl((sl-p.tcSlip)/p.tcSpan,0,1),pass=1-tc*p.tcCut/1024;if(g.tc===2)pass=cl(last+(pass-last)*.32,.55,1);jerk+=Math.abs(pass-last);last=pass;cut+=1-pass;mph+=Math.max(0,(pass*mu*1.1)-mph*.012);rpm=target}return{mph,cut,jerk}}
function braking(mu){let mph=48,rpm=mph/p.rpmK,lock=0,release=0;for(let i=0;i<100;i++){let ideal=Math.max(0,mph-0.62*mu),wheel=Math.max(0,rpm-(540+120*(1-mu))),x=cl((p.absLock-wheel)/p.absLock,0,1);if(g.abs===2)x=cl(x*.65+Math.max(0,(rpm-wheel)/12000)*.35,0,1);if(x>.2)release++;if(wheel<mph/p.rpmK*.45)lock++;mph=ideal;rpm=wheel}return{lock,release,stop:mph}}
function truth(){let t=0,e=0,drop=0;for(let i=0;i<180;i++){let real=i<70?i*.55:i<120?38.5:(180-i)*.64,gps=i%37<5?0:real+(i%9-4)*.08,rpm=(real+(i<70?3:0))/p.rpmK,q=gps>0?1:.15,rm=rpm*p.rpmK,target=q>.75?gps+cl(rm-gps,0,g.truth===2?10:7)*.42:rm>1?rm*.98:t*p.coast;t+= (cl(target,0,120)-t)*p.truthRate;e+=Math.abs(t-real);if(q<.2&&t>real+8)drop++}return{mae:e/180,drop}}
function jump(){let conf=0,falsePos=0,hit=0,land=0;for(let i=0;i<150;i++){let airborne=i>=60&&i<75,rise=airborne?4.2:(i%41===0?3.4:.3),fall=airborne?2.1:(i%41===0?1.2:.2),a=rise>p.jumpRise&&fall>p.jumpFall;if(a)conf=Math.min(9,conf+2);else conf=Math.max(0,conf-1);let det=conf>=5;if(det&&airborne)hit++;if(det&&!airborne)falsePos++;if(i===75&&det)land=p.landHold}return{hit,falsePos,land}}
const L1=launch(.92),L2=launch(.58),B1=braking(.95),B2=braking(.55),T=truth(),J=jump();
let score=100;score-=cl(L1.jerk*2.2,0,18);score-=cl(L2.cut*.08,0,14);score-=cl(B1.lock*.45,0,12);score-=cl(B2.lock*.35,0,12);score-=cl(T.mae*3.2,0,20);score-=cl(T.drop*.8,0,10);score-=cl(J.falsePos*1.5,0,12);score+=cl(J.hit*.25,0,5);score+=g.director+g.learn+g.logger+g.mood+g.landing;score=Number(score.toFixed(3));
const best=Number(pending.bestScore||0),pass=score>=Math.max(55,best-1.5);pending.last={...pending.last,score,simPass:pass,metrics:{dryLaunch:L1,wetLaunch:L2,dryBrake:B1,wetBrake:B2,truth:T,jump:J}};if(pass&&score>=best){pending.bestScore=score;pending.accepted=(pending.accepted||0)+1}fs.writeFileSync(path.join(R,'pending-state.json'),JSON.stringify(pending,null,2));const base=path.basename(process.argv[2]||pending.last.file,'.lua');const report={engine:'hand-built-deterministic-simulator',candidate:base,score,bestBefore:best,passed:pass,metrics:pending.last.metrics};fs.writeFileSync(path.join(R,`${base}-sim.json`),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!pass)process.exit(3);
