#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';
const root=process.cwd(),R=path.join(root,'reports'),file=process.argv[2];if(!file)throw Error('candidate required');const base=path.basename(file,'.lua'),pending=JSON.parse(fs.readFileSync(path.join(R,'pending-factory.json'),'utf8')),c=pending.batch.find(x=>path.basename(x.file,'.lua')===base);if(!c)throw Error('candidate metadata missing');const p=c.params||{},v=c.variant||2,cl=(x,a,b)=>Math.max(a,Math.min(b,x));
const P={rpmK:p.rpmK||.000914,tcSlip:p.tcSlip||7.4,tcSpan:p.tcSpan||5.4,tcCut:p.tcCut||25,absLock:p.absLock||7200,truthRate:p.truthRate||.18,coast:p.coast||.985};
function launch(mu,bumpy=false){let mph=0,cut=0,jerk=0,last=1,falseCut=0,peakSlip=0;for(let i=0;i<180;i++){const target=37000*(1-Math.exp(-i/32)),noise=bumpy?Math.sin(i*.9)*900:0,rm=(target+noise)*P.rpmK,sl=Math.max(0,rm-mph),x=(sl-P.tcSlip)/P.tcSpan;let tc=v===4?cl(x*.54+x*x*.20,0,1):v===3?cl(x*.68+x*x*.12,0,1):cl(x*.82,0,1),pass=1-tc*P.tcCut/1024;pass=cl(last+(pass-last)*(v===2?.45:.31),.55,1);jerk+=Math.abs(pass-last);if(sl<P.tcSlip*.72&&pass<.94)falseCut++;last=pass;cut+=1-pass;peakSlip=Math.max(peakSlip,sl);mph+=Math.max(0,pass*mu*1.08-mph*.012)}return{mph,cut,jerk,falseCut,peakSlip}}
function brake(mu,rough=false){let mph=48,rpm=mph/P.rpmK,lock=0,release=0,osc=0,last=0;for(let i=0;i<120;i++){const disturbance=rough?Math.sin(i*.7)*420:0,wheel=Math.max(0,rpm-(530+140*(1-mu))+disturbance),lk=cl((P.absLock-wheel)/P.absLock*.72+Math.max(0,(rpm-wheel)/12000)*.28,0,1),rel=lk>.2?lk:0;if(rel>0)release++;osc+=Math.abs(rel-last);last=rel;if(wheel<mph/P.rpmK*.44)lock++;mph=Math.max(0,mph-.62*mu);rpm=wheel}return{lock,release,osc,stop:mph}}
function truth(dropEvery=41,lag=0){let t=0,e=0,spike=0,overshoot=0;const hist=[];for(let i=0;i<220;i++){const real=i<75?i*.52:i<145?39:(220-i)*.52;hist.push(real);const delayed=hist[Math.max(0,hist.length-1-lag)],gps=i%dropEvery<6?0:delayed+(i%9-4)*.09,rpm=(real+(i<82?3.0:0))/P.rpmK,q=gps>0?1:.15,rm=rpm*P.rpmK,d=rm-gps,target=q>.72?gps+cl(d,-3,10)*(.34+q*.08):rm>1?rm*.98:t*P.coast;t+=(cl(target,0,120)-t)*P.truthRate;e+=Math.abs(t-real);if(Math.abs(t-real)>8)spike++;if(t-real>5)overshoot++}return{mae:e/220,spike,overshoot}}
function jumpClassifier(){let fp=0,miss=0,delay=0;for(let s=0;s<80;s++){const realJump=s%4===0,rough=s%4===1,score=(realJump?0.72:0)+(rough?0.28:0)+((s*17)%11)/100,det=score>(v===4?.66:v===3?.7:.74);if(det&&!realJump)fp++;if(!det&&realJump)miss++;if(det&&realJump)delay+=score<.82?2:1}return{fp,miss,delay}}
function dropout(){let unsafe=0,recovery=0,last=1;for(let i=0;i<90;i++){const drop=i>25&&i<34,cmd=drop?1:cl(last+(0.72-last)*.28,.55,1);if(drop&&cmd<.98)unsafe++;if(!drop&&i>=34&&Math.abs(cmd-.72)>.12)recovery++;last=cmd}return{unsafe,recovery}}
const Ld=launch(.92),Lw=launch(.56),Lb=launch(.62,true),Bd=brake(.95),Bw=brake(.54),Br=brake(.62,true),T0=truth(41,0),Tlag=truth(37,5),J=jumpClassifier(),D=dropout(),src=fs.readFileSync(file,'utf8'),tokens=new Set(src.match(/[A-Za-z_][A-Za-z0-9_]*/g)||[]),funcs=(src.match(/local function|function\s+[A-Za-z_]/g)||[]).length,systems=['aicmem.csv','playFile','lcd.draw','RPM2MPH','setgv(7','setgv(1','neural','bb_line','voiceTick','memLearn'].filter(x=>src.includes(x)).length,novelty=cl((c.changes?.length||0)/4,0,1),architecture=cl((funcs-20)/35,0,1),parity=systems/10;
const penalties={launchJerk:cl((Ld.jerk+Lw.jerk+Lb.jerk)*1.2,0,18),falseCut:cl((Ld.falseCut+Lw.falseCut+Lb.falseCut)*.18,0,10),wetCut:cl(Lw.cut*.06,0,13),brakeLock:cl(Bd.lock*.25+Bw.lock*.3+Br.lock*.22,0,15),brakeOsc:cl((Bd.osc+Bw.osc+Br.osc)*.22,0,9),truth:cl((T0.mae*2.5+Tlag.mae*2.8),0,24),truthSpikes:cl((T0.spike+Tlag.spike)*.28,0,10),jump:cl(J.fp*.6+J.miss*1.4+J.delay*.08,0,12),dropout:cl(D.unsafe*3+D.recovery*.35,0,14)};let score=112-Object.values(penalties).reduce((a,b)=>a+b,0)+novelty*3+architecture*2+parity*5;score=Number(score.toFixed(3));const prior=Number(c.previousBest||0),improvement=Number((score-prior).toFixed(3)),regressions=[];if(T0.mae>=6.5||Tlag.mae>=8)regressions.push('truth');if(Ld.jerk>=8||Lw.jerk>=9)regressions.push('traction-jerk');if(Bw.lock>=24)regressions.push('wet-brake');if(J.miss>=8)regressions.push('jump-miss');if(D.unsafe>0)regressions.push('fail-open');if(parity<1)regressions.push('subsystem-parity');const improved=score>prior+.15,passed=score>=66&&improved&&!regressions.length;const report={engine:'luac-factory-simulator-v3',candidate:base,family:c.family,generation:c.generation,experiment:c.experiment,style:c.style,objective:c.objective,score,previousBest:prior,improvement,novelty:Number(novelty.toFixed(3)),architecture:Number(architecture.toFixed(3)),parity:Number(parity.toFixed(3)),improved,passed,regressions,changes:c.changes||[],metrics:{dryLaunch:Ld,wetLaunch:Lw,bumpyLaunch:Lb,dryBrake:Bd,wetBrake:Bw,roughBrake:Br,truth:T0,lagTruth:Tlag,jump:J,dropout:D},penalties};fs.writeFileSync(path.join(R,`${base}-sim.json`),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!passed)process.exit(3);