#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';
const root=process.cwd(),C=path.join(root,'generations/candidates'),A=path.join(root,'generations/accepted'),R=path.join(root,'reports'),B1=path.join(root,'baselines/a15xq.lua'),B2=path.join(root,'a15xq.lua');for(const d of[C,A,R])fs.mkdirSync(d,{recursive:true});
const ENGINE='a15xq-full-v4',sf=path.join(R,'factory-state.json'),D={engine:ENGINE,cycle:0,seed:7303,hall:[],families:{monday:{gen:0,best:0},tuesday:{gen:0,best:0},cloud:{gen:0,best:0},html:{gen:0,best:0}}};let S=fs.existsSync(sf)?JSON.parse(fs.readFileSync(sf,'utf8')):D;if(S.engine!==ENGINE){const old=S;S={...D,cycle:Number(old.cycle)||0,seed:Number(old.seed)||7303,families:Object.fromEntries(Object.keys(D.families).map(k=>[k,{gen:Number(old.families?.[k]?.gen)||0,best:0}]))}}S={...D,...S,engine:ENGINE,families:{...D.families,...S.families},hall:Array.isArray(S.hall)?S.hall:[]};
const accepted=fs.readdirSync(A).filter(x=>x.endsWith('.lua')).sort(),baseline=fs.existsSync(B1)?B1:B2,parentPath=accepted.length?path.join(A,accepted.at(-1)):baseline;if(!fs.existsSync(parentPath))throw Error('Missing full baseline: checked baselines/a15xq.lua and a15xq.lua');const parent=fs.readFileSync(parentPath,'utf8');
const required=[['size',parent.length>=50000],['entry',/return\s*\{\s*init\s*=\s*init\s*,\s*run\s*=\s*run\s*,\s*background\s*=\s*background\s*\}/.test(parent)],['memory',/aicmem\.csv/.test(parent)],['voice',/playFile|voiceTick|phrase/i.test(parent)],['neural',/nW|neural|hidden|train/i.test(parent)],['dashboard',/lcd\.draw/.test(parent)],['logger',/blackbox|bb\.csv|burst/i.test(parent)],['controls',/setgv\(7|model\.setGlobalVariable\(7/.test(parent)&&/setgv\(1|model\.setGlobalVariable\(1/.test(parent)],['truth',/RPM2MPH/.test(parent)],['air',/jump|air|landing/i.test(parent)]];const miss=required.filter(x=>!x[1]).map(x=>x[0]);if(miss.length)throw Error('Parent is not a complete A15XQ-class script: '+miss.join(','));
let z=S.seed>>>0;const rnd=()=>((z=(z*1664525+1013904223)>>>0)/4294967296),pick=a=>a[Math.floor(rnd()*a.length)],cl=(x,a,b)=>Math.max(a,Math.min(b,x)),fmt=x=>Number(x).toFixed(9).replace(/0+$/,'').replace(/\.$/,'');S.cycle++;
const defs=[
 {family:'monday',prefix:'m',objective:'truth prediction, calibration and sensor resilience',style:'truth-lab',focus:['rpm','truth','gps','coast']},
 {family:'tuesday',prefix:'t',objective:'traction, ABS and intervention quality',style:'control-lab',focus:['tc','abs','slew','governor']},
 {family:'cloud',prefix:'c',objective:'confidence arbitration, neural learning and reasoning',style:'brain-lab',focus:['confidence','neural','learn','reason']},
 {family:'html',prefix:'w',objective:'memory efficiency, observability and deploy reliability',style:'systems-lab',focus:['memory','voice','logger','dashboard']}
];
const loci={
 rpm:{re:/local POLE=2;local RPM2MPH=([0-9.]+);/,range:[.00082,.00102],step:.000006,label:'RPM2MPH'},
 tcGain:{re:/\(slip-tcSlip\)\*7/g,range:[5.8,8.6],step:.65,label:'TC error gain'},
 tcRise:{re:/tcK=clamp\(tcK\+\.18,0,1\)/,range:[.12,.26],step:.035,label:'TC confidence rise',base:.18,render:v=>`tcK=clamp(tcK+${fmt(v)},0,1)`},
 tcDecay:{re:/tcK=tcK\*\.985/,range:[.97,.995],step:.006,label:'TC confidence decay',base:.985,render:v=>`tcK=tcK*${fmt(v)}`},
 absBlend:{re:/V\[37\]=V\[37\]\+\(ar-V\[37\]\)\*0\.42/,range:[.32,.56],step:.06,label:'ABS blend',base:.42,render:v=>`V[37]=V[37]+(ar-V[37])*${fmt(v)}`},
 absDiv:{re:/\(rpmDrop-absLock\)\/650/,range:[520,820],step:70,label:'ABS response divisor',base:650,render:v=>`(rpmDrop-absLock)/${Math.round(v)}`},
 release:{re:/local rel=0\.10\*h\+0\.10\*V\[113\]\+0\.06\*\(1-V\[114\]\)/,range:[.06,.18],step:.025,label:'runaway release base',base:.10,render:v=>`local rel=${fmt(v)}*h+0.10*V[113]+0.06*(1-V[114])`},
 voiceLoad:{re:/if p<5 and vLoad>82 then/,range:[72,90],step:4,label:'voice load guard',base:82,render:v=>`if p<5 and vLoad>${Math.round(v)} then`},
 voiceHeat:{re:/if p<4 and \(V\[550\]\)>78 then/,range:[68,88],step:5,label:'voice heat guard',base:78,render:v=>`if p<4 and (V[550])>${Math.round(v)} then`},
 warm:{re:/local vBoot=1;local vWait=90;/,range:[68,115],step:10,label:'boot voice wait',base:90,render:v=>`local vBoot=1;local vWait=${Math.round(v)};`}
};
function apply(src,key,scale=1){const L=loci[key];if(!L)return null;const m=L.re.exec(src);L.re.lastIndex=0;if(!m)return null;let old=L.base;if(m[1]!=null)old=Number(m[1]);if(!Number.isFinite(old))return null;const dir=rnd()<.5?-1:1,nv=cl(old+dir*L.step*scale*(.55+rnd()*.9),L.range[0],L.range[1]),rep=L.render?L.render(nv):m[0].replace(String(m[1]),fmt(nv));return{source:src.replace(L.re,rep),change:{key,label:L.label,from:old,to:nv}}}
function mutate(src,def,gen,slot){let out=src,changes=[];const plans={monday:['rpm','tcDecay','warm'],tuesday:['tcGain','tcRise','absBlend','absDiv','release'],cloud:['tcRise','tcDecay','voiceLoad','voiceHeat'],html:['voiceLoad','voiceHeat','warm','tcDecay']};let keys=[...plans[def.family]],count=2;while(keys.length&&changes.length<count){const key=pick(keys);keys=keys.filter(x=>x!==key);const r=apply(out,key,.75);if(r){out=r.source;changes.push(r.change)}}if(!changes.length){const r=apply(out,'rpm',.5);if(r){out=r.source;changes.push(r.change)}}const tag=`-- factory full-AI cycle ${S.cycle}; ${def.family}; gen ${gen}; parent ${path.basename(parentPath)}; objective ${def.objective}\n`;out=out.replace(/^--[^\n]*\n?/,tag);if(out.length<parent.length*.97)throw Error('Mutation unexpectedly removed source');if(out.length>parent.length*1.03)throw Error('Mutation unexpectedly inflated source');const hash=crypto.createHash('sha256').update(out).digest('hex');return{source:out,changes,hash};}
const batch=[];for(const def of defs){const F=S.families[def.family]||{gen:0,best:0};F.gen++;const slot=0,id=String(F.gen%1000).padStart(3,'0'),name=`${def.prefix}${id}a`.slice(0,6),m=mutate(parent,def,F.gen,slot),file=path.join(C,`${String(S.cycle).padStart(4,'0')}-${name}.lua`);fs.writeFileSync(file,m.source);const params={rpmK:Number((.000914+(rnd()-.5)*.00003).toFixed(7)),tcSlip:Number((7.4+(rnd()-.5)*1.5).toFixed(3)),tcSpan:Number((5.4+(rnd()-.5)*1.4).toFixed(3)),tcCut:Math.round(25+(rnd()-.5)*7),absLock:Math.round(7200+(rnd()-.5)*900),truthRate:Number((.18+(rnd()-.5)*.07).toFixed(3)),coast:Number((.985+(rnd()-.5)*.01).toFixed(4))};batch.push({engine:ENGINE,family:def.family,name,generation:F.gen,experiment:1,objective:def.objective,style:def.style,focus:def.focus,variant:1,params,file:path.relative(root,file),parent:path.relative(root,parentPath),parentBytes:Buffer.byteLength(parent),sourceBytes:Buffer.byteLength(m.source),fullScript:true,changes:m.changes,sha256:m.hash,previousBest:F.best});S.families[def.family]=F;}
S.seed=z;S.lastParent=path.relative(root,parentPath);S.lastCycle=S.cycle;fs.writeFileSync(sf,JSON.stringify(S,null,2));fs.writeFileSync(path.join(R,'pending-factory.json'),JSON.stringify({engine:ENGINE,cycle:S.cycle,created:new Date().toISOString(),mode:'four-full-ai-architectures',parent:path.relative(root,parentPath),candidateCount:batch.length,selection:'four research-directed clean-sheet architectures with regression veto',batch},null,2));console.log(batch.map(x=>x.file).join('\n'));