#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';
const root=process.cwd(),C=path.join(root,'generations/candidates'),A=path.join(root,'generations/accepted'),R=path.join(root,'reports'),B1=path.join(root,'baselines/a15xq.lua'),B2=path.join(root,'a15xq.lua'),limit=Number(process.env.MT12_LIMIT||88944),hard=Number(process.env.MT12_HARD_MARGIN||48);for(const d of[C,A,R])fs.mkdirSync(d,{recursive:true});
const ENGINE='a15xq-full-v5',sf=path.join(R,'factory-state.json'),D={engine:ENGINE,cycle:0,seed:7303,families:{monday:{gen:0},tuesday:{gen:0},cloud:{gen:0},html:{gen:0}}};let S=fs.existsSync(sf)?JSON.parse(fs.readFileSync(sf,'utf8')):D;S={...D,...S,engine:ENGINE,families:{...D.families,...S.families}};S.cycle++;
const defs=[{family:'monday',prefix:'m',objective:'truth prediction, calibration and sensor resilience',style:'truth-lab',focus:['rpm','truth','gps','coast']},{family:'tuesday',prefix:'t',objective:'traction, ABS and intervention quality',style:'control-lab',focus:['tc','abs','slew','governor']},{family:'cloud',prefix:'c',objective:'confidence arbitration, neural learning and reasoning',style:'brain-lab',focus:['confidence','neural','learn','reason']},{family:'html',prefix:'w',objective:'memory efficiency, observability and deploy reliability',style:'systems-lab',focus:['memory','voice','logger','dashboard']}];
const readJson=p=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return null}},accepted=fs.existsSync(A)?fs.readdirSync(A).filter(x=>x.endsWith('.lua')):[];
function info(name){const base=name.slice(0,-4),j=readJson(path.join(A,`${base}-changelog.json`)),luac=path.join(A,`${base}.luac`),bytes=fs.existsSync(luac)?fs.statSync(luac).size:Number(j?.files?.luac?.bytes||0),score=Number(readJson(path.join(R,`${base}-sim.json`))?.score??j?.score??0);return{name,base,bytes,margin:bytes?limit-bytes:0,score,safe:bytes>0&&limit-bytes>=hard}}
const all=accepted.map(info),baseline=fs.existsSync(B1)?B1:B2;
function parentFor(def){const mark=`-${def.prefix}`,family=all.filter(x=>x.name.includes(mark)),safe=family.filter(x=>x.safe).sort((a,b)=>b.score-a.score||b.margin-a.margin),any=family.sort((a,b)=>b.score-a.score||b.margin-a.margin),globalSafe=all.filter(x=>x.safe).sort((a,b)=>b.score-a.score||b.margin-a.margin);const pick=safe[0]||any[0]||globalSafe[0];return pick?path.join(A,pick.name):baseline}
function validate(src){const req=[src.length>=50000,/return\s*\{[\s\S]*init\s*=/.test(src),/aicmem\.csv/.test(src),/playFile/.test(src),/nW|neural/i.test(src),/lcd\.draw/.test(src),/RPM2MPH/.test(src)];if(req.some(x=>!x))throw Error('selected parent is incomplete')}
const batch=[];for(const def of defs){const F=S.families[def.family]||{gen:0};F.gen++;const parentPath=parentFor(def),parent=fs.readFileSync(parentPath,'utf8');validate(parent);const id=String(F.gen%1000).padStart(3,'0'),name=`${def.prefix}${id}a`.slice(0,6),tag=`-- factory isolated-AI cycle ${S.cycle}; ${def.family}; gen ${F.gen}; parent ${path.basename(parentPath)}; objective ${def.objective}\n`,source=parent.replace(/^--[^\n]*\n?/,tag),file=path.join(C,`${String(S.cycle).padStart(4,'0')}-${name}.lua`);fs.writeFileSync(file,source);batch.push({engine:ENGINE,family:def.family,name,generation:F.gen,experiment:1,experimentIsolation:true,allowConstantChanges:false,objective:def.objective,style:def.style,focus:def.focus,file:path.relative(root,file),parent:path.relative(root,parentPath),parentBytes:Buffer.byteLength(parent),sourceBytes:Buffer.byteLength(source),fullScript:true,changes:[],sha256:crypto.createHash('sha256').update(source).digest('hex'),previousBest:0});S.families[def.family]=F}
S.lastCycle=S.cycle;fs.writeFileSync(sf,JSON.stringify(S,null,2));fs.writeFileSync(path.join(R,'pending-factory.json'),JSON.stringify({engine:ENGINE,cycle:S.cycle,created:new Date().toISOString(),mode:'four-family-isolated-architectures',candidateCount:batch.length,selection:'four family-parent isolated architectures; one family is architected per cycle and all generated files remain declared',batch},null,2));console.log(batch.map(x=>x.file).join('\n'));