import fs from 'node:fs';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const [planPath='michael/reconstruction/current.json',out='/tmp/reconstruction-proof.json']=process.argv.slice(2);
const p=read(planPath),errors=[],warnings=[];
if(!p.multiviewPhotogrammetry?.solveOneShared3DShape)errors.push('multiview shared-shape solve disabled');
if(!p.meshReconstruction?.championMeshProtected)errors.push('champion mesh not protected');
if(!p.lighting?.neutralStudioGeometryJudge)errors.push('geometry judge lighting not isolated');
if(!p.exteriorInteriorFit?.requireNoExteriorMutationByKeleb)errors.push('Keleb exterior boundary missing');
if(!p.exteriorInteriorFit?.requireNoInteriorMutationByNickelle)errors.push('Nickelle interior boundary missing');
if(!p.topologyQuality?.failClosed)errors.push('topology does not fail closed');
if(!p.promotion?.requireMobilePerformancePass)errors.push('mobile performance gate missing');
if(!p.lod?.levels?.some(x=>x.name==='LOD1'&&x.target==='mobile_near'))errors.push('mobile LOD1 missing');
if((p.componentPlan||[]).some(x=>!x.parameters?.length))warnings.push('some semantic components have no current genome authority and require mesh-level reconstruction');
const result={schema:1,at:new Date().toISOString(),pass:errors.length===0,errors,warnings,gates:{cameraSolve:Object.keys(p.cameraSolve||{}).length,multiview:p.multiviewPhotogrammetry?.enabled,landmarks:!!p.landmarkGraph,segmentation:p.componentSegmentation?.enabled,depthNormals:p.depthNormals?.enabled,mesh:p.meshReconstruction?.enabled,curvature:p.surfaceCurvature?.enabled,symmetry:p.symmetry?.enabled,materials:!!p.materials,liveryUV:p.liveryUV?.enabled,lighting:!!p.lighting,occlusion:p.occlusion?.enabled,fit:!!p.exteriorInteriorFit,topology:!!p.topologyQuality,scale:!!p.scaleAnchors,heatmap:!!p.errorHeatmap,locking:!!p.componentLocks,lod:!!p.lod}};
fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));if(!result.pass)process.exit(1);
