import fs from 'node:fs';
import path from 'node:path';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const save=(p,x)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n')};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const sys=read('michael/reconstruction/system.json');
const genome=read('michael/visual/genome.json');
const ref=read('michael/visual/reference-metrics.json');
const research=fs.existsSync('nickelle/research/constraints.json')?read('nickelle/research/constraints.json'):{};
const keleb=fs.existsSync('keleb/reconstruction.json')?read('keleb/reconstruction.json'):null;
const groups={headlights:['projector_outer_rx','projector_outer_ry','projector_red_inner_rx','projector_red_inner_ry','projector_black_outer_rx','projector_black_outer_ry','projector_black_inner_rx','projector_black_inner_ry'],grille:['grille_half_bottom','grille_half_top','grille_bottom_y','grille_top_y'],arches:['arch_x','wheel_radius','wheel_track_x','wheel_y'],roof_scoop:['scoop_width','scoop_height','scoop_length'],rear_aero:['wing_end_x','diffuser_half_bottom','diffuser_half_top'],stance:['wheel_radius','wheel_track_x','wheel_width','wheel_y']};
const aliases={headlights:['front_left_projector','front_right_projector','projector_left','projector_right'],grille:['front_grille'],arches:['front_arch_left','front_arch_right','wheel_fl','wheel_fr'],roof_scoop:['roof_scoop'],rear_aero:['rear_wing','rear_diffuser','diffuser'],stance:['wheel_fl','wheel_fr','wheel_rl','wheel_rr']};
function evidence(g){let c=0,n=0,r=0;for(const a of aliases[g]||[]){const x=research.componentConstraints?.[a];if(!x)continue;c+=Number(x.confidence||0);n++;r+=x.directVisualReferences?.length||0}return{confidence:n?c/n:0,references:r}}
function cameraSolve(){const out={};for(const v of sys.canonicalViews){const m=ref[v];if(!m?.valid)continue;out[v]={status:'relative_solve',targetAspect:m.bboxAspect??null,targetEdgeDensity:m.edgeDensity??null,targetDarkSpan:m.darkSpan??null,confidence:.62,locked:false}}return out}
function silhouetteTargets(){const out={};for(const v of sys.canonicalViews){const m=ref[v];if(!m?.valid)continue;out[v]={bboxAspect:m.bboxAspect,edgeDensity:m.edgeDensity,darkSpan:m.darkSpan,wheelFill:m.wheelFill??null,weight:v==='three'||v==='side'?1:.72}}return out}
function componentPlan(){return Object.keys(groups).map(g=>{const e=evidence(g),unc=1-e.confidence,params=groups[g].filter(k=>genome.bounds[k]);return{component:g,evidence:e,uncertainty:Number(unc.toFixed(3)),parameters:params,priority:Number((.55+unc*.7+Math.min(.25,e.references*.01)).toFixed(3)),authority:'Nickelle',strategy:e.references?'reference_constrained_reconstruction':'research_then_reconstruct'}}).sort((a,b)=>b.priority-a.priority)}
function materialPlan(){return{classes:['paint_clearcoat','paint_base','matte_aero','rubber','glass','polycarbonate_lamp','metal','carbon_composite','decal'],separateGeometryFromLighting:true,neutralStudioRequired:true,referenceMatchedLightingSecondary:true}}
function topology(){return{checks:['finite_vertices','valid_normals','no_self_intersection_proxy','no_floating_component_proxy','no_z_fighting_proxy','watertight_where_required','triangle_budget','connected_semantic_parts'],failClosed:true}}
function lod(){return{master:'reconstruction_master',levels:[{name:'LOD0',target:'desktop_high',detail:1},{name:'LOD1',target:'mobile_near',detail:.62},{name:'LOD2',target:'mobile_far',detail:.32}],preserve:['silhouette','lamp_identity','wheel_arch_fit','livery_readability'],mobileChampionUsesLOD:'LOD1'}}
function heatmap(){return{views:sys.canonicalViews,regions:['silhouette','landmarks','depth_normals','materials','livery','occlusion'],focusFraction:.05,policy:'allocate next reconstruction cycle to highest weighted residual error'}}
function locking(plan){return Object.fromEntries(plan.map(x=>[x.component,{winsRequired:4,minimumIndependentViews:3,minimumReferenceClasses:2,locked:false,mutationScaleWhenStable:.25}]))}
function fit(){return{NickelleExterior:'read_write',KelebInterior:'read_write_interior_only',interfaces:['windshield','door_windows','rear_window','dashboard_sightline','seat_sightline','cage_sightline'],requireNoExteriorMutationByKeleb:true,requireNoInteriorMutationByNickelle:true,status:keleb?'ready_for_joint_validation':'awaiting_keleb_reconstruction'}}
function run(out){const plan=componentPlan();const result={schema:1,generatedAt:new Date().toISOString(),director:sys.director,authority:sys.authority,physicalScale:sys.physicalAnchors,cameraSolve:cameraSolve(),silhouetteTargets:silhouetteTargets(),landmarkGraph:'michael/reconstruction/landmarks.json',componentPlan:plan,multiviewPhotogrammetry:{enabled:true,minimumViews:3,canonicalViews:sys.canonicalViews,solveOneShared3DShape:true},componentSegmentation:{enabled:true,domain:'C3_WRC_MJX7303_semantic_parts',genericSegmentationIsAdvisory:true},depthNormals:{enabled:true,models:['Depth Anything V2','rendered normal/depth proxies'],requireCrossViewConsistency:true},meshReconstruction:{enabled:true,componentFirst:true,allowNewVerticesSplinesMeshes:true,championMeshProtected:true},surfaceCurvature:{enabled:true,targets:['hood_crown','fender_shoulders','door_curvature','bumper_transitions','roof_curvature']},symmetry:{enabled:true,default:'bilateral_geometry',allowedAsymmetry:['livery','cockpit_equipment','documented_vents']},materials:materialPlan(),liveryUV:{enabled:true,separateFromBodyGeometry:true,projectFromValidatedReferences:true},lighting:{neutralStudioGeometryJudge:true,referenceMatchedSecondary:true,mobileRuntimeSeparate:true},occlusion:{enabled:true,reasons:['hidden_by_geometry','outside_camera','missing_component','material_merge','depth_conflict']},exteriorInteriorFit:fit(),topologyQuality:topology(),scaleAnchors:sys.physicalAnchors,detailLadder:sys.detailLadder,errorHeatmap:heatmap(),componentLocks:locking(plan),lod:lod(),promotion:sys.promotion,nextComponent:plan[0]?.component||null};save(out,result);console.log(JSON.stringify({director:result.director,nextComponent:result.nextComponent,components:plan.length,kelebFit:result.exteriorInteriorFit.status},null,2))}
const [cmd,out='michael/reconstruction/current.json']=process.argv.slice(2);if(cmd!=='run')throw Error('usage: michael_reconstruction_director.mjs run [OUT]');run(out);
