import fs from 'node:fs';
const R=p=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return null}},W=(p,x)=>{fs.mkdirSync(p.split('/').slice(0,-1).join('/')||'.',{recursive:true});fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n')},clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v)),avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0,n=v=>Number(v)||0;
const director=R('michael/art/ultra-art-director.json')||{},extBrain=R('nickelle/artist-brain.json')||{},intBrain=R('keleb/artist-brain.json')||{};
function critic(name,score,evidence){return{name,score:+clamp(score).toFixed(2),pass:score>=72,evidence}}
export function exteriorCouncil(gate,verdict={},decision={}){const comps=gate.components||{},scores=Object.values(comps).map(x=>n(x.score)).filter(x=>x>0),by=k=>n(comps[k]?.score),weak=gate.weak?.length||0,id=gate.identity?.candidate||{},turn=gate.turntable||{},sem=n(verdict.candidateScore||decision.candidateScore),pres=avg(Object.values(comps).map(x=>n(x.championPreservation)).filter(Boolean));const council=[
critic('automotiveDesigner',avg([by('headlights'),by('grille'),by('front_arch_aero'),by('side_aero'),by('rear_wing')]),'proportion/stance/aero integration'),
critic('sculptor',avg([by('side_aero'),by('roof_greenhouse'),by('rear_bumper'),by('rear_lamps'),pres]),'volume/continuity/edge integration'),
critic('hardSurfaceModeler',avg([by('headlights'),by('grille'),by('rear_lamps'),by('rear_diffuser'),100-Math.min(100,weak*14)]),'topology/recess/component integration'),
critic('materialArtist',avg([by('livery_materials'),(n(id.glass)*9000),(n(id.dark_aero)*5000),pres]),'material separation/glass/dark aero'),
critic('liveryArtist',avg([by('livery_materials'),n(id.white_livery)*12000,n(id.yellow_livery)*14000,pres]),'owner identity/decal/color blocks'),
critic('productPhotographer',avg([sem,pres,100-Math.min(100,n(turn.discontinuity)*700)]),'form readability/reflection continuity'),
critic('cinematographer',avg([sem,100-Math.min(100,n(turn.discontinuity)*850),scores.length?Math.min(...scores):0]),'hierarchy/depth/multiview continuity'),
critic('restorationArtist',avg([by('livery_materials'),by('rear_lamps'),by('headlights'),by('grille'),pres]),'owner-specific RC fidelity'),
critic('rallyEngineer',avg([by('front_arch_aero'),by('rear_diffuser'),by('rear_wing'),by('side_aero'),by('headlights')]),'functional aero/packaging plausibility'),
critic('restraintCritic',avg([pres,100-Math.min(100,(gate.regressed?.length||0)*25),100-Math.min(100,weak*12)]),'no unexplained geometry/no metric gaming')];
return finish('NICKELLE_EXTERIOR',council,{weak,turntable:turn,identity:id,brain:extBrain.name||null})}
export function interiorCouncil(measured={},heavy={},reconstruction={}){const err=n(measured.meanError),base=100-Math.min(100,err*100),views=n(measured.truthImages)*18,seg=n(heavy.summary?.semanticConfidence||heavy.semanticConfidence)*100,depth=n(heavy.summary?.depthConfidence||heavy.depthConfidence)*100,conf=n(reconstruction.confidence||reconstruction.evidenceConfidence)*100;const council=[
critic('cockpitDesigner',avg([base,views,conf]),'architecture/ergonomics/visibility'),critic('fabricator',avg([base,conf,seg||base]),'cage/mount/structural plausibility'),critic('sculptor',avg([base,depth||base,conf]),'seat/dash/wheel volume'),critic('modeler',avg([base,depth||base,views]),'topology/depth/component integration'),critic('materialArtist',avg([base,seg||base,conf]),'cabin material hierarchy'),critic('lightingArtist',avg([base,depth||base,seg||base]),'cabin depth/glass transmission'),critic('restorationArtist',avg([base,views,conf]),'period-correct C3 WRC detail'),critic('critic',avg([base,views,100-Math.min(100,err*130)]),'scale/alignment/restraint')];return finish('KELEB_INTERIOR',council,{meanError:err,truthImages:measured.truthImages||0,brain:intBrain.name||null})}
export function wholeCarCouncil(exterior={},interior={},boundaryOK=true){const ex=n(exterior.score||exterior.average),inn=n(interior.score||interior.average),coherence=100-Math.abs(ex-inn)*.55;const council=[critic('identityDirector',avg([ex,inn,coherence]),'one-car identity'),critic('materialContinuity',avg([ex,inn]),'exterior/interior material language'),critic('packagingDirector',avg([inn,boundaryOK?100:0]),'glass/cockpit/body compatibility'),critic('designLanguageDirector',avg([ex,inn,coherence]),'shared edge/surface language'),critic('restraintDirector',avg([coherence,boundaryOK?100:0]),'no cross-agent conflict')];return finish('MICHAEL_WHOLE_CAR',council,{coherence:+coherence.toFixed(2),boundaryOK})}
function finish(scope,council,meta){const minFrac=n(director.promotion?.minimumCouncilPassFraction)||.8,passed=council.filter(x=>x.pass).length,frac=passed/council.length,average=avg(council.map(x=>x.score)),pass=frac>=minFrac&&average>=76;return{schema:1,scope,generatedAt:new Date().toISOString(),pass,average:+average.toFixed(2),passed,critics:council.length,passFraction:+frac.toFixed(3),requiredPassFraction:minFrac,council,meta,authorityOrder:director.authorityOrder||[]}}
const [mode,...a]=process.argv.slice(2);if(mode==='exterior'){const out=exteriorCouncil(R(a[0])||{},R(a[1])||{},R(a[2])||{});W(a[3]||'/tmp/artist-council.json',out);console.log(JSON.stringify(out,null,2))}else if(mode==='interior'){const out=interiorCouncil(R(a[0])||{},R(a[1])||{},R(a[2])||{});W(a[3]||'/tmp/keleb-artist-council.json',out);console.log(JSON.stringify(out,null,2));if(!out.pass)process.exitCode=3}else if(mode==='wholecar'){const out=wholeCarCouncil(R(a[0])||{},R(a[1])||{},a[2]!=='false');W(a[3]||'/tmp/wholecar-artist-council.json',out);console.log(JSON.stringify(out,null,2))}else if(import.meta.url===`file://${process.argv[1]}`)throw Error('usage: michael_artist_council.mjs exterior GATE VERDICT DECISION OUT | interior MEASURED HEAVY RECON OUT | wholecar EXTERIOR INTERIOR BOUNDARY OUT');