import fs from 'node:fs';
import path from 'node:path';
import {PNG} from 'pngjs';

const ref=JSON.parse(fs.readFileSync('michael/visual/reference-metrics.json','utf8'));
const genome=JSON.parse(fs.readFileSync('michael/visual/genome.json','utf8'));
const VIEWS=['front','three','side','rear','top'];
const decode=f=>{const p=PNG.sync.read(fs.readFileSync(f));return{w:p.width,h:p.height,d:p.data}};
const lum=(r,g,b)=>.2126*r+.7152*g+.0722*b;
const red=(r,g,b)=>r>55&&r>g*1.34&&r>b*1.22;
const dark=(r,g,b)=>r<58&&g<62&&b<68;
const white=(r,g,b)=>r>145&&g>145&&b>140&&Math.max(r,g,b)-Math.min(r,g,b)<60;
const yellow=(r,g,b)=>r>120&&g>68&&g<205&&b<100&&r>g*1.10;
function comps(mask,w,h,min=12){const seen=new Uint8Array(mask.length),q=new Int32Array(mask.length),out=[];for(let p=0;p<mask.length;p++){if(!mask[p]||seen[p])continue;let a=0,b=0;q[b++]=p;seen[p]=1;let n=0,x0=w,y0=h,x1=0,y1=0;while(a<b){const u=q[a++],x=u%w,y=(u/w)|0;n++;x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const X=x+dx,Y=y+dy;if(X<0||Y<0||X>=w||Y>=h)continue;const v=Y*w+X;if(mask[v]&&!seen[v]){seen[v]=1;q[b++]=v}}}if(n>=min)out.push({area:n,x0,y0,x1,y1,w:x1-x0+1,h:y1-y0+1,cx:(x0+x1)/2,cy:(y0+y1)/2})}return out.sort((a,b)=>b.area-a.area)}
function inspect(file){const {w,h,d}=decode(file);let x0=w,y0=h,x1=0,y1=0,seeds=0;for(let y=0;y<h;y+=2)for(let x=0;x<w;x+=2){const i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2];if(red(r,g,b)||yellow(r,g,b)||white(r,g,b)){seeds++;x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y)}}if(seeds<60)return{valid:false};const px=Math.max(10,(x1-x0)*.12),py=Math.max(10,(y1-y0)*.12);x0=Math.max(0,Math.floor(x0-px));x1=Math.min(w-1,Math.ceil(x1+px));y0=Math.max(0,Math.floor(y0-py));y1=Math.min(h-1,Math.ceil(y1+py));const W=x1-x0+1,H=y1-y0+1,dm=new Uint8Array(W*H),wm=new Uint8Array(W*H);let n=0,R=0,D=0,Wh=0,Y=0,edges=0,centerN=0,centerD=0,lowerN=0,lowerD=0,topN=0,topW=0,sym=0,sn=0;for(let yy=0;yy<H;yy++)for(let xx=0;xx<W;xx++){const x=x0+xx,y=y0+yy,i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2],isD=dark(r,g,b),isW=white(r,g,b);n++;if(red(r,g,b))R++;if(isD)D++;if(isW)Wh++;if(yellow(r,g,b))Y++;dm[yy*W+xx]=isD;wm[yy*W+xx]=isW;if(xx>W*.22&&xx<W*.78&&yy>H*.32&&yy<H*.82){centerN++;if(isD)centerD++}if(yy>H*.52){lowerN++;if(isD)lowerD++}if(yy<H*.34){topN++;if(isW)topW++}if(xx+1<W&&yy+1<H){const a=lum(r,g,b),j=i+4,k=((y+1)*w+x)*4;if(Math.abs(a-lum(d[j],d[j+1],d[j+2]))>32||Math.abs(a-lum(d[k],d[k+1],d[k+2]))>32)edges++}}for(let yy=0;yy<H;yy+=2)for(let xx=0;xx<W/2;xx+=2){const a=((y0+yy)*w+x0+xx)*4,b=((y0+yy)*w+x0+W-1-xx)*4;sym+=Math.abs(lum(d[a],d[a+1],d[a+2])-lum(d[b],d[b+1],d[b+2]))/255;sn++}const wc=comps(wm,W,H,18).filter(c=>c.cy>H*.5&&c.w>H*.08&&c.h>H*.08);const wheels=wc.filter(c=>c.w/c.h>.55&&c.w/c.h<1.8).slice(0,2);const wheelFill=wheels.length?wheels.reduce((s,c)=>s+Math.sqrt(c.w*c.h)/H,0)/wheels.length:0;const dc=comps(dm,W,H,28).filter(c=>c.cy>H*.28&&c.cy<H*.78);const pods=dc.filter(c=>c.cx<W*.37||c.cx>W*.63).filter(c=>c.w/H>.04&&c.h/H>.03).slice(0,4);const podAspect=pods.length?pods.reduce((s,c)=>s+c.w/c.h,0)/pods.length:0;let rows=[];for(let yy=Math.floor(H*.45);yy<H*.82;yy++){let lo=W,hi=-1;for(let xx=0;xx<W;xx++)if(dm[yy*W+xx]){lo=Math.min(lo,xx);hi=Math.max(hi,xx)}if(hi>=lo)rows.push((hi-lo+1)/W)}rows.sort((a,b)=>a-b);return{valid:true,red:R/n,dark:D/n,white:Wh/n,yellow:Y/n,bboxAspect:W/H,centerDark:centerD/Math.max(1,centerN),lowerDark:lowerD/Math.max(1,lowerN),topWhite:topW/Math.max(1,topN),edgeDensity:edges/n,symmetryError:sym/Math.max(1,sn),wheelFill,podAspect,darkSpan:rows.length?rows[Math.floor(rows.length*.75)]:0}}
const close=(a,b,t)=>Number.isFinite(a)&&Number.isFinite(b)?Math.max(0,1-Math.abs(a-b)/t):0;
const center=(a,b,t)=>close(a,b,t);
function evaluate(dir){const s={};for(const v of VIEWS){const f=path.join(dir,`${v}.png`);s[v]=fs.existsSync(f)?inspect(f):{valid:false}}if(!s.front.valid||!s.side.valid||!s.three.valid||!s.rear.valid)return{score:0,features:s,parts:{},confidence:0,ownerTruthPass:false};const rs=ref.side,rt=ref.three,podTarget=Number(rs.podAspect||2.047),parts={
  grille:center(s.front.centerDark,Math.max(.20,rt.centerDark),.16)*100,
  grilleSpan:center(s.front.darkSpan,Math.max(.72,rt.darkSpan),.22)*100,
  sideSilhouette:center(s.side.bboxAspect,rs.bboxAspect,.42)*100,
  threeSilhouette:center(s.three.bboxAspect,rt.bboxAspect,.38)*100,
  sideDark:center(s.side.lowerDark,rs.lowerDark,.14)*100,
  wheelFill:center(s.side.wheelFill,rs.wheelFill,.10)*100,
  roofWhite:center(s.side.topWhite,rs.topWhite,.11)*100,
  liveryYellow:center(s.side.yellow,rs.yellow,.10)*100,
  liveryWhite:center(s.side.white,rs.white,.10)*100,
  edgeDetail:((center(s.side.edgeDensity,rs.edgeDensity,.08)+center(s.three.edgeDensity,rt.edgeDensity,.08))/2)*100,
  projectorShape:center(s.front.podAspect,podTarget,.72)*100,
  frontSymmetry:center(s.front.symmetryError,.10,.18)*100,
  rearMass:center(s.rear.lowerDark,.25,.15)*100,
  rearLivery:center(s.rear.yellow,Math.max(.06,rt.yellow*.35),.09)*100
};const weights={grille:1.8,grilleSpan:1.6,sideSilhouette:1.4,threeSilhouette:1.2,sideDark:1.4,wheelFill:1.5,roofWhite:1.35,liveryYellow:1.6,liveryWhite:1.45,edgeDetail:1.1,projectorShape:1.8,frontSymmetry:.8,rearMass:1.5,rearLivery:1.0};let sum=0,wt=0;for(const k in parts){sum+=parts[k]*weights[k];wt+=weights[k]}const critical=['grille','grilleSpan','projectorShape','sideSilhouette','sideDark','roofWhite','liveryYellow','liveryWhite','rearMass'];const floors={grille:42,grilleSpan:48,projectorShape:48,sideSilhouette:55,sideDark:45,roofWhite:42,liveryYellow:35,liveryWhite:35,rearMass:38};const failures=critical.filter(k=>parts[k]<floors[k]);return{score:Math.round(sum/wt*100)/100,features:s,parts:Object.fromEntries(Object.entries(parts).map(([k,v])=>[k,Math.round(v*10)/10])),confidence:Math.round((Object.values(parts).filter(v=>v>25).length/Object.keys(parts).length)*1000)/1000,ownerTruthFailures:failures,ownerTruthPass:failures.length===0,podAspectTarget:podTarget}}
function bound(k,v){const b=genome.bounds[k];if(!b)return genome.parameters[k];const [lo,hi]=b,old=genome.parameters[k],step=(hi-lo)*(genome.maxStepFraction||.18);return Math.round(Math.max(old-step,Math.min(old+step,Math.max(lo,Math.min(hi,v))))*10000)/10000}
function propose(dir){const e=evaluate(dir),p=e.parts,f=e.features,c={},d=[],weakest=Object.entries(p).sort((a,b)=>a[1]-b[1]).map(x=>x[0]);for(const k of weakest){if(Object.keys(c).length>=5)break;if(k==='grille'||k==='grilleSpan'){const need=f.front.centerDark<Math.max(.20,ref.three.centerDark);c.grille_half_bottom=bound('grille_half_bottom',genome.parameters.grille_half_bottom+(need?.02:-.015));c.grille_half_top=bound('grille_half_top',genome.parameters.grille_half_top+(need?.015:-.012));d.push('Owner Truth: correct wide low central grille coverage.')}else if(k==='sideDark'){c.door_black_top=bound('door_black_top',genome.parameters.door_black_top+(f.side.lowerDark<ref.side.lowerDark?.014:-.014));d.push('Owner Truth: correct long black lower-door aero coverage.')}else if(k==='projectorShape'&&f.front.podAspect){const target=Number(ref.side.podAspect||2.047),tooRound=f.front.podAspect<target;c.headlamp_width=bound('headlamp_width',genome.parameters.headlamp_width+(tooRound?.018:-.012));c.headlamp_height=bound('headlamp_height',genome.parameters.headlamp_height+(tooRound?-.010:.008));d.push(`Owner Truth: elongate lower lamp pod toward aspect ${target.toFixed(2)}; never optimize toward circular projectors.`)}else if(k==='roofWhite'||k==='liveryWhite'){c.roof_y_front=bound('roof_y_front',genome.parameters.roof_y_front+(f.side.topWhite<ref.side.topWhite?.006:-.006));c.roof_y_rear=bound('roof_y_rear',genome.parameters.roof_y_rear+(f.side.topWhite<ref.side.topWhite?.006:-.006));d.push('Owner Truth: restore white roof/upper identity coverage.')}else if(k==='rearMass'){c.diffuser_half_bottom=bound('diffuser_half_bottom',genome.parameters.diffuser_half_bottom+(f.rear.lowerDark<.25?.012:-.012));d.push('Owner Truth: strengthen rear bumper/diffuser dark mass.')}else if(k==='liveryYellow'){c.skirt_y_top=bound('skirt_y_top',genome.parameters.skirt_y_top+(f.side.yellow<ref.side.yellow?.006:-.004));d.push('Owner Truth: restore yellow identity/rocker coverage.')}else if(k==='wheelFill'){d.push(`Wheel fill weak (${f.side.wheelFill.toFixed(3)} vs owner ${ref.side.wheelFill.toFixed(3)}); native wheel authority required.`)}}if(!Object.keys(c).length){const k='headlamp_width';c[k]=bound(k,genome.parameters[k]+.006);d.push('Fallback mutation preserves owner elongated-lamp direction.')}return{score:e.score,subsystemScores:e.parts,diagnosis:d,candidateParameters:c,rationale:['Nickelle Internal Vision V2 optimizes directly toward Owner Truth metrics.','Critical exterior identity is scored absolutely, not merely relative to the previous champion.'],internalVision:true,confidence:e.confidence,features:e.features,ownerTruthFailures:e.ownerTruthFailures,podAspectTarget:e.podAspectTarget}}
function compare(baseDir,candDir,out){const a=evaluate(baseDir),b=evaluate(candDir),gain=b.score-a.score,reg=Object.keys(a.parts).filter(k=>Number.isFinite(b.parts[k])&&b.parts[k]<a.parts[k]-4),critical=['grille','grilleSpan','projectorShape','sideSilhouette','sideDark','roofWhite','liveryYellow','liveryWhite','rearMass'],stalled=critical.filter(k=>b.ownerTruthFailures.includes(k)&&b.parts[k]<a.parts[k]+1.5),catastrophic=[];if(b.features.front.podAspect&&b.features.front.podAspect<1.35)catastrophic.push(`front lamp pods too square/round: ${b.features.front.podAspect.toFixed(2)} < 1.35`);if(b.features.side.topWhite<ref.side.topWhite*.35)catastrophic.push('white roof identity effectively missing');if(b.features.side.yellow<ref.side.yellow*.25)catastrophic.push('yellow/livery identity effectively missing');if(b.features.front.darkSpan<ref.three.darkSpan*.45)catastrophic.push('front black/grille span collapsed');const promote=gain>=1&&!reg.length&&!catastrophic.length&&stalled.length<=2;const r={baselineScore:a.score,candidateScore:b.score,promote,regressions:[...reg.map(k=>`${k} regressed ${a.parts[k]} -> ${b.parts[k]}`),...catastrophic.map(x=>`CATASTROPHIC: ${x}`)],improvements:Object.keys(a.parts).filter(k=>b.parts[k]>a.parts[k]+3).map(k=>`${k} improved ${a.parts[k]} -> ${b.parts[k]}`),ownerTruthFailures:b.ownerTruthFailures,stalledCritical:stalled,reason:'Nickelle Internal Vision V2 direct Owner Truth comparison with catastrophic visual vetoes',internalVision:true,confidence:Math.min(a.confidence,b.confidence),baseline:a,candidate:b};fs.writeFileSync(out||'/tmp/michael-verdict.json',JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify(r,null,2))}
const mode=process.argv[2];if(mode==='evaluate')console.log(JSON.stringify(evaluate(process.argv[3]),null,2));else if(mode==='propose'){const r=propose(process.argv[3]);fs.writeFileSync(process.argv[4]||'/tmp/michael-proposal.json',JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify(r,null,2))}else if(mode==='compare')compare(process.argv[3],process.argv[4],process.argv[5]);else throw Error('usage: michael_internal_vision.mjs evaluate DIR | propose DIR OUT | compare BASE CAND OUT');
