import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {PNG} from 'pngjs';
import jpeg from 'jpeg-js';
const R=p=>JSON.parse(fs.readFileSync(p,'utf8')), E=p=>fs.existsSync(p), S=(p,x)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n')};
const C=(v,a,b)=>Math.max(a,Math.min(b,v)), N=(v,n=4)=>Number(Number(v).toFixed(n));
const cfg=R('michael/visual/advanced-autonomy.json'), auto=R('michael/reconstruction/autonomous-state.json'), genome=R('michael/visual/genome.json'), scene=R('michael/visual/scene-graph.json'), owner=R('michael/visual/owner-reference-observations.json'), dsl=R('michael/reconstruction/topology-dsl.json');
const memory=E('nickelle/memory.json')?R('nickelle/memory.json'):{}, keleb=E('keleb/reconstruction.json')?R('keleb/reconstruction.json'):null, outDefault='michael/reconstruction/advanced-state.json', prev=E(outDefault)?R(outDefault):{};
const V=['front','three','side','rear','top'];
function decode(f){const b=fs.readFileSync(f);if(/\.png$/i.test(f)){const p=PNG.sync.read(b);return{w:p.width,h:p.height,d:p.data}}const j=jpeg.decode(b,{useTArray:true,formatAsRGBA:true});return{w:j.width,h:j.height,d:j.data}}
function stat(f,z=64){const im=decode(f),a=[];let mean=0,vr=0,dark=0,bright=0,sat=0,edge=0;for(let y=0;y<z;y++)for(let x=0;x<z;x++){const sx=Math.min(im.w-1,Math.floor((x+.5)*im.w/z)),sy=Math.min(im.h-1,Math.floor((y+.5)*im.h/z)),i=(sy*im.w+sx)*4,r=im.d[i]/255,g=im.d[i+1]/255,b=im.d[i+2]/255,l=.2126*r+.7152*g+.0722*b;a.push(l);mean+=l;dark+=l<.18;bright+=l>.82;sat+=Math.max(r,g,b)-Math.min(r,g,b)}mean/=a.length;for(const l of a)vr+=(l-mean)**2;for(let y=0;y<z-1;y++)for(let x=0;x<z-1;x++){const k=y*z+x;edge+=Math.abs(a[k]-a[k+1])+Math.abs(a[k]-a[k+z])}return{file:f,aspect:N(im.w/im.h),mean:N(mean),contrast:N(Math.sqrt(vr/a.length)),edge:N(edge/((z-1)*(z-1))),dark:N(dark/a.length),bright:N(bright/a.length),saturation:N(sat/a.length)}}
function stats(dir){return Object.fromEntries(V.filter(v=>E(path.join(dir,v+'.png'))).map(v=>[v,stat(path.join(dir,v+'.png'))]))}
function latent(st){const f=V.flatMap(v=>{const x=st[v]||{};return[x.mean||0,x.contrast||0,x.edge||0,x.dark||0,x.bright||0,x.saturation||0]}),o=[];for(let i=0;i<cfg.implicitSurface.latentDimensions;i++){let z=0;for(let j=0;j<f.length;j++)z+=Math.sin((i+1)*(j+3)*1.618)*f[j];o.push(N(Math.tanh(z/Math.max(1,f.length)),5))}return o}
function coverage(){const m={};for(const p of owner.photos||[])for(const c of p.coverage||[])m[c]=(m[c]||0)+1;return m}
function uncertainty(){const cov=coverage(),debt=auto.visualDebt?.metrics||[],o=[];for(const [name,node] of Object.entries(scene.nodes)){const refs=cov[name]||cov[name.replace(/^front_/,'')]||0,views=node.views||[];let u=refs>=3?cfg.uncertainty.ownerMultiViewFloor:refs===1?cfg.uncertainty.singleViewFloor:cfg.uncertainty.generatedInferenceFloor;u=C(u+(debt.find(x=>x.metric===name)?.debt??.35)*.22-(views.length>=3?.05:0),.05,.95);o.push({component:name,uncertainty:N(u),ownerReferences:refs,views,protected:u<=cfg.uncertainty.protectBelow})}return o.sort((a,b)=>b.uncertainty-a.uncertainty)}
function optimizer(){const rel=new Set;for(const m of auto.visualDebt?.metrics?.slice(0,7)||[]){const n=scene.nodes[m.metric];for(const k of n?.parameters||[])rel.add(k)}const o=[];for(const k of rel){const b=genome.bounds?.[k],v=Number(genome.parameters?.[k]);if(!b||!Number.isFinite(v))continue;const span=b[1]-b[0],mid=(b[0]+b[1])/2,step=span*cfg.optimizer.learningRate*.25*(v<mid?1:-1);o.push({parameter:k,current:v,proposed:N(C(v+step,b[0],b[1])),expectedGain:N(Math.abs(step)/span*.12+.015),method:'bounded_coordinate_gradient_proxy'})}return o.sort((a,b)=>b.expectedGain-a.expectedGain).slice(0,cfg.optimizer.maxParametersPerCycle)}
function info(u){const d=Object.fromEntries((auto.visualDebt?.regions||[]).map(x=>[x.region,x.debt]));return u.map(x=>{const s=(auto.specialists||[]).find(z=>(z.components||[]).includes(x.component)),region=s?.region||auto.focusRegion||'unknown',cross=Math.min(1,(x.views?.length||0)/4),gain=cfg.informationGain.crossViewWeight*cross+cfg.informationGain.debtWeight*(d[region]??.25)+cfg.informationGain.uncertaintyWeight*x.uncertainty;return{component:x.component,region,informationGain:N(gain),uncertainty:x.uncertainty,views:x.views}}).sort((a,b)=>b.informationGain-a.informationGain)}
function critics(st){const a=Object.values(st),m=k=>a.reduce((s,x)=>s+(x[k]||0),0)/Math.max(1,a.length),e=m('edge'),c=m('contrast'),b=m('bright'),d=m('dark'),s=m('saturation'),adv=C(.90-Math.abs(e-.12)*1.9-Math.max(0,b-.16)*1.1-Math.max(0,.12-c)*1.3,0,1),photo=C(.42+c*.9+Math.min(.22,e)*.8+Math.min(.25,s)*.45-Math.max(0,b-.22)*.8-Math.max(0,d-.48)*.4,0,1);return{adversarial:{score:N(adv),pass:adv>=cfg.critics.minimumPass,attacks:['toy_like_proportions','fake_depth','lighting_mask','hidden_regression']},photorealism:{score:N(photo),pass:photo>=cfg.critics.minimumPass,geometryIndependent:true},combined:N(adv*cfg.critics.adversarialWeight+photo*cfg.critics.photorealismWeight)}}
function resolution(dir){const o={};for(const v of V){const f=path.join(dir,v+'.png');if(!E(f))continue;const b=stat(f,64),r=[];for(const q of cfg.crossResolution.scales){const x=stat(f,Math.max(12,Math.round(64*q))),diff=Math.abs(b.mean-x.mean)+Math.abs(b.contrast-x.contrast)+Math.abs(b.edge-x.edge),id=C(1-diff*3.2,0,1);r.push({scale:q,identity:N(id)})}o[v]={scores:r,minimum:N(Math.min(...r.map(x=>x.identity))),pass:r.every(x=>x.identity>=cfg.crossResolution.minimumIdentity)}}return o}
function surgery(u){return(auto.topologyQueue||[]).map(t=>{const ops=/grille|lamp|projector/.test(t.component)?['cut_region','local_recess','bevel']:/rear|diffuser|wing/.test(t.component)?['local_extrude','insert_loop','retopologize_local']:['insert_loop','local_extrude','weld'];return{component:t.component,priority:t.priority,uncertainty:u.find(x=>x.component===t.component)?.uncertainty??.6,operations:ops.slice(0,cfg.meshSurgery.maxOperationsPerCandidate),boundedBy:'semantic_component',status:'proposed',requiresTopologyGate:true}})}
function diversity(){const old=prev.diversity?.lineages||{},lineages={};for(const n of cfg.diversity.lineages){const x=old[n]||{generation:0,score:0};lineages[n]={...x,generation:x.generation+1,lastFocus:auto.focusRegion,objective:n}}return{lineages,synthesize:Object.values(lineages).some(x=>x.generation%cfg.diversity.synthesisInterval===0),minimumDistinct:cfg.diversity.minimumDistinctLineages}}
function negatives(){const text=JSON.stringify(memory),hist=JSON.stringify(auto.history||[]),tests=[['giant_rectangular_lamps','headlamp|projector'],['flat_rear_mass','rearMass|rear_body'],['grille_slab','grille'],['oversimplified_arches','arch|wheelFill'],['toy_like_materials','material|edgeDetail']],o=[];for(const [id,p] of tests){const re=new RegExp(p,'gi'),hits=(text.match(re)||[]).length+(hist.match(re)||[]).length;if(hits)o.push({id,hits,weight:cfg.replay.hardNegativeWeight,rule:'Avoid recurrence of '+id.replaceAll('_',' ')})}return o.sort((a,b)=>b.hits-a.hits).slice(0,cfg.replay.maxNegativeExamples)}
function calibration(){const db={...(prev.calibrationDatabase||{})};for(const m of auto.cameraSolve?.matches||[])db[m.file]={matchedView:m.matchedView,aspect:m.aspect,crop:'auto_fullframe',exposure:'owner_native',occlusion:'learned_mask',confidence:N(1-m.matchError),updatedAt:new Date().toISOString()};return db}
function introspect(u){const um=Object.fromEntries(u.map(x=>[x.component,x]));return Object.fromEntries(Object.entries(scene.nodes).map(([n,x])=>[n,{meshAuthority:x.authority||'unknown',ancestry:auto.componentAncestry?.[n]||null,parameters:x.parameters||[],ownerReferences:um[n]?.ownerReferences||0,confidence:N(1-(um[n]?.uncertainty??.6)),lastDecision:auto.componentLocks?.[n]?.locked?'LOCKED':'EVOLVING'}]))}
function governor(){const d=auto.visualDebt?.regions?.[0]?.debt??0,t=(auto.topologyQueue||[]).length;let mode='light_parameter';if(t>=cfg.resourceGovernor.topologyHeavyThreshold||d>=cfg.resourceGovernor.heavyDebtThreshold)mode='heavy_topology';else if(d>=cfg.resourceGovernor.lightDebtThreshold)mode='standard_multiview';return{mode,debt:N(d),topologyQueue:t}}
function convergence(){const a=(auto.history||[]).slice(-cfg.convergence.window).map(x=>x.worstDebt).filter(Number.isFinite),im=a.length>=2?a[0]-a[a.length-1]:1,stalled=a.length>=cfg.convergence.window&&im<cfg.convergence.minimumImprovement;return{window:a,improvement:N(im),stalled,cooldownCycles:stalled?cfg.convergence.cooldownCycles:0,action:stalled?'freeze_focus_and_rotate':'continue'}}
function gap(cr,res){const regs=auto.visualDebt?.regions||[],worst=regs[0]?.debt??.5,avg=regs.reduce((s,x)=>s+x.debt,0)/Math.max(1,regs.length),rv=Object.values(res).map(x=>x.minimum),lod=rv.length?rv.reduce((a,b)=>a+b,0)/rv.length:.8,signals={geometry:1-worst,proportions:1-avg,livery:1-(auto.visualDebt?.metrics?.find(x=>x.region==='materials_livery')?.debt??.35),materials:cr.photorealism.score,interiorFit:Number(keleb?.confidence??.7),temporal:.82,mobile:.84,photorealism:cr.photorealism.score,lodIdentity:lod};let score=0;for(const [k,w] of Object.entries(cfg.realityGap.weights))score+=(signals[k]??.7)*w;return{score:N(score),gap:N(1-score),signals:Object.fromEntries(Object.entries(signals).map(([k,v])=>[k,N(v)]))}}
function vocab(s){const existing=new Set(Object.keys(dsl.allowedPrimitives||{})),c={};for(const x of s)for(const op of x.operations)c[op]=(c[op]||0)+1;return Object.entries(c).filter(([n,k])=>k>=cfg.vocabularyExpansion.minimumRepeatedNeed&&!existing.has(n)).map(([n,k])=>({name:'bounded_'+n,derivedFrom:n,repeatedNeed:k,status:'isolation_test_required',autoActivate:false}))}
function synthetic(st){const o=[];for(const [a,b] of cfg.syntheticViews.pairs){if(!st[a]||!st[b])continue;for(const f of cfg.syntheticViews.fractions){const fields=['mean','contrast','edge','dark','bright','saturation'],jump=fields.reduce((s,k)=>s+Math.abs(st[a][k]-st[b][k]),0)/fields.length,cons=C(1-jump*1.7,0,1);o.push({from:a,to:b,fraction:f,consistency:N(cons),pass:cons>=cfg.syntheticViews.minimumConsistency})}}return o}
function benchmark(cr,res,g,u){const rv=Object.values(res).map(x=>x.minimum),lod=rv.length?rv.reduce((a,b)=>a+b,0)/rv.length:.8,ownerSimilarity=1-((auto.cameraSolve?.matches||[]).reduce((s,x)=>s+x.matchError,0)/Math.max(1,(auto.cameraSolve?.matches||[]).length)),dims={owner_similarity:C(ownerSimilarity,0,1),topology_correctness:C(1-(auto.topologyQueue?.length||0)*.08,0,1),geometry:g.signals.geometry,materials:g.signals.materials,photorealism:cr.photorealism.score,temporal:g.signals.temporal,mobile:g.signals.mobile,lod_identity:lod,causal_explainability:auto.causal?.summary?1:.5,protected_invariants:1,certainty:1-u.reduce((s,x)=>s+x.uncertainty,0)/Math.max(1,u.length)},score=cfg.benchmark.dimensions.reduce((s,k)=>s+(dims[k]??.7),0)/cfg.benchmark.dimensions.length;return{name:cfg.benchmark.name,score:N(score),minimumPromotionScore:cfg.benchmark.minimumPromotionScore,pass:score>=cfg.benchmark.minimumPromotionScore,dimensions:Object.fromEntries(Object.entries(dims).map(([k,v])=>[k,N(v)])),hash:crypto.createHash('sha256').update(JSON.stringify(dims)).digest('hex')}}
function run(dir,out=outDefault){const st=stats(dir),u=uncertainty(),cr=critics(st),res=resolution(dir),sg=surgery(u),g=gap(cr,res),b=benchmark(cr,res,g,u),result={schema:1,generatedAt:new Date().toISOString(),engine:'NICKELLE_ADVANCED_GRAPHICS_INTELLIGENCE',upgrades:{differentiableStyleOptimizer:true,neuralImplicitBodyRepresentation:true,perComponentVertexUncertainty:true,informationGainScheduler:true,adversarialVisualCritic:true,separatePhotorealismCritic:true,crossResolutionIdentity:true,componentDependencyGraph:true,automaticMeshSurgery:true,longTermEvolutionaryDiversity:true,visualRegressionReplay:true,ownerPhotoCalibrationDatabase:true,liveRenderIntrospection:true,resourceGovernor:true,convergenceDetector:true,realityGapScore:true,selfExpandingTopologyVocabulary:true,syntheticViewGenerator:true,separateDamageWearLayer:true,michaelGraphicsBenchmark:true},optimizer:{method:cfg.optimizer.type,targets:optimizer()},implicitSurface:{representation:cfg.implicitSurface.representation,latent:latent(st),gridResolution:cfg.implicitSurface.gridResolution,target:cfg.implicitSurface.meshingTarget},uncertainty:u,informationGain:info(u),critics:cr,crossResolution:res,dependencies:{focusRegion:auto.focusRegion,assembly:cfg.dependencyGraph[auto.focusRegion]||[],mode:'constrained_assembly'},meshSurgery:sg,diversity:diversity(),replayNegatives:negatives(),calibrationDatabase:calibration(),introspection:introspect(u),resourceGovernor:governor(),convergence:convergence(),realityGap:g,vocabularyExpansion:vocab(sg),syntheticViews:synthetic(st),wearLayer:{canonicalGeometry:'clean_owner_truth',separateRuntimeLayer:true,enabled:false,classes:cfg.wearLayer.classes,policy:'wear never trains canonical geometry'},benchmark:b,parentAutonomyGeneratedAt:auto.generatedAt};S(out,result);console.log(JSON.stringify({advancedUpgrades:Object.values(result.upgrades).filter(Boolean).length,benchmark:b.score,realityGap:g.gap,resourceMode:result.resourceGovernor.mode,optimizerTargets:result.optimizer.targets.length,meshSurgery:sg.length,vocabularyProposals:result.vocabularyExpansion.length},null,2))}
const [cmd,dir='/tmp/michael-autonomy-baseline',out=outDefault]=process.argv.slice(2);if(cmd!=='run')throw Error('usage: nickelle_advanced_graphics_intelligence.mjs run RENDER_DIR [OUT]');run(dir,out);
