import fs from 'node:fs';
import path from 'node:path';
import { pipeline, env } from '@huggingface/transformers';

const VIEWS=['front','three','side','rear','top'];
const SEG_MODEL=process.env.NICKELLE_SEG_MODEL||'Xenova/segformer-b5-finetuned-ade-640-640';
const DEPTH_MODEL=process.env.NICKELLE_DEPTH_MODEL||'onnx-community/depth-anything-v2-base';
env.cacheDir=process.env.HF_HOME||'.cache/huggingface';
process.on('unhandledRejection',e=>{console.error(e);process.exit(1)});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const std=a=>{const m=mean(a);return Math.sqrt(mean(a.map(v=>(v-m)*(v-m))))};
const quantile=(a,q)=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),i=Math.min(b.length-1,Math.max(0,Math.floor(q*(b.length-1))));return b[i]};
function maskCoverage(mask){const d=mask?.data||mask;if(!d?.length)return 0;let n=0;for(const v of d)if(v>0)n++;return n/d.length}
function depthStats(depth){const d=depth?.data||[];if(!d.length)return{mean:0,std:0,q10:0,q50:0,q90:0,range:0,edge:0};const vals=Array.from(d,Number),w=depth.width||Math.round(Math.sqrt(vals.length)),h=depth.height||Math.floor(vals.length/w);let edge=0,c=0;for(let y=0;y<h-1;y+=2)for(let x=0;x<w-1;x+=2){const i=y*w+x,a=vals[i];edge+=Math.abs(a-vals[i+1])+Math.abs(a-vals[i+w]);c+=2}const q10=quantile(vals,.1),q50=quantile(vals,.5),q90=quantile(vals,.9);return{mean:mean(vals),std:std(vals),q10,q50,q90,range:q90-q10,edge:c?edge/c:0}}
function groupSegments(out){const groups={vehicle:0,road:0,structure:0,vegetation:0,sky:0,other:0},labels={};for(const s of out||[]){const label=String(s.label||'unknown').toLowerCase(),coverage=maskCoverage(s.mask);labels[label]=(labels[label]||0)+coverage;if(/car|truck|bus|van|vehicle|motorcycle|bicycle/.test(label))groups.vehicle+=coverage;else if(/road|sidewalk|floor|earth|ground|grass|field/.test(label))groups.road+=coverage;else if(/building|wall|fence|rail|bridge|ceiling/.test(label))groups.structure+=coverage;else if(/tree|plant|vegetation|flower/.test(label))groups.vegetation+=coverage;else if(/sky/.test(label))groups.sky+=coverage;else groups.other+=coverage}return{groups,labels}}
async function analyze(dir,outFile){const started=Date.now();const segmenter=await pipeline('image-segmentation',SEG_MODEL,{dtype:'q8'}),depth=await pipeline('depth-estimation',DEPTH_MODEL,{dtype:'q8'}),views={};for(const view of VIEWS){const file=path.resolve(dir,`${view}.png`),seg=await segmenter(file),dep=await depth(file);views[view]={segmentation:groupSegments(seg),depth:depthStats(dep.depth)}}const vehicle=VIEWS.map(v=>views[v].segmentation.groups.vehicle),ranges=VIEWS.map(v=>views[v].depth.range),edges=VIEWS.map(v=>views[v].depth.edge);const result={schema:1,engine:'NICKELLE_HEAVY_VISION',segmentationModel:SEG_MODEL,depthModel:DEPTH_MODEL,views,summary:{vehicleCoverage:mean(vehicle),vehicleCoverageSpread:std(vehicle),depthRange:mean(ranges),depthEdge:mean(edges),consistency:clamp(1-std(vehicle)/.18,0,1),runtimeSeconds:(Date.now()-started)/1000},heavyweight:true};fs.writeFileSync(outFile,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.summary,null,2))}
function compare(aFile,bFile,outFile){const a=JSON.parse(fs.readFileSync(aFile,'utf8')),b=JSON.parse(fs.readFileSync(bFile,'utf8')),perView={};let penalties=0,improvements=0;for(const v of VIEWS){const A=a.views[v],B=b.views[v],vehicleDelta=B.segmentation.groups.vehicle-A.segmentation.groups.vehicle,edgeDelta=B.depth.edge-A.depth.edge,rangeDelta=B.depth.range-A.depth.range;perView[v]={vehicleDelta,depthEdgeDelta:edgeDelta,depthRangeDelta:rangeDelta};if(vehicleDelta<-.045)penalties+=Math.abs(vehicleDelta)*18;if(edgeDelta<-.035)penalties+=Math.abs(edgeDelta)*8;if(rangeDelta<-.08)penalties+=Math.abs(rangeDelta)*4;if(vehicleDelta>0)improvements+=vehicleDelta*6;if(edgeDelta>0)improvements+=edgeDelta*2}const consistencyDelta=b.summary.consistency-a.summary.consistency;if(consistencyDelta<-.08)penalties+=Math.abs(consistencyDelta)*5;else improvements+=Math.max(0,consistencyDelta)*2;const scoreDelta=improvements-penalties,pass=penalties<1.25&&scoreDelta>-.35,result={schema:1,engine:'NICKELLE_HEAVY_VISION',pass,scoreDelta,penalties,improvements,consistencyDelta,perView,baseline:a.summary,candidate:b.summary,models:{segmentation:a.segmentationModel,depth:a.depthModel}};fs.writeFileSync(outFile,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2))}
const [mode,...args]=process.argv.slice(2);if(mode==='analyze')await analyze(args[0],args[1]||'/tmp/nickelle-heavy.json');else if(mode==='compare')compare(args[0],args[1],args[2]||'/tmp/nickelle-heavy-verdict.json');else throw Error('usage: nickelle_heavy_vision.mjs analyze RENDER_DIR OUT | compare BASE_JSON CAND_JSON OUT');
