import fs from 'node:fs';
import path from 'node:path';
import {PNG} from 'pngjs';

const MODEL='nickelle/neural-model.json';
const VIEWS=['front','three','side','rear','top'];
const OUT=['grille','grilleSpan','sideSilhouette','threeSilhouette','sideDark','wheelFill','roofWhite','liveryYellow','edgeDetail','projectorShape','frontSymmetry','rearMass','total'];
const sigmoid=x=>1/(1+Math.exp(-Math.max(-20,Math.min(20,x))));
const lcg=()=>{let s=0x4e49434b;return()=>((s=(1664525*s+1013904223)>>>0)/4294967296-.5)};
function init(m){if(m.weights)return m;const rnd=lcg(),I=m.architecture.inputSize,H=m.architecture.hidden,O=OUT.length,scale=.045;m.weights={w1:Array.from({length:H},()=>Array.from({length:I},()=>rnd()*scale)),b1:Array(H).fill(0),w2:Array.from({length:O},()=>Array.from({length:H},()=>rnd()*scale)),b2:Array(O).fill(0)};return m}
function pixels(file){const p=PNG.sync.read(fs.readFileSync(file)),d=p.data,W=p.width,H=p.height,a=[];for(let gy=0;gy<8;gy++)for(let gx=0;gx<8;gx++){let r=0,g=0,b=0,n=0;const x0=Math.floor(gx*W/8),x1=Math.floor((gx+1)*W/8),y0=Math.floor(gy*H/8),y1=Math.floor((gy+1)*H/8);for(let y=y0;y<y1;y+=Math.max(1,Math.floor((y1-y0)/6)))for(let x=x0;x<x1;x+=Math.max(1,Math.floor((x1-x0)/6))){const i=(y*W+x)*4;r+=d[i];g+=d[i+1];b+=d[i+2];n++}a.push(r/(255*n),g/(255*n),b/(255*n))}return a}
function features(dir){return VIEWS.flatMap(v=>pixels(path.join(dir,`${v}.png`)))}
function forward(m,x){m=init(m);const {w1,b1,w2,b2}=m.weights,h=w1.map((row,j)=>Math.tanh(row.reduce((s,w,i)=>s+w*x[i],b1[j]))),y=w2.map((row,j)=>sigmoid(row.reduce((s,w,i)=>s+w*h[i],b2[j]))*100);return{h,y}}
function predict(m,dir){const x=features(dir),f=forward(m,x),scores=Object.fromEntries(OUT.map((k,i)=>[k,Math.round(f.y[i]*1000)/1000]));return{scores,confidence:m.training.confidence||0,samples:m.training.samples||0,version:m.version||'NV1'}}
function targetFrom(side){const p=side?.parts||{},a=OUT.slice(0,-1).map(k=>Number.isFinite(p[k])?p[k]:50),total=Number.isFinite(side?.score)?side.score:(Number.isFinite(side?.candidateScore)?side.candidateScore:50);return[...a,total]}
function trainOne(m,x,t,lr=.0025){const {w1,b1,w2,b2}=m.weights,{h,y}=forward(m,x),O=OUT.length,H=h.length,I=x.length,do2=Array(O);let loss=0;for(let o=0;o<O;o++){const yn=y[o]/100,tn=t[o]/100,e=yn-tn;loss+=e*e;do2[o]=2*e*yn*(1-yn)/O}const dh=Array(H).fill(0);for(let o=0;o<O;o++)for(let j=0;j<H;j++)dh[j]+=do2[o]*w2[o][j];for(let o=0;o<O;o++){for(let j=0;j<H;j++)w2[o][j]-=lr*do2[o]*h[j];b2[o]-=lr*do2[o]}for(let j=0;j<H;j++){const dz=dh[j]*(1-h[j]*h[j]);for(let i=0;i<I;i++)w1[j][i]-=lr*dz*x[i];b1[j]-=lr*dz}return loss/O}
function save(m,p=MODEL){fs.writeFileSync(p,JSON.stringify(m)+'\n')}
function train(base,cand,verdictPath,decisionPath,out=MODEL){let m=init(JSON.parse(fs.readFileSync(MODEL,'utf8'))),v=JSON.parse(fs.readFileSync(verdictPath,'utf8')),d=JSON.parse(fs.readFileSync(decisionPath,'utf8'));const entries=[{x:features(base),t:targetFrom(v.baseline)},{x:features(cand),t:targetFrom(v.candidate)}];for(const e of entries)m.replay.push(e);m.replay=m.replay.slice(-(m.training.maxReplay||40));let loss=0,steps=0;for(let ep=0;ep<18;ep++)for(const e of m.replay){loss+=trainOne(m,e.x,e.t);steps++}loss/=Math.max(1,steps);m.training.samples=m.replay.length;m.training.cycles=(m.training.cycles||0)+1;m.training.lastLoss=loss;m.training.lastDecision=!!d.promote?'PROMOTE':'REJECT';m.training.confidence=Math.max(0,Math.min(.92,(m.training.samples/24)*Math.max(0,1-Math.sqrt(loss)*1.8)));m.training.updatedAt=new Date().toISOString();save(m,out);console.log(JSON.stringify({neural:'trained',samples:m.training.samples,loss,confidence:m.training.confidence},null,2))}
function compare(base,cand,out){const m=init(JSON.parse(fs.readFileSync(MODEL,'utf8'))),a=predict(m,base),b=predict(m,cand),gain=b.scores.total-a.scores.total,res={baselineScore:a.scores.total,candidateScore:b.scores.total,gain,baseline:a,candidate:b,confidence:Math.min(a.confidence,b.confidence),samples:m.training.samples||0,neuralVision:true};fs.writeFileSync(out,JSON.stringify(res,null,2)+'\n');console.log(JSON.stringify(res,null,2))}
const [mode,...a]=process.argv.slice(2);if(mode==='predict'){const m=init(JSON.parse(fs.readFileSync(MODEL,'utf8'))),r=predict(m,a[0]);fs.writeFileSync(a[1]||'/tmp/nickelle-neural.json',JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify(r,null,2))}else if(mode==='compare')compare(a[0],a[1],a[2]||'/tmp/nickelle-neural-verdict.json');else if(mode==='train')train(a[0],a[1],a[2],a[3],a[4]||MODEL);else throw Error('usage: nickelle_neural_vision.mjs predict DIR OUT | compare BASE CAND OUT | train BASE CAND INTERNAL_VERDICT DECISION [MODEL]');
