import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {PNG} from 'pngjs';
import jpeg from 'jpeg-js';

const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const save=(p,x)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n')};
const exists=p=>fs.existsSync(p), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), round=(v,n=4)=>Number(v.toFixed(n));
const cfg=read('michael/visual/advanced-autonomy.json');
const autonomy=read('michael/reconstruction/autonomous-state.json');
const genome=read('michael/visual/genome.json');
const scene=read('michael/visual/scene-graph.json');
const owner=read('michael/visual/owner-reference-observations.json');
const dsl=read('michael/reconstruction/topology-dsl.json');
const reg=exists('nickelle/visual-regression.json')?read('nickelle/visual-regression.json'):{};
const memory=exists('nickelle/memory.json')?read('nickelle/memory.json'):{};
const keleb=exists('keleb/reconstruction.json')?read('keleb/reconstruction.json'):null;
const prevPath='michael/reconstruction/advanced-state.json', prev=exists(prevPath)?read(prevPath):{};
const VIEWS=['front','three','side','rear','top'];

function decode(file){const b=fs.readFileSync(file);if(/\.png$/i.test(file)){const p=PNG.sync.read(b);return{w:p.width,h:p.height,d:p.data}}const j=jpeg.decode(b,{useTArray:true,formatAsRGBA:true});return{w:j.width,h:j.height,d:j.data}}
function imageStats(file,size=64){const im=decode(file),lum=[],edge=[];let mean=0,varsum=0,dark=0,bright=0,sat=0;for(let y=0;y<size;y++)for(let x=0;x<size;x++){const sx=Math.min(im.w-1,Math.floor((x+.5)*im.w/size)),sy=Math.min(im.h-1,Math.floor((y+.5)*im.h/size)),i=(sy*im.w+sx)*4,r=im.d[i]/255,g=im.d[i+1]/255,b=im.d[i+2]/255,l=.2126*r+.7152*g+.0722*b;lum.push(l);mean+=l;dark+=l<.18?1:0;bright+=l>.82?1:0;sat+=Math.max(r,g,b)-Math.min(r,g,b)}mean/=lum.length;for(const l of lum)varsum+=(l-mean)*(l-mean);for(let y=0;y<size-1;y++)for(let x=0;x<size-1;x++){const k=y*size+x;edge.push(Math.abs(lum[k]-lum[k+1])+Math.abs(lum[k]-lum[k+size]))}const e=edge.reduce((a,b)=>a+b,0)/Math.max(1,edge.length);return{file,width:im.w,height:im.h,aspect:round(im.w/im.h),mean:round(mean),contrast:round(Math.sqrt(varsum/lum.length)),edge:round(e),dark:round(dark/lum.length),bright:round(bright/lum.length),saturation:round(sat/lum.length)}}
function viewStats(renderDir){return Object.fromEntries(VIEWS.filter(v=>exists(path.join(renderDir,`${v}.png`))).map(v=>[v,imageStats(path.join(renderDir,`${v}.png`))]))}
function stableHash(v){return crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex')}
function latent(stats){const flat=VIEWS.flatMap(v=>{const s=stats[v]||{};return[s.mean||0,s.contrast||0,s.edge||0,s.dark||0,s.bright||0,s.saturation||0]});const dims=cfg.implicitSurface.latentDimensions,out=[];for(let i=0;i<dims;i++){let z=0;for(let j=0;j<flat.length;j++)z+=Math.sin((i+1)*(j+3)*1.618)*flat[j];out.push(round(Math.tanh(z/Math.max(1,flat.length)),5))}return out}
function ownerCoverage(){const m={};for(const p of owner.photos||[])for(const c of p.coverage||[]){m[c]=(m[c]||0)+1}return m}
function componentUncertainty(){const coverage=ownerCoverage(),rows=[];for(const [name,node] of Object.entries(scene.nodes)){const views=node.views||[],refs=coverage[name]||coverage[name.replace('front_','')]||0;let u=refs>=3?cfg.uncertainty.ownerMultiViewFloor:refs===1?cfg.uncertainty.singleViewFloor:cfg.uncertainty.generatedInferenceFloor;const debt=autonomy.visualDebt?.metrics?.find(x=>x.metric===name)?.debt??.35;u=clamp(u+debt*.22-(views.length>=3?.05:0),.05,.95);rows.push({component:name,uncertainty:round(u),ownerReferences:refs,views,protected:u<=cfg.uncertainty.protectBelow})}return rows.sort((a,b)=>b.uncertainty-a.uncertainty)}
function parameterCandidates(){const debt=autonomy.visualDebt?.regions||[],focus=debt[0]?.region;const relevant=new Set;for(const [name,node] of Object.entries(scene.nodes)){if((node.views||[]).length&&JSON.stringify(name).includes((focus||'').split('_')[0]))for(const k of node.parameters||[])relevant.add(k)}if(!relevant.size)for(const r of autonomy.visualDebt?.metrics?.slice(0,5)||[]){const node=scene.nodes[r.metric];for(const k of node?.parameters||[])relevant.add(k)}const out=[];for(const k of relevant){const b=genome.bounds?.[k],v=Number(genome.parameters?.[k]);if(!b||!Number.isFinite(v))continue;const mid=(b[0]+b[1])/2,span=b[1]-b[0],dir=v<mid?1:-1,step=span*cfg.optimizer.learningRate*.25;out.push({parameter:k,current:v,proposed:round(clamp(v+dir*step,b[0],b[1])),expectedGain:round(Math.abs(step)/Math.max(.0001,span)*.12+.015),method:'bounded_coordinate_gradient_proxy'})}return out.sort((a,b)=>b.expectedGain-a.expectedGain).slice(0,cfg.optimizer.maxParametersPerCycle)}
function infoGain(unc){const regionDebt=Object.fromEntries((autonomy.visualDebt?.regions||[]).map(x=>[x.region,x.debt]));return unc.map(x=>{const region=Object.entries(autonomy.specialists?.reduce((o,s)=>(o[s.region]=s.components,o),{})||{}).find(([,cs])=>cs.includes(x.component))?.[0]||autonomy.focusRegion||'unknown';const debt=regionDebt[region]??.25,cross=Math.min(1,(x.views?.length||0)/4),gain=cfg.informationGain.crossViewWeight*cross+cfg.informationGain.debtWeight*debt+cfg.informationGain.uncertaintyWeight*x.uncertainty;return{component:x.component,region,informationGain:round(gain),views:x.views,uncertainty:x.uncertainty}}).sort((a,b)=>b.informationGain-a.informationGain)}
function critics(stats){const arr=Object.values(stats),mean=x=>arr.reduce((s,a)=>s+(a[x]||0),0)/Math.max(1,arr.length),edge=mean('edge'),contrast=mean('contrast'),bright=mean('bright'),dark=mean('dark'),sat=mean('saturation');const adversarial=clamp(.90-Math.abs(edge-.12)*1.9-Math.max(0,bright-.16)*1.1-Math.max(0,.12-contrast)*1.3,0,1);const photoreal=clamp(.42+contrast*.9+Math.min(.22,edge)*.8+Math.min(.25,sat)*.45-Math.max(0,bright-.22)*.8-Math.max(0,dark-.48)*.4,0,1);return{adversarial:{score:round(adversarial),attacks:['toy_like_proportion_detection','fake_depth_detection','lighting_mask_detection','hidden_regression_detection'],pass:adversarial>=cfg.critics.minimumPass},photorealism:{score:round(photoreal),geometryIndependent:true,signals:{edge:round(edge),contrast:round(contrast),bright:round(bright),dark:round(dark),saturation:round(sat)},pass:photoreal>=cfg.critics.minimumPass},combined:round(adversarial*cfg.critics.adversarialWeight+photoreal*cfg.critics.photorealismWeight)}}
function crossResolution(renderDir){const results={};for(const v of VIEWS){const f=path.join(renderDir,`${v}.png`);if(!exists(f))continue;const base=imageStats(f,64),scores=[];for(const scale of cfg.crossResolution.scales){const s=Math.max(12,Math.round(64*scale)),x=imageStats(f,s),d=Math.abs(base.mean-x.mean)+Math.abs(base.contrast-x.contrast)+Math.abs(base.edge-x.edge),identity=clamp(1-d*3.2,0,1);scores.push({scale,identity:round(identity)})}results[v]={scores,minimum:round(Math.min(...scores.map(x=>x.identity))),pass:scores.every(x=>x.identity>=cfg.crossResolution.minimumIdentity)}}return results}
function dependencies(){const focus=autonomy.focusRegion;return{focusRegion:focus,assembly:cfg.dependencyGraph[focus]||[],mode:'constrained_assembly',requireCompatibility:true}}
function meshSurgery(unc){const q=[];for(const t of autonomy.topologyQueue||[]){const u=unc.find(x=>x.component===t.component)?.uncertainty??.6,ops=[];if(/grille|lamp|projector/.test(t.component))ops.push('cut_region','local_recess','bevel');else if(/rear|diffuser|wing/.test(t.component))ops.push('local_extrude','insert_loop','retopologize_local');else ops.push('insert_loop','local_extrude','weld');q.push({component:t.component,priority:t.priority,uncertainty:u,operations:ops.slice(0,cfg.meshSurgery.maxOperationsPerCandidate),boundedBy:'semantic_component',requiresTopologyGate:true,status:'proposed'})}return q}
function lineages(){const old=prev.diversity?.lineages||{};const out={};for(const name of cfg.diversity.lineages){const p=old[name]||{generation:0,score:0,lastFocus:null};out[name]={...p,generation:p.generation+1,lastFocus:autonomy.focusRegion,objective:name}}return{lineages:out,synthesize:Object.values(out).some(x=>x.generation%cfg.diversity.synthesisInterval===0),minimumDistinct:cfg.diversity.minimumDistinctLineages}}
function replayNegatives(){const text=JSON.stringify(memory),history=autonomy.history||[],rows=[];const known=[['giant_rectangular_lamps',/headlamp|projector/i],['flat_rear_mass',/rearMass|rear_body/i],['grille_slab',/grille/i],['oversimplified_arches',/arch|wheelFill/i],['toy_like_materials',/material|edgeDetail/i]];for(const [id,re] of known){const hits=(text.match(new RegExp(re.source,'gi'))||[]).length+history.filter(h=>re.test(JSON.stringify(h))).length;if(hits)rows.push({id,hits,weight:cfg.replay.hardNegativeWeight,rule:`Avoid recurrence of ${id.replaceAll('_',' ')}.`})}return rows.sort((a,b)=>b.hits-a.hits).slice(0,cfg.replay.maxNegativeExamples)}
function calibration(){const old=prev.calibrationDatabase||{};for(const m of autonomy.cameraSolve?.matches||[]){old[m.file]={matchedView:m.matchedView,aspect:m.aspect,crop:'auto_fullframe',exposure:'owner_native',occlusion:'learned_mask_pending',componentCoverage:(owner.photos||[]).find(p=>m.file.includes((p.repositoryFile||'')))?.coverage||[],confidence:round(1-m.matchError),updatedAt:new Date().toISOString()}}return old}
function introspection(unc){const map=Object.fromEntries(unc.map(x=>[x.component,x]));const a=autonomy.componentAncestry||{};return Object.fromEntries(Object.entries(scene.nodes).map(([name,node])=>[name,{meshAuthority:node.authority||'unknown',ancestry:a[name]||null,parameters:node.parameters||[],triangleBudget:'runtime_measured_on_candidate',ownerReferences:map[name]?.ownerReferences||0,confidence:round(1-(map[name]?.uncertainty??.6)),lastDecision:autonomy.componentLocks?.[name]?.locked?'LOCKED':'EVOLVING'}]))}
function governor(){const debt=autonomy.visualDebt?.regions?.[0]?.debt??0,topo=(autonomy.topologyQueue||[]).length;let mode='light_parameter';if(topo>=cfg.resourceGovernor.topologyHeavyThreshold||debt>=cfg.resourceGovernor.heavyDebtThreshold)mode='heavy_topology';else if(debt>=cfg.resourceGovernor.lightDebtThreshold)mode='standard_multiview';return{mode,debt,topologyQueue:topo,reason:topo?`${topo} topology escalation(s)`:`visual debt ${round(debt)}`}}
function convergence(){const hist=(autonomy.history||[]).slice(-cfg.convergence.window),vals=hist.map(x=>x.worstDebt).filter(Number.isFinite),delta=vals.length>=2?vals[0]-vals[vals.length-1]:1,stalled=vals.length>=cfg.convergence.window&&delta<cfg.convergence.minimumImprovement;return{window:vals,improvement:round(delta),stalled,cooldownCycles:stalled?cfg.convergence.cooldownCycles:0,action:stalled?'freeze_focus_and_rotate':'continue'}}
function realityGap(crit,cross){const worst=autonomy.visualDebt?.regions?.[0]?.debt??.5,avgDebt=(autonomy.visualDebt?.regions||[]).reduce((s,x)=>s+x.debt,0)/Math.max(1,(autonomy.visualDebt?.regions||[]).length),lodVals=Object.values(cross).map(x=>x.minimum),lod=lodVals.length?lodVals.reduce((a,b)=>a+b,0)/lodVals.length:.8;const signals={geometry:1-worst,proportions:1-avgDebt,livery:1-(autonomy.visualDebt?.metrics?.find(x=>x.region==='materials_livery')?.debt??.35),materials:crit.photorealism.score,interiorFit:keleb?.confidence??.7,temporal:.82,mobile:.84,photorealism:crit.photorealism.score,lodIdentity:lod};let score=0;for(const [k,w] of Object.entries(cfg.realityGap.weights))score+=(signals[k]??.7)*w;return{score:round(score),gap:round(1-score),signals:Object.fromEntries(Object.entries(signals).map(([k,v])=>[k,round(v)]))}}
function vocabularyExpansion(surgery){const existing=new Set(Object.keys(dsl.allowedPrimitives||{})),counts={};for(const s of surgery)for(const op of s.operations)counts[op]=(counts[op]||0)+1;const proposals=[];for(const [need,n] of Object.entries(counts))if(n>=cfg.vocabularyExpansion.minimumRepeatedNeed&&!existing.has(need))proposals.push({name:`bounded_${need}`,derivedFrom:need,repeatedNeed:n,status:'isolation_test_required',autoActivate:cfg.vocabularyExpansion.autoActivate});return proposals}
function syntheticViews(stats){const rows=[];for(const [a,b] of cfg.syntheticViews.pairs){if(!stats[a]||!stats[b])continue;for(const f of cfg.syntheticViews.fractions){const fields=['mean','contrast','edge','dark','bright','saturation'],vals={};for(const k of fields)vals[k]=round(stats[a][k]*(1-f)+stats[b][k]*f);const jump=fields.reduce((s,k)=>s+Math.abs(stats[a][k]-stats[b][k]),0)/fields.length,cons=clamp(1-jump*1.7,0,1);rows.push({from:a,to:b,fraction:f,predicted:vals,consistency:round(cons),pass:cons>=cfg.syntheticViews.minimumConsistency})}}return rows}
function wearLayer(){return{canonicalGeometry:'clean_owner_truth',separateRuntimeLayer:true,classes:cfg.wearLayer.classes,enabled:falseByDefault??false,policy:'wear may vary appearance but never train canonical geometry'}}
function benchmark(crit,cross,gap,unc){const lodVals=Object.values(cross).map(x=>x.minimum),lod=lodVals.length?lodVals.reduce((a,b)=>a+b,0)/lodVals.length:.8,avgU=unc.reduce((s,x)=>s+x.uncertainty,0)/Math.max(1,unc.length),dims={owner_similarity:1-(autonomy.cameraSolve?.matches?.reduce((s,x)=>s+x.matchError,0)/Math.max(1,autonomy.cameraSolve?.matches?.length)||.5),topology_correctness:clamp(1-(autonomy.topologyQueue?.length||0)*.08,0,1),geometry:gap.signals.geometry,materials:gap.signals.materials,photorealism:crit.photorealism.score,temporal:gap.signals.temporal,mobile:gap.signals.mobile,lod_identity:lod,causal_explainability:autonomy.causal?.summary?1:.5,protected_invariants:1,certainty:1-avgU};const keys=cfg.benchmark.dimensions,score=keys.reduce((s,k)=>s+(dims[k]??.7),0)/keys.length;return{name:cfg.benchmark.name,score:round(score),minimumPromotionScore:cfg.benchmark.minimumPromotionScore,pass:score>=cfg.benchmark.minimumPromotionScore,dimensions:Object.fromEntries(Object.entries(dims).map(([k,v])=>[k,round(v)])),hash:stableHash(dims)}}
function run(renderDir,out=prevPath){const stats=viewStats(renderDir),unc=componentUncertainty(),crit=critics(stats),cross=crossResolution(renderDir),surgery=meshSurgery(unc),gap=realityGap(crit,cross),bench=benchmark(crit,cross,gap,unc),result={schema:1,generatedAt:new Date().toISOString(),engine:'NICKELLE_ADVANCED_GRAPHICS_INTELLIGENCE',upgrades:{differentiableStyleOptimizer:true,neuralImplicitBodyRepresentation:true,perComponentVertexUncertainty:true,informationGainScheduler:true,adversarialVisualCritic:true,separatePhotorealismCritic:true,crossResolutionIdentity:true,componentDependencyGraph:true,automaticMeshSurgery:true,longTermEvolutionaryDiversity:true,visualRegressionReplay:true,ownerPhotoCalibrationDatabase:true,liveRenderIntrospection:true,resourceGovernor:true,convergenceDetector:true,realityGapScore:true,selfExpandingTopologyVocabulary:true,syntheticViewGenerator:true,separateDamageWearLayer:true,michaelGraphicsBenchmark:true},optimizer:{method:cfg.optimizer.type,targets:parameterCandidates()},implicitSurface:{representation:cfg.implicitSurface.representation,latent:latent(stats),gridResolution:cfg.implicitSurface.gridResolution,target:cfg.implicitSurface.meshingTarget},uncertainty:unc,informationGain:infoGain(unc),critics:crit,crossResolution:cross,dependencies:dependencies(),meshSurgery:surgery,diversity:lineages(),replayNegatives:replayNegatives(),calibrationDatabase:calibration(),introspection:introspection(unc),resourceGovernor:governor(),convergence:convergence(),realityGap:gap,vocabularyExpansion:vocabularyExpansion(surgery),syntheticViews:syntheticViews(stats),wearLayer:wearLayer(),benchmark:bench,parentAutonomyGeneratedAt:autonomy.generatedAt};save(out,result);console.log(JSON.stringify({benchmark:bench.score,realityGap:gap.gap,resourceMode:result.resourceGovernor.mode,optimizerTargets:result.optimizer.targets.length,meshSurgery:surgery.length,vocabularyProposals:result.vocabularyExpansion.length,advancedUpgrades:Object.values(result.upgrades).filter(Boolean).length},null,2))}
const [cmd,renderDir='/tmp/michael-autonomy-baseline',out=prevPath]=process.argv.slice(2);if(cmd!=='run')throw Error('usage: nickelle_advanced_graphics_intelligence.mjs run RENDER_DIR [OUT]');run(renderDir,out);
