import fs from 'node:fs';
import path from 'node:path';
const genome=JSON.parse(fs.readFileSync('michael/visual/genome.json','utf8')),research=fs.existsSync('nickelle/research/constraints.json')?JSON.parse(fs.readFileSync('nickelle/research/constraints.json','utf8')):{},direct=fs.existsSync('nickelle/research/direct-evidence.json')?JSON.parse(fs.readFileSync('nickelle/research/direct-evidence.json','utf8')):{},director=fs.existsSync('michael/reconstruction/current.json')?JSON.parse(fs.readFileSync('michael/reconstruction/current.json','utf8')):{},ownerRefs=JSON.parse(fs.readFileSync('michael/visual/owner-reference-observations.json','utf8')),ref=JSON.parse(fs.readFileSync('michael/visual/reference-metrics.json','utf8')),owner=JSON.parse(fs.readFileSync('michael/visual/owner-truth.json','utf8')),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=v=>Math.round(v*10000)/10000,P=genome.parameters,B=genome.bounds;
const aliases={headlights:['front_left_lamp_housing','front_right_lamp_housing','front_left_projector','front_right_projector','front_left_drl','front_right_drl','projector_left','projector_right'],grille:['front_grille'],arches:['front_arch_left','front_arch_right','front_arches','wheel_fl','wheel_fr'],roof_scoop:['roof_scoop'],rear_wing:['rear_wing','rear_diffuser','diffuser']},ownerAlias={headlights:'headlights',grille:'grille',arches:'arches',roof_scoop:'roof_scoop',rear_wing:'rear_wing'};
function evidenceScore(group){let s=0,n=0,refs=0;const ids=new Set;for(const k of aliases[group]||[]){const x=research.componentConstraints?.[k];if(x){n++;s+=Number(x.confidence||0);for(const z of x.directVisualReferences||[]){refs++;if(z.evidenceId)ids.add(z.evidenceId)}}for(const id of direct.componentEvidence?.[k]||[])ids.add(id)}const d=director.componentPlan?.find(x=>x.component===group),o=ownerRefs.componentAuthority?.[ownerAlias[group]];const confidence=Math.max(Number(o?.confidence||0),n?s/n:0,Number(d?.evidence?.confidence||0),ids.size?Math.min(.92,.32+ids.size*.025):0);return{confidence:round(confidence),references:Math.max(refs,ids.size,Number(d?.evidence?.references||0),o?.photoIds?.length||0),uniqueDirectReferences:Math.max(ids.size,Number(d?.evidence?.uniqueDirectReferences||0)),ownerPhotoReferences:o?.photoIds||[],ownerPrimary:!!o}}
function step(k,dir,scale=1){const [lo,hi]=B[k],cur=P[k],span=hi-lo,max=span*(genome.maxStepFraction||.18)*scale;return round(clamp(cur+dir*max,lo,hi))}
function proposal(group,variant,params,why){return{schema:6,mode:'component_reconstruction',component:group,variant,candidateParameters:{...params},diagnosis:[`Nickelle owner-photo component reconstruction: ${group} / ${variant}.`,why,'Repository Owner Truth JPEGs are primary geometry authority; web research is secondary.','Only this semantic component family is intentionally changed; cameras, driving physics, track and unrelated body systems remain invariant.'],rationale:['Reconstruct one exterior component at a time from the exact owner shell photographs.','Headlamp topology is native rounded-rectangle geometry; legacy ellipse radii are deprecated.','Grille topology is a native recessed rounded opening with perimeter and mesh authority, not a flat bumper quad.','Treat generated geometry as a challenger only; protected visual gates must prove it better before promotion.','Owner Truth outranks research and generated inference.'],requiresVisualValidation:true,reconstruction:{component:group,evidence:evidenceScore(group),referenceSource:'owner_repo_jpegs',ownerTruthSchema:owner.schema||1,topologyAuthority:group==='headlights'?'native_topology_v41':group==='grille'?'native_topology_v42':'visual_genome'}}}
function candidates(){const out=[];
out.push(proposal('headlights','owner-rounded-rectangle-pods',{headlamp_width:step('headlamp_width',-1,.24),headlamp_height:step('headlamp_height',-1,.20),headlamp_corner_radius:step('headlamp_corner_radius',1,.14),headlamp_lens_width:step('headlamp_lens_width',-1,.12),headlamp_lens_height:step('headlamp_lens_height',-1,.10),headlamp_lens_offset_x:step('headlamp_lens_offset_x',1,.10)},'Owner front views show compact outboard horizontal rounded-rectangle pods, recessed dark cavities, small offset inner lenses and a separate thin upper DRL.'));
out.push(proposal('headlights','owner-lens-placement',{headlamp_width:step('headlamp_width',-1,.10),headlamp_height:step('headlamp_height',-1,.08),headlamp_corner_radius:step('headlamp_corner_radius',1,.08),headlamp_lens_width:step('headlamp_lens_width',-1,.22),headlamp_lens_height:step('headlamp_lens_height',-1,.18),headlamp_lens_offset_x:step('headlamp_lens_offset_x',1,.22)},'Tests the owner-photo relationship between a compact housing and a much smaller lens shifted toward the vehicle centerline.'));
out.push(proposal('grille','owner-recessed-wide-low',{grille_half_bottom:step('grille_half_bottom',1,.30),grille_half_top:step('grille_half_top',1,.20),grille_bottom_y:step('grille_bottom_y',-1,.16),grille_top_y:step('grille_top_y',-1,.18),grille_corner_radius:step('grille_corner_radius',1,.24),grille_frame_thickness:step('grille_frame_thickness',-1,.12)},'Straight front owner photo shows a broad low rounded opening with a thin contrasting perimeter, recessed dark cavity and visible mesh—not a tall flat central slab.'));
out.push(proposal('grille','owner-thin-frame-mesh',{grille_half_bottom:step('grille_half_bottom',1,.12),grille_half_top:step('grille_half_top',1,.10),grille_top_y:step('grille_top_y',-1,.12),grille_corner_radius:step('grille_corner_radius',1,.14),grille_frame_thickness:step('grille_frame_thickness',-1,.28)},'Tests a thinner owner-photo perimeter around a deeper-looking low mesh opening.'));
const wf=ref.side?.wheelFill||.2357;out.push(proposal('arches','owner-side-fit',{arch_x:step('arch_x',1,.4),wheel_radius:step('wheel_radius',1,.4),wheel_track_x:step('wheel_track_x',1,.28),wheel_y:step('wheel_y',-1,.2)},`Owner true-side photo is primary wheel/arch proportion anchor; current reference wheelFill=${wf.toFixed(4)}.`));
out.push(proposal('roof_scoop','owner-low-rectangular',{scoop_width:step('scoop_width',1,.5),scoop_height:step('scoop_height',-1,.65),scoop_length:step('scoop_length',1,.35)},'Owner views show a low rectangular forward-facing scoop rather than a tall roof block.'));
out.push(proposal('rear_wing','owner-two-plane-rear',{wing_end_x:step('wing_end_x',1,.65),diffuser_half_bottom:step('diffuser_half_bottom',1,.55),diffuser_half_top:step('diffuser_half_top',1,.25)},'Owner rear views show a nearly full-width high wing with large endplates and a wider multi-fin diffuser.'));
return out.sort((a,b)=>(b.reconstruction.evidence.ownerPrimary?10:0)+(b.reconstruction.evidence.confidence+b.reconstruction.evidence.uniqueDirectReferences*.02)-((a.reconstruction.evidence.ownerPrimary?10:0)+(a.reconstruction.evidence.confidence+a.reconstruction.evidence.uniqueDirectReferences*.02)))}
const [mode,outDir='/tmp/nickelle-lab']=process.argv.slice(2);if(mode!=='generate')throw Error('usage: nickelle_component_reconstruct.mjs generate OUT_DIR');fs.mkdirSync(outDir,{recursive:true});const cs=candidates();let i=0;for(const c of cs)fs.writeFileSync(path.join(outDir,`candidate-reconstruct-${String(++i).padStart(2,'0')}-${c.component}.json`),JSON.stringify(c,null,2)+'\n');const report={schema:5,engine:'NICKELLE_OWNER_PHOTO_COMPONENT_RECONSTRUCTION',generatedAt:new Date().toISOString(),ownerPhotoCount:ownerRefs.photos?.length||0,count:cs.length,components:[...new Set(cs.map(x=>x.component))],headlampTopology:'native_topology_v41',grilleTopology:'native_topology_v42',candidates:cs.map(x=>({component:x.component,variant:x.variant,evidence:x.reconstruction.evidence}))};fs.writeFileSync(path.join(outDir,'component-reconstruction-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
