import fs from 'node:fs';
import path from 'node:path';
import {PNG} from 'pngjs';

const genome=JSON.parse(fs.readFileSync('michael/visual/genome.json','utf8'));
const state=JSON.parse(fs.readFileSync('michael/visual/state.json','utf8'));
const scene=JSON.parse(fs.readFileSync('michael/visual/scene-graph.json','utf8'));
const lab=JSON.parse(fs.readFileSync('nickelle/lab.json','utf8'));
const regPath='nickelle/visual-regression.json',researchPath='nickelle/research-queue.json',criticPath='nickelle/critic-weights.json';
const VIEWS=['front','three','side','rear','top'];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const round=(v,n=5)=>Number(v.toFixed(n));
const load=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const save=(p,x)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n')};
const rgbClass=(r,g,b)=>r>60&&r>g*1.3&&r>b*1.2?'body':r<58&&g<62&&b<68?'dark_aero':r>150&&g>150&&b>145&&Math.max(r,g,b)-Math.min(r,g,b)<55?'white_livery':r>120&&g>65&&g<210&&b<105?'yellow_livery':b>r*1.15&&b>g*1.05&&b>65?'glass':'background';
function png(file){return PNG.sync.read(fs.readFileSync(file))}
function imageAnalysis(file){const p=png(file),d=p.data,w=p.width,h=p.height,counts={},edge=[],lumRows=Array(h).fill(0),lumCols=Array(w).fill(0),mask=new Uint8Array(w*h);let total=0,L=0,L2=0,edges=0,clip=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2],c=rgbClass(r,g,b),l=(.2126*r+.7152*g+.0722*b)/255;counts[c]=(counts[c]||0)+1;total++;L+=l;L2+=l*l;lumRows[y]+=l;lumCols[x]+=l;mask[y*w+x]=c==='background'?0:1;if(r>250||g>250||b>250)clip++;if(x+1<w&&y+1<h){const j=(y*w+x+1)*4,k=((y+1)*w+x)*4,lr=(.2126*d[j]+.7152*d[j+1]+.0722*d[j+2])/255,ld=(.2126*d[k]+.7152*d[k+1]+.0722*d[k+2])/255,gx=Math.abs(l-lr),gy=Math.abs(l-ld);if(gx+gy>.22)edges++;edge.push(Math.hypot(gx,gy))}}let x0=w,y0=h,x1=0,y1=0,n=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(mask[y*w+x]){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);n++}if(!n){x0=0;y0=0;x1=w-1;y1=h-1}const mean=L/total,variance=Math.max(0,L2/total-mean*mean),top=lumRows.slice(0,Math.floor(h/2)).reduce((a,b)=>a+b,0),bottom=lumRows.slice(Math.floor(h/2)).reduce((a,b)=>a+b,0),left=lumCols.slice(0,Math.floor(w/2)).reduce((a,b)=>a+b,0),right=lumCols.slice(Math.floor(w/2)).reduce((a,b)=>a+b,0);edge.sort((a,b)=>a-b);const q=p=>edge.length?edge[Math.floor((edge.length-1)*p)]:0;return{width:w,height:h,segmentation:Object.fromEntries(Object.entries(counts).map(([k,v])=>[k,round(v/total,4)])),registration:{bbox:[x0/w,y0/h,x1/w,y1/h],aspect:round((x1-x0+1)/Math.max(1,y1-y0+1),4),coverage:round(n/total,4)},depthNormalProxy:{gradientMedian:round(q(.5),4),gradientP90:round(q(.9),4),normalRoughness:round(q(.75)*2,4)},material:{meanLuma:round(mean,4),contrast:round(Math.sqrt(variance),4),highlightDensity:round(clip/total,4),darkResponse:round((counts.dark_aero||0)/total,4),whiteResponse:round((counts.white_livery||0)/total,4)},lighting:{topBottom:round((top-bottom)/Math.max(1,top+bottom),4),leftRight:round((left-right)/Math.max(1,left+right),4)},perceptual:{edgeDensity:round(edges/total,4),clipRatio:round(clip/total,4),flatness:round(1-Math.min(1,Math.sqrt(variance)*3),4),aliasingProxy:round(q(.9)-q(.5),4)}}}
function analyze(dir){const views={};for(const v of VIEWS){const f=path.join(dir,`${v}.png`);if(fs.existsSync(f))views[v]=imageAnalysis(f)}const aspects=Object.values(views).map(v=>v.registration.aspect),edges=Object.values(views).map(v=>v.perceptual.edgeDensity),multiview={aspectSpread:round(Math.max(...aspects)-Math.min(...aspects),4),edgeSpread:round(Math.max(...edges)-Math.min(...edges),4),coverage:round(Object.keys(views).length/VIEWS.length,3)};const uncertainty=round(clamp(.15+multiview.aspectSpread*.08+multiview.edgeSpread*1.5+(1-multiview.coverage)*.8,0,1),3);return{views,multiview,uncertainty,semanticSceneNodes:Object.keys(scene.nodes),nativeEscalations:Object.entries(scene.nodes).filter(([,v])=>v.authority==='native_renderer').map(([k])=>k)}}
function paramToNode(k){for(const [name,n] of Object.entries(scene.nodes))if((n.parameters||[]).includes(k))return name;return null}
function bounded(k,v){const b=genome.bounds[k],old=genome.parameters[k];if(!b||!Number.isFinite(old))return old;const span=b[1]-b[0],step=span*(genome.maxStepFraction||.18);return round(clamp(v,Math.max(b[0],old-step),Math.min(b[1],old+step)),4)}
function uniqCandidates(list){const seen=new Set(),out=[];for(const c of list){const key=JSON.stringify(c.candidateParameters,Object.keys(c.candidateParameters).sort());if(seen.has(key))continue;seen.add(key);out.push(c)}return out}
function generate(baseDir,seedPath,outDir){const seed=load(seedPath),params=seed.candidateParameters||{},analysis=analyze(baseDir),weak=(seed.nickelle?.weakest||[]).map(x=>x.k||x),locked=new Set(state.lockedParameters||[]),cand=[];const base=(tag,p,why)=>({score:seed.score,subsystemScores:seed.subsystemScores,diagnosis:[...(seed.diagnosis||[]),why],candidateParameters:p,rationale:[...(seed.rationale||[]),`Nickelle Visual Laboratory ${tag}`],lab:{tag,analysisUncertainty:analysis.uncertainty}});cand.push(base('seed',{...params},'Seed candidate from Nickelle visual AI.'));const keys=Object.keys(params).filter(k=>!locked.has(k)&&genome.bounds[k]);for(const k of keys){const [lo,hi]=genome.bounds[k],span=hi-lo,old=genome.parameters[k],s=span*(lab.gradientStepFraction||.08);cand.push(base(`fd-${k}-plus`,{...params,[k]:bounded(k,old+s)},`Finite-difference positive probe for ${k}.`));cand.push(base(`fd-${k}-minus`,{...params,[k]:bounded(k,old-s)},`Finite-difference negative probe for ${k}.`))}const nodeParams=[];for(const name of weak){const n=scene.nodes[name];for(const k of n?.parameters||[])if(!locked.has(k)&&genome.bounds[k])nodeParams.push(k)}for(let i=0;i<Math.max(2,lab.population||10);i++){const p={};const pool=[...new Set([...keys,...nodeParams])];for(let j=0;j<Math.min(lab.maxMutatedParameters||6,Math.max(1,pool.length));j++){const k=pool[(i*3+j*5)%pool.length];if(!k)continue;const [lo,hi]=genome.bounds[k],span=hi-lo,old=genome.parameters[k],dir=((i+j)%2?1:-1),mag=span*((lab.mutationJitterFraction||.035)*(1+(i%3)));p[k]=bounded(k,old+dir*mag)}if(Object.keys(p).length)cand.push(base(`population-${i+1}`,p,'Evolutionary population mutation across semantic visual nodes.'))}const final=uniqCandidates(cand).slice(0,lab.population||10);fs.mkdirSync(outDir,{recursive:true});final.forEach((c,i)=>save(path.join(outDir,`candidate-${String(i+1).padStart(2,'0')}.json`),c));save(path.join(outDir,'analysis.json'),analysis);save(path.join(outDir,'manifest.json'),{generatedAt:new Date().toISOString(),count:final.length,weakest:weak,uncertainty:analysis.uncertainty,nativeEscalations:analysis.nativeEscalations});console.log(JSON.stringify({outDir,count:final.length,uncertainty:analysis.uncertainty},null,2))}
function record(proposalPath,verdictPath,metricsPath,out){const p=load(proposalPath),v=load(verdictPath),m=load(metricsPath);const neural=v.nickelle?.neural||v.neural||{},confidence=Number(neural.confidence??v.confidence??0),uncertainty=1-confidence,frame=Number(m.frameMs||20),qualityPenalty=Math.max(0,(m.captureSize||480)<400?.5:0),perfPenalty=Math.max(0,frame-16.7)*(lab.framePenaltyPerMs||1.8),regPenalty=(v.regressions||[]).length*12,score=Number(v.candidateScore||0)-uncertainty*(lab.uncertaintyPenalty||3)-perfPenalty-regPenalty-qualityPenalty;const rec={proposalPath,proposal:p,verdict:v,metrics:m,tournamentScore:round(score,4),uncertainty:round(uncertainty,3),semanticNodes:[...new Set(Object.keys(p.candidateParameters||{}).map(paramToNode).filter(Boolean))]};save(out,rec);console.log(JSON.stringify(rec,null,2))}
function select(dir,outProposal,outReport){const files=fs.readdirSync(dir).filter(x=>x.endsWith('.record.json')),r=files.map(f=>load(path.join(dir,f))).sort((a,b)=>b.tournamentScore-a.tournamentScore),winner=r[0];if(!winner)throw Error('No laboratory tournament records');save(outProposal,{...winner.proposal,labWinner:{tournamentScore:winner.tournamentScore,uncertainty:winner.uncertainty,semanticNodes:winner.semanticNodes,fieldSize:r.length}});save(outReport,{winner:{score:winner.tournamentScore,proposal:winner.proposalPath,semanticNodes:winner.semanticNodes},ranking:r.map(x=>({proposal:x.proposalPath,score:x.tournamentScore,candidateScore:x.verdict.candidateScore,uncertainty:x.uncertainty,regressions:x.verdict.regressions||[],frameMs:x.metrics.frameMs}))});console.log(JSON.stringify({winner:winner.proposalPath,score:winner.tournamentScore,field:r.length},null,2))}
function learn(proposalPath,verdictPath,decisionPath,analysisPath,temporalPath,metricsPath){const p=load(proposalPath),v=load(verdictPath),d=load(decisionPath),a=load(analysisPath),t=fs.existsSync(temporalPath)?load(temporalPath):{},m=load(metricsPath),reg=load(regPath),critic=load(criticPath),rq=load(researchPath),promote=!!d.promote;const parts=v.candidate?.parts||{},base=v.baseline?.parts||{};if(promote){const row={at:new Date().toISOString(),score:v.candidateScore,frameMs:m.frameMs,parameters:p.candidateParameters||{},parts,temporal:t.summary||{},uncertainty:a.uncertainty};reg.champions=[...(reg.champions||[]),row].slice(-(reg.maxHistory||40));for(const [k,x] of Object.entries(parts)){const b=reg.bestBySubsystem[k];if(!b||x>b.score)reg.bestBySubsystem[k]={score:x,at:row.at};reg.protectedFloors[k]=Math.max(reg.protectedFloors[k]||0,x-8)}reg.performanceBaselines.frameMs=Math.min(reg.performanceBaselines.frameMs||999,m.frameMs||999);if(t.summary)reg.temporalBaselines=t.summary}const lr=critic.learningRate||.025;for(const k of Object.keys(critic.weights||{})){if(!Number.isFinite(parts[k])||!Number.isFinite(base[k]))continue;const delta=parts[k]-base[k],sign=promote?1:-.35;critic.weights[k]=round(clamp(critic.weights[k]+sign*lr*Math.sign(delta)*(Math.abs(delta)>1?1:.25),critic.min||.35,critic.max||2.5),4)}critic.updates=(critic.updates||0)+1;const uncertain=Object.entries(v.candidate?.parts||{}).filter(([,x])=>x<60).map(([k,x])=>({subsystem:k,score:x}));for(const u of uncertain){if(rq.queue.some(q=>q.subsystem===u.subsystem&&q.status==='open'))continue;rq.queue.push({id:`${Date.now()}-${u.subsystem}`,status:'open',subsystem:u.subsystem,priority:round((100-u.score)/100,3),request:`Find authoritative MJX Hyper Go 7303 / Citroen C3 WRC reference imagery or dimensions that clarify ${u.subsystem}. Prefer owner-body-matching angles and measurable proportions.`,createdAt:new Date().toISOString()})}rq.queue=rq.queue.sort((a,b)=>b.priority-a.priority).slice(0,rq.maxQueue||24);save(regPath,reg);save(criticPath,critic);save(researchPath,rq);console.log(JSON.stringify({promote,regressionChampions:reg.champions.length,criticUpdates:critic.updates,researchQueued:rq.queue.length},null,2))}
const [cmd,...a]=process.argv.slice(2);if(cmd==='analyze')save(a[1]||'/tmp/nickelle-analysis.json',analyze(a[0]));else if(cmd==='generate')generate(a[0],a[1],a[2]);else if(cmd==='record')record(a[0],a[1],a[2],a[3]);else if(cmd==='select')select(a[0],a[1],a[2]);else if(cmd==='learn')learn(...a);else throw Error('usage: nickelle_graphics_lab.mjs analyze DIR OUT | generate BASE SEED OUTDIR | record PROPOSAL VERDICT METRICS OUT | select DIR OUT_PROPOSAL OUT_REPORT | learn PROPOSAL VERDICT DECISION ANALYSIS TEMPORAL METRICS');
