import fs from 'node:fs';import path from 'node:path';import {PNG} from 'pngjs';import jpeg from 'jpeg-js';
const R=p=>JSON.parse(fs.readFileSync(p,'utf8')),W=(p,x)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n')};const E=fs.existsSync;
const owner=R('michael/visual/owner-reference-observations.json'),genome=R('michael/visual/genome.json');
function dec(f){const b=fs.readFileSync(f);if(/\.png$/i.test(f)){const p=PNG.sync.read(b);return{w:p.width,h:p.height,d:p.data}}const j=jpeg.decode(b,{useTArray:true,formatAsRGBA:true});return{w:j.width,h:j.height,d:j.data}}
function feat(f,Wd=72,H=48){const im=dec(f),g=new Float32Array(Wd*H),e=new Float32Array(Wd*H);for(let y=0;y<H;y++)for(let x=0;x<Wd;x++){const sx=Math.min(im.w-1,Math.floor((x+.5)*im.w/Wd)),sy=Math.min(im.h-1,Math.floor((y+.5)*im.h/H)),i=(sy*im.w+sx)*4,k=y*Wd+x;g[k]=(.2126*im.d[i]+.7152*im.d[i+1]+.0722*im.d[i+2])/255}for(let y=0;y<H-1;y++)for(let x=0;x<Wd-1;x++){const k=y*Wd+x;e[k]=Math.abs(g[k]-g[k+1])+Math.abs(g[k]-g[k+Wd])}return{g,e}}
function d(a,b){let l=0,e=0;for(let i=0;i<a.g.length;i++){l+=Math.abs(a.g[i]-b.g[i]);e+=Math.abs(a.e[i]-b.e[i])}return .58*l/a.g.length+.42*e/a.g.length}
function ownerMap(){const a=R('michael/reconstruction/autonomous-state.json');return a.cameraSolve?.matches||[]}
function score(dir){const m=ownerMap();let s=0,n=0;for(const x of m){if(!x.matchedView)continue;const rf=path.join(dir,x.matchedView+'.png');if(!E(x.file)||!E(rf))continue;s+=d(feat(x.file),feat(rf));n++}return n?s/n:1}
function generate(out){const params=genome.parameters||{},bounds=genome.bounds||{},keys=['headlamp_width','headlamp_height','headlamp_corner_radius','headlamp_lens_width','headlamp_lens_height','headlamp_lens_offset_x','grille_half_bottom','grille_half_top','grille_corner_radius','grille_frame_thickness'].filter(k=>bounds[k]&&Number.isFinite(Number(params[k]))).slice(0,6),probes=[];for(const k of keys){const [lo,hi]=bounds[k].map(Number),v=Number(params[k]),eps=(hi-lo)*.035;for(const sign of [-1,1]){const nv=Math.max(lo,Math.min(hi,v+sign*eps));probes.push({id:`${k}-${sign<0?'minus':'plus'}`,parameter:k,sign,current:v,value:+nv.toFixed(5),proposal:{candidateParameters:{[k]:+nv.toFixed(5)},reason:'measured finite-difference owner-truth probe'}})}}W(out,{schema:1,probes});console.log(`generated ${probes.length} measured probes`)}
function evaluate(probeFile,root,out){const p=R(probeFile),base=score(path.join(root,'baseline')),rows=[];for(const z of p.probes){const q=path.join(root,z.id);if(!E(q))continue;rows.push({...z,error:score(q)})}const by={};for(const r of rows)(by[r.parameter]??=[]).push(r);const gradients=[];for(const [k,a] of Object.entries(by)){const m=a.find(x=>x.sign<0),p1=a.find(x=>x.sign>0);if(!m||!p1)continue;const grad=(p1.error-m.error)/(p1.value-m.value||1e-9),best=[m,p1].sort((x,y)=>x.error-y.error)[0];gradients.push({parameter:k,baselineError:+base.toFixed(6),minusError:+m.error.toFixed(6),plusError:+p1.error.toFixed(6),gradient:+grad.toFixed(6),bestValue:best.value,measuredGain:+Math.max(0,base-best.error).toFixed(6),direction:best.value>best.current?'increase':'decrease'})}W(out,{schema:1,method:'actual_render_finite_difference_owner_truth',baselineError:+base.toFixed(6),gradients:gradients.sort((a,b)=>b.measuredGain-a.measuredGain)});console.log(JSON.stringify({baselineError:base,gradients},null,2))}
const [cmd,a,b,c]=process.argv.slice(2);if(cmd==='generate')generate(a);else if(cmd==='evaluate')evaluate(a,b,c);else throw Error('usage: generate OUT | evaluate PROBES ROOT OUT');
