import Foundation
import CryptoKit
import Security

struct KeychainStore {
    static func set(_ value:String,key:String){let data=Data(value.utf8);SecItemDelete([kSecClass:kSecClassGenericPassword,kSecAttrAccount:key]as CFDictionary);SecItemAdd([kSecClass:kSecClassGenericPassword,kSecAttrAccount:key,kSecValueData:data,kSecAttrAccessible:kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly]as CFDictionary,nil)}
    static func get(_ key:String)->String{var result:CFTypeRef?;let q:[CFString:Any]=[kSecClass:kSecClassGenericPassword,kSecAttrAccount:key,kSecReturnData:true,kSecMatchLimit:kSecMatchLimitOne];guard SecItemCopyMatching(q as CFDictionary,&result)==errSecSuccess,let data=result as? Data else{return""};return String(data:data,encoding:.utf8)??""}
}

enum MobileCore {
    static let repo="gymwhaleysspot-dot/mt12-jarvis-continuous"
    static let catalogURL=URL(string:"https://raw.githubusercontent.com/\(repo)/main/public/device-data/releases.json")!
    static let logIndexURL=URL(string:"https://raw.githubusercontent.com/\(repo)/main/public/control-data/log-hashes.json")!
    static let builderResultsURL=URL(string:"https://github.com/\(repo)/actions/workflows/workbench.yml")!
    static func sha256(_ data:Data)->String{SHA256.hash(data:data).map{String(format:"%02x",$0)}.joined()}
    static func validateMT12(_ root:URL)->Bool{let names=(try?FileManager.default.contentsOfDirectory(atPath:root.path).map{$0.uppercased()}) ?? [];return names.contains("LOGS")&&(names.contains("SCRIPTS")||names.contains("MODELS")||names.contains("RADIO"))}
    static func request(_ url:URL,method:String="GET",token:String?=nil,json:Any?=nil)async throws->(Data,HTTPURLResponse){var req=URLRequest(url:url);req.httpMethod=method;req.setValue("application/vnd.github+json",forHTTPHeaderField:"Accept");req.setValue("2022-11-28",forHTTPHeaderField:"X-GitHub-Api-Version");if let token,!token.isEmpty{req.setValue("token \(token)",forHTTPHeaderField:"Authorization")};if let json{req.setValue("application/json",forHTTPHeaderField:"Content-Type");req.httpBody=try JSONSerialization.data(withJSONObject:json)};let(data,response)=try await URLSession.shared.data(for:req);guard let http=response as? HTTPURLResponse else{throw NSError(domain:"A17Y",code:1,userInfo:[NSLocalizedDescriptionKey:"Invalid HTTP response"])};return(data,http)}
    static func runLuacAIBuilder(token:String,child:String,mission:String)async throws->String{guard token.hasPrefix("ghp_")else{throw NSError(domain:"A17Y",code:30,userInfo:[NSLocalizedDescriptionKey:"Classic GitHub PAT required"])};let source=child.trimmingCharacters(in:.whitespacesAndNewlines);if !source.isEmpty{let bad=source=="a17y.lua"||source.hasPrefix("protected/")||source.hasPrefix(".github/")||source.hasPrefix("toolchain/");guard source.lowercased().hasSuffix(".lua")&&!bad else{throw NSError(domain:"A17Y",code:31,userInfo:[NSLocalizedDescriptionKey:"Use a safe candidate path or leave blank for AI generation from protected A17Y"])} };let task=mission.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty ? "Build the strongest verified MT12 LUAC without regressions":mission.trimmingCharacters(in:.whitespacesAndNewlines);let(body,response)=try await request(URL(string:"https://api.github.com/repos/\(repo)/actions/workflows/workbench.yml/dispatches")!,method:"POST",token:token,json:["ref":"main","inputs":["child":source,"mission":task,"generate":source.isEmpty ? "true":"false"]]);guard response.statusCode==204 else{throw NSError(domain:"A17Y",code:32,userInfo:[NSLocalizedDescriptionKey:"LUAC builder dispatch failed: \(String(data:body,encoding:.utf8) ?? "unknown")"])};return "Full LUAC AI pipeline started.\nMode: \(source.isEmpty ? "AI diagnosis, generation and repair":"verify existing candidate")\nMission: \(task)"}
    static func fetchCatalogData()async throws->Data{let(data,response)=try await URLSession.shared.data(from:catalogURL);guard(response as?HTTPURLResponse)?.statusCode==200 else{throw NSError(domain:"A17Y",code:10,userInfo:[NSLocalizedDescriptionKey:"Firmware catalog unavailable"])};return data}
    static func fetchCatalog()async throws->String{String(data:try await fetchCatalogData(),encoding:.utf8)??"{}"}
    static func repositoryLogHashes()async->Set<String>{guard let(data,response)=try?await URLSession.shared.data(from:logIndexURL),(response as?HTTPURLResponse)?.statusCode==200,let obj=try?JSONSerialization.jsonObject(with:data)as?[String:Any],let files=obj["files"]as?[[String:Any]]else{return[]};return Set(files.compactMap{$0["sha256"]as?String})}
    static func officialFirmwareMatch(catalog:Data,fileName:String,hash:String)->Bool{guard let root=try?JSONSerialization.jsonObject(with:catalog)else{return false};func scan(_ value:Any)->Bool{if let d=value as?[String:Any]{if let h=d["sha256"]as?String,let n=d["name"]as?String,h.caseInsensitiveCompare(hash)==.orderedSame,n.caseInsensitiveCompare(fileName)==.orderedSame{return true};return d.values.contains(where:scan)};if let a=value as?[Any]{return a.contains(where:scan)};return false};return scan(root)}
    static func uploadLog(token:String,name:String,data:Data,hash:String,remote:Set<String>)async throws->String{guard token.hasPrefix("ghp_")else{throw NSError(domain:"A17Y",code:11,userInfo:[NSLocalizedDescriptionKey:"Classic GitHub PAT required"])};guard !remote.contains(hash)else{throw NSError(domain:"A17Y",code:17,userInfo:[NSLocalizedDescriptionKey:"This log already exists in the repository"])};let safe=name.replacingOccurrences(of:"[^A-Za-z0-9._-]",with:"_",options:.regularExpression),path="tests/replays/mobile-\(Int(Date().timeIntervalSince1970*1000))-\(safe)";let(reply,response)=try await request(URL(string:"https://api.github.com/repos/\(repo)/contents/\(path)")!,method:"PUT",token:token,json:["message":"Import MT12 log \(safe) [\(hash)]","content":data.base64EncodedString(),"branch":"main"]);guard response.statusCode==201,let obj=try JSONSerialization.jsonObject(with:reply)as?[String:Any],let content=obj["content"]as?[String:Any],!((content["sha"]as?String)??"").isEmpty else{throw NSError(domain:"A17Y",code:12,userInfo:[NSLocalizedDescriptionKey:"GitHub did not confirm upload"])};return path}
    static func sync(root:URL,token:String)async throws->String{guard root.startAccessingSecurityScopedResource()else{throw NSError(domain:"A17Y",code:13,userInfo:[NSLocalizedDescriptionKey:"Folder permission unavailable"])};defer{root.stopAccessingSecurityScopedResource()};guard validateMT12(root)else{throw NSError(domain:"A17Y",code:14,userInfo:[NSLocalizedDescriptionKey:"Selected folder is not an MT12 root"])};let logs=root.appendingPathComponent("LOGS",isDirectory:true),files=try FileManager.default.contentsOfDirectory(at:logs,includingPropertiesForKeys:nil).filter{$0.pathExtension.lowercased()=="csv"};var imported=Set(UserDefaults.standard.stringArray(forKey:"importedHashes") ?? []);let remote=await repositoryLogHashes();var lines:[String]=[],count=0;for file in files{let data=try Data(contentsOf:file),hash=sha256(data);if imported.contains(hash)||remote.contains(hash){lines.append("KNOWN \(file.lastPathComponent)");imported.insert(hash);continue};let path=try await uploadLog(token:token,name:file.lastPathComponent,data:data,hash:hash,remote:remote);imported.insert(hash);UserDefaults.standard.set(Array(imported),forKey:"importedHashes");count+=1;lines.append("UPLOADED \(file.lastPathComponent) → \(path)")};return "Uploaded \(count) new logs.\n"+lines.joined(separator:"\n")}
    static func backupManifest(root:URL)throws->Data{guard root.startAccessingSecurityScopedResource()else{throw NSError(domain:"A17Y",code:15,userInfo:[NSLocalizedDescriptionKey:"Folder permission unavailable"])};defer{root.stopAccessingSecurityScopedResource()};guard validateMT12(root)else{throw NSError(domain:"A17Y",code:16,userInfo:[NSLocalizedDescriptionKey:"Not an MT12 root"])};let e=FileManager.default.enumerator(at:root,includingPropertiesForKeys:[.isRegularFileKey]);var files:[[String:Any]]=[];while let url=e?.nextObject()as?URL{let v=try url.resourceValues(forKeys:[.isRegularFileKey]);if v.isRegularFile==true{let d=try Data(contentsOf:url);files.append(["path":url.path.replacingOccurrences(of:root.path+"/",with:""),"size":d.count,"sha256":sha256(d)])}};return try JSONSerialization.data(withJSONObject:["schema":2,"radio":"RadioMaster MT12","createdAt":ISO8601DateFormatter().string(from:Date()),"files":files],options:[.prettyPrinted])}
}
